DFE-Digital/dfe-complete-conversions-transfers-and-changes

CHANGELOG.md, app/views/all/export/education_and_skills_funding_agency/projects/show.html.erb, app/views/all/export/funding_agreement_letters/projects/show.html.erb, config/locales/project.en.yml
The navigation was missing from the individual (per month) export pages.
=> Add navigation to export page

script/start_backing_services, script/stop_backing_services
The name of the two containers has changed, so these two scripts are not
looking for the right thing - this updates them.
=> Update backing service dev scripts

CHANGELOG.md, app/forms/contact/create_project_contact_form.rb, app/models/contact.rb, config/locales/academies_api_en.yml, config/locales/contact.en.yml, config/locales/conversion_project.en.yml, config/locales/project.en.yml, config/locales/project_information.en.yml, config/locales/transfer_project.en.yml, spec/features/conversions/users_can_create_conversion_projects_spec.rb, spec/features/users_can_manage_contacts_spec.rb, spec/forms/contact/contact_project_form_spec.rb, spec/requests/contacts_controller_spec.rb
Change the "Contact" category from "School" to "School or academy". Transfer projects will happen to academies, so change the wording slightly to reflect a "School" contact could actually belong to a school or academy.
Also remove any references to "Establishments" in the text. These are schools or academies.
=> Update school contact category

app/services/import/director_of_child_services_csv_importer_service.rb, app/services/import/local_authority_csv_importer_service.rb, app/services/import/user_csv_importer_service.rb, lib/tasks/director_of_child_services/import.rake, lib/tasks/local_authority/import.rake, lib/tasks/users/import.rake, spec/lib/tasks/director_of_child_services/import_spec.rb, spec/lib/tasks/local_authorities/import_spec.rb, spec/lib/tasks/users/import_spec.rb, spec/services/import/director_of_child_services_csv_importer_spec.rb, spec/services/import/local_authority_csv_importer_service_spec.rb, spec/services/import/user_csv_importer_service_spec.rb
Keeping to a naming convention helps identify classes and makes our code
more approachable.
This work renames and groups all the service objects we have that import
csv data.
=> Rename import related service objects

doc/developer-scripts.md
This is just a small fix to the script name for `lint_and_format`. It was originally down wrong as `linting_and_formatting`
=> Fix script name for lint_and_format

CHANGELOG.md, app/views/team/projects/_in_progress_table.html.erb, app/views/team/projects/in_progress.html.erb, config/locales/project.en.yml, spec/features/your_team_projects/users_can_view_their_team_projects_spec.rb
`Regional case workers` need to be able to see an overview of all the regions projects and so this work is to ensure that if the current user is a `Regional case worker`, they will see what region each project belongs to. For all `Regional delivery officers`, they will only see the projects which are within their same team, and therefore will see a `Team` column in place of the `Region` column.
=> Update 'Your team projects' in progress table

README.md, app/forms/conversion/create_project_form.rb, app/models/concerns/eventable.rb, app/models/event.rb, app/models/project.rb, db/migrate/20230919103947_add_events_table.rb, db/schema.rb, doc/event-logging.md, spec/models/event_spec.rb
We want offer users an 'audit log' of changes made in the application.
To faclilitate this we have the Event model. Events can be grouped and
assoicated to any ActiveRecord objects, a Project here.
We validate this all works by logging when a project is created, later we can
expose this to users in the UI.
This work lays a foundation for other logging to happen in a consistent way,
there is documentation in the PR.
This work does not include capturing further events or exposing the events.
We already know we want to log the events relating to importing GIAS data and
this also makes a clear path to that.
Interested to hear thoughts on naming here as it was tough to reach a decision -
we do have our old friend 'able' in 'eventable' - I've decided just to follow
convention here as it is at …
=> Basic event log model

CHANGELOG.md, app/controllers/external_contacts_controller.rb, app/forms/contact/create_project_contact_form.rb, app/models/contact.rb, app/models/contact/director_of_child_services.rb, app/models/contact/project.rb, app/models/project.rb, app/services/contacts_fetcher_service.rb, app/views/conversions/external_contacts/index.html.erb, app/views/external_contacts/_contact_group.html.erb, app/views/external_contacts/edit.html.erb, app/views/external_contacts/new.html.erb, app/views/transfers/external_contacts/index.html.erb, config/locales/contact.en.yml, spec/features/users_can_manage_contacts_spec.rb, spec/forms/contact/contact_project_form_spec.rb, spec/models/contact/director_of_child_services_spec.rb, spec/models/contact/project_spec.rb, spec/models/contact_spec.rb, spec/requests/contacts_controller_spec.rb, spec/services/contacts_fetcher_service_spec.rb
This work started out as 'I wonder why calling the `project` association on a `Contact` results in nil?...' to what you see here!
There is a fair bit so jump in:
The project association was caused by a naming collision between `Contact::Project` and `Project` - ideally we would rename the `Contact::Project` class - but the scope of felt a bit big (at the time!).
Whilst working on this we found a bug on the 'main contact' behaviour that meant any time the main contact for a category was updated, all of the other main contact states were dropped - this would have meant a sort of data loss if we deployed it.  We fixed that and simplified the approach, we don't think this is the final solution to this area, but it does let us deploy the feature. We've changed most of the language around this …
=> Refactor and fix Contacts

Dockerfile
We base our application container off the official Ruby one.
We recently updated to Ruby 3.1.4, we then started to see issues as soon
as this was deployed. They issue seems to relate to Sidekiq and Redis
and shows up as a 500.
```
E, [2023-09-28T12:34:45.186167 #1] ERROR -- :
[4c75378d-4fda-41d7-869a-aa79da7b9159] [ActiveJob] Failed enqueuing
ActionMailer::MailDeliveryJob to Sidekiq(default):
OpenSSL::SSL::SSLError (SSL_read: unsupported method)
```
The issue is very itermittent, we can validate that most email jobs get
sent because we can see them in the Notify API:
https://www.notifications.service.gov.uk/services/32d75f94-b459-4e65-b753-3f9d55c8c9b7/api
We have a working hypothesis that release 40 was the change point and
that included the change to ruby 3.1.4 which by default …
=> Change Ruby image

app/services/import/gias_establishment_csv_importer_service.rb, spec/services/import/gias_establishment_csv_importer_service_spec.rb
When the importer encounters an error, it should continue, break stops
the entire loop, next moves on and is the correct behaviour here.
=> Use next not break

CHANGELOG.md, app/models/user.rb, app/views/projects/shared/_new_projects.html.erb, spec/features/home_page/regional_casework_services_user_spec.rb, spec/models/user_spec.rb, spec/requests/conversions/projects_controller_spec.rb, spec/requests/project_management_spec.rb
We want to temporarily grant RCS users the ability to add new projects
(specifically Transfer projects, but all projects for convenience).
To do this, we have overridden the `add_new_project` column in the db with
a method. The db column is still set to `false` on creation of an RCS user,
but the overriding method returns true.
Once that is done, add the "Add new transfer" button for users who can `add_new_project`.
=> Allow RCS and RDO users to add a new transfer project

CHANGELOG.md, app/helpers/environment_banner_helper.rb, spec/features/user_can_see_environment_banner_spec.rb, spec/helpers/environment_banner_helper_spec.rb
We used sentry for our application performance monitoring and erroring insights, but we are now required to use App Insights. This means that we will be dropping support for sentry and removing it from the service. This work is to remove all dependencies on sentry within the environment banner scope.
`USER_ENV` has replaced `SENTRY_ENV`. This will need adding to the environment variable set by terraform for `production`
=> Move the site banner environment variable away from sentry

CHANGELOG.md, app/views/pages/maintenance.html.erb
This is a temporary static page that will be used when the service is being intentionally switched off to users for maintenance work. 
As the service won't actually be down, we are able to use HighVoltage for this. This reflects the other static pages we have within the service.
There is no navigation to this page from the service, but is accessed via `/maintenance` route.
=> Setup a maintenance page

CHANGELOG.md, app/forms/create_project_form.rb, app/forms/transfer/create_project_form.rb, spec/forms/transfer/create_project_form_spec.rb
When we put Transfer projects live, we were getting uncaught exceptions from a user trying to create a Transfer. After some investigation we discovered they were trying to add a UKPRN for a trust that doesn't exist, to the outgoing trust UKPRN field.
After some investigation we discovered that the outgoing trust UKPRN field was not being validated in the same way as the incoming trust. We were checking it was an integer, but not that the trust existed. There was a typo in the create transfer form spec which masked this error.
Add proper validations for both the incoming & outgoing trust UKPRNs, for both Conversions and Transfers.
=> (Fix) Validate outgoing trust exists on Transfers

app/jobs/application_job.rb, app/jobs/import/gias_establishment_import_job.rb, app/mailers/gias_establishment_import_mailer.rb, config/environments/test.rb, spec/jobs/import/gias_establishment_import_job_spec.rb, spec/mailers/gias_establishment_import_mailer_spec.rb, spec/spec_helper.rb
Add a job to run the GIAS Establishment Importer from a provided file. The job then sends an email to the requesting user with the output of the importer. 
The email has not been "contentified" - it just sends the raw output. We can iterate on this.
A requirement of this ticket was to run the job at 4am (or a provided time). However, we need to do this from the controller which calls the job. When we call the job, we should call it with (e.g.)
`Import::GiasEstablishmentImportJob.set(wait_until: <DateTime>).perform_later(file_path, user)`
Finally, when the job has been run & the email has been sent, the uploaded file is deleted.
=> Import GIAS establishments data job

config/brakeman.ignore, terraform/.terraform.lock.hcl
As our code changes over time we update what we may have previously ignored in
Brakeman (static analysis).
We do this by running `bin/brakeman -I`.
[Task 141046](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/141046): Update Brakeman ignore entries
=> Update the Brakeman ignore list

.env.example, .gitignore, CHANGELOG.md, Dockerfile, app/controllers/service_support/upload/gias/establishments_controller.rb, app/forms/service_support/upload/gias/upload_establishments_form.rb, app/mailers/gias_establishment_import_mailer.rb, app/policies/import_policy.rb, app/views/service_support/upload/gias/establishments/new.html.erb, config/locales/en.yml, config/locales/service_support.en.yml, config/routes.rb, spec/features/service_support/users_can_upload_gias_establishments_data_spec.rb, spec/fixtures/files/text_file.txt, spec/forms/service_support/upload/gias/upload_establishments_form_spec.rb, spec/mailers/gias_establishment_import_mailer_spec.rb, spec/policies/import_policy_spec.rb, spec/requests/service_support/upload/gias/establishments_controller_spec.rb
Ticket [Task 140090](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/140090): Upload GIAS establishment data via application
Add a very basic upload page to allow service support users to upload GIAS data. This needs content designing!
The page will show validation errors if the uploaded file is not CSV, or is empty, has the wrong headers, or is too large (> 150Mb)
On successful upload, the user will see a success message and the file will be scheduled for ingestion at 4am the next day. This time can be overridden via the `GIAS_IMPORT_TIME` environment variable.
If the ingestion fails later on, the user will receive an email with the errors; they will not be shown on this page.
=> Import GIAS data upload page

CHANGELOG.md, app/models/transfer/task_list.rb, spec/models/transfer/task_list_spec.rb
[Task 142894](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/142894): Change order of "get ready to transfer" tasks
=> Reorder tasks in the Transfer task list "Get ready for transfer" section

app/forms/service_support/upload/gias/upload_establishments_form.rb, app/mailers/gias_establishment_import_mailer.rb, app/services/import/gias_establishment_csv_importer_service.rb, spec/mailers/gias_establishment_import_mailer_spec.rb, spec/services/import/gias_establishment_csv_importer_service_spec.rb
We change three main things here:
We recently lowered the resolution of the file name timestamp as we were
seeing them not matching up with the two calls, but even with seconds,
it was still possible to make the second `file_path` call in the 'next'
second, making the job be queued with the wrong filename.
To remove this issue all together, we assign the file name and use that
instead, this guarentees that the filename is the same.
We fix a bug in the results email which added one too many 'results'
causing nil errors.
We also change the keys of the results hash to be symbols instead of
integers as ActiveJob does not support integer as hash keys:
https://guides.rubyonrails.org/active_job_basics.html#supported-types-for-arguments
=> Fix: Update GIAS job handling

CHANGELOG.md, config/locales/project.en.yml
Adding a bullet point about including the SFSO lead's name in the handover comments for a conversion.
Also slight change to the first line of that guidance to make it consistent with how it appears in transfers.
=> Conversion handover comments content update

CHANGELOG.md, Gemfile, Gemfile.lock, README.md, app/helpers/application_helper.rb, app/helpers/environment_banner_helper.rb, config/initializers/sentry.rb, doc/environment-variables.md, docker-compose.checks.yml, spec/helpers/application_helper_spec.rb
We no longer use Sentry. We now use the `USER_ENV` env variable to determine which environment we're in, and we use Application Insights for error reporting.
=> Remove any references to Sentry

app/services/import/gias_establishment_csv_importer_service.rb, spec/services/import/gias_establishment_csv_importer_service_spec.rb
We changed the two instances above, but missed this one.
When this results object is passed to the ActiveJob that sends the
'import complete' email, it fails.
Here we switch all the keys to strings for consistency, we cannot
symbolize an integer.
=> Hash keys passed to ActiveJob cannot be integers

Dockerfile, doc/decisions/0007-use-the-academies-db-as-the-datastore.md, doc/decisions/0021-use-a-seperate-database-server-instance.md
Our CI runs inside a container into which not everything is copied -
this results in a different set of errors when linting local to the CI.
Here we add the `doc` directory as this is covered by Prettier.
We also commit some missing fixes.
=> Ensure documentation is linted in CI

app/models/api/members_api/client.rb, app/models/contact/parliament.rb, config/locales/members_api.en.yml, spec/models/api/members_api/client_spec.rb, spec/models/contact/parliament_spec.rb
Model the Member of Parliament contact like the other contact types. However, this contact doesn't persist in our database - they are fetched from the Members API via the constituency name, and only modeled as a transient object.
If there are any errors from the Members API, raise them. We will have to ensure we handle these errors in the relevant controllers.
=> Model Contact::Parliament

terraform/README.md, terraform/container-apps-hosting.tf, terraform/locals.tf, terraform/variables.tf
- Deploys a Storage Account and a File Share and mounts it as a volume on the Container App.
- The volume mount path default is `/srv/app/storage`
- The volume is made available to the main container and the worker container so they can both read/write to it
- An IP address allow list can be specified to allow humans to access the file share on the Azure Portal
=> Deploy File Shares and mount it to the Container App

CHANGELOG.md, app/controllers/conversions/projects_controller.rb, app/controllers/transfers/projects_controller.rb, app/forms/conversion/edit_project_sharepoint_link_form.rb, app/forms/transfer/edit_project_sharepoint_link_form.rb, app/views/conversions/project_information/_school_details.html.erb, app/views/conversions/projects/edit.html.erb, app/views/shared/project_information/_incoming_trust_details.html.erb, app/views/transfers/project_information/_academy_details.html.erb, app/views/transfers/project_information/_outgoing_trust_details.html.erb, app/views/transfers/projects/edit.html.erb, config/locales/sharepoint_link_en.yml, config/routes.rb, spec/features/conversions/users_can_change_the_sharepoint_links_spec.rb, spec/features/transfers/users_can_change_the_sharepoint_links_spec.rb, spec/forms/conversion/edit_project_sharepoint_link_form_spec.rb, spec/forms/transfer/edit_project_sharepoint_link_form_spec.rb
We know that the SharePoint links can be added incorrectly or need updating.
This provides a simple way to update the SharePoint Links through the UI.
Each SharePoint link within the `Project Information` section now has a `Change` link, which takes the user to an edit page.
A conversion project will only display the School and Incoming trust's SharePoint links
A transfer project will also display the outgoing trust SharePoint link too
=> Allow sharepoint folder links to be changed

app/controllers/assignments_controller.rb, spec/requests/assignments_controller_spec.rb
Sentry error: https://sdd-n7.sentry.io/issues/4589134654/events/77ffc5f7670946b48667dfe044c8ebbd/
We were seeing an error on production where someone seemed to be trying to send an "assigned to" mail on a project with no assignee. The project's `assigned_to` value was nil, and no-one was being assigned to the project, and as a result the mailer was trying to sent an email to a nil person.
=> (Fix) Do not attempt to send "Assigned to" mail when assignee is nil

CHANGELOG.md, app/views/your/projects/in_progress.html.erb
All our other table views use the `govuk-grid-column-full` class so this change is to reflect that and keep the views consistent
=> Fix govuk class name for your projects table view

CHANGELOG.md, app/assets/stylesheets/application.scss, app/assets/stylesheets/patterns/_project-summary.scss, app/views/conversions/shared/_project_summary.html.erb, app/views/transfers/shared/_project_summary.html.erb
The project summary information view has been simplified to ensure consistency across the different applications within the service
=> Change project summary information styling

terraform/README.md, terraform/container-apps-hosting.tf, terraform/locals.tf, terraform/variables.tf
The default scale rules of the Container App Terraform module allows the worker container to scale from 1 to 2 replicas. We would like to be able to control that using a Terraform variable
=> Override the maximum number of replicas deployed for the worker

app/jobs/import/gias_headteacher_import_job.rb, spec/jobs/import/gias_headteacher_import_job_spec.rb
When working on the GIAS headteacher importing, we missed actually
sending the email at the end of the process.
=> Acutally send the GIAS headteacher import email

app/jobs/import/gias_establishment_import_job.rb, app/jobs/import/gias_headteacher_import_job.rb, app/mailers/gias_headteacher_import_mailer.rb, spec/jobs/import/gias_establishment_import_job_spec.rb, spec/jobs/import/gias_headteacher_import_job_spec.rb, spec/mailers/gias_headteacher_import_mailer_spec.rb
After importing GIAS establishment and headteacher contacts we send an
email to the user that summerises the import.
When queuing the email we pass the whole `result` object from the import
service - this has the potential to be very large e.g. on inital import
of 50K rows, you can expect 50K x number of imported columns.
On testing in the development environment, we suspect this hash is
unreasonably large for Sidekiq to serialise.
As we do not include the changes in the email anyway, here we remove the
changes before queuing the job.
We also fix the template ID for the headteacher import email.
=> Fix: do not queue the import results hash

CHANGELOG.md, app/services/project_search_service.rb, spec/services/project_search_service_spec.rb
Note that the search service is still not available to users.
Extend the existing search service to search by words (establishment name) and GIAS number (4-digit string). 
The search by words allows partial matches and is case-insensitive.
The search by GIAS number expects an exact 4-digit number. 6 digit numbers are assumed to be URNs and 8-digit numbers are assumed to be UKPRNs. We cannot do partial number matches at the moment.
=> Extend search service to search by establishment name and GIAS number

app/jobs/import/gias_establishment_import_job.rb, app/jobs/import/gias_headteacher_import_job.rb
`delete` a hash key resturns the value of that key, so this method is
not working as expected returning the deleted value instaead of the new
(smaller) hash, causing the same problem that we wanted to remove the
changes for!
=> Fix delete changes from import result

CHANGELOG.md, app/controllers/search_controller.rb, app/services/project_search_service.rb, app/views/search/_results_table.html.erb, app/views/search/results.html.erb, app/views/shared/_dfe_header.html.erb, app/views/shared/navigation/_dfe_header_search.html.erb, config/locales/search.en.yml, config/routes.rb, spec/features/users_can_search_for_projects_spec.rb, spec/requests/search_controller_spec.rb
Add UI search to the application (!)
Add a search box to the DfE header as per the [standard pattern](https://design.education.gov.uk/design-system/components/header#example3).
Add search results views which differ depending on the number of results.
No search term entered:
No results found: 
Results found:
=> Search projects

CHANGELOG.md, app/controllers/team/projects_controller.rb, app/models/project.rb, app/services/by_team_project_fetcher_service.rb, app/views/shared/navigation/_team_projects_primary_navigation.html.erb, app/views/team/projects/_new_table.html.erb, app/views/team/projects/new.html.erb, config/locales/en.yml, config/locales/project.en.yml, config/routes.rb, spec/features/your_team_projects/users_can_view_their_team_projects_spec.rb, spec/services/by_team_project_fetcher_service_spec.rb
Our views of projects are usually sorted by the significant date, which is the most valuable, but there are some instances where it is valuable to know what projects have been added and to view them in order of when they were first created.
=> Add New project table view for your team projects

app/models/gias/group.rb, db/migrate/20231108110923_add_gias_group.rb, db/schema.rb, spec/factories/gias/group_factory.rb, spec/models/gias/group_spec.rb
A Gias Group is what we currently think of as a "trust", but the data from GIAS contains more than just trusts, so for safety's sake we are calling them Groups.
Note that the Companies House number is being stored as a string, because it can contain leading zeros which are significant. If we stored it as an integer, Rails would "helpfully" strip off leading zeroes.
=> Add Gias::Group model

CHANGELOG.md, app/controllers/transfers/projects_controller.rb, app/forms/conversion/create_project_form.rb, app/forms/create_project_form.rb, app/forms/transfer/create_project_form.rb, app/views/conversions/projects/new.html.erb, app/views/transfers/project_information/_information_list.erb, app/views/transfers/project_information/_outgoing_trust_details.html.erb, app/views/transfers/project_information/_reasons_for_transfer.html.erb, app/views/transfers/projects/new.html.erb, config/locales/conversion_project.en.yml, config/locales/project.en.yml, config/locales/project_information.en.yml, config/locales/transfer_project.en.yml, db/migrate/20231114112915_add_attibutes_for_transfer_reason.rb, db/schema.rb, spec/factories/transfer/create_project_form_factory.rb, spec/factories/transfer/project_factory.rb, spec/features/transfers/users_can_create_a_transfer_project_spec.rb, spec/features/transfers/users_can_view_a_transfer_spec.rb, spec/forms/conversion/create_project_form_spec.rb, spec/forms/transfer/create_project_form_spec.rb, spec/models/conversion/project_spec.rb
Transfer projects are initiated for a bunch of different reasons that we need to capture and either resruface or use to make decisions within the business logic of the application.
Our first step is to collect the values and store them when creating a new transfer project.
Whilst it is likely some of this information is or should be captured earlier in the service, we are not yet in a position to fetch it, leaving this only best option right now.
The 'result of 2RI' reason already exists on a conversion project, so we reuse that.
The others are all new and since they only relate to a transfer, we decided to store the values on the transfer specific `tasks_data` as this is the intention for that table.
We expose each value on the 'About the project' tab as a first step.
This work does …
=> (146600) Add questions to new transfer form

CHANGELOG.md, app/forms/conversion/task/receive_grant_payment_certificate_task_form.rb, app/views/conversions/tasks/receive_grant_payment_certificate/edit.html.erb, config/locales/conversion/tasks/receive_grant_payment_certificate.en.yml, db/migrate/20231116110013_remove_update_kim_action_from_receive_grant_payment_task.rb, db/schema.rb, spec/accessibility/projects_spec.rb, spec/features/conversions/users_can_complete_a_conversion_project_spec.rb, spec/models/conversion/project_spec.rb
We are gradually removing any need for or mention of KIM in our applications, so remove this action in the Receive Grant Payment Certificate task as we do not want to encourage people to still use KIM.
=> Users are not directed to update KIM in 'Receive grant payment certificate' task

CHANGELOG.md, app/forms/conversion/task/proposed_capacity_of_the_academy_task_form.rb, app/models/conversion/task_list.rb, app/views/conversions/tasks/proposed_capacity_of_the_academy/edit.html.erb, config/locales/conversion/tasks/proposed_capacity_of_the_academy.en.yml, db/migrate/20231122162528_add_proposed_capacity_of_the_academy_task.rb, db/schema.rb, spec/features/conversions/users_can_complete_conversion_tasks_spec.rb, spec/models/conversion/task_list_spec.rb
This work adds in a new Conversion task, Proposed capacity of the academy, which has some customised validations for the text fields. 
If the `Not applicable` checkbox is not selected, then each text field is required to be filled with either the proposed capacity for that age group or with a `0`
=> Add proposed capacity of the academy task to Conversion projects

CHANGELOG.md, app/forms/transfer/task/bank_details_changing_task_form.rb, app/models/transfer/task_list.rb, app/views/transfers/tasks/bank_details_changing/edit.html.erb, config/locales/transfer/tasks/bank_details_changing.en.yml, db/migrate/20231128152937_add_transfer_bank_details_changing_task_attributes.rb, db/schema.rb, spec/features/transfers/users_can_complete_transfer_tasks_spec.rb, spec/models/transfer/task_list_spec.rb
This task indicates in the bank details for an establishment are changing on transfer.
=> Add "Bank details changing" task to Transfer projects

CHANGELOG.md, app/presenters/export/csv/project_presenter.rb, app/services/export/education_and_skills_funding_agency_csv_export_service.rb, config/locales/export/csv/project.en.yml, spec/presenters/export/csv/project_presenter_spec.rb
The proposed academy capacity numbers are now part of the ESFA csv export.
The headers are shown as:
=> Users can access the proposed academy capacity numbers in the esfa data export

CHANGELOG.md
Added
- Add ability to import GIAS groups from csv data
- transfer project now collect if they are a result of 2RI and show this information on the about the project tab
- transfer project now collect if they are a result of 2RI and show this information on the about the project tab
- transfer projects now collect if they are the result of an inadequate Ofsted inspection and show this information on the about the project tab
- transfer projects now collect if they are the result of financial, safeguarding or governance issues and who this information on the about project tab
- transfer projects now collect if the outgoing trust is expected to close once the transfer is completed and this is shown on the about the project tab
- Add a page to allow Grant management and finance unit members …
=> Release 47

terraform/README.md, terraform/container-apps-hosting.tf, terraform/variables.tf
* Event Hub namespaces are only useful if we intend on exporting logs out of Azure
=> Disable default deployment of Event Hub

CHANGELOG.md, app/models/concerns/teamable.rb, config/locales/teams.en.yml, config/locales/user.en.yml, spec/models/statistics/user_statistics_spec.rb, spec/models/user_spec.rb
We need a new user team to represent Business support users. Eventually these users will have access to all the exports in the system.
=> Add new "business_support" team for users

CHANGELOG.md, app/controllers/all/export/education_and_skills_funding_agency/conversions/projects_controller.rb, app/controllers/all/export/funding_agreement_letters/conversions/projects_controller.rb, app/controllers/all/export/grant_management_and_finance_unit/conversions/projects_controller.rb, app/views/all/export/education_and_skills_funding_agency/conversions/projects/index.html.erb, app/views/all/export/education_and_skills_funding_agency/conversions/projects/show.html.erb, app/views/all/export/funding_agreement_letters/conversions/projects/index.html.erb, app/views/all/export/funding_agreement_letters/conversions/projects/show.html.erb, app/views/shared/navigation/_all_projects_primary_navigation.html.erb, config/routes.rb, spec/features/all_projects/export/grant_management_and_finance_users_can_export_download_spec.rb, spec/features/projects/export/education_and_skills_funding_agency/users_can_export_esfa_data_spec.rb, spec/features/projects/export/funding_agreement_letters/users_can_export_fal_data_spec.rb, spec/requests/all/export/education_and_skills_funding_agency/conversions/projects_controller_spec.rb, spec/requests/all/export/funding_agreement_letters/conversions/projects_controller_spec.rb
We are starting to add exports for Transfers as well as Conversions.
In order to support this, we need to move the existing exports into a `conversions` namespace. This will allow us to keep the Conversion and Transfer exports separate (as they need to contain different data).
This follows the pattern already started for the Grant managment and finance unit exports, which already live in a `conversions` namespace.
For now, the `Export` link in the site navigation leads to the Conversion exports, as they are the only existing ones.
=> Move the existing ESFA and Funding letter exports to `conversion` namespace

CHANGELOG.md, app/views/all/by_month/projects/_revised_table.html.erb, app/views/all/by_month/projects/revised.html.erb, config/locales/en.yml, config/locales/project.en.yml, spec/accessibility/all_projects_spec.rb, spec/features/projects/revised_conversion_date/viewing_projects_with_a_revised_converison_date_spec.rb, spec/requests/all/by_month/projects_controller_spec.rb
This is part of the iterative work to the `By month` view. 
First steps here are to make the `By month` view be descripive of both `transfer` and `conversion` projects and reflect the current state of data displayed.
=> Update By month view language to reflect transfers and conversions

CHANGELOG.md, app/presenters/export/csv/incoming_trust_presenter_module.rb, app/presenters/export/csv/outgoing_trust_presenter_module.rb, app/presenters/export/csv/project_presenter.rb, app/services/export/transfers/academies_due_to_transfer_csv_export_service.rb, config/locales/export/csv/project.en.yml, spec/presenters/export/csv/incoming_trust_presenter_module_spec.rb, spec/presenters/export/csv/outgoing_trust_presenter_module_spec.rb, spec/presenters/export/csv/project_presenter_spec.rb, spec/services/export/transfers/academies_due_to_transfer_csv_export_service_spec.rb
Devops: [Task 150256](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/150256): Build the CSV
We need to generate a CSV of Academies due to transfer. The required CSV headers are as per the linked ticket.
Firstly, we needed to extend the Project presenter to present the required information from Transfer projects. Because all our previous exports were for Conversion projects, we didn't have all the fields necessary for a Transfer project (both project types have slightly different tasks data).
Once we have the necessary methods in the presenters, build a service to create a CSV with the required columns and information.
This CSV export is not currently linked from anywhere, so this work is not publicly accessible or testable in the UI.
=> (150256) Build an export for Academies due to Transfer

CHANGELOG.md, app/views/all/in_progress/projects/index.html.erb, app/views/service_support/projects/without_academy_urn.html.erb, app/views/shared/_christmas_notification_banner.html.erb, app/views/team/projects/unassigned.html.erb, app/views/your/projects/in_progress.html.erb
This banner is only being applied to the landing pages within the service to communicate the reduced support available over the christmas period.
=> Add reduced support service banner

CHANGELOG.md, app/controllers/all/export/education_and_skills_funding_agency/conversions/projects_controller.rb, app/controllers/all/export/funding_agreement_letters/conversions/projects_controller.rb, app/controllers/all/export/grant_management_and_finance_unit/conversions/projects_controller.rb, app/services/export/conversions/education_and_skills_funding_agency_csv_export_service.rb, app/services/export/conversions/funding_agreement_letters_csv_exporter_service.rb, app/services/export/conversions/grant_management_and_finance_unit_csv_export_service.rb, spec/services/export/conversions/education_and_skills_funding_agency_csv_export_service_spec.rb, spec/services/export/conversions/funding_letter_agreement_csv_exporter_service_spec.rb, spec/services/export/conversions/grand_management_and_finance_unit_csv_export_service_spec.rb
We currently only export services for `Conversions`, so this work is to accurately reflect what the export services do and to allow `Transfers` exports to be added in once that work is ready.
=> Move existing export services into a conversions namespace

CHANGELOG.md, app/controllers/all/export/by_month/transfers/projects_controller.rb, app/services/projects_for_export_service.rb, app/views/all/export/by_month/transfers/projects/index.html.erb, app/views/all/export/by_month/transfers/projects/show.html.erb, config/locales/export/by_month_csv_export.en.yml, config/locales/project.en.yml, config/routes.rb, spec/requests/all/export/by_month/transfers/projects_controller_spec.rb, spec/services/projects_for_export_service_spec.rb
[Task 148322](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/148322): Build the export journey to download the transfer reports
Now that we have a CSV export for Transfers in transferring in a given month, we can build a journey in the UI for the user to access this export.
First, the user visits an index page where they can see the next 6 months, with links to view the confirmed and revised transfers for each month.
Upon clicking on the Download link, the user is taken to a page where they see information about the export, and a link to download the CSV file
The resulting CSV export has the required columns as per previous ticket [Task 150256](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/150256): Build the CSV
=> (148322) Build the export journey for Academies due to transfer in a given month

CHANGELOG.md, app/assets/stylesheets/components/app-content.scss, app/controllers/all/export/projects_controller.rb, app/views/all/export/projects/index.html.erb, app/views/shared/navigation/_all_projects_primary_navigation.html.erb, config/locales/export/landing_page.en.yml, config/routes.rb, spec/features/all_projects/export/esfa_users_can_export_download_spec.rb, spec/features/all_projects/export/export_users_can_see_an_export_landing_page_spec.rb
To be merged after https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/1254
[Task 148320](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/148320): Build landing page for all exports for all users
We now have several different export types, and previously access to them was
constrained by the user's team (e.g. only ESFA users could see the ESFA exports)
We now want access to exports to be easier, and to do this we have added an
exports landing page. This lists all available exports, instead of restricting
access to exports by team type.
This export landing page is available to anyone who can view exports (currently
the `academies_operational_practice_unit` and `education_and_skills_funding_agency`
teams)
=> (148320) Build exports landing page

CHANGELOG.md, app/forms/conversion/create_project_form.rb, app/forms/transfer/create_project_form.rb, app/mailers/team_leader_mailer.rb, spec/forms/conversion/create_project_form_spec.rb, spec/forms/transfer/create_project_form_spec.rb, spec/mailers/team_leader_mailer_spec.rb
When a new Conversion project is created and handed over to RCS, the team leaders receive an email informing them.
However, when we build the Transfer project journey, this functionality was missed out.
Create a new mailer to send an email to the team leaders, informing them when a new Transfer is created and handed over to RCS. This duplicates the Conversions functionality, but uses a slightly different email template in GovUK Notify.
=> (150847) Send a notification when a Transfer is created and handed over to RCS

CHANGELOG.md, app/views/shared/project_information/_incoming_trust_details.html.erb
The `Conversion` project's `incoming trust sharepoint link` edit view was displaying the `outgoing trust sharepoint link` field too. 
This fixes this issue to correctly display only the `incoming trust sharepoint link` field.
=> Fix Conversion project incoming trust sharepoint link edit view

CHANGELOG.md, app/views/all/statistics/statistics/index.html.erb
This is a small fix to the statistics page, to the `by region` table for `Transfer's`. It was incorrectly pulling the `Conversion` data for `by region`.
This is now pulling the `Transfer` data for `by region`
=> Fix statistics page to show accurate data for Transfer's `by region`

CHANGELOG.md, app/forms/conversion/task/receive_grant_payment_certificate_task_form.rb, app/views/conversions/tasks/receive_grant_payment_certificate/edit.html.erb, config/locales/conversion/tasks/receive_grant_payment_certificate.en.yml, db/migrate/20240108113131_add_date_received_to_conversion_grant_payment_certificate_task.rb, db/migrate/20240109143032_split_conversion_grant_certificate_check_and_save_task.rb, db/schema.rb, spec/accessibility/projects_spec.rb, spec/features/conversions/users_can_complete_a_conversion_project_spec.rb, spec/features/conversions/users_can_complete_conversion_tasks_spec.rb, spec/forms/conversion/tasks/receive_grant_payment_certificate_task_form_spec.rb, spec/models/conversion/project_spec.rb
1. We need to be able to enter the date the Grant payment certificate was received to the Conversion task list. This was not a simple piece of work as we do not yet have any tasks that collect dates.
Refactor the Grant payment certificate task form to collect a date, or show an existing date if one was previously entered. We have also modified the `Project#grant_payment_certificate_received?` method to take the date received into account.
2. Then, split the "Check and save" action on this task into "Check" and "Save". This has required a database data migration for existing projects. 
Without an entered date
With an entered date
=> (151107) Add date field to Conversions Receive grant payment certificate task, and split "Check and save" action

CHANGELOG.md, app/forms/conversion/task/sponsored_support_grant_task_form.rb, db/migrate/20240110145231_remove_eligibility_from_sponsored_support_grant_task.rb, db/schema.rb, spec/features/conversions/users_can_complete_conversion_tasks_spec.rb
In commit https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/commit/640256d1da7ce2f76086f043979f5744d41b8597 we removed the old `eligibility` question from the `SponsoredSupportGrantTaskForm` and replaced it with a series of radio buttons instead. However, the eligibility attribute and associate database column were not removed.
As we had removed the checkbox from the UI, users were unable to check off the `eligibility` question and therefore the task was never completable.
Remove the eligibility attribute from the task form, and the associated db column. Also add a test to demonstrate the task is still completable - this was missing before and the reason we didn't pick up the bug.
=> (Fix) The Sponsored support grant task is not completable

CHANGELOG.md, app/services/import/grant_certificate_date_importer_service.rb, config/locales/en.yml, lib/tasks/project_tasks/project_data_import.rake, spec/lib/tasks/project_tasks/project_data_import_spec.rb, spec/services/import/grant_certificate_date_importer_service_spec.rb
In https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/1283 we added a new date field to the Conversion Grant payment certificate received task.
Some Conversion projects are already completed in production and therefore cannot be edited by users. We need a way to backfill these projects with their relevant dates.
A spreadsheet has been supplied with URNs of the academies, and the date the grant payment certificate was received. Once this script is deployed, we can run the associated rake task with this CSV (uploaded to Azure) and update the relevant projects.
=> Script to backfill Grant payment certificate dates for live data

CHANGELOG.md, app/forms/transfer/task/check_and_confirm_financial_information_task_form.rb, app/models/transfer/task_list.rb, app/views/transfers/tasks/check_and_confirm_financial_information/edit.html.erb, config/locales/transfer/tasks/check_and_confirm_financial_information.en.yml, db/migrate/20240111162641_add_transfer_check_and_confirm_financial_information_task_attributes.rb, db/schema.rb, spec/features/transfers/users_can_complete_transfer_tasks_spec.rb, spec/models/transfer/task_list_spec.rb
A new task where users can state if an academy and trust for a transferring academy are in a financial surplus or deficit. The collected answers are strings ("surplus" or "deficit"), or the task can be marked as Not applicable.
Add the task to the bottom of the kick-off section.
=> (151369) Add new Transfer Check and confirm financial information task

CHANGELOG.md, app/presenters/export/csv/project_presenter.rb, app/services/export/transfers/grant_management_and_finance_unit_csv_export_service.rb, config/locales/export/csv/project.en.yml, spec/presenters/export/csv/project_presenter_spec.rb
To be merged after https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/1289
Expose the new Check and confirm financial information values for Transfers in the Grant management and finance unit export.
=> (151370) Check and confirm financial information values added to Grant management export

CHANGELOG.md, app/models/conversion/project.rb, app/models/gias/establishment.rb, app/views/projects/shared/_with_academy_urn_table.html.erb, spec/features/project_information/users_can_view_academy_details_spec.rb, spec/features/service_support/users_can_navigate_the_application_spec.rb, spec/models/conversion/project_spec.rb, spec/models/gias/establishment_spec.rb, spec/requests/all/projects_controller_spec.rb
To be merged after #1304 and #1300 
Now that we have local Gias::Establishment data uploaded from GIAS by service support, we can use these records to display academy data. The records should include entries for academies which have not yet opened, and are not available on the Academies API.
On the Conversion project information page, show the data for the new academy as retrieved from Gias::Establishment records. Also add some checks to the views to only show academy data if it is present.
=> (147050) Fetch academy details on Conversion project page from local Gias::Establishment records

CHANGELOG.md, app/helpers/project_helper.rb, app/models/user.rb, app/policies/project_policy.rb, app/policies/task_list_policy.rb, spec/helpers/project_helper_spec.rb, spec/models/user_spec.rb, spec/policies/project_policy_spec.rb, spec/policies/task_list_policy_spec.rb
The service support user does a lot of data quality work in KIM and updates projects within this service on behalf of regional delivery officers when there is an error. This change will allow this process to happen without needing the assigned user to be present and make the process a lot simplier.
=> Enable service support users to be able to update all projects

CHANGELOG.md, app/presenters/export/csv/project_presenter.rb, app/services/export/transfers/academies_due_to_transfer_csv_export_service.rb, config/locales/export/csv/project.en.yml, spec/presenters/export/csv/project_presenter_spec.rb
The header for the "All conditions met" column in the Transfers export should be
"Authority to proceed"
The simplest way to do this is to add a `authority_to_proceed` alias to the
Project Presenter, and use this to return the `all_conditions_met` method. 
Because the name of the method (alias) is `authority_to_proceed`, we
can add a new I18n string to the file with the correct header.
Therefore when we call the column header `authority_to_proceed` in the export,
we get the I18n string for `authority_to_proceed` as the header, and the value
of `all_conditions_met` in the value.
=> (154339) Change "All conditions met" header in exports for Transfer projects

CHANGELOG.md, config/locales/export/csv/project.en.yml
We received a bug report that the strings for `full_sponsored` and `intermediate` values were missing from the CSV reports. We added/corrected the string for intermediate in a previous commit (ba9244254ad1d63f361b9535081133c89cec92df)
=> (Fix) Add missing I18n string for Conversion data export

CHANGELOG.md, app/presenters/export/csv/school_presenter_module.rb, app/services/export/transfers/academies_due_to_transfer_csv_export_service.rb, config/locales/export/csv/project.en.yml, spec/presenters/export/csv/school_presenter_module_spec.rb
Add School phase, school age range, school type, and main contact details to the Academies due to transfer export
=> Add more columns to the Academies due to transfer export

CHANGELOG.md, app/presenters/export/csv/project_presenter.rb, spec/presenters/export/csv/project_presenter_spec.rb
we had a bug report that the exports did not always contain the correct main contact details for the school. While the `Project.main_contact` association works fine in the UI the project presenter pattern is always returning the first Contact association, and not the one indicated by the `main_contact_id` attribute.
To temporarily fix this, return the main contact details in the project presenter a different way. We will have to circle back to this and figure out why the associations aren't working as expected at a later date.
=> Bugfix: Return the correct main contact details in the project presenter

CHANGELOG.md, app/presenters/export/csv/academy_presenter_module.rb, app/services/export/conversions/education_and_skills_funding_agency_csv_export_service.rb, config/locales/export/csv/project.en.yml, spec/presenters/export/csv/academy_presenter_module_spec.rb
We need to add to the funding agreement letters export:
- Academy UKPRN. This can be retrieved from the GIAS::Establishment record associated with the project. In a previous commit we changed the academy associated with the project from an AcademiesApi::Establishment to GIAS::Establishment, so alter the academy presenter test to use the correct association, and retrieve the Academy UKPRN from the GIAS::EStablishment
- School DfE number. We already have a presenter for this.
- Academy DfE number. Add a new presenter for this.
=> Add more columns to the ESFA funding agreement letters export

CHANGELOG.md, app/assets/stylesheets/application.scss, app/assets/stylesheets/components/date-range.scss, app/controllers/all/by_month/conversions/projects_controller.rb, app/helpers/project_helper.rb, app/views/all/by_month/conversions/projects/_by_month_table.html.erb, app/views/all/by_month/conversions/projects/date_range.html.erb, app/views/shared/_date_range.html.erb, app/views/shared/navigation/_all_projects_primary_navigation.html.erb, config/initializers/date_formats.rb, config/locales/project.en.yml, config/routes.rb, spec/features/all_projects/by_month/data_users_can_choose_a_date_range_spec.rb, spec/helpers/project_helper_spec.rb, spec/requests/all/by_month/conversions/projects_controller_spec.rb, spec/requests/conversions/projects_controller_spec.rb
Change the By Month view for data consumers (i.e. people who can Export). They now see a date range picker that allows them to view a set of months. By default the page is set to the current month. If they choose a from date that's after the to date, they see an error message.
The table has slightly different columns to before.
There is a place to put the link to download the information as CSV, but this has not been developed yet.
Transfers are TBA.
=> (154582) By Month view for data consumers - Conversions

CHANGELOG.md, app/controllers/all/by_month/conversions/projects_controller.rb, app/services/by_month_project_fetcher_service.rb, app/views/all/by_month/conversions/projects/_by_month_table.html.erb, app/views/all/by_month/conversions/projects/single_month.html.erb, app/views/shared/navigation/_all_projects_primary_navigation.html.erb, config/locales/project.en.yml, config/routes.rb, spec/features/all_projects/by_month/users_can_view_projects_by_month_spec.rb, spec/requests/all/by_month/conversions/projects_controller_spec.rb, spec/services/by_month_project_fetcher_service_spec.rb
To be merged after #1330 and #1338 
Add a new view for non-data consumer users to view a list of Conversion projects
with a significant date in the upcoming month. The table view is identical to
the date range view added in https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/1330
Non-data consumer users do not see the date range picker, and instead only see
the upcoming month. We have built in the ability for a different month to be
viewed by manipulating the URL.
=> (154885) By month view for Caseworkers & other non-data consumer users - Conversions

.github/workflows/build-and-push-image.yml, .github/workflows/ci-checks.yml, .github/workflows/continuous-integration-terraform.yml
Updates the github actions versions we use to be ones that support node 20 now that node 16 is being deprecated.
See: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
=> Update workflows to use actions on node 20

CHANGELOG.md, app/policies/export_policy.rb, spec/features/all_projects/export/export_users_can_see_an_export_landing_page_spec.rb, spec/policies/export_policy_spec.rb
We added the business support team a while ago, but never actually granted any rights to users in that team. Add them to the "can export" team group via the ExportPolicy. Check they can see the export pages.
=> (156240) Enable business support users to view exports

CHANGELOG.md, app/presenters/export/csv/academy_presenter_module.rb, app/presenters/export/csv/outgoing_trust_presenter_module.rb, app/presenters/export/csv/school_presenter_module.rb, app/services/export/transfers/by_month_csv_export_service.rb, config/locales/export/csv/project.en.yml, spec/presenters/export/csv/academy_presenter_module_spec.rb, spec/presenters/export/csv/outgoing_trust_presenter_module_spec.rb, spec/presenters/export/csv/school_presenter_module_spec.rb, spec/services/export/transfers/by_month_csv_export_services_spec.rb
Create a `by month` CSV export for Transfers. 
We have added alias methods to extract the establishment information for a Transfer from the `project.establishment` association but with different Column labels from the original `school_name`, `school_urn` (etc) implementations. Because Conversions get their data for their new academies from the `project.academy` association, we were unable to use the `academy_name`, `academy_urn` (etc) implementations for extracting Academy information in Transfers, because Transfers do not use the `project.academy` association. The required "Academy" information is on the `project.establishment` association. By creating alias methods, we can use the same methods to extract `project.establishment` data, but use labels more suited to Transfer projects (e.g. …
=> Create a by month csv export for Transfers

app/presenters/export/csv/academy_presenter_module.rb, app/presenters/export/csv/local_authority_presenter_module.rb, spec/presenters/export/csv/academy_presenter_module_spec.rb, spec/presenters/export/csv/local_authority_presenter_module_spec.rb
When testing the CSV exports for Conversions and Transfers, we noticed that the Local Authority and School/Academy contacts in the CSVs did not match the contacts in the UI.
Upon investigation, we realised the UI uses the ContactsFetcherService to get *all* contacts for a project, not just the Contact::Project ones, and display them on the UI grouped by category type. Some of the contacts in the UI are Contact::EStablishment contact types, which are linked to the projects via the `urn` of the project.
To fix, we are now calling ContactsFetcherService in the CSV presenters, and picking out the desired contacts by their category type. This means the contacts can be a mix of Contact::Project and Contact::Establishment. This also means that some CSVs will have multiple contacts in the same …
=> (Fix) Return all local authority and establishment contacts for a project in CSV

app/presenters/export/csv/incoming_trust_presenter_module.rb, app/presenters/export/csv/outgoing_trust_presenter_module.rb, app/presenters/export/csv/project_presenter.rb, spec/presenters/export/csv/incoming_trust_presenter_module_spec.rb, spec/presenters/export/csv/outgoing_trust_presenter_module_spec.rb
In https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/1366 we used the ContactsFetcherService to correctly return all contacts for a project in order to pull out the local authority and school/academy contacts. We now need to duplicate this work for Trust contacts, and for completeness we have used the same method to get the Diocese and Solicitor contacts this way.
This means that if a contact is not a Contact::Project but instead a Contact::Establishment contact, we still get them and put them in the CSV.
=> (Fix) Return all other contacts for a project in CSV via ContactsFetcherService

db/migrate/20240214120824_add_trn_and_trust_name_to_projects.rb, db/schema.rb
We need to add a new project type of "Form a MAT". Due to time constraints, we are adding this in as stripped-back a form as possible. Form a MAT projects are Conversion or Transfer projects which are grouped together under a new Trust. As this Trust does not yet exist in GIAS, we need to store its name and TRN somewhere - so we will store it for now on the projects.
As the Trust doesn't exist in GIAS, we cannot reference it using the UKPRN from GIAS/Academies API.
=> (156391 ) Add new trust name & reference number to projects (for Form a MAT)

app/models/project.rb, spec/models/project_spec.rb
To be merged after #1353 and #1355 
Add a small helper method to allow projects to be identified as Form a MAT or not. If a project has a Trust reference number and Trust name, and no Incoming Trust UKPRN, we assume it is Form a MAT.
=> (156694) Projects can say if they are Form a MAT

CHANGELOG.md, app/presenters/export/csv/project_presenter.rb, app/services/export/conversions/grant_management_and_finance_unit_csv_export_service.rb, app/services/export/transfers/grant_management_and_finance_unit_csv_export_service.rb, app/services/projects_for_export_service.rb, config/locales/export/csv/project.en.yml, spec/presenters/export/csv/project_presenter_spec.rb, spec/services/projects_for_export_service_spec.rb
The Grant management and finance unit want their csv export to include both
confirmed and provisional projects. They also want to see the provisional date
regardless - this helps them manage their work.
This work takes the steps to make this happen:
- alter the scopes to include both confirmed and provisional projects
- allow the csv presenter to show the provisional date
- include the provisonal date in the csv export for conversions and transfers
I don't think this export is currently exposed in the UI, but you can get to it at:
`/projects/all/export/grant-management-and-finance-unit/conversions/`
=> (157556) Grant managment export include provisional projects

sonar-project.properties
Now we have Sonarcloud able to read our coverage report, we have to
tweak what is thinks is 'testable code', we would not expect to have
test coverage on:
- Rails config
- Migration files
- Database config
- Our generators
So we exclude them.
=> Update Sonarcloud exclusions

sonar-project.properties
When we excluded these locations they should have been globs.
=> Use globs in the Sonarcloud exclusions

CHANGELOG.md, app/helpers/project_helper.rb, spec/helpers/project_helper_spec.rb
We can think of these two dates as:
- Confirmed: The most current significant date for the project
- Original: The provisional date i.e. the first significant date whent
the project was created
We want the behaviour here to be:
- when the date is provisional: show nothing
- when the date is confirmed: show the current confirmed date with the
provisional date as the 'original' in brackets
Because project dates can move forwards and back there is no 'order' to
how the dates appear.
=> (157550) Fix: Confirmed/Original date

app/presenters/export/csv/project_presenter.rb, spec/presenters/export/csv/project_presenter_spec.rb
We have a 'not applicable' locale already so it makes sense to use it
here, Sonarcloud is monaing about the repeated string and by moving to
locales we can ignore it.
=> Use locales instead of strings

CHANGELOG.md, app/presenters/export/csv/project_presenter.rb, config/locales/export/csv/project.en.yml, spec/presenters/export/csv/project_presenter_spec.rb
The assigned_to_name and assigned_to_email assumed that projects are
always assigend to a user, which is not technically the case.
We discovered this whilst testing one of the csv exports where we have
added a new column of data.
Adding a guard resolves this, outputting 'unassigned' as a more useful
indictator than a empty cell.
=> (157961) Fix unassigned project can render to csv

app/models/contact/project.rb, app/models/project.rb, app/presenters/export/csv/project_presenter.rb, spec/forms/conversion/tasks/funding_agreement_contact_task_form_spec.rb, spec/forms/transfer/tasks/main_contact_task_form_spec.rb, spec/models/project_spec.rb
Conceptually all these 'main contact' associations work the same way, when we added them we got the `belongs_to`/`has_one` declarations the wrong way around, they worked, but when other `Project.contacts were` present, these would get returned as the 'main contacts' in error.
This work fixes this by declaring the `belongs_to` on the class that contains the foreign key, `Project` here, see the Rails guide:
https://guides.rubyonrails.org/association_basics.html#choosing-between-belongs-to-and-has-one
We've kept this work focused on fixing the associations and nothing else.
=> Fix main contact associations

CHANGELOG.md, app/services/export/conversions/education_and_skills_funding_agency_csv_export_service.rb, app/services/export/conversions/funding_agreement_letters_csv_exporter_service.rb, app/services/export/transfers/academies_due_to_transfer_csv_export_service.rb, app/services/projects_for_export_service.rb, spec/services/projects_for_export_service_spec.rb
The follow csv exports now include both provisional and confirmed projects and include the provisional date in the exported columns:
- Academies due to transfer csv export
- Funding agreement letter csv export
- ESFA csv export
This brings them inline with the two pre-opening grant exports, leaving only the 'by-month' export without the provisonal date.
=> (156033) Add provisional dates to more exports

CHANGELOG.md, app/presenters/export/csv/project_presenter.rb, app/services/export/conversions/grant_management_and_finance_unit_csv_export_service.rb, spec/presenters/export/csv/project_presenter_spec.rb
Add date grant payment certificate received date to the Grant managemnet and finance unit conversions csv export.
We already include this in the 'by month' export so we update the nil state to return 'unconfirmed' and added it to the correct export.
=> (158338) Add grant payment certificate received to csv export

CHANGELOG.md, app/forms/conversion/task/update_esfa_task_form.rb, config/locales/conversion/tasks/update_esfa.en.yml, spec/features/conversions/users_can_complete_conversion_tasks_spec.rb, spec/forms/conversion/tasks/update_esfa_task_form_spec.rb
We cannot use KIM so this task has to change. 
We update the content to ask users to add a task note instead.
The task is only compelte when the task is checked AND at least one task note is added.
=> (156562) Change the update ESFA task

app/presenters/export/csv/incoming_trust_presenter_module.rb, app/presenters/export/csv/outgoing_trust_presenter_module.rb, spec/presenters/export/csv/incoming_trust_presenter_module_spec.rb, spec/presenters/export/csv/outgoing_trust_presenter_module_spec.rb
While a user can select a main outgoing/incoming trust contact ID, not all projects have one selected. If this is the case, we can try to fall back onto the next trust contact, instead of presenting an empty column.
=> (158463) Fall back to next trust contact if a project doesn't have a main trust contact

CHANGELOG.md, app/presenters/export/csv/project_presenter.rb, app/services/export/conversions/education_and_skills_funding_agency_csv_export_service.rb, config/locales/export/csv/project.en.yml, spec/presenters/export/csv/project_presenter_spec.rb
This work includes the 'Add notes for ESFA' notes in the appropriate csv export.
Based on #1393
=> (157876) Include ESFA notes in export

CHANGELOG.md, app/models/api/members_api/member_details.rb, spec/models/api/members_api/member_details_spec.rb
We were having an error on production related to an incomplete or missing MP details record from the Parliamentary Members API:
```
undefined method `email' for nil:NilClass @member_contact_details.email
```
It seems the MP details are not totally missing, otherwise the guard on `app/presenters/export/csv/mp_presenter_module.rb:9` `Export::Csv::MpPresenterModule#mp_email`
would have caught it.
This fix should guard against the error reoccurring.
=> (Fix) Handle incomplete member details from the Parliamentary Members API

CHANGELOG.md, app/views/all/in_progress/projects/index.html.erb, app/views/service_support/projects/without_academy_urn.html.erb, app/views/your/projects/in_progress.html.erb
We'll keep the banner for future use and remove the places it was
rendered.
=> Remove the maintenance banner

CHANGELOG.md, app/forms/conversion/create_project_form.rb, app/forms/transfer/create_project_form.rb, spec/forms/conversion/create_project_form_spec.rb, spec/forms/transfer/create_project_form_spec.rb
We usually validate the provisional conversion/transfer date on a project to always be in the future. However, as we are asking users to input historical projects into Complete ahead of KIM shutting down, we need to loosen this validation rule to allow projects with conversion/transfer dates in the past to be added to the system.
We can re-introduce this validation at a later date.
=> (158871) Temporarily remove the future date validation on project creation

CHANGELOG.md, app/presenters/export/csv/incoming_trust_presenter_module.rb, app/presenters/export/csv/outgoing_trust_presenter_module.rb, app/presenters/export/csv/project_presenter.rb, app/presenters/export/csv/school_presenter_module.rb, app/services/contacts_fetcher_service.rb, app/services/export/conversions/funding_agreement_letters_csv_exporter_service.rb, config/locales/export/csv/project.en.yml, spec/presenters/export/csv/incoming_trust_presenter_module_spec.rb, spec/presenters/export/csv/outgoing_trust_presenter_module_spec.rb, spec/presenters/export/csv/project_presenter_spec.rb, spec/presenters/export/csv/school_presenter_module_spec.rb, spec/services/contacts_fetcher_service_spec.rb
Add more columns to the Funding agreement letters export: School contact details, Incoming trust contact details and "Other" contact details.
=> (158464) Add School, Incoming trust and "Other" contacts to Funding agreement letters export

CHANGELOG.md, app/controllers/transfers/projects_controller.rb, app/forms/transfer/create_project_form.rb, app/views/transfers/projects/new_mat.html.erb, config/locales/transfer_project.en.yml, config/routes.rb, spec/features/transfers/users_can_create_a_transfer_project_spec.rb
This form is available at `/projects/transfers/new_mat` and will create a new "Form a MAT" transfer project. This is much like the form created for "Form a MAT" conversions in https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/1355
=> (158810) Add a form to create Form a MAT transfer projects

CHANGELOG.md, app/forms/conversion/task/confirm_date_academy_opened_task_form.rb, app/forms/transfer/task/confirm_date_academy_transferred_task_form.rb, app/models/conversion/task_list.rb, app/models/transfer/task_list.rb, app/views/conversions/tasks/confirm_date_academy_opened/edit.html.erb, app/views/transfers/tasks/confirm_date_academy_transferred/edit.html.erb, config/locales/conversion/tasks/confirm_date_academy_opened.en.yml, config/locales/transfer/tasks/confirm_date_academy_transferred.en.yml, db/migrate/20240228171427_add_confirm_date_academy_opened_attributes_to_conversion.rb, db/migrate/20240306112000_add_confirm_date_academy_transferred_attributes_to_transfer.rb, db/schema.rb, spec/features/conversions/users_can_complete_conversion_tasks_spec.rb, spec/features/transfers/users_can_complete_transfer_tasks_spec.rb, spec/forms/conversion/tasks/confirm_date_academy_opened_task_form_spec.rb, spec/forms/transfer/tasks/confirm_date_academy_transferred_task_form_spec.rb, spec/models/conversion/task_list_spec.rb, spec/models/transfer/task_list_spec.rb
A user can now confirm the date the conversion of transfer happened.
We lean on the existing receive grant payment certificate task to
validate the three parameter date, our use case is slightly different as
the date can be updated once set.
We also added some range validation on the year to help catch errors.
We did look to extract some of the validation to share among the form
objects, but on balance decided the duplication was better than the
miss-direction.
=> User can confirm the date the conversion or transfer happened

CHANGELOG.md
Due to a merge error, the Changelog entry for PR
https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/1400 has ended up in the wrong spot.
=> (Fix) Correct Changelog entry for Funding agreement letters PR

CHANGELOG.md, app/views/projects/shared/_new_projects.html.erb, spec/requests/project_management_spec.rb
=> (158812) Add a button to allow users to create a new Form a MAT Transfer project

CHANGELOG.md, app/presenters/export/csv/project_presenter.rb, app/services/export/transfers/grant_management_and_finance_unit_csv_export_service.rb, config/locales/export/csv/project.en.yml, spec/presenters/export/csv/project_presenter_spec.rb
Show the date a transfer actually happened in the Grant management and finance unit export. Show "unconfirmed" if the value has not yet been entered.
=> (157070) Show the date a transfer happened (if available) in the Grant management export

config/database.yml
We have some BIG, unoptimised queries that are taking too long so we see
timeouts. We want to increase the time the application will wait for a
query to see if we can improved things in the short term.
The default for TinyTDS and so SQLServer is 5 seconds:
https://github.com/rails-sqlserver/tiny_tds?tab=readme-ov-file#tinytdsclient-usage
Although the value is supplied in milliseconds in the Rails
database.yml:
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/c0088ce4193a6b70d89ed4d4123bf8b388e92cc0/lib/active_record/connection_adapters/sqlserver_adapter.rb#L106
=> Allow database timeout to be set

CHANGELOG.md, app/forms/transfer/task/sponsored_support_grant_task_form.rb, app/models/transfer/task_list.rb, app/models/transfer/tasks_data.rb, app/presenters/export/csv/project_presenter.rb, app/services/export/transfers/grant_management_and_finance_unit_csv_export_service.rb, app/views/transfers/tasks/sponsored_support_grant/edit.html.erb, config/locales/export/csv/project.en.yml, config/locales/transfer/tasks/sponsored_support_grant.en.yml, db/migrate/20240311084953_add_transfer_sponsored_support_grant_task_attributes.rb, db/schema.rb, spec/features/transfers/users_can_complete_transfer_tasks_spec.rb, spec/models/transfer/task_list_spec.rb, spec/presenters/export/csv/project_presenter_spec.rb
Add a new task to the transfer task list that is basically a copy of the 'Confirm and process the sponsored support grant' with minor changes, it acually has less values to capture at this point.
We've kept the database attributes the same name as the conversion project version, as it is functionally the same, but as the value has to be exported with a different 'column header' we have to duplicate in the export presenter to allow for this.
=> (159072) Transfer confirm support grant task

app/controllers/external_contacts_controller.rb, app/presenters/export/csv/academy_presenter_module.rb, app/presenters/export/csv/incoming_trust_presenter_module.rb, app/presenters/export/csv/local_authority_presenter_module.rb, app/presenters/export/csv/outgoing_trust_presenter_module.rb, app/presenters/export/csv/project_presenter.rb, app/presenters/export/csv/school_presenter_module.rb, app/services/contacts_fetcher_service.rb, app/services/export/csv_export_service.rb, spec/presenters/export/csv/academy_presenter_module_spec.rb, spec/presenters/export/csv/incoming_trust_presenter_module_spec.rb, spec/presenters/export/csv/local_authority_presenter_module_spec.rb, spec/presenters/export/csv/outgoing_trust_presenter_module_spec.rb, spec/presenters/export/csv/project_presenter_spec.rb, spec/presenters/export/csv/school_presenter_module_spec.rb, spec/services/contacts_fetcher_service_spec.rb
We do a lot of fetching contacts and this service is pretty happy to hit
the database a lot. In production with ~120 projects, exports are taking
a full minute to run and so the app is timing out.
We want to start by optimising our queries and this is the first
candidate (with more to follow).
The principles here are:
- there can generally be one ContactsFetcherService for one Project as
it references the project internally
- our exports presenters are actually modules that all get mixed in to
`project_presenter` so we make one instance of ContactsFetcherService
available to all rather than instantiating (and so new db calls) new
ones
This change has a big impact on the presenter specs as we have to stub
extra methods or (as we chose) switch to factories.
The result of this is, for a …
=> Refactor ContactsFetcherService for performance

app/presenters/export/csv/academy_presenter_module.rb, app/presenters/export/csv/director_of_child_services_presenter_module.rb, app/presenters/export/csv/local_authority_presenter_module.rb, app/presenters/export/csv/project_presenter.rb, app/services/contacts_fetcher_service.rb, spec/presenters/export/csv/academy_presenter_module_spec.rb, spec/presenters/export/csv/director_of_child_services_presenter_module_spec.rb, spec/presenters/export/csv/local_authority_presenter_module_spec.rb, spec/services/contacts_fetcher_service_spec.rb
This work builds on #1422 and takes a similar view that we can load objects from the database once per project during the export process and re-use them.
We refactor the some of the presenter modules to expect instance variables that are loaded once by the `ProjectPresenter` class.
Testing locally shows this reduces database calls down to 8 per project, which feels about right.
=> Improve export performance: Part II

db/migrate/20240314083733_add_additional_indicies.rb, db/schema.rb
This is a bit speculative as I have no way to test this locally (not
enough seed data), but it seems reasonable that anything that is
referenced from one table to another would benefit from an index - these
all look to meet that criteria, so I've added one.
For the record:
Testing in production with the 'Conversion funding agreement letters
export' from April 2024 which contains 116 projects.
```
Benchmark.measure do
projects = ProjectsForExportService.new.funding_agreement_letters_projects(month: 4, year: 2024)
end
```
~2 seconds to fetch the projects and get their details from the
Academies API
```
Benchmark.measure do
Export::Conversions::FundingAgreementLettersCsvExporterService.new(projects).call
end
```
~38 seconds to generate the csv (Rails caches after this and we drop to
~6 …
=> (159705) Add additional database indicies

CHANGELOG.md, config/locales/conversion_project.en.yml, config/locales/transfer_project.en.yml
Trust TRN field hint text for Form a MAT conversions and transfers points user to a spreadsheet to get the trust reference number so they can add the project to Complete.
The text says open in new tab, but it opens in the same tab. This happens for conversions and transfers.
This work opens those links in new tabs.
=> Add Form a MAT project forms open TRN spreadsheet link in new tab

CHANGELOG.md, app/forms/concerns/conversion_datable.rb, app/forms/concerns/transfer_datable.rb, spec/forms/conversion/tasks/stakeholder_kick_off_task_form_spec.rb, spec/forms/transfer/tasks/stakeholder_kick_off_task_form_spec.rb
We need to temporarily remove the future date validation for confirmed significant dates. People are backfilling the application with projects already completed, and the confirmed dates will be in the past for some of these projects.
=> (159810) Temporarily remove future date validation for confirmed project dates

CHANGELOG.md, app/controllers/all/export/by_month/conversions/projects_controller.rb, app/services/projects_for_export_service.rb, app/views/all/export/by_month/conversions/projects/index.html.erb, app/views/all/export/by_month/conversions/projects/show.html.erb, config/locales/export/by_month_csv_export.en.yml, config/locales/export/education_and_skills_funding_agency_csv_export.en.yml, config/locales/export/funding_agreement_letters_csv_export.yml, config/locales/export/grant_management_and_finance_unit_csv_export.en.yml, config/locales/export/landing_page.en.yml, config/locales/project.en.yml, config/routes.rb, spec/features/all_projects/export/esfa_users_can_export_download_spec.rb, spec/features/all_projects/export/grant_management_and_finance_users_can_export_download_spec.rb, spec/requests/all/export/by_month/conversions/projects_controller_spec.rb, spec/services/projects_for_export_service_spec.rb
Build out the UI for the new "mega" Conversions export. This is at `/projects/all/export/by-month/conversions` but not currently linked from the Exports page.
=> (159129) Add UI for "all schools converting" mega-export

CHANGELOG.md, app/views/all/export/projects/index.html.erb, config/locales/export/landing_page.en.yml, spec/features/all_projects/export/esfa_users_can_export_download_spec.rb, spec/features/all_projects/export/export_users_can_see_an_export_landing_page_spec.rb
We only want to show 4 exports on the export landing page:
- The grant management & finance exports for Conversions & Transfers
- The "all by month" exports for Conversions and Transfers
=> (159431) Reconfigure the exports page

CHANGELOG.md, app/forms/transfer/task/declaration_of_expenditure_certificate_task_form.rb, app/models/transfer/task_list.rb, app/presenters/export/csv/project_presenter.rb, app/services/export/transfers/grant_management_and_finance_unit_csv_export_service.rb, app/views/transfers/tasks/declaration_of_expenditure_certificate/edit.html.erb, config/locales/export/csv/project.en.yml, config/locales/transfer/tasks/declaration_of_expenditure_certificate.en.yml, db/migrate/20240315085020_add_transfer_declaration_of_expenditure_certificate_task_attributes.rb, db/schema.rb, spec/features/transfers/users_can_complete_transfer_tasks_spec.rb, spec/models/transfer/task_list_spec.rb, spec/presenters/export/csv/project_presenter_spec.rb
Add the task to the transfers task list and the date value to the appropriate export.
Because the task has a date, we have to duplicate our code that handles this in the form, one day we might make that reusable, but that day is not today! 
Task in the list:
Task:
Included in the export:
=> (159930) Add declaration of expenditure certificate task

CHANGELOG.md, app/presenters/export/csv/project_presenter.rb, app/services/export/transfers/academies_due_to_transfer_csv_export_service.rb, config/locales/export/csv/project.en.yml, spec/presenters/export/csv/project_presenter_spec.rb
The AOPU want to continue to 'baseline' projects and want to know which
team a project is with, either:
- Regional Casework Services
- Regional group
We can include the `team` attribute in the appropriate export to meet
this need.
=> (159343) Export the team a project is assigned to

CHANGELOG.md, config/locales/conversion/tasks/redact_and_send.en.yml, config/locales/transfer/tasks/redact_and_send_documents.en.yml
This work adds new guidance to an action in the Redact and send documents tasks in both conversions and transfers.
The guidance explain how to name the files the user must send to the funding agreements mailbox.
=> Adding more guidance to Redact and send documents tasks

CHANGELOG.md, app/policies/assignment_policy.rb, app/policies/project_policy.rb, spec/policies/assignment_policy_spec.rb, spec/policies/project_policy_spec.rb
We wanted to allow Service Support to:
- edit any project details
- change the project conversion or transfer date
- change the assignment
It turned out most of this was already possible because we include Service
Support users in the `project_assigned_to_user?` policy method.
I found this really hard to follow, so I've taken it out and hopefully left
things a little simpler to follow.
This work also allows Service Support to change the assignment, something that
was not previously possible.
=> Refactor Service Support permissions

CHANGELOG.md, app/presenters/export/csv/project_presenter.rb, app/services/export/conversions/by_month_csv_export_service.rb, app/services/export/conversions/grant_management_and_finance_unit_csv_export_service.rb, app/services/export/conversions/schools_due_to_convert_csv_export_service.rb, app/services/export/transfers/academies_due_to_transfer_csv_export_service.rb, app/services/export/transfers/by_month_csv_export_service.rb, app/services/export/transfers/grant_management_and_finance_unit_csv_export_service.rb, config/locales/export/csv/project.en.yml
This work adds provisional conversion and transfer date columns to the 'by month' csv exports.
It also relabels the same columns in other exports instead of showing 'provisional date'.
=> (160892) Add provisional significant date to by month exports

CHANGELOG.md, app/models/concerns/significant_date.rb
The 'by month' views show only confirmed projects i.e. those with a
significant date that is NOT provisional.
There is no reasons to deal with the SignificantDateHistory here as we
have already filtered out any project that does not have a confirmed
significant date and we only want confirmed projects anyway.
The `significant_date` field holds this date and we can query it.
We only need to deal with SignificantDateHistory when we want projects
that were due to convert or transfer but have 'slipped' or 'slid' to
another month.
As we are looking for performance improvements, I will record the
current approx time for a request/response in production now, so that we
can compare the effect:
Date Range: Jan 2024 to Dec 2024
Date run: 25 Mar 2024
Time: ~13163ms
=> Update significant_date_in_range scope

CHANGELOG.md, app/forms/conversion/task/sponsored_support_grant_task_form.rb, app/forms/transfer/task/sponsored_support_grant_task_form.rb, spec/forms/conversion/tasks/sponsored_support_grant_task_form_spec.rb, spec/forms/transfer/tasks/sponsored_support_grant_task_form_spec.rb
We had a bug (more a UI anomaly) on the Sponsored Support Grant task: a user had previously selected a support grant type but now wanted the task to be "Not applicable". However because the support grant types are in radio buttons, they were unable to clear the value.
This confused the user, as although the task was now correctly logged as "not applicable" the UI showed the type still selected.
Override the `save` method on these two tasks, so that if the Not applicable box is checked, any value in sponsored_support_grant_type is removed.
=> (Fix) Clear the value of sponsored_support_grant_type if "Not applicable" ticked

CHANGELOG.md, app/models/api/members_api/client.rb, app/models/concerns/application_insights_event_trackable.rb, app/models/project.rb, config/locales/members_api.en.yml, spec/models/api/members_api/client_spec.rb, spec/models/concerns/appliation_insights_event_trackable_spec.rb, spec/models/contact/parliament_spec.rb, spec/models/project_spec.rb, spec/support/members_api_helpers.rb
We are seeing some Members API errrors in production that are stopping some view and exports from completing, this work is mosly focused on resolving that.
We do so by making the Memeber API client always retrun the same `Result` object and dealing with it appropriately.
With that done, we update the Application Insights event tracking so we can better surface errors and add event tracking to the Academies API for good measure.
=> Update Members API error handling and Application Insights events

CHANGELOG.md, app/presenters/export/csv/project_presenter.rb, config/locales/export/csv/project.en.yml, spec/presenters/export/csv/project_presenter_spec.rb
Feedback from ESFA is that the terms `single converter` and `single transfer` are not clear.
`join a MAT` has been used to help make this clearer and will also match the `form a MAT` convention too.
=> Replace conversion/transfer type wording to be more descriptive

CHANGELOG.md, app/presenters/export/csv/chair_of_governors_presenter_module.rb, app/presenters/export/csv/project_presenter.rb, app/services/export/conversions/schools_due_to_convert_csv_export_service.rb, config/locales/export/csv/project.en.yml, spec/presenters/export/csv/chair_of_governors_presenter_module_spec.rb
Based on #1467 
We recently added the ability to identify the chair of governors for a
school converting into an academy, which can now be included in the
export used for preparing and sending the funding agreement letters.
=> (161265) Include chair of governors contact in export

CHANGELOG.md, app/controllers/conversions/projects_controller.rb, app/forms/conversion/edit_project_form.rb, app/models/govuk_date_field_parameters.rb, app/views/conversions/projects/edit.html.erb, app/views/shared/project_information/_advisory_board_details.html.erb, config/locales/project.en.yml, spec/features/conversions/users_can_edit_project_details_spec.rb, spec/forms/conversion/edit_project_form_spec.rb, spec/models/govuk_date_field_parameters_spec.rb
As these attribute include a date, we had to overcome our friend 'three field date validation' - we've tried to solve it once for all and hope this new `GovukDateFieldParameter` class can be used wheneve we have a date, except on tasks as they are special!
@lozette we want you to have a look at this to make sure you are happy with the approach and then we can go back and refactor other forms to use this.
The rest of this work follows the existing patterns to allow project attributes to be changed.
=> (160908) Users can change the conversion advisory board details

spec/features/conversions/users_can_complete_conversion_tasks_spec.rb
While writing code elsewhere we uncovered a small anomaly in this test - the contact which is created to be the Chair of Governors contact for a project must actually belong to that project before it is assigned. In not linking the contact to the project, the test is actually reassigning the contact from one project to another, as well as updating its attributes.
This anomaly was showing up as a bug in other branches (specifically when working on soft deleting projects).
=> (Fix) A contact must be assigned to a project before it is added as chair of governors

CHANGELOG.md, app/controllers/conversions/projects_controller.rb, app/forms/conversion/create_project_form.rb, app/forms/conversion/edit_project_form.rb, app/forms/create_project_form.rb, app/helpers/project_helper.rb, app/views/conversions/project_information/_reasons_for_conversion.html.erb, app/views/conversions/projects/edit.html.erb, app/views/conversions/projects/new.html.erb, app/views/conversions/projects/new_mat.html.erb, app/views/shared/project_information/_advisory_board_details.html.erb, app/views/shared/project_information/_incoming_trust_details.html.erb, app/views/transfers/projects/new.html.erb, app/views/transfers/projects/new_mat.html.erb, spec/features/conversions/users_can_edit_project_details_spec.rb, spec/forms/conversion/edit_project_form_spec.rb
Based on #1481 
Following the existing pattern for allowing users to edit conversion project attributes, here we allow:
-  academy order type
- result of two requires improvement
to be changed.
=> (160908) Users can change directive academy order and two requires improvement responses

CHANGELOG.md, config/locales/conversion_project.en.yml, config/locales/transfer_project.en.yml
This work add the RCS acronym to the "Are you handing this project over to Regional Casework Services?" questions on the add project pages. This follows feedback that delivery officers often recognise the acronym over the name.
=> Adding RCS acronym to add project pages

app/models/project.rb, spec/factories/conversion/project_factory.rb, spec/factories/transfer/project_factory.rb
In https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/1473 we added the concept of state to projects. Now in addition to "active" and "completed", we have "deleted". This enables us to "soft delete" projects without actually removing their database records.
=> (161543) Projects can have deleted state

app/controllers/all/export/grant_management_and_finance_unit/conversions/projects_controller.rb, app/controllers/all/export/grant_management_and_finance_unit/transfers/projects_controller.rb, app/models/project.rb, app/policies/project_policy.rb, spec/features/projects/in_progress/users_can_view_a_list_of_all_projects_spec.rb, spec/features/your_projects/users_can_view_their_projects_spec.rb, spec/models/project_spec.rb, spec/models/statistics/project_statistics_spec.rb, spec/policies/project_policy_spec.rb, spec/services/projects_for_export_service_spec.rb
Now that we have the concept of "soft deleted" projects (projects which exist in the database but are in a deleted state) we need to ensure they never appear to users.
To ensure this, we have decided to use a `default_scope` for projects. Default scopes can be problematic as they can conceal issues and cause confusion - but the alternative is to add `active` and `completed` scopes to ALL calls to Project in the application. 
This does mean that we lose access to the `Project.deleted` scope, but if we need to call on deleted projects specifically we can unscope the default scope and call `Project.unscoped.where(state: :deleted)`
We then go on to add some Policy changes and extra specs, to make sure deleted projects do not appear in listing pages, and cannot be shown/edited.
=> (161623) Do not show "deleted" projects in application

CHANGELOG.md, app/assets/stylesheets/application.scss
When we adopted the DfE design system we switched the button colour to
DfE blue, this is not part of the design system and not consistent with
other products so we switch them back.
=> (162272) Make all primary buttons green

CHANGELOG.md, app/models/conversion/task_list.rb, spec/features/conversions/users_can_complete_conversion_tasks_spec.rb, spec/models/conversion/task_list_spec.rb
User research has shown that data consumers do not use this information
so we want to disable the task for now but not delete it.
This is achieved by removing the task from the task list definition.
We've also skipped the spec.
This work called for the note to be removed from the exports, but I cannot find it in any exports? It is in the presenter so may have been missed - so that user need is met?!
=> Disable the Add notes for ESFA task

CHANGELOG.md, config/locales/conversion/tasks/check_accuracy_of_higher_needs.en.yml, config/locales/conversion/tasks/complete_notification_of_change.en.yml
This work corrects references to the notification of change document. 
The correct name is the "notification of changes to funded high needs places form".
This change is reflected in content, including a task name.
The work also clarifies that it is the local authority who complete that form.
=> Updating content in high needs places task to use right name for form

CHANGELOG.md, app/controllers/projects_controller.rb, app/policies/project_policy.rb, app/views/projects/confirm_delete.html.erb, app/views/shared/projects/_actions.html.erb, config/locales/project.en.yml, config/routes.rb, spec/features/service_support/users_can_soft_delete_a_project_spec.rb, spec/requests/projects_controller_spec.rb
Now that projects can have a "deleted" state (where they do not appear on the UI but are still in the database) we want to allow service support users to "soft delete" a project.
To do this, we have used a "delete" route as opposed to the usual "destroy". As a result, the delete routes are not the same as the destroy routes for notes and contacts. "Destroy" implies the record is removed from the database, while the projects are only hidden, not removed.
We use a "confirm delete" pattern to be absolutely sure the user wants to delete the project, as there is currently no way for a user to restore a "deleted" project.
Once a project is "soft deleted", the user is returned to the All Projects list page, with a confirmation the project was deleted.
=> (161624) Service support users can "soft delete" a project

app/controllers/date_histories_controller.rb, app/models/project.rb, app/views/conversions/date_histories/index.html.erb, app/views/shared/projects/_significant_dates_table.html.erb, app/views/transfers/date_histories/index.html.erb, config/locales/project.en.yml, config/routes.rb, spec/features/conversions/users_can_change_the_conversion_date_spec.rb, spec/models/project_spec.rb
We store and some users want to see the history of the changes to the
significant date over time.
This commit adds a `/dates` path to projects and displays a table of the
date history.
We have intentionally not added a link to this view as it has not been
designed, it is merely a technical response to the fact we model this
behaviour.
=> Users can view date history

CHANGELOG.md, app/forms/conversion/create_project_form.rb, app/forms/transfer/create_project_form.rb, app/validators/form_a_multi_academy_trust_name_validator.rb, config/locales/project.en.yml, spec/forms/conversion/create_project_form_spec.rb, spec/forms/transfer/create_project_form_spec.rb, spec/validators/form_a_multi_academy_trust_name_validator_spec.rb
We want users to use the same New trust name on all projects in a 'form
a multi academy trust' collection.
To aid this we want to validate that:
- if a project for the same new trust already exists, the provided trust
names must match
The validator relies on the first returned project i.e. the first
project in the application locks the trust name, subsequent projects
will have to match or the first be corrected.
The trust names are not case sensitive, we convert them to UPPERCASE for
comparison.
We then use the validator on conversion and transfer projects.
=> (162829) form a multi academy trust name validator

CHANGELOG.md, app/presenters/export/csv/project_presenter.rb, spec/presenters/export/csv/project_presenter_spec.rb
In the export presenter the `option` was assigned the reason value when
it should be the option value.
This issue presented itself when we viewed existing projects in
development that were already set to 'commercial' but had `nil` reason -
this case is an exception we cannot do anything about as we don't know
the reason, the only option is for users to backfill the values.
Any project that has RPA of 'commercial' will now be in progress until a
reason is given.
=> Fix the RPA reason export value

doc/releases-and-deploys.md
We want to try and NOT tag a release before the product review so we can
still easily amend the release before it gets deployed.
Documenting this gives us a line to hold ourselves to.
=> Update the release and deployment docs

CHANGELOG.md, app/views/sessions/new.html.erb, app/views/shared/_dfe_footer.html.erb
This work fixes 2 broken links. One in the footer and one on the sign in page.
Both pointed to SharePoint guidance which has been moved.
=> Fixing broken link to SharePoint guidance

CHANGELOG.md, app/assets/stylesheets/application.scss, app/controllers/all/in_progress/projects_controller.rb, app/controllers/projects_controller.rb, app/controllers/root_controller.rb, app/views/all/in_progress/projects/_all_projects_tabs.html.erb, app/views/all/in_progress/projects/_conversions_table.html.erb, app/views/all/in_progress/projects/_transfers_table.html.erb, app/views/all/in_progress/projects/all_index.html.erb, app/views/all/in_progress/projects/conversions_index.html.erb, app/views/all/in_progress/projects/transfers_index.html.erb, app/views/shared/navigation/_all_projects_primary_navigation.html.erb, app/views/shared/navigation/_dfe_header_navigation.html.erb, app/views/shared/navigation/_header_navigation.html.erb, config/locales/project.en.yml, config/routes.rb, spec/accessibility/all_projects_spec.rb, spec/features/all_projects/export/esfa_users_can_export_download_spec.rb, spec/features/all_projects/export/export_users_can_see_an_export_landing_page_spec.rb, spec/features/home_page/user_without_role_spec.rb, spec/features/information_banner_spec.rb, spec/features/navigation/header_navigation_spec.rb, spec/features/projects/in_progress/users_can_view_a_list_of_all_projects_spec.rb, spec/features/projects/in_progress/users_can_view_all_in_progress_projects_by_type_spec.rb, spec/requests/all/in_progress/projects_controller_spec.rb
We want to split the all in progress projects view up into different tabs so users can scope in progress projects to:
- all
- conversions only
- transfers only
Then later this is the home for form a multi academy trust projects.
This work updates the existing view so that it sits in a tab and then adds the conversions and transfers tabs.
Along the way we noticed a style bug on the MOJ sub navigation item, and fixed it.
=> (162943) Split all projects in progress into tabs

CHANGELOG.md, app/controllers/form_a_multi_academy_trust/project_groups_controller.rb, app/models/form_a_multi_academy_trust/project_group.rb, app/views/form_a_multi_academy_trust/project_groups/_table.html.erb, app/views/form_a_multi_academy_trust/project_groups/_tabs.html.erb, app/views/form_a_multi_academy_trust/project_groups/show.html.erb, config/locales/form_a_multi_academy_trust_en.yml, config/routes.rb, spec/features/form_a_multi_academy_trust_spec.rb, spec/models/form_a_multi_academy_trust/project_group_spec.rb, spec/requests/form_a_multi_academy_trust/project_groups_controller_spec.rb
Schools and academies may come together to form a new Multi academy trust and users want to see these collections of projects reflected in the applicaiton.
We've creeated a simple object as an interface to this need and then added a show view for the object.
The `ProjectGroup` object loads projects with the same trust reference number so we can show them in a table.
The only gotya here is that we felt the same authorisation as projects applies to the project group, so we have to implement the `deleted?` method to use the `ProjectPolicy`.
The  `ProjectGroup` is so close to being an ActiveRecord model, I think it possibly should be, this would also make fetching multiple project groups faster (this is not implemented at this point).
=> (162958) Form a multi academy trust show view

.github/workflows/build-and-push-image.yml
When trying to run the matrix in the deployment workflow, only 1 seems to run because of a concurrency condition:
> [Canceling since a higher priority waiting request for xxx](https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/actions/runs/8739633643)
So hopefully adding this run_number is enough but it might not be
=> Try to prevent concurrency from stopping matrix runs

CHANGELOG.md, app/controllers/all/in_progress/projects_controller.rb, app/helpers/form_a_multi_academy_trust_helper.rb, app/models/form_a_multi_academy_trust/project_group.rb, app/services/form_a_multi_academy_trust/project_group_fetcher_service.rb, app/views/all/in_progress/projects/_all_projects_tabs.html.erb, app/views/all/in_progress/projects/_form_a_multi_academy_trust_table.html.erb, app/views/all/in_progress/projects/form_a_multi_academy_trust_index.html.erb, config/locales/project.en.yml, config/routes.rb, spec/features/projects/in_progress/users_can_view_all_in_progress_projects_by_type_spec.rb, spec/helpers/form_a_multi_academy_trust_helper_spec.rb, spec/models/form_a_multi_academy_trust/project_group_spec.rb, spec/requests/all/in_progress/projects_controller_spec.rb, spec/services/form_a_multi_academy_trust/project_group_fetcher_service_spec.rb
This is the final step to expose all 'form a multi academy trust' project groups to users.
This work adds a service object to collate the project groups and an index view to show them.
Some of this design is a bit odd:
- showing a single region for a project group assumes all project regions are the same which we have no validation for, so we show the region from the first project
- showing a single assigned_to users for a project groups assumes all projects are assigned the same, which we have no way to enforce, so we show the user from the first project
We also hit a Bullet false positive which is documented in the commit, but we ended up skipping bullet on the spec as our best option - please let us know if there is a better way.
=> (162946) Form a multi academy trust index view

CHANGELOG.md, app/forms/conversion/task/confirm_date_academy_opened_task_form.rb, app/models/conversion/project.rb, app/models/transfer/project.rb, config/locales/conversion_project.en.yml, spec/accessibility/projects_spec.rb, spec/features/conversions/users_can_complete_a_conversion_project_spec.rb, spec/models/conversion/project_spec.rb, spec/models/transfer/project_spec.rb
We want to make the "Date the academy opened" task mandatory on Conversion projects.
To do this, we have to add the task to the list of mandatory conditions & tasks in the project. Before adding it, we have refactored the `Conversion::Project.completable?` method slightly to make it easier to add more tasks/conditions.
Now when a user goes to complete a project, if the "Date the academy opened" task is not filled out, the user will see an error message telling them this task needs to be completed before the project is completed.
=> (163286) Make the "Date the academy opened" task mandatory on Conversion projects

app/views/all/in_progress/projects/_form_a_multi_academy_trust_table.html.erb, config/locales/project.en.yml
Because form a multi academy trust project groups do not exists, we just
load a collection based on the 'trust reference number', we cannot
really show the region and assigned to for the collection, they could be
different.
We did show them by using the values from the first project in the
collection, but this could cause confusion so we decided to take the
columns out.
=> (163645) Remove form columns from form a multi academy trust index table

CHANGELOG.md, app/presenters/export/csv/school_presenter_module.rb, spec/presenters/export/csv/school_presenter_module_spec.rb
If a school is a PRU/special school, the `school phase` will be "Not applicable" within the Academies API.
ESFA do not want to see "Not applicable" in the `school phase` column within the exports. So instead we now show the `school type` in the `school phase` column if the `phase` is missing.
=> Display school type instead of phase if the school phase is not applicable

app/services/import/academy_open_date_importer_service.rb, spec/services/import/academy_open_date_importer_service_spec.rb
This import service is intended to be run once by a developer and
assumes:
- we have console access in production
- we can upload the source data to the file share that is mounted inside
the running container
As this is a real data migration, we cannot run it in the development or
test environments as the data in those will not match the supplied data; 
This makes any kind of testing in those environments pretty low value.
We return a result that the developer running this service can copy and
paste from the console and supply to Service Support if there are
errors.
To run this service from the console:
```
result =
Import::AcademyOpenDateImporterService.new("path/to/source/file.csv").import!
```
=> (163285) Add service for one off academy open date import

app/presenters/export/csv/project_presenter.rb, spec/presenters/export/csv/project_presenter_spec.rb
The correct implementation and location for the `school_phase` method is
the `school_presenter` so we remove this one.
=> Remove duplicate presenter method

terraform/README.md, terraform/variables.tf
* We want to use the centralised RSD container registry instead of deploying one just for this service
=> Do not deploy a container registry by default

app/models/project.rb, spec/factories/conversion/project_factory.rb, spec/features/projects/viewing_completed_projects_spec.rb, spec/helpers/project_helper_spec.rb, spec/policies/contact_policy_spec.rb, spec/policies/note_policy_spec.rb, spec/policies/project_policy_spec.rb, spec/policies/task_list_policy_spec.rb
We previously determined if a project was completed by seeing if the `completed_at` date was present. Since we added an enum value for Project.state, which includes `completed`, we get `Project.completed?` for free. The enum method looks to see if a project has a state of `completed`.
We forgot to remove the old `Project.completed?` method which looks at the value of `completed_at`. This was an oversight.
Remove this old method and let the enum value of `state` take over. When we introduced the enum, we did a data migration to update all projects with a `completed_at` date to have the `completed` state, so this refactor should not affect the live data.
=> (163941) Refactor out the previous `Project.completed?` method

CHANGELOG.md, app/javascript/assign_user_autocomplete.js, spec/features/internal_contacts/users_can_change_the_assigned_user_with_autocomplete_spec.rb
As soon as we deployed the new autocomplete to development we realised
it was assume there is ALWAYS an assigned user, which is not true.
This work adds a spec to test this and fixes the autocomplete code to
handle the scenario.
=> Fix autocomplete handles no user

CHANGELOG.md, app/controllers/internal_contacts/projects_controller.rb, spec/requests/internal_contacts/projects_controller_spec.rb
The strong params for editing a project team do not work the way this
code tries to use.
Instead we separate out the conversion and transfer params and have each
return nil if the relevant param is missing, shifting the OR into the
calling code.
=> Fix edit project team works for transfers

CHANGELOG.md, Gemfile, Gemfile.lock, app/api/api.rb, app/api/auth_helpers.rb, app/api/v1/api.rb, app/api/v1/auth.rb, app/api/v1/healthcheck.rb, app/models/api_key.rb, config/routes.rb, db/migrate/20240509104059_create_api_keys.rb, db/schema.rb, spec/api/v1/auth_spec.rb, spec/api/v1/healthcheck_spec.rb, spec/models/api_key_spec.rb, spec/rails_helper.rb
Add the [Grape](https://github.com/ruby-grape/grape/) gem to enable us to add an API to the application. 
To demonstrate the API works, add a very simple "healthcheck" endpoint (cribbed from the [Grape demo app](https://github.com/ruby-grape/grape-on-rails)).
Next, show we can use Api key based authentication. Create a basic ApiKey model with a token & expiry date. Use this token in an "auth" endpoint to show we can authenticate users.
=> (Spike) Use the Grape gem to build an API

CHANGELOG.md, doc/api.md, lib/tasks/api_key/generate_api_key.rake, spec/lib/tasks/api_key/generate_api_key_spec.rb
Now that we have Api keys in the application, we need a way to generate them.
Add a rake task to generate keys, and documentation to inform developers of how
to generate them for production users.
=> Generate Api keys using a task

CHANGELOG.md, app/forms/conversion/create_project_form.rb, app/forms/create_project_form.rb, app/forms/transfer/create_project_form.rb, config/locales/project.en.yml, spec/forms/conversion/create_project_form_spec.rb, spec/forms/transfer/create_project_form_spec.rb
We have a number of different approaches to validating the GOV.UK three
field date fields and we want to consolidate them down.
This work updates the conversion and transfer create forms and uses the
`GovukDateFieldParameters` to validate the parameters before assignment
takes place.
Unfortunately, if any parameters are invalid there is not much we can do
accept clear them out, which leads to a nil value and we cannot give the
user useful feedback beyond what we have, e.g:
> Enter a date for the advisory board, like 1 4 2023
We've seen users entering two digit years and this error hints at that
issue, which is now covered.
We've tested the form objects extensively even though we can rely on
`GovukDateFieldParameters` - your taste might vary.
There is definitely scope for improvement here, …
=> (165667) Update date validations on create project forms

app/controllers/date_histories_controller.rb, app/forms/new_date_history_form.rb, config/locales/conversion_date_history.en.yml, config/locales/transfer_date_history.en.yml, spec/forms/new_date_form_spec.rb
We are consolidating our approach to date validation to use the
`GovukDateFieldParameters` class before assignment.
This work updates the conversion and transfer change significant date
form to use it. Because the validation sets any invalid dates to `nil`
and for this form, nil is not allowed, we can do nothing other than show
the error for blank state.
Base on #1569
=> (165750) update significant date validation

app/forms/conversion/task/receive_grant_payment_certificate_task_form.rb, config/locales/conversion/tasks/receive_grant_payment_certificate.en.yml, spec/forms/conversion/tasks/receive_grant_payment_certificate_task_form_spec.rb
We want all out date validation to work in a similar way.
This work updates the receive grant payment certificate task to use the
`GovukDateFieldParameters` before assignment.
Based on #1571
=> (166099) update date validation for receive grant payment certificate task

app/forms/transfer/task/confirm_date_academy_transferred_task_form.rb, config/locales/transfer/tasks/confirm_date_academy_transferred.en.yml, spec/forms/transfer/tasks/confirm_date_academy_transferred_task_form_spec.rb
We want to take the same approach to all our date validation, using the
`GovukDateFieldParameters` class before assignment takes place.
Based on #1571
=> (166101) Update confirmed transfer date task validation

app/forms/transfer/task/declaration_of_expenditure_certificate_task_form.rb, config/locales/transfer/tasks/declaration_of_expenditure_certificate.en.yml, spec/features/transfers/users_can_complete_transfer_tasks_spec.rb, spec/forms/transfer/tasks/declaration_of_expenditure_certificate_task_form_spec.rb
We want all our date validations to work the same way, using the
`GovukDateFieldParameters` class before assignment.
This work updates the transfer project declaration of expenditure task.
We've moved some feature specs into the form spec as they run faster
there.
Based on #1571
=> (166102) Update declaration of expenditure date validation

CHANGELOG.md, Gemfile, Gemfile.lock, app/api/api.rb, app/assets/config/manifest.js, app/controllers/swagger_controller.rb, app/javascript/swagger-initializer.js, app/views/layouts/swagger.html.erb, app/views/swagger/show.html.erb, config/initializers/assets.rb, config/initializers/content_security_policy.rb, config/routes.rb, package.json, spec/requests/swagger_controller_spec.rb, yarn.lock
This work adds the Swagger UI to the application on a public path and renders the Swagger docs that get generated by our API code.
The UI is at `/api/docs` and relies heavily on JavaScript, but out regular users are not the audiance for this information.
Our API is still in very early development and having the docs generated will help us build it out as well as provide low effort, long term documentation.
=> App includes Swagger UI for the API

app/views/layouts/swagger.html.erb
We need to prefix these paths for them to work in production where they
are pre-compiled into the directory `swagger-ui-dist`.
=> Correct asset paths for Swagger UI

app/javascript/swagger-initializer.js
We had this set to localhost which will not work in production like
environments.
=> Fix Swagger UI json path

CHANGELOG.md, app/models/api/academies_api/client.rb, app/models/api/academies_api/establishment.rb, app/models/api/academies_api/trust.rb, app/models/project.rb, spec/models/api/academies_api/client_spec.rb
These newer v4 endpoints fetch everything we need and do it about 70ms
quicker, so this feels worth doing.
=> Switch Academies API client to new endpoints

CHANGELOG.md, app/services/api/conversions/create_project_service.rb, spec/api/v1/conversions_spec.rb, spec/services/api/conversions/create_project_service_spec.rb
We use these validators to validate URN and UKPRN in the Create project form and Project model. Use them in the service object that creates projects via the API as well.
We also had to correct the URN in one of the API tests, as the original URN in that test (12345) was invalid. That test was not demonstrating param validation failure, so correct it to get the right test case!
=> Use validation on URN and UKPRN in the API project creation service

app/services/api/conversions/create_project_service.rb, spec/services/api/conversions/create_project_service_spec.rb
When we create projects, we also create their TasksData. We need to do this when creating projects via the API, as there is no other way to create a TasksData object (not even if we manually edit the project).
=> When creating the project via the API, also create an empty TasksData

app/services/api/conversions/create_project_service.rb, spec/services/api/conversions/create_project_service_spec.rb
We don't have a way of setting the region on a project except during project creation. It is set from the region of the establishment. We can fetch the establishment's region and set it during creation via the API.
=> Set Region on project during API creation

app/services/api/conversions/create_project_service.rb, spec/services/api/conversions/create_project_service_spec.rb
When we create a new project via the API with a new (unknown to Complete) user, we were putting this new user into the Regional casework services team. This is most likely incorrect, as RCS do not use the Prepare service. Instead, make an assumption that the Prepare user is from the same region as the establishment, and put them in the same regional team.
If this is not correct, the new user can be amended by Service Support later on
=> Put the newly-created user (from API) into a regional team

CHANGELOG.md, app/policies/project_policy.rb, app/policies/task_list_policy.rb, app/views/shared/projects/_task_list.html.erb, config/locales/project.en.yml, spec/policies/project_policy_spec.rb, spec/policies/task_list_policy_spec.rb, spec/requests/project_complete_spec.rb
This work allow Service Support users to update project and task data even after the project is completed.
It also fixes an issue where the 'complete project' button was shown on complted projects.
=> (167284) Update service support policies

CHANGELOG.md
- Add the Grape gem and demonstrate a simple Api endpoint in the application
- Add simple authentication to the Api endpoints using an Api key
- Add a task to generate Api keys, along with documentation
- A simple POST Api endpoint to create a Conversion project
- API documentation is now available at /api/docs
- Validation on the new Academy URN so that it cannot be the same as the school
URN has been added.
- The API does validation of URN and UKPRN on project creation
- When creating a new project, two digit dates are no longer accepted which
means incorrect dates cannot be submitted.
- The 'complete project' button is no longer shown on completed projects.
- URLs pointing links in content to SharePoint guidance updated to new guidance
pages
- The application fetches establishment and …
=> Release 70

CHANGELOG.md, app/api/v1/conversions.rb, app/services/api/conversions/create_project_service.rb, spec/api/v1/conversions_spec.rb, spec/services/api/conversions/create_project_service_spec.rb
The API can now create a Conversion Form a MAT project. The endpoint is `/api/v1/projects/conversions/form-a-mat` and is documented in the API Docs.
I created this as a spike branch but feel it can be added to the codebase alongside the `conversions` endpoint for now. Both endpoints need refining once we have more of the required data to create projects in Prepare.
=> (API) Form a MAT Conversion endpoint

app/api/v1/conversions.rb, app/services/api/conversions/create_project_service.rb, config/locales/project.en.yml, db/migrate/20240517100215_add_prepare_id_to_projects.rb, db/schema.rb, spec/api/v1/conversions_spec.rb, spec/models/project_spec.rb, spec/services/api/conversions/create_project_service_spec.rb
API changes:
- We now require the Prepare project ID on project creation, and store it on the created project. The Prepare ID is an integer.
=> API: Consume Prepare ID, return Complete ID

CHANGELOG.md, app/forms/transfer/task/conditions_met_task_form.rb, app/models/transfer/project.rb, app/views/transfers/tasks/conditions_met/edit.html.erb, config/locales/transfer/tasks/conditions_met.en.yml, db/migrate/20240523104451_add_additional_fields_to_all_conditions_met_for_transfers.rb, db/migrate/20240523125015_update_all_completed_transfers.rb, db/schema.rb, spec/features/transfers/tasks/users_can_complete_all_conditions_met_spec.rb
The "All conditions met" task should be called "Authority to proceed" for Transfers.
We have decided to keep the name of the attribute the same (`all_conditions_met`) for simplicity, but change the accompanying text. We have added an alias `authority_to_proceed` on the attribute.
We have also added two more checkboxes to this task.
=> (152117) Change the "All conditions met" task for transfers

CHANGELOG.md, app/presenters/export/csv/project_presenter.rb, config/locales/export/csv/project.en.yml, spec/presenters/export/csv/project_presenter_spec.rb
We have heard from users that their preference for the
'sponsored_grant_type' column header must be 'Project route and
sponsored grant type' and when not applicable the value must be
'voluntary converter - not eligible'.
Our content designer came up with this solution after much discussion
with users.
=> (167527) Rename column header and value

CHANGELOG.md, app/forms/transfer/task/form_m_task_form.rb, app/views/transfers/tasks/form_m/edit.html.erb, config/locales/transfer/tasks/form_m.en.yml, db/migrate/20240523112726_make_transfer_form_m_task_optional.rb, db/schema.rb, spec/features/transfers/users_can_complete_transfer_tasks_spec.rb
We have learnt that this task is often optional. This work allows it to
be marked as not applicable.
=> (167788) Update the Transfers form M task

CHANGELOG.md, app/assets/stylesheets/application.scss
We couldn't find the styles that are preventing this from being
underline so had to resort to ensuring it is applied with `!important`.
We can only assume it is either the DfE Frontend or the MOJ Frontend,
but inspecting the page shows `text-decoration: underline` is applied?
=> (146767) Fix: Skip to content style

CHANGELOG.md, app/policies/contact_policy.rb, spec/policies/contact_policy_spec.rb
During a product review we noticed that as a service support users we
couldn't edit contacts, our product owner felt this group of users
should be able to edit contacts, particularly the chair of governors
once added, this work fixes this.
The cause was the `has_role?` method does not include service support
users, the solution was a early return for service support users,
generally speaking, service support users can do 'anything'.
=> (162613) Fix: service support can edit all contacts

CHANGELOG.md, app/views/conversions/projects/edit.html.erb, app/views/conversions/projects/new.html.erb, app/views/conversions/projects/new_mat.html.erb, app/views/transfers/projects/edit.html.erb, app/views/transfers/projects/new.html.erb, app/views/transfers/projects/new_mat.html.erb
***Speculative work***
We have a number of fields where the user has to enter a unique
identifier, having autocomplete enabled on fields like these increases
the chance of errors at the cost of easily entering repeated uids, which
feels like a good trade off.
If a users enters an incorrect uids, the chances of doing so again also
increase as the browser will store the incorrect uid for
autocompletion.
=> Disable autocomplete on uid fields

app/models/concerns/significant_date.rb, app/services/by_month_project_fetcher_service.rb, spec/models/concerns/significant_date_spec.rb, spec/services/by_month_project_fetcher_service_spec.rb
The 'by month' export has a different criteria for which projects to
include than the other exports.
We want to offer all exports with a date range and want to utilise the
`significant_date_in_range` scope but without the `in_progress` and
`confirmed` scopes pre applied.
To do so we move those pre scopes to where they get used to render the
'by month' views and exports, leaving the scope focused only on the date
range and available for use in other exports.
=> (168420) Move scoping of project exports

terraform/README.md, terraform/providers.tf, terraform/versions.tf
By setting this value to `true` we can ensure any data sources used by the Container App module are correctly handled as HCL syntax instead of JSON.
JSON output was previously used in earlier versions of the AzAPI provider but they have since switched to using HCL which will eventually become the default instead of JSON.
=> Ensure data sources always output HCL instead of JSON

CHANGELOG.md, app/models/project.rb, app/models/transfer/project.rb, app/services/academies_api_pre_fetcher_service.rb, spec/models/project_spec.rb, spec/models/transfer/project_spec.rb, spec/services/academies_api_pre_fetcher_service_spec.rb
Background: We have an issue on Production where projects keep becoming invalid.
The UKPRN entered for the incoming trust, which was valid when the project was
created, is being changed upstream in the Academies DB. That change is then
being ingested into the Academies API, and when we try to load an existing
project, the UKPRN is not found and it significantly breaks the application
for users.
Because the Project model is "at rest", we do not think it needs validations.
Any Project creation or editing is done via FormObjects, which have their own
validations. We do not need to be validating the Projects on load into listing
pages, view pages or exports.
This PR enables the application to still work (load listing pages, show pages and exports) even if an invalid UKPRN is present in one of …
=> handle when UKPRNs are changed upstream

CHANGELOG.md, app/models/api/members_api/client.rb, config/locales/members_api.en.yml, spec/models/api/members_api/client_spec.rb, spec/models/project_spec.rb
We found a bug with the exports where a project is in an unknown constituency. We thought we had all exceptions handled but evidently not this one - and this error is likely to become more frequent following the upcoming constituency boundary changes.
Handle an unknown constituency. Also flesh out the error message to return the response status and searched-for term, which will make future debugging easier.
=> Do not raise an error when the Members API does not return a constituency

app/controllers/all/export/rpa_sug_and_fa_letters_controller.rb, spec/requests/all/export/new_rpa_sug_fa_letters_export_spec.rb
Some browsers do not use the file mime type to identify the exported
file, so we add `.csv` to help.
=> Fix: missing export file extension

CHANGELOG.md
Fixed
- Do not raise an exception in reports when an establishment is in an unknown
constituency and the MP details cannot be found.
Changed
- Ingest two additional fields into Gias::Establishments for PowerBI reporting
`open_date` and `status_name`
- The RPA, SUG and FA letters export now includes the projects for a supplied
date range.
=> Release 72

CHANGELOG.md, app/models/project.rb, app/presenters/export/csv/mp_presenter_module.rb, spec/models/project_spec.rb, spec/presenters/export/csv/mp_presenter_module_spec.rb
Background: The Parliamentary Members API is not efficient enough to use when generating exports with large numbers of projects. Additionally, during the pre-election period, the API does not actually return any MP details so it is pointless for us to use a lot of processing power for no results.
Return `nil` for all MPs on all projects. Our presenter code can handle a nil MP record.
We have had to add the `nocov` instruction to the relevant implementation code as our CI rules expect 100% code coverage, and skipped tests do not count towards our code coverage.
=> Do not return a Member of Parliament for projects

app/forms/export/new_pre_conversion_grants_form.rb, app/forms/export/new_rpa_sug_and_fa_letters_form.rb, app/services/export/conversions/pre_conversion_grants_csv_export_service.rb, app/services/export/conversions/rpa_sug_and_fa_letters_csv_export_service.rb, spec/forms/export/new_pre_conversion_grants_form_spec.rb, spec/forms/export/new_rpa_sug_and_fa_letters_form_spec.rb, spec/services/export/conversions/pre_conversion_grants_csv_export_service_spec.rb, spec/services/export/conversions/rpa_sug_and_fa_letters_csv_export_service_spec.rb
We are attempting to keep all the code that relates to a specific export
coupled together, this works follows up on the new exports by matching the
namers of the conversion export service classes to that of the specific export.
=> (168868) Rename csv conversion export services

app/forms/export/new_pre_transfer_grants_form.rb, app/services/export/transfers/pre_transfer_grants_csv_export_service.rb, spec/forms/export/new_pre_transfer_grants_form_spec.rb, spec/services/export/transfers/pre_transfer_grants_csv_export_service_spec.rb
We are attempting to keep all the code that relates to a specific export
coupled together, this works follows up on the new exports by matching the
namers of the transfers export service classes to that of the specific export.
Based on #1634
=> (168868) Rename csv transfers export services

CHANGELOG.md, app/controllers/all/local_authorities/projects_controller.rb, app/services/by_local_authority_project_fetcher_service.rb, spec/services/by_local_authority_project_fetcher_service_spec.rb
We have no option for this fetcher but to load ALL active projects
because of the way our data is structured, with local authority a
property of the establishment and so not in the database.
But we can improve things slightly in two ways:
- ensuring the projects returned always preload the establishments
- when returning projects for a given local authority we re-use the
already fetched project rather than going to the database again, this
results in an array instead of an `ActiveRecord::Relation` so we change
the controller
=> Optimise the local authority project fetcher

CHANGELOG.md, app/helpers/application_helper.rb, app/javascript/application-insights.js, app/views/cookies/edit.html.erb, app/views/layouts/application.html.erb, config/initializers/content_security_policy.rb, package.json, spec/helpers/application_helper_spec.rb, yarn.lock
We want to run Application Insights browser telemetry alongside Google Analytics
so we can evaluate whether we can stop using Google Analytics.
This works only aims to get the connection working and allow us to validate
that, we may want or need to tweak things as we move forward.
We only want to enable tracking:
- in the production like environments of development, test and production
- if the connection string is set
- if the user has allowed optional cookies
@DrizzlyOwl has updated the cookie policy so we are assuming this is all good, I
noticed this along the way, it might be worth double checking:
https://github.com/microsoft/ApplicationInsights-JS?tab=readme-ov-file#data-collection
=> Add MS Application Insights browser telemetry

app/models/significant_date_history.rb, app/models/significant_date_history_reason.rb, db/migrate/20240606152236_create_significant_date_history_reason.rb, db/schema.rb, spec/models/significant_date_history_reason_spec.rb, spec/models/significant_date_history_spec.rb
We will need to start recording a reason for a chaange to Significant Dates on
projects. These reasons will be taken from a list of predefined reasons in a
form. To begin, we add a SignificantDateHistoryReason model, which sits between
the SignificantDateHistory record and its Note.
To ensure we do not break the existing SignificantDateHistory functionality, we
need ot preserve the connection between SignificantDateHistory and Note. Once
the new SignificantDateHistoryReasons are in place, we can do a data migration
to break these connections and re-join the existing SignificantDateHistory
records to their Notes via a SignificantDateHistoryReason record.
=> Add SignificantDateHistoryReasons

app/controllers/date_histories_controller.rb, app/forms/conversion/task/stakeholder_kick_off_task_form.rb, app/forms/new_date_history_form.rb, app/forms/transfer/task/stakeholder_kick_off_task_form.rb, app/models/significant_date_history.rb, app/models/significant_date_history_reason.rb, app/services/significant_date_creator_service.rb, app/services/significant_date_reasons_data_migration.rb, app/views/shared/projects/_significant_dates_table.html.erb, db/migrate/20240612105707_add_user_reference_to_significant_date_history.rb, db/schema.rb, spec/factories/conversion/date_history_factory.rb, spec/features/conversions/users_can_change_the_conversion_date_spec.rb, spec/models/significant_date_history_spec.rb, spec/services/significant_date_creator_service_spec.rb, spec/services/significant_date_reasons_data_migration_spec.rb
With the new `SignificantDateHistoryReason` model in place, we want any changes to significant dates to add a new reason.
We update the `SignificantDateCreatorService` and the two places it is currently used:
- the stakeholder kick off task for conversions and transfers
- any change to significant date
We also add a user to the date history as there is no longer a one to one association between a date history and the note which made delegating the user possible.
We also want to migrate the existing data to use a reason.
Once deployed, we need to run the `SignificantDateReasonsDataMigration`, see the file for details.
=> (169272) Significant date reasons

.github/workflows/build-and-push-image.yml
* This is only set up for development whilst we test the changes
* The `matrix.suffix == '' ` condition is to ensure we don't write the same release note twice when the worker container gets deployed
After a deployment to the 'Development' environment has been completed, an annotation should be added to App Insights to mark the release in the timeline
1. Deploy a release to Development
2. View the associated App Insights instance 
3. See an annotation on the transaction timeline
=> Annotate App Insights after each release

CHANGELOG.md, app/policies/project_policy.rb, spec/policies/project_policy_spec.rb
Service support users should be able to edit completed projects, as this is a work request we get occasionally and service support should be able to manage on their own.
=> (Fix) Allow service support users to edit completed projects

Dockerfile
(Speculative!)
We have had an issue twice now where the latest version of StandardRB v1.37.0 has caused the deploying container to crash on Azure. Aside from attempting to figure out why this happens on deployments but not locally, we do not actually need to include Standard (and ERBLint) in our Dockerised version.
Exclude the gems in the `linting` group when building the application in Docker.
See previous PR https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/1665
=> Don't include `linting` gems in the Dockerised application

CHANGELOG.md, app/models/contact/establishment.rb, app/services/contact_establishment_data_migration.rb, app/services/contacts_fetcher_service.rb, spec/models/contact/establishment_spec.rb, spec/services/contact_establishment_data_migration_spec.rb, spec/services/contacts_fetcher_service_spec.rb
We ingest Headteacher contact details where possible from GIAS records as `Contact::Establishment` records.
However, due to an oversight we were not marking those contacts as `school_or_academy` contacts (via the `category` attribute). When picking the school main contact for exports, we first try to get the "main contact" (as chosen via a select box on the application), and if none is present then we get the first `school_or_academy` contact. 
Because the Headteacher records were not being marked as `school_or_academy` they were never being chosen.
Fix this via:
- Ensuring all new Contact::Establishment records are always category `school_or_academy`
- Ensuring that when picking the "first" school_or_academy contact, Contact::Establishment records are picked first
- Updating all existing …
=> (Fix) Pick the Headteacher contact for "school main contact" where possible

app/models/dao_revocation.rb, app/models/project.rb, config/locales/dao_revoked_decision.en.yml, db/migrate/20240618140233_create_dao_revocations.rb, db/schema.rb, spec/models/dao_revocation_spec.rb, spec/models/project_spec.rb
We are going to want to record a DAO Revocation for sponsored projects.
This will be a decision attached to a project, recording when the DAO was
revoked and who authorised the decision.
The DaoRevocation will be a 1:1 association on projects.
=> Create DAO Revocation Model

app/controllers/external_contacts_controller.rb, app/models/project.rb, app/presenters/export/csv/academy_presenter_module.rb, app/presenters/export/csv/local_authority_presenter_module.rb, app/presenters/export/csv/project_presenter.rb, app/services/contacts_fetcher_service.rb, app/views/conversions/tasks/main_contact/edit.html.erb, app/views/transfers/tasks/main_contact/edit.html.erb, spec/features/conversions/users_can_select_a_main_contact_spec.rb, spec/models/project_spec.rb, spec/services/contacts_fetcher_service_spec.rb
The "Confirm the main contact" task should show all eligible contacts associated with a project. However, due to an oversight, contacts which were ingested - e.g. Head teachers from GIAS and Director of Child services for the local authority - were not being shown on this page. 
This had a knock on effect of meaning the Main project contact in exports was usually incorrect.
In the "Confirm the main contact" task show ALL project contacts, whether a project association or not. Use existing functionality from the ContactsFetcherService to do this.
=> (170900) (Fix) Allow users to select ingested contacts in the Main project contact task

app/controllers/dao_revocations_controller.rb, app/forms/dao_revocation_stepped_form.rb, app/policies/project_policy.rb, app/views/dao_revocations/change_date.html.erb, app/views/dao_revocations/change_minister.html.erb, app/views/dao_revocations/change_reasons.html.erb, app/views/dao_revocations/check.html.erb, app/views/dao_revocations/confirm.html.erb, app/views/dao_revocations/date.html.erb, app/views/dao_revocations/minister.html.erb, app/views/dao_revocations/reasons.html.erb, app/views/dao_revocations/start.html.erb, config/locales/dao_revocations.en.yml, config/locales/dao_revoked_decision.en.yml, config/routes.rb, spec/features/dao_revocation/user_can_record_the_revocation_of_a_dao_from_a_project_spec.rb, spec/forms/dao_revocation_stepped_form_spec.rb, spec/policies/project_policy_spec.rb, spec/requests/dao_revocations_controller_spec.rb
A DAO revocation is applied to a Conversion project that has a DAO applied to it.
The design is a 'check your answers' stepped form. This work delivers the basic flow but does not expose it in the application, that will follow.
There are four 'steps' here plus teh check your answers view:
- start page: infomation only
- confirm page: collects responses but does not save them
- reasons: collects up to three reasons for the revocation
- minister name: the name of the minister who approved the revocation
- date: the date on which the revocation was approved
We created a form object to handle everyting except the start page, which is just a action and view.
We do not want to create the actual DaoRevocation in the database until the check answers view is confirmed, so we store the temporay …
=> (168445) DAO Revocation flow

CHANGELOG.md, app/views/projects/show/_complete.html.erb, app/views/shared/projects/_task_list.html.erb, config/locales/project.en.yml, spec/features/conversions/users_can_complete_a_conversion_project_spec.rb, spec/features/transfers/users_can_complete_a_transfer_project_spec.rb
Marking the project as complete could be seen as the final section of
the task list so here we add a jump to link for access to it.
=> Add task list link to completion section

CHANGELOG.md, app/forms/conversion/task/stakeholder_kick_off_task_form.rb, app/forms/transfer/task/stakeholder_kick_off_task_form.rb, config/locales/conversion/tasks/stakeholder_kick_off.en.yml, config/locales/transfer/tasks/stakeholder_kick_off.en.yml
When creating a date change note for a transfer project as part of the stakeholder kick off task, the text in the note said "Conversion". This should be "Transfer".
The existing notes themselves will be fixed up separately.
=> (Fix) Correct text for transfer stakeholder kick off task

app/forms/dao_revocation_stepped_form.rb, app/models/project.rb, app/views/conversions/shared/_project_summary.html.erb, config/locales/conversion_project.en.yml, config/locales/project.en.yml, spec/features/users_can_view_a_project_spec.rb, spec/forms/dao_revocation_stepped_form_spec.rb, spec/models/project_spec.rb
This work updates the `DaoRevocationSteppedForm` to update the project state
once the DAO Revocation is saved. At the point of saving we should have a valid
`DaoRevocation` and `Project` so we bang(!) to raise any unexpected errors.
We move on to show when a project has its DAO revoked, showing a red 'DAO
REVOKE' tag and notification banner as per the design.
Lastly we add a helper method to project to tell us if a project is appropriate
for DAO revocation i.e. it is a conversion with an DAO applied - we'll use this
helper soon to allow users to actually revoke DAOs in the application.
=> DAO Revocation change project state

CHANGELOG.md, app/models/significant_date_history_reason.rb, spec/models/significant_date_history_reason_spec.rb
When adding the new date history reasons we missed 'voluntary deferral',
this fix adds it in and ensures that all of the form values are in the
`reason_type` enum with a spec.
=> Fix missing reason type

CHANGELOG.md, app/services/export/conversions/pre_conversion_grants_csv_export_service.rb
The date an academy transferred is already on the GMFU export for transfers. Add the date an academy opened to the same report for conversions.
=> Add the Date the academy opened to the Grant Management report

CHANGELOG.md, app/controllers/all/by_month/conversions/projects_controller.rb, app/controllers/all/by_month/transfers/projects_controller.rb, app/controllers/all/export/by_significant_date/conversions/all_data/projects_controller.rb, app/controllers/all/export/by_significant_date/transfers/all_data/projects_controller.rb, app/controllers/concerns/date_rangable.rb, app/forms/export/new_rpa_sug_and_fa_letters_form.rb, app/models/project.rb, app/presenters/export/csv/project_presenter.rb, app/services/by_month_project_fetcher_service.rb, app/services/export/conversions/pre_conversion_grants_csv_export_service.rb, config/locales/export/csv/project.en.yml, spec/factories/dao_revocation_factory.rb, spec/features/all_projects/by_month/users_can_view_projects_by_month_spec.rb, spec/forms/export/new_rpa_sug_and_fa_letters_form_spec.rb, spec/presenters/export/csv/project_presenter_spec.rb, spec/services/by_month_project_fetcher_service_spec.rb
This is the next step in supporting converison projects with a DAO that gets revoked. Once revoked the project is essentially over, similar to completion. Our first step is to ensure the project only show up in the exports when they are of value, otherwise they should not be included.
This requires work for both exports that will not include them and those that do, because `dao_revoked` is a new `state`
we have to deal with them pretty much everywhere as they are not `completed` nor are they `active` or `deleted` (the other states).
This work sets at to resolve the exports, following this logic/understanding:
- The by month exports do not include the DAO revoked conversions.
- The pre conversion grant export includes DAO revoked conversion projects and we have added a column to indicate …
=> (169471) DAO dao revocations in exports

CHANGELOG.md, app/policies/project_policy.rb, spec/policies/project_policy_spec.rb
Project is our primary model and this policy for it has grown over time.
This work adds changes for the new `dao_revoked` project state (a
conversion project with a DAO that has been revoked) and also attempts
to refactor.
Generally speaking:
- service support can edit anything except a deleted project
- the user assigned to a project can edit it
- any recognised user can add notes or contact unless the project is
'finsihed' i.e. completed, deleted or dao_revoked
The change significant date methods are really just aliases for
conversions and transfers and have been updated.
There are still some other policies here that are pretty opaque so I've
added a comment to indicate what they are doing.
Base on top of #1701
=> (168448) DAO revoked projects cannot be edited

CHANGELOG.md, app/policies/project_policy.rb, spec/policies/project_policy_spec.rb
The project policy was recently refactored and we immediately saw this
issue. These two policy methods are used to render (or not) the button
to change the date so should encompass the type of project in question.
=> Fix project policy

app/controllers/all/dao_revoked/projects_controller.rb, app/views/all/dao_revoked/projects/index.html.erb, app/views/projects/shared/_dao_revoked_table.html.erb, config/locales/project.en.yml, config/routes.rb, spec/features/projects/dao_revoked/projects_can_be_viewed_spec.rb
Right now there is no way to see these projects once the DAO is revoked,
for now we'll add this view just to have something, we will not link to
it in the application.
=> All DAO revoked projects view (hidden)

app/views/dao_revocations/change_date.html.erb, app/views/dao_revocations/change_minister.html.erb, app/views/dao_revocations/change_reasons.html.erb, app/views/dao_revocations/check.html.erb, app/views/dao_revocations/confirm.html.erb, app/views/dao_revocations/date.html.erb, app/views/dao_revocations/minister.html.erb, app/views/dao_revocations/reasons.html.erb, app/views/dao_revocations/start.html.erb, spec/features/dao_revocation/user_can_record_the_revocation_of_a_dao_from_a_project_spec.rb
The DAO Revocation steps need cancel links. 
The Cancel links on the initial steps just take you back to the task list. 
The Cancel links on the "Change" steps (ie. if you are changing a value from the "Confirm" page) take you back to the Confirm page.
=> Add Cancel links to the DAO Revocation steps

CHANGELOG.md
Added
- Add the date an academy opened to the Grant management export for conversions
- Add the team a project is assigned to to the RPA, SUG and FA letters export
Changed
- The RPA, SUG and FA letter export does not include conversion projects with a revoked DAO.
- The by month exports do not include conversion projects with a revoked DAO.
- The single by month view and export are now sorted by the conversion or transfer date only.
- The pre conversion grants export includes a new column that shows the DAO revocation state of a project as applicable.
- Once a project has it's DAO revoked, it can no longer be edited, except by Service Support.
- Conversion projects with a DAO (Directive Academy Order) can now be 'revoked' from the task list.
- DAO revocation is a stepped process which …
=> Release 77

CHANGELOG.md, app/forms/new_date_history_form.rb, config/locales/conversion_date_history.en.yml, config/locales/date_history.en.yml, config/locales/transfer_date_history.en.yml, spec/forms/new_date_form_spec.rb
When changing the significant date it should not be the same date.
This validation prevents that from happening.
We used a lower case D for the word 'date' as mentioned here: https://ukgovernmentdfe.slack.com/archives/C05UBB0EZ43/p1719838553779419
=> (171855) Validate the significant date

app/views/shared/_environment_banner.html.erb
This banner is not shown in production so this doesn't strictly matter,
but SonarCloud is complaining about it.
We can use an aside tag which has an implicit role of 'complimentary',
so let's do that and get the SonarCloud green tick back.
=> Change tag for environment banner

app/models/dao_revocation.rb, spec/models/dao_revocation_spec.rb
When fiddling with test data, we realised that if a DaoRevocation is destroyed, it causes the parent project to become unavailable in the UI, because the DaoRevocation does not exist but the project's state is still :dao_revoked.
This is a rare occurrence as DaoRevocations probably won't be deleted, but it may happen if we're asked to remove one manually. This ensures the parent project does not become inaccessible.
=> (Fix) Update Project state after DaoRevocation destruction

app/controllers/cookies_controller.rb
During the June 2024 IT Health check it was raised that our
`ACCEPT_OPTIONAL_COOKIES` should be httponly.
This change will not take effect for users who already have the cookie
set, until they delete the existing cookie or it expires.
Clearing cookies for the application will set the new cookie and is
recommended.
=> Update optional cookies cookie

config/application.rb
Our June 2024 IT Health Check recommends we set the X-Frame-Options
header to DENY, we are already SAMEORIGIN, so not really at risk, but
here is the change to DENY.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
=> Update X-Frame-Options header

config/application.rb
Our June 2024 IT Health Check recommends we set the HSTS, or Strict
transport security header to preload.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
=> Set the HSTS header

app/models/contact/project.rb, app/models/project.rb, db/migrate/20240703133114_remove_funding_agreement_letters_contact.rb, db/schema.rb, spec/models/project_spec.rb
This association hasn't been used for a long time. Remove it to keep the codebase tidy.
=> (Chore) Remove funding agreement contact ID

app/forms/cookies_form.rb, spec/forms/cookies_form_spec.rb
We keep seeing deployments fail with this error:
```
/srv/app/app/forms/cookies_form.rb:7:in `<class:CookiesForm>': uninitialized constant CookiesForm::OpenStruct (NameError)
```
So far this only seems to happen when we update the Standardrb gem and
backing that out has consistently fixed the issue, although it could
just be a coincidence!
We cannot reproduce the issue locally either.
If the failure is this OpenStruct in CookiesForm the only thing unusual
about it is the assignment to a const, there is really no need to do
this, so let's try it without and see how we get on.
=> (fix) CookiesForm do not load responses

CHANGELOG.md, app/forms/contact/create_project_contact_form.rb, app/models/contact/project.rb, app/models/project.rb, app/views/external_contacts/_contact_group.html.erb, config/locales/contact.en.yml, db/migrate/20240703142240_local_authority_main_contact_id.rb, db/schema.rb, spec/forms/contact/contact_project_form_spec.rb, spec/models/contact/project_spec.rb, spec/models/project_spec.rb
Users have requested the ability to set a local authority contact as the main
local authority contact, should a project have multiple local authority
contacts.
=> (167653) Allow users to add a local authority main contact

app/javascript/application.js, app/javascript/google-tag-manager.js, app/views/layouts/application.html.erb, app/views/shared/_google_tag_manager.html.erb, config/initializers/content_security_policy.rb
Around 13 June we stopped getting Google Analytics data via Tag manager. This may have been when we added Applicaiton Insights?
This is hard to debug as we only run Tag Manger in production.
We've made the two approaches consistent across Tag Manager and Application Insights and tried to simplify the content security policy, see the commit for details.
=> Update Google Tag Manager

spec/features/internal_contacts/users_can_edit_the_added_by_user_with_autocomplete_spec.rb
This autocomplete spec often fails in ci:
```
Unable to find css "li#user-autocomplete__option--0"
```
This work is an attempt to make this less flaky by pausing briefly
after filling in the autocomplete to give it time to render.
We also pass the page object to the helper just in-case!
=> Fix flaky feature spec

config/initializers/content_security_policy.rb
As mentioned here:
https://developers.google.com/tag-platform/security/guides/csp
Once you have tag manager/analytics working, you'll need to allow this
img_src (assume they use a hidden gif to track).
=> Allow img-src from Google tag manager

CHANGELOG.md, app/presenters/export/csv/local_authority_presenter_module.rb, app/services/contacts_fetcher_service.rb, spec/presenters/export/csv/local_authority_presenter_module_spec.rb, spec/services/contacts_fetcher_service_spec.rb
Now that we can choose a "main" contact for the local authority in the application, export that contact in exports under the "Local authority contact" column (as opposed to just outputting *all* local authority contacts).
If no contact is chosen as the "main" contact, export the next contact with the local authority category.
=> Use the "main" Local Authority contact in exports

config/application.rb
The HSTS Header requires that we set the max-age property when using preload. Additionally, the 2024 ITHC recommends we also add the includeSubDomains property too.
=> Configuration for HSTS Header

app/models/note.rb, app/models/significant_date_history_reason.rb, app/policies/note_policy.rb, db/migrate/20240709090855_add_notable_to_note.rb, db/migrate/20240709115448_remove_significant_date_history_from_note.rb, db/schema.rb, spec/factories/conversion/date_history_factory.rb, spec/factories/note_factory.rb, spec/models/note_spec.rb, spec/models/significant_date_history_spec.rb, spec/policies/note_policy_spec.rb
This works lays the foundation for adding free text to the DAO
revocation reasons. We want to store the free text as Notes just like we do for
the reasons on the SignificantDateHistoryReason.
We change the existing column to be the notable_id and add the notable_type to
store the parents class.
We then clean up some leftover parts of the prior association to
SignificantDateHistory.
=> Introduce notable association on note

README.md, config/application.rb, config/environments/development.rb, config/environments/test.rb, doc/decisions/0026-storing-temporary-data-for-stepped-forms.md, doc/redis.md
Whilst we do not use the Rails cache for caching, we want to use it to
store temporary values on our stepped forms.
This work configures the cache to use Redis and enable it in all
environments.
In development caching can be toggled on and off and we have retained
this behaviour.
You will need to be running Redis locally and have the REDIS_URL
variable set in .env.development.local from this point forwards.
=> Configure the Rails cache to use Redis

CHANGELOG.md, app/controllers/dao_revocations_controller.rb, app/forms/dao_revocation_stepped_form.rb, app/models/dao_revocation.rb, app/models/dao_revocation_reason.rb, app/views/dao_revocations/change_reasons.html.erb, app/views/dao_revocations/check.html.erb, app/views/dao_revocations/reasons.html.erb, config/locales/dao_revocations.en.yml, db/migrate/20240709143301_add_dao_revocation_reasons.rb, db/migrate/20240715115518_remove_reasons_from_dao_revocation.rb, db/schema.rb, spec/factories/dao_revocation_factory.rb, spec/features/dao_revocation/user_can_record_the_revocation_of_a_dao_from_a_project_spec.rb, spec/features/users_can_view_a_project_spec.rb, spec/forms/dao_revocation_stepped_form_spec.rb, spec/models/dao_revocation_reason_spec.rb, spec/models/dao_revocation_spec.rb, spec/requests/dao_revocations_controller_spec.rb
We want to collect details about each reason for a DAO being revoked. Our approach to this is the same as the reasons on a SignificantDateHistory, a joining 'reason' model that links the revocation to a note which lets us keep all 'notes' in one table.
With the model inplace we move on to update the form objects, views and controllers and finally drop the columns that used to store the reasons on DaoRevocation - there are no DaoRevocations in production and if one is added before this work is deployed we will deal with it manually (DAO Revocation is very rare).
=> DAO revocation reasons model

CHANGELOG.md, config/locales/conversion/tasks/academy_details.en.yml, config/locales/conversion/tasks/conditions_met.en.yml
This work removes uses of ADOP (Academy Delivery Operational Policy) and ADOP (Academies Delivery Operational Practice) and replaces it with the correct AOPU (Academies Operational Practice Unit)
=> Correcting acronym for APOU from ADOP

CHANGELOG.md, app/controllers/conversions/projects_controller.rb, app/controllers/transfers/projects_controller.rb, app/forms/conversion/edit_project_form.rb, app/forms/transfer/edit_project_form.rb, app/models/project.rb, app/views/conversions/project_information/_assignment.html.erb, app/views/conversions/project_information/_information_list.erb, app/views/conversions/projects/edit.html.erb, app/views/transfers/project_information/_assignment.html.erb, app/views/transfers/project_information/_information_list.erb, app/views/transfers/projects/edit.html.erb, config/locales/project_information.en.yml, spec/features/conversions/users_can_edit_project_details_spec.rb, spec/features/transfers/users_can_edit_project_details_spec.rb, spec/forms/conversion/edit_project_form_spec.rb, spec/forms/transfer/edit_project_form_spec.rb, spec/models/project_spec.rb
The RCS team have reported that users creating projects, intending to hand them
over to RCS, are not filling out the project creation form correctly and
instead keeping the projects assigned to themselves. The RCS team are then
having to spend time every day informing users how to reassign projects
via the Internal Contacts tab. Additionally, you cannot assign the project to
"no one" in the internal contacts tab, and the RCS team use a list of unassigned
projects in their workflow.
In order to try to mitigate this, make the "Handover to Regional casework
services" field on the Edit project form editable. This field is not actually
an attribute on the project, it adjusts who and to which team a project
is assigned to.
The user can now assign the project to RCS via the edit project form. …
=> (172824) Allow users to edit the "Handover to RCS" field on projects

CHANGELOG.md, config/locales/transfer/tasks/master_funding_agreement.en.yml
This work adds a small piece of additional content to the master funding agreement task in a transfer following some user feedback.
=> Adding guidance to master funding agreement task in transfers

CHANGELOG.md, config/locales/conversion/tasks/receive_grant_payment_certificate.en.yml, config/locales/conversion_project.en.yml, spec/features/conversions/users_can_complete_conversion_tasks_spec.rb
This work replaces references in content the grant payment certificate with declaration of expenditure certificate
=> Correcting grant payment certificate references

CHANGELOG.md, app/models/transfer/project.rb, config/locales/transfer_project.en.yml, spec/features/transfers/users_can_complete_a_transfer_project_spec.rb, spec/models/conversion/project_spec.rb, spec/models/transfer/project_spec.rb
This work updates the logic that controls when a user can complete a transfer
project.
The following must have been completed:
- The transfer date has been confirmed and is in the past
- The confirm this transfer has authority to proceed task is completed
- The receive declaration of expenditure certificate task is completed
- The confirm the date the academy transferred task is completed
=> (173677) Update transfer completion logic

.github/workflows/build-and-push-image.yml
* The condition ensures that when the worker container deploys there is not an additional marker in app insights. We dont want this to happen because they are both deployed at the same time using the same image tag so it is not necessary to do it twice
=> Annotate releases in App Insights for all environments

CHANGELOG.md, app/models/statistics/project_statistics.rb, app/views/all/statistics/statistics/index.html.erb, spec/models/statistics/project_statistics_spec.rb
This work adds the number of DAO conversion projects to the statistics page.
Transfers cannot be issued a DAO so can never have one revoked.
=> Add a count of DAO revoked projects to statistics

app/forms/export/new_academies_due_to_transfer_form.rb, app/forms/export/new_pre_conversion_grants_form.rb, app/forms/export/new_pre_transfer_grants_form.rb, app/forms/export/new_rpa_sug_and_fa_letters_form.rb, app/models/project.rb, app/models/statistics/project_statistics.rb, app/services/by_region_project_fetcher_service.rb, app/services/by_team_project_fetcher_service.rb, app/services/by_trust_project_fetcher_service.rb, app/services/by_user_project_fetcher_service.rb, spec/forms/export/new_academies_due_to_transfer_form_spec.rb, spec/forms/export/new_pre_conversion_grants_form_spec.rb, spec/forms/export/new_pre_transfer_grants_form_spec.rb, spec/forms/export/new_rpa_sug_and_fa_letters_form_spec.rb, spec/models/project_spec.rb, spec/services/by_region_project_fetcher_service_spec.rb, spec/services/by_team_project_fetcher_service_spec.rb, spec/services/by_trust_project_fetcher_service_spec.rb, spec/services/by_user_project_fetcher_service_spec.rb
We introduced a default scope to exclude deleted projects everywhere. This
became a problem with the `project` association on Note (don't use default
scopes for anything other than ordering?!?!)
This work removes the default scope and takes the steps to ensure that the
application continues to work as expected.
We rely on the `state` enum and the `in_progress` scope, which uses the `active`
state internally.
In summary we have a state machine, where projects are:
- active
- in progress (assigned to a user)
- completed *
- deleted * 
- DAO revoked *
* all of these result in the project essentially being over
=> (173735) Remove and refactor default scope for deleted projects

app/models/statistics/project_statistics.rb
We worked on this DAO revocation count whilst other work in the same
place and we lost this change in the rebasing.
=> Fix the DAO Revocation count

CHANGELOG.md
Added
- details component and content to explain when to use a deed of termination to end a master funding agreement in a transfer project
- a count of the number of DAO conversion projects has been added to the statistics page.
Changed
- If a project is not assigned to RCS on creation, the assigned user can edit the project in the usual way and assign it to RCS, along with adding a handover note
- Use of ADOP change to AOPU
- Corrected references in content to the grant payment certificate in conversions to declaration of expenditure certificate
- To complete a transfer project users will have to ensure that the following:
- The transfer date has been confirmed and is in the past
- The confirm this transfer has authority to proceed task is completed
- The receive declaration of …
=> Release 80

app/views/shared/_dfe_footer.html.erb
This is in line with the [RSD footer design pattern](https://design-system-rsd-c10b0db1a3a1.herokuapp.com/design-system/rsd-design-system/design-patterns/footer).
=> Remove extra horizontal line in footer

CHANGELOG.md, app/services/export/conversions/rpa_sug_and_fa_letters_csv_export_service.rb, config/locales/export/csv/project.en.yml
A user reported that they were adding a contact as the "Project main contact" but that contact was not being output to the RPA/SUG report. Despite the "select the main contact for a project" task
indicating that "this person will receive funding letters", the main contact for a project was not actually being included in the report.
As a temporary fix, add this contact into the RPA/SUG report. Also update the column name to make it (hopefully) more obvious this is the *Project* main contact. 
When we rework the contacts pages, this commit will become redundant, as users will be able to choose the contacts output to the RPA/SUG report.
=> Add "project main contact" details to RPA/SUG report

CHANGELOG.md, app/forms/conversion/task/articles_of_association_task_form.rb, app/forms/transfer/task/articles_of_association_task_form.rb, app/views/conversions/tasks/articles_of_association/edit.html.erb, app/views/transfers/tasks/articles_of_association/edit.html.erb, config/locales/conversion/tasks/articles_of_association.en.yml, config/locales/transfer/tasks/articles_of_association.en.yml, db/migrate/20240725110919_add_sent_field_to_articles_of_association_task.rb, db/schema.rb, spec/forms/conversion/tasks/articles_of_association_task_form_spec.rb
Add a new "sent" field to the Articles of Association tasks for both Conversions and Transfers. Amend the content to reflect the process more accurately.
=> Articles of association content changes

CHANGELOG.md, app/controllers/all/trusts/projects_controller.rb, app/models/project.rb, app/services/by_trust_project_fetcher_service.rb, app/views/all/trusts/projects/_trust_table.html.erb, config/routes.rb, spec/factories/academies_api/trust.rb, spec/features/projects/trusts/users_can_view_a_list_of_projects_for_a_given_from_a_mat_trust_spec.rb, spec/features/projects/trusts/users_can_view_a_list_of_projects_for_a_given_trust_spec.rb, spec/features/projects/trusts/users_can_view_projects_by_trust_spec.rb, spec/models/project_spec.rb, spec/services/by_trust_project_fetcher_service_spec.rb
Users want to see both 'regular' trusts and 'form a multi academy' trusts in the all projects by trust view.
This is a little messy because we do not model the form a MAT trust, it is simply an attribute of a `Project`.
We did not want to change this by adding a model at this point, so we work around it. Full details are in the commit, but in summary we treat each type differently and combine them before sorting, this requires adding more code to handle this in actions, routes and views.
=> (174872) include form a mat in by trust view

app/models/project.rb, app/models/project_group.rb, db/migrate/20240801080056_add_project_groups.rb, db/schema.rb, spec/models/project_group_spec.rb, spec/models/project_spec.rb
Conversions and transfers are 'grouped' together at advisory board to
join the same trust and doing so opens the door to funding under new
policies.
We need to support this grouping of projects, but will not originate the
groups as this is done pre-advisory board (so in the Prepare
applications).
A project can only belong to one group, but a trust could have multiple
groups over time.
Right now a group will always relate to a Trust, for now we will capture
the incoming trust UKPRN to make this connection.
This work sets up a basic model to handle this.
=> (175111) Add ProjectGroup model

CHANGELOG.md
Added
- The "project main contact" (selected via a task) is output to the RPA/SUG export
Changed
- content changes to articles of association task in conversions and transfers to describe the process more accurately
- addition of 1 checkbox to articles tasks in conversions and transfers
- the all project by trust view now includes 'form a multi academy trusts'
=> Release 81

app/models/contact.rb, app/models/contact/project.rb, app/models/conversion/project.rb, app/models/project.rb, spec/presenters/export/csv/project_presenter_spec.rb, spec/presenters/export/csv/school_presenter_module_spec.rb
When testing PR #1780 in development, we realised that any Contact type other than Contact::Project, when selected for the "main contact for the project" (Project.main_contact), was not showing in the exports.
This was because the contact type for project main contact was set to Contact::Project, but the "Choose a main contact for the project" task allows *any* contact type to be selected.
Additionally, when fixing this issue we realised that the Chair of Governors contact association was only on the Conversion Project type, when we allow Transfer projects to choose a Chair of Governors as well.
Fix both of these by moving the associations into the base Contact and Project classes.
=> (Fix) Allow all Contact types to be a "project main contact"

CHANGELOG.md, app/controllers/conversions/projects_controller.rb, app/controllers/transfers/projects_controller.rb, app/forms/conversion/create_project_form.rb, app/forms/create_project_form.rb, app/forms/transfer/create_project_form.rb, app/views/conversions/projects/new.html.erb, app/views/transfers/projects/new.html.erb, config/locales/conversion_project.en.yml, config/locales/project.en.yml, config/locales/transfer_project.en.yml, spec/factories/project_group_factory.rb, spec/features/conversions/users_can_create_converison_projects_in_a_group_spec.rb, spec/features/conversions/users_can_create_conversion_projects_spec.rb, spec/features/transfers/users_can_create_a_transfer_project_spec.rb, spec/features/transfers/users_can_create_transfer_projects_in_a_group_spec.rb, spec/forms/conversion/create_project_form_spec.rb, spec/forms/transfer/create_project_form_spec.rb, spec/support/project_helpers.rb
Projects can be grouped together for advisory board to receive additional funding.
This work adds the group reference number to both create conversion and transfer
projects. The group reference number originates in the Prepare application and
so, for now is a matter of copy and pasting the value from one application to
the other (one day the applications should be connected).
We validate the group reference number format and that the project incoming
trust UKPRN matches that of the group (this grouping is by trust).
As the behaviour is shared, we add it to the base `create_project_form`.
Right now, we do not think form a MAT projects needs this behaviour.
=> (175117) Collect group reference number

CHANGELOG.md, app/controllers/conversions/projects_controller.rb, app/controllers/transfers/projects_controller.rb, app/forms/conversion/edit_project_form.rb, app/forms/create_project_form.rb, app/forms/edit_project_form.rb, app/forms/transfer/edit_project_form.rb, app/validators/group_id_validator.rb, app/views/conversions/projects/edit.html.erb, app/views/shared/project_information/_project_details.html.erb, app/views/transfers/projects/edit.html.erb, config/locales/conversion_project.en.yml, config/locales/project.en.yml, config/locales/project_information.en.yml, config/locales/transfer_project.en.yml, spec/features/conversions/users_can_edit_project_details_spec.rb, spec/features/project_information/users_can_view_project_details_spec.rb, spec/forms/conversion/edit_project_form_spec.rb, spec/validators/group_id_validator_spec.rb
Whilst users have to supply the group reference number, there is a chance it
could be incorrect, so we want to allow it to be changed.
We already have a pattern for this with the concept of 'edit project form' for
both conversion and transfers.
This work extracts the common behaviour across those forms and then adds in the
group reference number for editing.
Editing the group reference number needs to allow it to be set to nothing, i.e.
the association to the group cancelled, this is achieved by submitting an empty
value.
=> (175119) Group reference number editing

CHANGELOG.md
Added
- new conversion projects now collect the group reference number, used in the Prepare application to group projects together for advisory board.
- new transfer projects now collect the group reference number, used in the Prepare application to group projects together for advisory board.
- the group reference number for a conversion or transfer can now be changed from the project information view.
- show an indicator when a project is part of a group
- a new index page listing all grouped projects
- a list of the project groups is shown on the index page
- individual project groups can now be viewed
Fixed
- the time for a date history item is now shown in the London timezone
Changed
- The feedback form link in the phase banner is now the same as the one in the footer
=> Release 82

app/models/key_contacts.rb, app/models/project.rb, db/migrate/20240808094556_add_key_contacts.rb, db/schema.rb, spec/models/key_contacts_spec.rb, spec/models/project_spec.rb
Key contacts are those used by data consumers to send important
communications to those involved in projects.
They fill DfE defined roles in the project:
- headteacher
- chair of governors
- incoming trust CEO
- outgoing trust CEO
- director of children services
- member of parliament
These roles are not the contact job title.
We want to encapsulate these into a model that sits outside of Project
(to keep Project as clean as we can).
We settled on `key_contacts` which is a simple joining model between the
project and the contacts.
Here we are only adding headteacher, but the others will follow.
We have no referential integrity here as:
- a project will destroy its own key_contacts
- we want a contact to be deleted even if referenced from a key_contact,
which will then return `nil`, which …
=> Model key contacts

CHANGELOG.md, app/forms/conversion/task/confirm_headteacher_contact_task_form.rb, app/models/contact.rb, app/models/conversion/task_list.rb, app/views/conversions/tasks/confirm_headteacher_contact/edit.html.erb, config/locales/conversion/tasks/confirm_headteacher_contact.en.yml, spec/features/conversions/users_can_complete_conversion_tasks_spec.rb, spec/features/conversions/users_can_confirm_the_headteacher_contact_spec.rb, spec/models/contact_spec.rb, spec/models/conversion/task_list_spec.rb
We are going to ask users to specifically identify the headteacher
contact in an effort to improve the quality of the data being provided
from the application.
We run the generator to create the scaffold of the task.
The task sets the association on the recently added `KeyContacts` class
rather than the `Project` class.
Only contacts from the `school_or_academy` category are used to populate
the available contacts, although this is not enforced beyond this.
=> (176156) Add confrim headteacher contact task

CHANGELOG.md, app/forms/transfer/task/confirm_headteacher_contact_task_form.rb, app/models/transfer/task_list.rb, app/views/transfers/tasks/confirm_headteacher_contact/edit.html.erb, config/locales/transfer/tasks/confirm_headteacher_contact.en.yml, spec/features/transfers/users_can_complete_transfer_tasks_spec.rb, spec/features/transfers/users_can_confirm_the_headteacher_contact_spec.rb, spec/models/transfer/task_list_spec.rb
Just like conversions, we want to explicitly ask the user to confirm
which contact is the headteacher. The information is important to
downstream data users.
This work is a repeat of the conversions work.
=> Add confirm headteacher contact to transfers

CHANGELOG.md, app/presenters/export/csv/school_presenter_module.rb, app/services/export/conversions/all_data_csv_export_service.rb, app/services/export/conversions/rpa_sug_and_fa_letters_csv_export_service.rb, app/services/export/transfers/academies_due_to_transfer_csv_export_service.rb, config/locales/export/csv/project.en.yml, spec/presenters/export/csv/school_presenter_module_spec.rb
We recently added new tasks for conversions and transfers to confirm the
headteacher contact details.
This work exposes that data, if available in the exports.
=> Add the headteacher contact to exports

CHANGELOG.md, app/forms/conversion/task/confirm_incoming_trust_ceo_contact_task_form.rb, app/forms/transfer/task/confirm_incoming_trust_ceo_contact_task_form.rb, app/models/conversion/task_list.rb, app/models/key_contacts.rb, app/models/transfer/task_list.rb, app/presenters/export/csv/incoming_trust_presenter_module.rb, app/services/export/conversions/all_data_csv_export_service.rb, app/services/export/transfers/all_data_csv_export_service.rb, app/views/conversions/tasks/confirm_incoming_trust_ceo_contact/edit.html.erb, app/views/transfers/tasks/confirm_incoming_trust_ceo_contact/edit.html.erb, config/locales/conversion/tasks/confirm_incoming_trust_ceo_contact.en.yml, config/locales/export/csv/project.en.yml, config/locales/transfer/tasks/confirm_incoming_trust_ceo_contact.en.yml, db/migrate/20240815105444_add_incoming_trust_ceo_to_key_contacts.rb, db/schema.rb, spec/features/conversions/users_can_complete_conversion_tasks_spec.rb, spec/features/conversions/users_can_confirm_the_incoming_trust_ceo_contact_spec.rb, spec/features/transfers/users_can_complete_transfer_tasks_spec.rb, spec/features/transfers/users_can_confirm_the_incoming_trust_ceo_contact_spec.rb, spec/models/conversion/task_list_spec.rb, spec/models/key_contacts_spec.rb, spec/models/transfer/task_list_spec.rb, spec/presenters/export/csv/incoming_trust_presenter_module_spec.rb
Just like the new headteacher and chair of governors, the incoming trust CEO is required data for downstream data users.
Our users are tasked with collecting the latest contact details and confirming them in a task on both conversions and transfers.
The data is exported as appropriate.
This is a repeat of the existng headteacher and chair of governors work.
There is no data to migrate and the existing 'main contact for incoming trust' will remain for now.
=> (176162 and 176163) Incoming trust CEO contact task

CHANGELOG.md, app/forms/transfer/task/confirm_outgoing_trust_ceo_contact_task_form.rb, app/models/key_contacts.rb, app/models/transfer/task_list.rb, app/presenters/export/csv/outgoing_trust_presenter_module.rb, app/services/export/transfers/all_data_csv_export_service.rb, app/views/transfers/tasks/confirm_outgoing_trust_ceo_contact/edit.html.erb, config/locales/export/csv/project.en.yml, config/locales/transfer/tasks/confirm_outgoing_trust_ceo_contact.en.yml, db/migrate/20240815142453_add_outgoing_trust_ceo_to_key_contacts.rb, db/schema.rb, spec/features/transfers/users_can_complete_transfer_tasks_spec.rb, spec/features/transfers/users_can_confirm_the_outgoing_trust_ceo_contact_spec.rb, spec/models/key_contacts_spec.rb, spec/models/transfer/task_list_spec.rb, spec/presenters/export/csv/outgoing_trust_presenter_module_spec.rb
The outgoing trust CEO contact details are required be some downstream data users.
This work adds a task to collect and confirm the contact details and include them in the export.
Based on #1807
=> (176165 and 176166) Outgoing trust CEO contact task

CHANGELOG.md, app/services/project_search_service.rb, spec/services/project_search_service_spec.rb
When removed the default scope that excluded deleted project (don't use
default scopes for filtering!) we missed the search results.
Right now deleted project should not show up anywhere except on the console.
=> Fix: deleted projects not shown in search results

CHANGELOG.md, app/presenters/export/csv/chair_of_governors_presenter_module.rb, app/services/export/conversions/rpa_sug_and_fa_letters_csv_export_service.rb, config/locales/export/csv/project.en.yml, spec/presenters/export/csv/chair_of_governors_presenter_module_spec.rb
When exported the confirmed chair of governors contact should include
their role.
=> Add the Chair of governors role to exports

app/services/export/conversions/rpa_sug_and_fa_letters_csv_export_service.rb
Our new 'contact tasks' are about to be deployed but we realised that we
are about to enter the largest openers month of the year, September and
doing so will introduce gaps in the data that downstream users rely on.
On reflection, we decided that it would be better to leave this export
as is until after September.
=> Remove headteacher column from export

CHANGELOG.md, app/helpers/contacts_helper.rb, app/views/external_contacts/_contact_group.html.erb, config/locales/contact.en.yml, spec/features/users_can_manage_contacts_spec.rb, spec/helpers/contacts_helper_spec.rb
- The contact group headers now feature the school/trust/local authority name,
or group type (solicitor etc) if there is no named organisation
- The contact entries do not show the organisation name, except in the case of
"other" contacts, which could belong to any organisation.
- Change the display of the "Primary contact" indicator
=> (177164) Change the index view for external contacts

app/forms/contact/create_project_contact_form.rb, config/locales/contact.en.yml, spec/forms/contact/create_project_contact_form_spec.rb
Conversion projects don't have the concept of an outgoing trust, so creating an outgoing trust contact for them doesn't make sense. Show a validation error if the user tries to create one.
=> Do not allow an outgoing trust contact to be created for Conversion projects

CHANGELOG.md, config/locales/conversion/tasks/conversion_grant.en.yml, config/locales/conversion/tasks/sponsored_support_grant.en.yml
This work changes uses of 'conversion grant' to 'conversion support grant'
This makes small content changes to 2 tasks.
- Process the conversion grant (now Process the conversion support grant)
- Confirm and process the sponsored support grant
This follows discussion with funding teams to understand what the names of the pre-opening support grants are and is part of wider work to make this naming convention consistent across Apply, Prepare and Complete.
=> Making conversion support grant references consistent

app/views/conversions/external_contacts/index.html.erb, app/views/external_contacts/_member_of_parliament.html.erb, app/views/transfers/external_contacts/index.html.erb, config/locales/contact.en.yml, spec/features/users_can_manage_contacts_spec.rb
We want to show the MP for a project on the external contacts page, if one exists. This contact is not part of the "other" project contacts (it is a different type, and retrieved from an API) so will not appear in the Grouped contacts list.
=> Show the Member of Parliament (if one exists) on external contacts page

app/views/external_contacts/_contact_group.html.erb
The contact summary card's IDs were not unique. We were going to add unique ones but 1) the IDs are not used in any tests; and 2) an ID is not mandatory according to the design system. So instead we have removed them.
=> (Fix) Remove non-unique ID from Contact Summary Card

spec/features/external_contacts/users_can_add_new_external_contacts_spec.rb, spec/features/external_contacts/users_can_edit_external_contacts_spec.rb, spec/features/external_contacts/users_can_view_external_contacts_spec.rb
This spec had become too big and unwieldy; split it up into 3 smaller feature specs.
=> (Chore) Split the "manage contacts" feature spec up

app/services/headteacher_data_migration_service.rb, spec/services/headteacher_data_migration_service_spec.rb
When running the Headteacher migration on test, we found two issues:
1) The Academies API timed out. Get around this be getting the contact establishment name (school name) from our local GIAS:Establishment tables.
2) There is a risk that we will try to create a new contact with the same email address as an existing contact. Skip the contact if this is the case.
=> Refine the Headteacher data migration

Dockerfile, app/views/conversions/external_contacts/index.html.erb, app/views/external_contacts/_member_of_parliament.html.erb, app/views/transfers/external_contacts/index.html.erb
We recently saw erb lint fail locally but pass in CI. This is why and the fix.
=> Copy erb lint config to built image

.github/workflows/ci-checks.yml
* These additional steps will upload a CVE report to GitHub Security after an image has been built
=> Scan built Docker image for vulnerabilities

CHANGELOG.md, app/forms/conversion/task/commercial_transfer_agreement_task_form.rb, app/forms/transfer/task/commercial_transfer_agreement_task_form.rb, app/views/conversions/tasks/commercial_transfer_agreement/edit.html.erb, app/views/transfers/tasks/commercial_transfer_agreement/edit.html.erb, config/locales/conversion/tasks/commercial_transfer_agreement.en.yml, config/locales/transfer/tasks/commercial_transfer_agreement.en.yml, db/migrate/20240822104104_update_conversion_commercial_transfer_agreement_task.rb, db/migrate/20240827092019_update_transfer_commercial_transfer_agreement_task.rb, db/schema.rb
We received feedback on the commercial transfer agreement task for both conversion and transfer projects.
This works implements the changes the design team came to from this feedback.
For conversion projects, we include a reversible schema and data migration as the actions have changed, these were validated with @SteveMilnes.
For transfers two actions have been added.
=> Update commercial transfer agreement tasks

Gemfile.lock
There is an open CVE for the RDoc Gem. Whilst the app doesn't use it directly, `irb` has it as a dependency. This PR simply bumps the version constrained in the `Gemfile.lock` so that the patched version is installed.
[1] https://www.ruby-lang.org/en/news/2021/05/02/os-command-injection-in-rdoc/
=> CVE-2021-31799: A command injection vulnerability in RDoc

doc/getting-started.md, script/start_backing_services, script/stop_backing_services
The `docker-compose` command has been removed and included in the
`docker` command - this work adjust our scripts to reflect this change
and use `docker compose`.
=> Update for docker compose

CHANGELOG.md, app/models/concerns/teamable.rb, app/policies/export_policy.rb, config/locales/teams.en.yml, config/locales/user.en.yml, spec/features/all_projects/by_month/users_can_view_projects_by_month_spec.rb, spec/features/all_projects/export/export_users_can_see_an_export_landing_page_spec.rb, spec/models/statistics/user_statistics_spec.rb, spec/models/user_spec.rb, spec/policies/export_policy_spec.rb
We are going to consolidate the EFSA & APOU users into one "can export" team.
First of all, create a new team these users will eventually belong to and give the team the same permissions as existing ESFA & AOPU teams.
=> (178320) Add a new "Data consumers" team

CHANGELOG.md, app/models/note.rb, spec/factories/note_factory.rb, spec/models/note_spec.rb
'Project level notes' are:
- not notes associated to a task
- not notes associated to a change of significant date
but they are:
- notes associated to a DAO revocation
- all other types of notes
This work adjusts the scope we use to define this and in summary,
removes the significant date change notes from the project notes tab,
they are still shown on their own tab.
=> Update project level notes scope

Gemfile, Gemfile.lock, config/initializers/govuk_markdown.rb
Whilst testing a Rails update, we found the new version of this gem
requires a slight change to our custom renderer.
We are just passing the new `govuk_options` in.
=> Update the govuk_markdown gem

app/services/data_consumers_migration_service.rb, spec/services/data_consumers_migration_service_spec.rb
We are consolidating all ESFA and AOPU users into a new "data consumers" team. This migration moves all ESFA and AOPU users innto the new team.
=> Migrate users in the AOPU and ESFA teams into the "data consumers" team

README.md
Fix the link to the event logging doc.
=> Fix readme link to event logging doc

CHANGELOG.md, app/models/conversion/task_list.rb, app/models/transfer/task_list.rb, spec/features/conversions/users_can_confirm_the_chair_of_governors_contact_spec.rb, spec/features/conversions/users_can_confirm_the_headteacher_contact_spec.rb, spec/features/conversions/users_can_confirm_the_incoming_trust_ceo_contact_spec.rb, spec/features/transfers/users_can_confirm_the_headteacher_contact_spec.rb, spec/features/transfers/users_can_confirm_the_incoming_trust_ceo_contact_spec.rb, spec/features/transfers/users_can_confirm_the_outgoing_trust_ceo_contact_spec.rb, spec/models/conversion/task_list_spec.rb, spec/models/transfer/task_list_spec.rb
The RPA task is being missed by some caseworkers, move it higher up the task list to see if this makes it more obvious.
=> Move the Risk Protection Policy task to the first tasklist section

CHANGELOG.md, app/controllers/tasks_controller.rb, spec/requests/tasks_controller_spec.rb
When loading a task into the edit view it was previously possible to put
in any string as the path and raise an error as the controller tries to
load the class with the string.
This work adds an error when the path cannot be turned into a Task class
and `rescues_from` from the error with a 404 page.
=> Fix unknown task identifiers

CHANGELOG.md, app/forms/conversion/task/proposed_capacity_of_the_academy_task_form.rb, spec/features/conversions/users_can_complete_conversion_tasks_spec.rb, spec/forms/conversion/tasks/proposed_capacity_of_the_academy_task_form_spec.rb
Whilst the implementation of this task is not ideal, we know it was
working at some point as we have data in production. Around the time of
the upgrade to Rails 7.1 we had a report of not being able to submit
valid values.
When we investigated we noticed that the columns in the database are
stored as strings, there wasn't any test coverage for the custom data in
the task and the validation was not working as expected.
This work fixes the validation and adds test coverage, however we
decided not to change the database column at this time because we want
to unblock users quickly.
=> Fix the proposed capacity task

CHANGELOG.md
- unknown task identifier paths now show a 'page not found' error.
- the conversion project 'Confirm the proposed capacity of the academy' is now
fixed and accepting values.
=> Release 86

CHANGELOG.md, app/models/project.rb, spec/accessibility/contacts_spec.rb, spec/features/conversions/users_can_complete_conversion_tasks_spec.rb, spec/features/conversions/users_can_select_a_main_contact_spec.rb, spec/features/external_contacts/users_can_add_new_external_contacts_spec.rb, spec/features/external_contacts/users_can_edit_external_contacts_spec.rb, spec/features/external_contacts/users_can_view_external_contacts_spec.rb, spec/features/transfers/tasks/users_can_compelte_main_contact_spec.rb, spec/features/transfers/users_can_view_a_transfer_spec.rb, spec/models/project_spec.rb, spec/presenters/export/csv/mp_presenter_module_spec.rb, spec/requests/external_contacts_controller_spec.rb, spec/requests/member_of_parliament_controller_spec.rb
We had this disabled whilst the Persons API was deployed to all
environments, as this has now been done, we can enable the return of an
MP.
=> Return a Member of parliament from Project

CHANGELOG.md, app/services/export/conversions/all_data_csv_export_service.rb
Adding the MP details to exports affects the performance. Users don't need the MP details in this export anyway, so remove them.
=> Remove the MP details from the Conversion "by month" exports

terraform/README.md, terraform/container-apps-hosting.tf, terraform/locals.tf, terraform/variables.tf
The default number of containers is `1` but in Production we occasionally run into issues with Container App host migrations. Having `2` minimum in Production should cover us for any interruptions
=> Allow operators to override the default minimum number of app Containers

CHANGELOG.md, config/locales/conversion/tasks/academy_details.en.yml, config/locales/conversion/tasks/conditions_met.en.yml, config/locales/conversion/tasks/direction_to_transfer.en.yml, config/locales/conversion/tasks/trust_modification_order.en.yml, config/locales/transfer/tasks/conditions_met.en.yml
The new government have change the name of the Academies Operational Practice Unit to the Schools Operational Practice Unit.
This work makes those changes in content in Complete.
=> AOPU becomes SOPU

config/locales/project.en.yml, spec/features/projects/users_can_view_a_list_of_regional_casework_services_projects_spec.rb
Make these page titles more explicit, mainly so that they show up in
analytics clearly.
=> Update your team page titles

config/locales/en.yml, spec/features/users_can_view_static_pages_spec.rb
It would be helpful to the team to see this specific error in the
analytics.
=> Update Academies API timeout error

CHANGELOG.md, app/presenters/export/csv/school_presenter_module.rb, app/services/export/conversions/rpa_sug_and_fa_letters_csv_export_service.rb, spec/presenters/export/csv/school_presenter_module_spec.rb
The headteacher needs to be included in the RPA, SUG and FA letters
export.
The role must always be 'Headteacher' so we update the presenter to make
sure this is the case (we have taken steps to ensure that newly added
contacts have the correct role, but this covers legacy contacts as
well).
=> Add confirm headteacher contact details to export

CHANGELOG.md, app/presenters/export/csv/incoming_trust_presenter_module.rb, app/services/export/conversions/rpa_sug_and_fa_letters_csv_export_service.rb, spec/presenters/export/csv/incoming_trust_presenter_module_spec.rb
The incoming trust CEO needs to be included in the RPA, SUG and FA letters
export.
The role must always be 'CEO' so we update the presenter to make
sure this is the case (we have taken steps to ensure that newly added
contacts have the correct role, but this covers legacy contacts as
well).
=> Add confirm incoming trust contact details to export

app/forms/base_optional_task_form.rb, app/forms/base_task_form.rb, app/forms/conversion/task/sponsored_support_grant_task_form.rb, app/forms/transfer/task/declaration_of_expenditure_certificate_task_form.rb, app/forms/transfer/task/sponsored_support_grant_task_form.rb, spec/forms/conversion/tasks/articles_of_association_task_form_spec.rb
When marked as not applicable, some tasks clear their other values. We want this
to be the default behaviour for all optional tasks.
This work does that using callbacks on the `BaseTaskForm` which all tasks
inherit from.
=> Not applicable tasks clear their values

CHANGELOG.md, app/policies/export_policy.rb, spec/policies/export_policy_spec.rb
We want team lead users, those with the `manage_team` attribute set to
use the exports.
Here we adjust the policy to allow this.
=> Allow team leads to export data

CHANGELOG.md, app/presenters/export/csv/school_presenter_module.rb, app/services/contacts_fetcher_service.rb, config/locales/export/csv/project.en.yml, spec/presenters/export/csv/school_presenter_module_spec.rb, spec/services/contacts_fetcher_service_spec.rb
Remove logic from primary establishment contact
Having this logic is confusing users, if the primary establishment
contact is not set, showing nothing is a better outcome.
The column header is also causing confusion, we are going to use the
phrase 'Primary school contact' for this export as it matches up with
the application UI.
=> Remove logic from primary establishment contact

CHANGELOG.md, app/presenters/export/csv/incoming_trust_presenter_module.rb, app/services/contacts_fetcher_service.rb, config/locales/export/csv/project.en.yml, spec/presenters/export/csv/incoming_trust_presenter_module_spec.rb, spec/services/contacts_fetcher_service_spec.rb
Having this logic is confusing users, if the primary incoming trust
contact is not set, showing nothing is a better outcome.
The column header is also causing confusion, we are going to use the
phrase 'Primary contact for incoming trust' for this export as it
matches up with the application UI.
=> Remove logic from primary incoming trust contact

CHANGELOG.md, app/presenters/export/csv/outgoing_trust_presenter_module.rb, app/services/contacts_fetcher_service.rb, app/services/export/transfers/all_data_csv_export_service.rb, config/locales/export/csv/project.en.yml, spec/presenters/export/csv/outgoing_trust_presenter_module_spec.rb, spec/services/contacts_fetcher_service_spec.rb
Having this logic is confusing users, if the primary outgoing trust
contact is not set, showing nothing is a better outcome. We also added
the primary outgoing trust contact role.
The column header is also causing confusion, we are going to use the
phrase 'Primary contact for outgoing trust' for this export as it
matches up with the application UI.
=> Remove logic from primary outgoing trust contact

CHANGELOG.md, config/locales/conversion/tasks/main_contact.en.yml, config/locales/transfer/tasks/main_contact.en.yml
This content is misleading as the main contact is not used for the
funding letters.
=> Update the main contact task content

app/models/project.rb, spec/models/project_spec.rb
Projects will soon be able to be added to Complete via an API call. These projects will be automatically created by the Prepare application.
Because the Prepare application does not hold all the mandatory information we need to create projects in Complete, these projects will be invalid. We need a way to indicate they are not ready to be worked on yet - they need to be triaged by DOs and put into a valid state.
To this end, add an "inactive" state to indicate these projects are not valid yet, and therefore cannot be worked on ("active" state).
=> Add an "inactive" state to projects

app/api/v1/api.rb, app/api/v1/conversions.rb, app/api/v1/transfers.rb, app/services/api/base_create_project_service.rb, app/services/api/conversions/create_project_service.rb, app/services/api/transfers/create_project_service.rb, spec/api/v1/conversions_spec.rb, spec/api/v1/transfers_spec.rb, spec/services/api/conversions/create_project_service_spec.rb, spec/services/api/transfers/create_project_service_spec.rb
The Complete API can already create a conversion project and a form a MAT
conversion project. This work adds transfer and form a MAT transfer projects
along with some improvements and fixes.
The API is not used in production yet so we have time to make improvements
beyond this work, but we wanted to keep this part as small as we could.
=> API can create transfer projects

CHANGELOG.md, app/presenters/export/csv/incoming_trust_presenter_module.rb, app/presenters/export/csv/outgoing_trust_presenter_module.rb, app/presenters/export/csv/school_presenter_module.rb, app/services/contacts_fetcher_service.rb, app/services/export/conversions/rpa_sug_and_fa_letters_csv_export_service.rb, app/services/export/transfers/all_data_csv_export_service.rb, config/locales/export/csv/project.en.yml, spec/presenters/export/csv/incoming_trust_presenter_module_spec.rb, spec/presenters/export/csv/outgoing_trust_presenter_module_spec.rb, spec/presenters/export/csv/school_presenter_module_spec.rb, spec/services/contacts_fetcher_service_spec.rb
Revert PRs #1881, #1882, #1883, #1869 and #1870
We do want to use these changes in the future, but not until October 2024 when the SOPU team will be ready for them and have updated their own processes accordingly.
Instead of reverting each PR in its own PR, we have reverted them all as commits in one PR. This will hopefully 🤞 make it easier to un-revert them in October.
=> Revert exports changes

app/api/v1/conversions.rb, app/api/v1/transfers.rb, app/services/api/base_create_project_service.rb, app/services/api/conversions/create_project_service.rb, app/services/api/transfers/create_project_service.rb, spec/services/api/conversions/create_project_service_spec.rb, spec/services/api/transfers/create_project_service_spec.rb
This work allows the API to create grouped projects by accepting the group
identifier from Prepare.
Along the way we update and refactor some specs.
[Task 180539](https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/180539?McasTsid=26110&McasCtx=4): Update existing API calls to find or create project groups
=> API can create grouped projects

app/api/v1/transfers.rb, spec/api/v1/transfers_spec.rb
We require the outgoing trust UKPRN to create Transfers via the API, but had accidentally omitted it from the API params.
=> (Fix) Add missing outgoing_trust_ukprn to Transfers API params

CHANGELOG.md, app/models/api/persons/member_details.rb, spec/features/external_contacts/users_can_view_external_contacts_spec.rb, spec/models/api/persons/client_spec.rb, spec/models/api/persons/member_details_spec.rb, spec/models/project_spec.rb, spec/presenters/export/csv/mp_presenter_module_spec.rb, spec/requests/member_of_parliament_controller_spec.rb, spec/support/persons_api_helpers.rb
The consumers of the exports want to address their letters to MPs using the MP's full name & title (e.g. the Right Honourable). We can get this from the Persons API as `displayNameWithTitle`
Keep the first & last name for now in case we still need to use these elsewhere.
=> (181801) Show the MP's display name with title

app/models/api/academies_api/client.rb, spec/models/api/academies_api/client_spec.rb
We can't rely on the bulk endpoints to return 404 if we send a single
parameter that cannot be found, instead we should use the single
endpoint which will tell us if a record cannot be found.
When nothing is found on the bulk endpoints, 200 is returned with an
empty array of results, this is probably fine for us because:
- projects with missing urns are very unlikely due to validation (but
not impossible!)
- the Project model falls back to fetching the establishment or trust
itself if the bulk prefetch operation returns nothing
This is all a hangover from when the 'bulk' endpoints were much (much)
faster than the single ones so we used them everywhere (v1 of the API).
=> Update Academies API client

app/services/api/base_create_project_service.rb, app/services/api/conversions/create_project_service.rb, app/services/api/transfers/create_project_service.rb, app/validators/urn_unique_for_api_validator.rb, config/locales/conversion_project.en.yml, config/locales/transfer_project.en.yml, spec/api/v1/conversions_spec.rb, spec/api/v1/transfers_spec.rb, spec/models/project_group_spec.rb, spec/services/api/conversions/create_project_service_spec.rb, spec/services/api/transfers/create_project_service_spec.rb, spec/support/academies_api_helpers.rb
This work sets out to update the validation applied when a new project is created via the API. Essentially the validation is the same as the manual process the form objects use, with slight variations.
There is a lot of duplication here which is to be expected as the objects work in similar ways with variations, the end goal is to get rid of the manual forms, so at that point a lot of the duplication goes away.
Along the way we tried to make the specs as clear and as similar as possible, but this is possibly subjective!
=> Add validaton to new projects on API

spec/api/v1/conversions_spec.rb, spec/api/v1/transfers_spec.rb
These API specs are working a little too hard, covering behaviour that really
belongs in the services that back the API.
This work refactors the specs to focus on more generic behaviour:
- successful request
- validation errors
- other errors
- required fields
- optional fields
- authorisation
=> Refactor API specs

app/services/api/base_create_project_service.rb, app/services/api/conversions/create_project_service.rb, spec/services/api/transfers/create_project_service_spec.rb
This attribute is only for conversions so we move it to the subclass and
remove it from the transfer spec where it never got used.
Based on #1918
=> Remove directive academy orders from API Transfers

app/api/v1/conversions.rb, app/api/v1/transfers.rb, app/services/api/base_create_project_service.rb, app/services/api/conversions/create_project_service.rb, app/services/api/transfers/create_project_service.rb, spec/api/v1/conversions_spec.rb, spec/api/v1/transfers_spec.rb, spec/services/api/conversions/create_project_service_spec.rb, spec/services/api/transfers/create_project_service_spec.rb
This work makes the validation errors returned by the API structured instead of
one big string.
Based on #1920
=> Better API validation errors

app/controllers/all/handover/projects_controller.rb, app/policies/project_policy.rb, app/views/all/handover/projects/_handover_table.html.erb, app/views/all/handover/projects/_transfer_summary.html.erb, app/views/all/handover/projects/conversion/check.html.erb, app/views/all/handover/projects/index.html.erb, app/views/all/handover/projects/transfer/check.html.erb, config/locales/handover.en.yml, config/locales/project.en.yml, config/routes.rb, spec/features/all_projects/handover/user_can_handover_projects_spec.rb, spec/features/all_projects/handover/user_can_view_a_list_of_projects_spec.rb, spec/policies/project_policy_spec.rb, spec/requests/all/handover/projects_controller_spec.rb
This works start the handover journeys for Regional Delivery Officers to hand
projects that have been created on the API from the Prepare application to other
users.
We introduce the index view of projects in the `inactive` state and a 'check
you have the right project' view for both conversions and transfers.
Users can cancel from the check pages, returning to the index.
We have not added the index to the navigation yet or implemented the actual handover process.
The API is not in use right now so there is no risk of users attempting this journey even if they came across it without the navigation.
=> Handover index and check views

app/forms/new_handover_stepped_form.rb, spec/forms/new_handover_stepped_form_spec.rb
To 'handover' a project created on the API we need to add some
attributes that do not exist in the Prepare application and so cannot be
provided, projects added via the API are invalid until this is done.
The attributes differ for conversions and transfers and the actual
assignment to a user is different depending on the team the project is
assigned to.
As the variation is so small, we kept to this single fancy form object
with two validation contexts. Project use single table inheritance, so
we can assign the project type attributes regardless.
The default context is used when the project is assigned to the Regional
casework services team.
The 'assign' context is used when the project is assigned to one of the
regional teams and so requires extra attributes to be set.
This essentially …
=> Add handover form object

app/api/api.rb
We need to make the security declaration and requirement for the API to
work in the Swagger docs:
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#security-requirement-object
=> Fix: Auth in API docs

CHANGELOG.md, app/controllers/your/projects_controller.rb, app/models/project.rb, spec/features/projects/added_by/user_can_view_the_projects_they_have_added_spec.rb, spec/models/project_spec.rb
A user reported that they were seeing a deleted project in their "Added by" page. We were not explicitly excluding deleted projects from the "Added by" page or scope.
=> (Fix) Do not show deleted projects in the "Added by" page

CHANGELOG.md, app/models/gias/establishment.rb, app/views/conversions/project_information/_academy_details.html.erb, config/locales/project_information.en.yml, spec/models/gias/establishment_spec.rb
This request came in the 'front door' from a service support user. We
already have the value as `dfe_number` to keep things as clear as we can
I've made an alias of that method and labelled the value with both
'LAESTAB' and 'DfE number'.
=> Add LAESTAB/DfE Number to new academy details

app/controllers/all/handover/handovers_controller.rb, app/controllers/all/handover/projects_controller.rb, app/controllers/concerns/projectable.rb, app/forms/new_handover_stepped_form.rb, app/views/all/handover/projects/_handover_table.html.erb, app/views/all/handover/projects/assign.html.erb, app/views/all/handover/projects/assigned_region.html.erb, app/views/all/handover/projects/assigned_regional_casework_services.html.erb, app/views/all/handover/projects/conversion/check.html.erb, app/views/all/handover/projects/conversion/new.html.erb, app/views/all/handover/projects/transfer/check.html.erb, app/views/all/handover/projects/transfer/new.html.erb, config/locales/en.yml, config/locales/handover.en.yml, config/locales/project.en.yml, config/routes.rb, spec/features/all_projects/handover/handover_conversion_project_spec.rb, spec/features/all_projects/handover/handover_transfer_project_spec.rb, spec/features/all_projects/handover/user_can_handover_projects_spec.rb, spec/forms/new_handover_stepped_form_spec.rb, spec/requests/all/handover/handovers_controller_spec.rb, spec/requests/all/handover/projects_controller_spec.rb
There is a lot here, apologies! This is one journey with four paths and
we are handling it all with the fancy `NewHandoverSteppedForm` object so
it all comes at once!
This delivers a basic, working path for:
- handing over a conversion to Regional Casework Services
- handing over a conversion to a user in the Regional teams
- handing over a transfer to Regional Casework Services
- handing over a transfer to a user in the Regional teams
Designs are here:
https://lucid.app/lucidspark/92056362-3523-413b-b954-7095607f95e9/edit?viewport_loc=13690%2C40250%2C5056%2C5276%2C0_0&invitationId=inv_1f6d15aa-a815-4f0e-91ac-c52940ae8ab8
The approach is that we don't want users to be able to return midway
through the steps (if they are on a path with steps) so we favour
rendering views over new paths - …
=> User can handover inactive projects

app/javascript/application.js, app/views/all/handover/projects/assign.html.erb, spec/features/all_projects/handover/handover_autocomplete_spec.rb, spec/rails_helper.rb
When assigning a Regional Delivery Officer to a project we progressively
enhance the email field into a autocomplete that looks up known users.
To test this we have to configure Capybara to `allow_label_click`
because the GOV.UK forms use hidden form elements.
Based on #1931
=> Handover assignment uses autocomplete

app/views/all/handover/projects/conversion/check.html.erb, app/views/all/handover/projects/transfer/check.html.erb, config/locales/handover.en.yml, spec/features/all_projects/handover/user_can_handover_projects_spec.rb
The only difference here is that the incoming trust is replaced by a new
trust and reference number, everything else is the same so we've popped
the logic into the view.
Based on #1931
=> Show form a MAT projects for Handover

CHANGELOG.md, app/views/all/handover/projects/assign.html.erb, app/views/all/handover/projects/assigned_region.html.erb, app/views/all/handover/projects/assigned_regional_casework_services.html.erb, app/views/all/handover/projects/conversion/check.html.erb, app/views/all/handover/projects/transfer/check.html.erb, app/views/shared/navigation/_all_projects_primary_navigation.html.erb, config/locales/en.yml, spec/features/all_projects/handover/user_can_view_a_list_of_projects_spec.rb, spec/requests/all/handover/projects_controller_spec.rb
This is only shown to user with the permission (Regional Delivery
Officers right now).
We also ensure all the handover paths have a page title and the primary
navigation is not shown unless on the index view.
=> Handover navigation

CHANGELOG.md, app/policies/export_policy.rb, app/views/all/export/projects/index.html.erb, app/views/shared/navigation/_service_support_primary_navigation.html.erb, spec/features/all_projects/export/export_users_can_see_an_export_landing_page_spec.rb
We think this is from a time when Service Support could not access the
All projects section. There is no good reasons to have two different
export menus and we loos a tiny bit of view logic!
=> Remove duplicate navigation item

app/services/api/base_create_project_service.rb, spec/api/v1/conversions_spec.rb, spec/api/v1/transfers_spec.rb
Returning the same validation as the application UI on the API can be a
little misleading, date formats are different for example.
This work changes from the error messages to the error details,
essentially the keys used to identify the validation error, which should
be descriptive enough for the API as it is only accessed by internal
developers.
=> Change API errors

CHANGELOG.md, app/forms/conversion/create_project_form.rb, app/forms/create_project_form.rb, app/forms/transfer/create_project_form.rb, spec/forms/conversion/create_project_form_spec.rb, spec/forms/transfer/create_project_form_spec.rb
We now have projects potentially being created on the API and do not
want users to attempt to manually create the same project i.e the same
type of in-progress project with the same URN.
This work updates the validation to facilitate this and moves the actual
validation methods into better locations.
=> Update create new project validation

app/views/shared/navigation/_all_projects_primary_navigation.html.erb, spec/features/all_projects/handover/user_can_view_a_list_of_projects_spec.rb
We don't want users to see this navigation item until the Prepare
application is successfully sending us projects.
=> Disable the Handover navigation

CHANGELOG.md, app/views/shared/_dfe_footer.html.erb, spec/features/navigation/footer_navigation_spec.rb, spec/features/your_projects/users_can_view_their_projects_spec.rb
The Regions Group footer was recently updated.
https://design-system-rsd-c10b0db1a3a1.herokuapp.com/design-system/rsd-design-system/design-patterns/footer#example-tabs__panel-footer
=> Update the footer to the latest version

spec/features/internal_contacts/users_can_edit_the_assigned_user_with_autocomplete_spec.rb
When running in CI we often see the autocomplete specs fail. We think
this might be caused by the suite running faster than the browser can
render the expected elements.
Elsewhere we have put a short sleep in to give the browser time to
load, so we do the same here.
=> Fix: attempt to fix flaky autocomplete spec

.github/workflows/ci-checks.yml
The Docker job in our CI fails almost every time due to a known issue.
As we do not require the docker tests to pass in order to pass, we would
rather not show our branches as failing, when they really aren't.
Here we tell Github actions to not fail the CI workflow if the docker job
fails.
=> Allow CI to pass without docker job

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .devcontainer/setup.sh, app/views/sessions/new.html.erb, config/environments/development.rb, config/initializers/omniauth.rb, doc/getting-started.md, doc/running-with-codespaces.md
We had a requirement to run this application on Windows instead of MacOS (which most developers use). After a lot of discussion it was decided that enabling Codespaces on this repo was the "simplest" solution of many complex ones! This PR adds the Codespaces config and instructions on how to use it.
Co-authored by @mec with help from @peteryates
=> Enable users to run this repository using Codespaces

CHANGELOG.md, config/locales/conversion/tasks/risk_protection_arrangement.en.yml, spec/features/conversions/users_can_complete_conversion_tasks_spec.rb
We've had user feedback to tell us that an academy cannot join a trust RPA. It much be standard, church or commercial insurance.
This work removes the text that refers to the trust RPA from the second radio button on the task.
=> removing trust from church and trust option in RPA task

CHANGELOG.md, app/models/note.rb, spec/models/note_spec.rb
When we had our first DAO revocation in production it was noted that the
associated note was shown on all projects in the application.
This was caused by the `or` statement not limited the notes to only
those for the project.
A DAO Revocation note should appear in project notes, but only for the
project to which it is associated.
We have removed the `or` altogether in this fix.
=> Fix: DAO revocation notes on all projects

CHANGELOG.md
Changed
- removed trust from the RPA radio button options text for conversions
Fixed
- The note added during DAO revocation only appears on the associated project notes, instead of all projects.
=> Release 93

spec/features/internal_contacts/users_can_edit_the_added_by_user_with_autocomplete_spec.rb, spec/features/internal_contacts/users_can_edit_the_assigned_user_with_autocomplete_spec.rb
Whilst most of these feature specs work fine, there is one that is
flaky in CI, we see this occasionally, e.g.
https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/actions/runs/11482067947/job/31954234121
Although adding these sleeps slows down the specs, the price is worth it
for consistency.
We basically have to wait for the autocomplete to be rendered so we can
target the resulting elements.
=> Fix autocomplete feature specs

CHANGELOG.md, app/views/shared/navigation/_all_projects_primary_navigation.html.erb, spec/features/all_projects/handover/user_can_view_a_list_of_projects_spec.rb
We are getting ready to accept projects from Prepare via our API.
In order for us to test projects have been sent over successfully, reveal the 'Handover' section for RDOs.
=> Enable the Project Handover section

CHANGELOG.md, app/policies/project_policy.rb, spec/policies/project_policy_spec.rb
Grant PASS users access to the Handover tab, so they can see projects handed over from the Prepare application. This is so they can respond to user queries.
=> Give Service Support users access to see projects from Prepare

Gemfile, Gemfile.lock
This isn't used anywhere, so remove it so we don't have to keep updating it.
=> Remove diffy gem

app/api/v1/conversions.rb, app/api/v1/transfers.rb, spec/api/v1/conversions_spec.rb, spec/api/v1/transfers_spec.rb
We have had several instances of Conversion projects (not form a MAT) being sent over from Prepare without an incoming trust UKPRN.
After some investigation we realised the projects were being sent with a UKRPN of "0", which passes the API validation (which looks for an integer) but is not a valid UKPRN. So the projects end up in our "Handover" section with an unknown UKPRN and cannot be progressed by users.
It seems like Prepare parses a nil UKPRN to 0. If Prepare was passing nil or an empty string, our validation would have worked.
To stop this happening, tighten up the validation on our side to look for an integer which is 8 digits long (for UKPRN) or 6 digits long (for URN) using a regular expression.
=> Add length validation to URN and UKPRN parameters in API

spec/rails_helper.rb
This allows us to see a styled page when debugging a test
and viewing the page with `save_and_open_page`.
=> Serve Capybara assets from localhost:3000

Gemfile, Gemfile.lock
This provides handy debugging behaviour on top of pry, e.g.
- *break*: Manage breakpoints.
- *step*: Step execution into the next line or method.
Takes an optional numeric argument to step
multiple times.
- *next*: Step over to the next line within the same frame.
Also takes an optional numeric argument to step
multiple lines.
- *finish*: Execute until current stack frame returns.
- *continue*: Continue program execution and end the Pry session.
=> Add pry-byebug for more debugging commands

.github/workflows/ci-checks.yml
Occasionally we run into a problem where the Docker image scan task encounters a TOOMANYREQUESTS error and times out. By caching the vulnerability database we reduce the frequency that we need to check for new versions.
=> Cache the trivydb for a day to mitigate TOOMANYREQUESTS error

spec/features/all_projects/by_month/users_can_view_projects_by_month_spec.rb
These tests started failing in December 2024 as we weren't factoring in the change of year 2024 -> 2025. We were expecting *this* year when looking for the next month's data,
but in December the "next month" exports will start returning *next* year's results.
=> (Fix) Account for the change in year in export tests

doc/auth-and-session-cookie.md, lib/tasks/session.rake
See `lib/tasks/session.rake` for a demonstration of how the session cookie is decrypted with a PBKDF2 secret (AES-256-GCM cipher) which includes:
- `Rails.application.secret_key_base`: a random string used as an input secret to the app's key generator
- `Rails.configuration.action_dispatch.authenticated_encrypted_cookie_salt`: Rails uses different salts for both encrypted and signed cookies
- `Rails.configuration.active_support.hash_digest_class`: a SHA256 digest
By decrypting the logged in user's cookie in this way the .NET application will be able to obtain the `user_id` needed to look up the user in the complete `users` table.
To run the rake task and decrypt a cookie which you've pulled out of your browser's devtools, supply the undecoded cookie like this:
```
bundle exec rake …
```
=> Add rake task to demonstrate session cookie decryption

.github/workflows/ci-checks.yml
* without the source, the sonar-project.properties file is missing which prevents Sonarcloud from understanding how we want it to scan the project
=> Ensure source is checked out for Sonar scan to work

CHANGELOG.md, app/assets/stylesheets/application.scss
These were being overridden by the DfE styles, ending up blue when they should be white.
=> (Fix) Force Header and DfE Nav links to always be white

app/models/concerns/teamable.rb, app/models/user.rb
On the dev environment (but not locally) we saw an issue with OpenStruct
not being loaded correctly when adding or editing a user in the Service
Support view:
```
ActionView::Template::Error (uninitialized constant User::OpenStruct):
```
We had previously seen a similar issue with the CookiesForm which was
also not reproducible locally, and was fixed in PR https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/1735
The issue seems to be with OpenStruct not loading or being overriden
by _something_ else, but as it is not reproducible locally it is hard
to diagnose.
In PR https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/1735 we "fixed" the issue by creating an array of OpenStruct
objects for a 2-answer form. For the create/edit …
=> (Fix) Replace OpenStruct with Struct to fix loading issue

CHANGELOG.md
- No longer unassign project on update when team is RCS.
- Header and DfE Navigation links are now always white, instead of being blue
when in the "unvisited" state.
=> Release 98

CHANGELOG.md
This reverts commit 7869128c063135ac4cc6f763f27f24513802fd7e, reversing changes made to 76f6af3f5c96286590561da68f4972d581cef578.
We've encountered a problem with the loading of OpenStruct which we're going to fix with
https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/2022 before recreating the release branch / tag
=> Revert "Merge pull request #2020 from DFE-Digital/release-98"

app/models/concerns/teamable.rb, app/models/user.rb, config/application.rb
Play past OpenStruct loading issue with global 'require'
We've been seeing "uninitialize constant" errors for OpenStruct
like
```
uninitialized constant ProjectHelper::OpenStruct
```
which we only see the deployed environments, not in local development
or in CI.
This appears to be a file/class/module loading problem which occurs after
unrelated changes to the codebase.
To play past this issue we now explictly `require "ostruct"` from the
main `application.rb` file.
=> Play past OpenStruct loading issue with global 'require'

.github/workflows/ci-checks.yml
Reverts DFE-Digital/dfe-complete-conversions-transfers-and-changes#2029
This seems to have stopped CI checks for all branches.
=> Revert "Exclude terraform folder from CI checks workflow"

CHANGELOG.md, app/api/v1/healthcheck.rb, spec/api/v1/healthcheck_spec.rb
The other products in the programme are all returning a string rather than a JSON representation.
We now:
- conform to that convention
- include a db connection test
=> Return 'Healthy' or 'Unhealthy' string after db test

app/controllers/healthcheck_controller.rb, spec/requests/healthcheck_controller_spec.rb
In PR #2030 we altered the API healthcheck (`/api/v1/healthcheck`) endpoint to return plain text instead of JSON. We forgot that we actually have two healthcheck endpoints, one simply at `/healthcheck`. Change this endpoint to also return plain text.
=> Change healthcheck endpoint to render plain text

app/api/v1/healthcheck.rb, app/controllers/healthcheck_controller.rb, lib/ops/db_availability.rb, spec/api/v1/healthcheck_spec.rb, spec/lib/ops/db_availability_spec.rb, spec/requests/healthcheck_controller_spec.rb
In a previous commit we attempted to check the DB is available by using `AxctiveRecord::Base.connection?`. However this will return false unless you have already opened a connection by (for example) fetching a record.
Change the healthcheck endpoints to check the db is connected by both fetching a record and then checking for DB availability. Put this into a helper module so we can reuse it in both checks.
=> Check DB connection is available by fetching a record

Gemfile, Gemfile.lock
In this PR we provide some support for developing with VSCode:
Add gems to aid dev with VSCode
- solargraph language server: the [solargraph gem][] works with the [VSCode Solargraph extension][] to provide a lot of functionality for exploring the code and language
- the [htmlbeautifier gem][] is required by VS Code's [ERB Formatter/Beautify extension][]
[solargraph gem]:
https://github.com/castwide/solargraph
[VSCode Solargraph extension]:
https://marketplace.visualstudio.com/items?itemName=castwide.solargraph
[htmlbeautifier gem]:
https://github.com/threedaymonk/htmlbeautifier
[ERB Formatter/Beautify extension]:
https://marketplace.visualstudio.com/items?itemName=aliariff.vscode-erb-beautify
=> Add gems to aid dev with VS Code

app/javascript/application-insights.js
See ticket [193590: Add tracking of "Time on page" with AppInsights](https://dev.azure.com/dfe-gov-uk/Academies-and-Free-Schools-SIP/_workitems/edit/193590)
This is to track "time on page".
See https://learn.microsoft.com/en-us/azure/azure-monitor/app/javascript-sdk-configuration
=> 193590: Set PageVisitTime metric in AppInsights

app/controllers/application_controller.rb, app/javascript/application-insights.js, app/views/layouts/application.html.erb, spec/features/home_page/track_user_with_appinsights_spec.rb
See [Ticket 193814](https://dev.azure.com/dfe-gov-uk/Academies-and-Free-Schools-SIP/_workitems/edit/193814)
We use the email address to identify the user. To achieve this we:
- set the email of the "current user" in a hidden input in the DOM,
defaulting to "Anonymous" if there is no logged-in user
- extract this email from the DOM when initialising AppInsights
(we now need to wait for the DOM to be ready/loaded)
- set `appInsights.setAuthenticatedUserContext(currentUserEmail(), null, true)`
see https://github.com/microsoft/ApplicationInsights-JS/blob/master/API-reference.md#setauthenticatedusercontext
for details
=> 193814: identify authenticated user in app insights

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/pages_controller.rb, config/application.rb, config/initializers/high_voltage.rb, config/routes.rb, lib/middleware/handle_bad_encoding.rb, lib/middleware/handle_bad_query.rb, spec/lib/middleware/handle_bad_encoding_spec.rb, spec/lib/middleware/handle_bad_query_spec.rb, spec/requests/error_handling_spec.rb
See Slack channel [`#temp-ruby-complete-alerts`](https://ukgovernmentdfe.slack.com/archives/C089F7F3CD6) and [ticket 197151](https://dev.azure.com/dfe-gov-uk/Academies-and-Free-Schools-SIP/_workitems/edit/197151)
In this PR we address 4 types of error which have been surfaced by our new Exception Notification process. These are currently manifesting as unhandled exceptions but in fact they are routine errors which can and should be handled by the application:
1. where `ActionController::InvalidAuthenticityToken` is raised as a result of a request having an an invalid auth token
2. where a very long request path was triggering an error in the `HighVoltage` gem
3. where a path with invalid encoding was causing Rack to raise `InvalidParameterError`  which is rescued by Rails as a internal …
=> Handle some common errors, previously seen as unhandled exceptions

lib/ops/db_availability.rb, spec/lib/ops/db_availability_spec.rb
When the application has been freshly started the db connection takes a second or two to get established.
If we ask `ActiveRecord::Base.connected?` during this period a `ActiveRecord::ConnectionNotEstablished` is raised.
We now rescue this in our `Ops::DbAvailability::db_available?` utility and return `false`.
=> Return false on healthcheck if db connection is cold

app/controllers/application_controller.rb, spec/requests/conversions/projects_controller_spec.rb, spec/requests/transfers/projects_controller_spec.rb, spec/support/academies_api_helpers.rb
Ticket [197794](https://dev.azure.com/dfe-gov-uk/Academies-and-Free-Schools-SIP/_workitems/edit/197794) 
We continue to render the `pages/academies_api_client_timeout` view and return a 500 status, but we now send an "exception notification" to the Slack channel to give us visibility on these errors.
=> 197794: Send an exception notification when rescuing AcademiesApi::Client::Error

CHANGELOG.md, db/migrate/20250127172701_backfill_missing_date_history_reason_notes.rb, db/schema.rb, spec/migrations/backfill_missing_date_history_reason_notes_spec.rb
See Ticket [198116](https://dev.azure.com/dfe-gov-uk/Academies-and-Free-Schools-SIP/_workitems/edit/198116) 
We've observed errors in production where a user is viewing the "Conversion data history" of a project at path such as:
`/projects/{projectId}/date-history`
due to a `SignificantDateHistoryReason` missing its `Note`.
On investigation we've found just one `Project` (and `SignificantDateHistory` record) affected by this problem where the "reason" for the change is blank:
```
irb(main):006> SignificantDateHistoryReason.count
=> 3621
irb(main):007> SignificantDateHistoryReason.joins(:note).count
=> 3620
```
The affected record was created on July 1st 2024. We note that since commit [31b50fb7174651649b385fe683bd384c81e5405f][] on June 24th (Release 75) there has been validation on the …
=> 198116 - Fix: Add note where missing from SignificantDateHistoryReason

app/controllers/project_groups_controller.rb, app/forms/conversion/create_project_form.rb, app/forms/transfer/create_project_form.rb, app/models/local_authority.rb, app/models/project.rb, app/services/by_local_authority_project_fetcher_service.rb, spec/factories/conversion/project_factory.rb, spec/factories/local_authority_factory.rb, spec/factories/transfer/project_factory.rb, spec/features/conversions/users_can_create_form_a_mat_conversions_spec.rb, spec/features/transfers/users_can_create_a_transfer_project_spec.rb, spec/forms/conversion/create_project_form_spec.rb, spec/forms/transfer/create_project_form_spec.rb, spec/helpers/contacts_helper_spec.rb, spec/models/project_spec.rb, spec/requests/conversions/projects_controller_spec.rb, spec/requests/transfers/projects_controller_spec.rb, spec/services/by_local_authority_project_fetcher_service_spec.rb
See ticket [196052](https://dev.azure.com/dfe-gov-uk/Academies-and-Free-Schools-SIP/_workitems/edit/196052)
After some more testing on  the dev and test envs we've observed that sometimes the data migration to backfill `projects#local_authority_id` fails to populate a few rows due to transient errors thrown by the Academies API (which is queried for each row). 
We're changing tack on the "deploy in one go" approach (see [PR 2064](https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/2064)) and will  now do the refactoring in 2 deployments:
- i) create the new field, 
- ii) start populating it, 
- iii) backfill the new field
Fix up any rows which didn't get backfilled. If not we may see "whiny nil" errors where projects are missing their local authority …
=> (196052) Step 1 of 2: Refactor project to record local authority

lib/ops/db_availability.rb, spec/lib/ops/db_availability_spec.rb
We're seeing the occasional ActiveRecord::StatementInvalid error from the healthcheck in the middle of the night. We assume this is a short maintenance outage:
An ActiveRecord::StatementInvalid occurred while GET </healthcheck>
was processed by healthcheck#check
Exception
TinyTds::Error: Database 'complete' on server 's184p01-comp' is not
currently available.  Please retry the connection later.
In this commit we adjust our healthcheck's `DbAvailability.db_available?` method to handle this error and return `false`.
=> Handle AR::StatementInvalid in healthcheck

.github/workflows/build-and-push-image.yml
* This change will ensure that the build and import stages no longer use a matrix, thus speeding up the deployment
* As both the main web app and the worker use the same image, we only need to run the deployment stage as a matrix so that we can update both container apps
=> Reduce complexity of deployment strategy

app/controllers/project_groups_controller.rb, app/forms/conversion/create_project_form.rb, app/forms/transfer/create_project_form.rb, app/models/local_authority.rb, app/models/project.rb, app/services/by_local_authority_project_fetcher_service.rb, spec/factories/conversion/project_factory.rb, spec/factories/local_authority_factory.rb, spec/factories/transfer/project_factory.rb, spec/forms/conversion/create_project_form_spec.rb, spec/forms/transfer/create_project_form_spec.rb, spec/helpers/contacts_helper_spec.rb, spec/models/project_spec.rb, spec/services/by_local_authority_project_fetcher_service_spec.rb
See https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/2073 and ticket [196052](https://dev.azure.com/dfe-gov-uk/Academies-and-Free-Schools-SIP/_workitems/edit/196052)
Now that we've successfully back-filled the new `projects.local_authority_id` foreign key we can proceed to:
- i) start using the new association
- ii) fix up the slow pages (e.g. projects/all/local-authorities) to get the benefit of the refactoring
**NB: this work has already been reviewed and merged (https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/2064). However, we decided to deploy in 2 discrete steps -- hence the two new PRs.**
=> (196052) Step 2 of 2: improve performance of local auth project page

app/models/project.rb, db/migrate/20250211093654_add_fk_constraint_on_project_local_authority.rb, db/schema.rb, spec/features/projects/local_authorities/users_can_view_projects_by_local_authority_spec.rb, spec/features/projects/local_authorities/users_can_view_projects_for_a_local_authority_spec.rb, spec/forms/conversion/create_project_form_spec.rb, spec/forms/transfer/create_project_form_spec.rb, spec/models/project_spec.rb, spec/requests/conversions/projects_controller_spec.rb, spec/requests/transfers/projects_controller_spec.rb, spec/support/academies_api_helpers.rb
Now that we have: 
- refactored `Project` to use an Active Record association on `LocalAuthority` rather than retrieving the local association from the `AcademiesApi::Establishment` ([PR 2073](https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/2073))
- backfilled the existing records so that every project has its `local_authority_id` ([PR 2077](https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/2077))
- extended the `Api::Conversions::CreateProjectService` and `Api::Transfers::CreateProjectService` to also set the local authority on projects imported automatically from Prepare ([PR 2085](https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/2085)) 
we are in a position to enforce the referential …
=> 200459 Enforce presence of project's local authority

app/models/capability.rb, app/models/user.rb, app/models/user_capability.rb, db/migrate/20250213122226_create_capability.rb, db/migrate/20250213131024_create_user_capability.rb, db/schema.rb, spec/features/your_projects/users_can_view_their_projects_spec.rb, spec/models/capability_spec.rb, spec/models/user_capability_spec.rb, spec/models/user_spec.rb
The way user roles is managed in Complete (Ruby) has grown quite complex and tangled over time. In this PR we introduce a mechanism to define capabilities on a per-user basis. This can be used to:
1. solve an immediate and urgent support requirement to allow an Regional casework services team member to i) assign projects, ii) be assigned projects, iii) add new projects
2. refactor the existing role/permission behaviour to make it clearer and more maintainable
This PR focuses on [1] (see support tickets [196438](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/196438) and [198181](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/198181))
In this work we define 3 new Capabilities which can be used to override user …
=> 198181: Use "User Capabilities" to override role-related attribute setting

Gemfile, Gemfile.lock
Our exception handling is being thwarted by an error in ApplicationInsights own exception handling. We need to fix this as we require AppInsights for general telemetry and metrics.
`TelemetryClient#track_exception` is throwing an
`undefined method '[]' for nil` error, coming out of:
```
/usr/local/bundle/gems/application_insights-0.5.6/lib/application_insights/telemetry_client.rb:86
:in 'block in ApplicationInsights::TelemetryClient#track_exception'
```
This is due to a failure in the regex which attempts to capture:
- file
- line
- method
from each line in the backtrace. Given:
`/home/roger/.local/share/mise/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/activerecord-sqlserver-adapter-7.1.11/lib/active_record/connection_adapters/sqlserver/database_statements.rb:429:in …
=> Use fixed fork of application insights gem

CHANGELOG.md, app/forms/conversion/task/receive_grant_payment_certificate_task_form.rb, app/models/conversion/project.rb, app/views/conversions/tasks/receive_grant_payment_certificate/edit.html.erb, config/locales/conversion/tasks/receive_grant_payment_certificate.en.yml, config/locales/conversion/tasks/share_information.en.yml, config/locales/conversion_project.en.yml, db/migrate/20250220121430_add_not_applicable_to_receive_grant_payment_certificate_task.rb, db/schema.rb, spec/features/conversions/users_can_complete_a_conversion_project_spec.rb, spec/features/conversions/users_can_complete_conversion_tasks_spec.rb, spec/forms/conversion/tasks/receive_grant_payment_certificate_task_form_spec.rb, spec/models/conversion/project_spec.rb
In December 2024 "voluntary conversion grants" were discontinued.
Note that "sponsored conversion grants" still exist.
In this PR we make the following changes related to the "conversion grant":
- the "Share information about opening" (`share_info`) task no longer refers to the "grant certificate" as "voluntary conversion grants" have been discontinued (See ticket [199562](https://dev.azure.com/dfe-gov-uk/Academies-and-Free-Schools-SIP/_workitems/edit/199562)) 
- the "Receive declaration of expenditure certificate" (`receive_grant_payment_certificate`) task now:
- has a new "Not applicable" option
- will show the "Not applicable" status in the task list, if that option has been selected
- "completing" the project: it is now possible to "complete" the project without having confirmed in …
=> 199543 & 199562: "complete" project without confirming receipt of grant payment certificate

Gemfile, Gemfile.lock
We got caught out after rewording the fix commit on `fix/correct-pattern-match-for-exception-handling` not appreciating that pinning the gem to the branch was actually tieing it to SHA `51cb59a34e3e36ff406f9ec3c8332fb2a2ff89c5` which was of course replaced when rewording the commit.
We now use a tag to pin the forked gem: this is more obviously a pointer to a particular SHA.
=> Fix: Pin forked AppInsights gem to tag rather than branch

CHANGELOG.md
CHANGED
- The "Receive declaration of expenditure certificate" task can now be marked as "Not applicable" and the conversion project can be "completed" in this state. This reflects the fact that voluntary conversion grants were discontinued in Dec 2024.
=> Release 108

CHANGELOG.md, app/controllers/all/handover/projects_controller.rb, app/views/all/handover/projects/_search_for_inactive_project.html.erb, app/views/all/handover/projects/_search_result.html.erb, app/views/all/handover/projects/index.html.erb, config/locales/search.en.yml, config/routes.rb, spec/features/all_projects/handover/user_can_view_a_list_of_projects_spec.rb, spec/requests/all/handover/projects_controller_spec.rb, vendor/assets/stylesheets/dfefrontend.css
See ticket [200841](https://dev.azure.com/dfe-gov-uk/Academies-and-Free-Schools-SIP/_workitems/edit/200841)
At certain times (e.g. now, start of March) there are a lot of projects to hand over, more than can be listed on a single index page.
If there is more than one page of projects to handover we now offer a  "Search for inactive project by URN" feature.
If a matching inactive project is found we provide a link to that project's "check handover details" page. If no matching inactive project exists we return the user to list of projects to be handed over.
- So that I can review a particular project which is to be handed over
- As a Regional Case Officer team leader at a time when there are over 20 projects in the "to be handed over" (inactive) state
- I want to locate this "to handover" …
=> 200841: Find inactive project to handover by urn

config/locales/conversion/tasks/conversion_grant.en.yml
Ticket [200581](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/200581)
We:
- amend the title of the option
- change the hint text and include a link to a document on SharePoint
- remove the guidance element
=> 200581:Tweak copy and guidance on 'send info' option on 'conversion grant' task

app/controllers/search_controller.rb, app/services/project_search_service.rb, app/views/pages/search_error.html.erb, config/locales/en.yml, spec/features/users_can_search_for_projects_spec.rb, spec/services/project_search_service_spec.rb
See https://dev.azure.com/dfe-gov-uk/Academies-and-Free-Schools-SIP/_workitems/edit/199738
We've seen errors coming from the project search module when the search results are very numerous, which then causes an excessive number of requests to the Academies API. 
These errors have only been seen in the development environment but could just as easily occur in production if a user searches for "the" or "1".
We add two guard clauses to avoid attempting to fetch large quantities of records from the Academies API:
- if the search term given is less than 4 characters we raise with "Search term too short"
- if the number of results is more than 100 we raise with "Too many results"
These "Search Errors" are handled by showing the user a new "search error" page which gives them helpful information …
=> (199738) Avoid attempting to return an excessive number of search results

.github/workflows/build-and-push-image.yml, CHANGELOG.md
Alters the build and push image yml config to use composite actions instead of workflows. 
This is a requirement of upgrading to deploy-azure-container-apps-action to v5, which otherwise constitutes a breaking change. 
This upgrade was introduced by the renovate [PR 2097 'DFE-Digital/deploy-azure-container-apps-action action to v5'](https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/2097).
This commit includes the v5 upgrade, and reconfigures the build, import and deploy steps to use github actions instead of workflows.
**Please note:** the annotate-release value in the deploy job is commented out. We are currently experiencing problems with this annotation step - the expected behaviour is that it run only in the 'web' container app of the deploy matrix, …
=> Switches to composite actions instead of workflows for build and push image

CHANGELOG.md, app/controllers/all/handover/handovers_controller.rb, spec/features/all_projects/handover/user_can_handover_projects_spec.rb
See Ticket [202355](https://dev.azure.com/dfe-gov-uk/Academies-and-Free-Schools-SIP/_workitems/edit/202355) 
We regularly see the scenario in support where: 
- a project has been imported from Prepare into Complete without an  "incoming trust UKPRN" to identify the trust which will be managing the new academy. 
- the user attempts to "hand over" the project (move it from the "inactive" or "to be handed over" state)
- the user sees a generic error message
Behind the scenes a validation error has occurred when the `NewHandoverForm` attempts to assign the project and set its state to "active":
```
ActiveRecord::RecordInvalid:
Validation failed: 
Incoming trust ukprn UKPRN must be 8 digits long and start with a 1. 
For example, 12345678.
``` 
In this PR we anticipate this scenario and show …
=> Show a error msg if project to hand over is missing UKPRN

CHANGELOG.md, app/views/shared/navigation/_all_projects_primary_navigation.html.erb, spec/features/all_projects/by_month/users_can_view_projects_by_month_spec.rb
See [ticket 204455](https://dev.azure.com/dfe-gov-uk/Academies-and-Free-Schools-SIP/_workitems/edit/204455)
Previously the "By month" link in the main navigation was linking to:
`projects/all/by-month/conversions/from/to` 
(`date_range_this_month_all_by_month_conversions_projects_path`)
which was showing a list of conversions for the current month. But because the url was not matching the more literal "Conversions" link in the sub-nav:
`/projects/all/by-month/conversions/from/3/2025/to/3/2025` 
(`date_range_all_by_month_conversions_projects_path`)
the current "Conversions" tab was not being styled as active. In this commit we change the main nav's "By month" link to use the more explicit link style for the current month's conversions. In this way we now see that the default tab is …
=> 204455: FIX - Link 'By month' to current month's conversions to show active state

CHANGELOG.md
FIXED
- Handle validation error when attempting to hand over a project missing its incoming trust UKPRN
- "By month" view now makes clear its default to "Conversions.
CHANGED
- The build and push image configuration now uses composite actions instead of workflows.
=> Release 110

.github/workflows/build-and-push-image.yml, CHANGELOG.md
When we [switched from using workflows to composite actions](https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/2112) to build image, a post deploy step `'annotate-release'` broke. The step is intended to only run for the 'web' app and not the 'worker', but was attempting to run for both.
We chose to merge those changes, as this error was not interfering with deployment, nor were any downstream consumers relying on the annotation step to run successfully. 
Investigation revealed that the `'annotate-release'` step was running unexpectedly for 'worker' as a boolean was being set to trigger (or not) the process. This is an unsupported data type, and deploy-azure-container-apps-action was not able to evaluate the 'false' condition correctly. 
We now use v5.1 of …
=> Fixes post deploy annotation error

CHANGELOG.md, app/controllers/all/handover/handovers_controller.rb, config/locales/handover.en.yml, spec/features/all_projects/handover/user_can_handover_projects_spec.rb
See [ticket 206152](https://dev.azure.com/dfe-gov-uk/Academies-and-Free-Schools-SIP/_workitems/edit/206152)
In [PR 2109][] we recently (Release 110 on March 12 2025) added a
guard to the handover controller to show the user an error message if
the project which they were trying to handover was missing its
`incoming_trust_ukprn`. Previously the user was seeing a generic error
page after a validation failure behind the scenes.
It turns out we were a bit too broad with our test, as in the case of 'Form a
MAT' projects it's acceptable for the project to have a
`new_trust_reference_number` (TRN) instead of a UKPRN for the
incoming trust. See [3e5cb1be5fe9ee876cbd1e817e113bbdbd9cfd3f][] from
Feb 2024.
In this commit we tweak:
- our handover controller guard to only bail out if **both** …
=> 206152: Allow 'Form a MAT' handover with TRN instead of incoming UKPRN

CHANGELOG.md, app/controllers/all/handover/handovers_controller.rb, app/forms/conversion/edit_project_form.rb, app/forms/transfer/edit_project_form.rb, spec/forms/conversion/edit_project_form_spec.rb, spec/forms/transfer/edit_project_form_spec.rb, spec/requests/all/handover/handovers_controller_spec.rb
See [ticket 205969](https://dev.azure.com/dfe-gov-uk/Academies-and-Free-Schools-SIP/_workitems/edit/205969)
Two classes of defective behaviour were identified:
1. Projects handed over from Prepare go un-notified
2. Notifications sent when project already assigned
When a project is created in Complete by Prepare through the API it
first goes into the "inactive" state. After it's:
- been checked
- had any missing details added
- been successfully "handed over" (which includes having a valid UKPRN for the incoming trust)
it's state is changed to "active". 
If it's assigned to the RCS team, at this point we now send the "new project to
assign" email notification to all RCS team leaders.
We also change the two `EditProjectForm` classes to verify when updating a project via the UI that the …
=> 205969: Send 'new project to assign email' on handover

CHANGELOG.md
- Allow handover of (Form a MAT) projects with a TRN instead of incoming trust UKPRN.
- Ensure that we don't send the "New project to assign" email on update if the project is already assigned to a caseworker.
- Send the "New project to assign" email when a project created by Prepare is handed over.
=> Release 111

CHANGELOG.md, config/locales/transfer/tasks/request_new_urn_and_record.en.yml
Previously our link to the "URN Transfer Guidance" on Sharepoint was to an inaccessible resource.
=> 205988: Fix link to transfer guidance on 'Request new urn and record' task

CHANGELOG.md, app/controllers/application_controller.rb, spec/requests/error_handling_spec.rb
See [Ticket 199772](https://dev.azure.com/dfe-gov-uk/Academies-and-Free-Schools-SIP/_workitems/edit/199772)
We sometimes see unhandled `Page::OverflowError` exceptions when users ask our pagination system for a page which doesn't exist, e.g.
```
GET /projects/team/in-progress?page=2
```
Perhaps the user has bookmarked this page or left it open in their browser overnight. In the interim the number of their team's "in-progress" has reduced, so that they are now listed on a single page. Asking for page 2  then produces
```
Page::OverflowError: expected :page in 1..1; got 2
```
We now rescue this error and show the "Not found" template with status 404.
=> (199772) Handle Pagy::OverflowError with 404 Not Found

config/application.rb, spec/requests/x_headers_spec.rb
This service is being [rewritten in .NET][] and we'll be running the two services side-by side, handing users off to the .NET version from this Ruby version for increasingly large portions of the user journeys.
This "dual-running" will work using "custom rerouting" from the [RSD Front Door service][] (Azure Front Door CDN). See this [initial configuration][]
In order to aid debugging and monitoring it's important to have visibility on which requests are handled by each version of the service.
In this commit we add an "experimental" response header (`X-Backed-Origin: ruby`) to identify the Ruby service. See the [Front Door config][] for the .NET version which will be added dynamically.
[rewritten in .NET]:
https://github.com/DFE-Digital/complete-conversions-transfers-changes
[RSD Front …
=> Add X-Backend-Origin header to identify this service

CHANGELOG.md, app/forms/conversion/create_project_form.rb, app/forms/internal_contacts/edit_added_by_user_form.rb, app/forms/transfer/create_project_form.rb, app/models/project.rb, db/migrate/20250331144723_make_projects_regional_delivery_officer_id_non_nullable.rb, db/schema.rb, spec/factories/conversion/create_project_form_factory.rb, spec/factories/transfer/create_project_form_factory.rb, spec/forms/conversion/create_project_form_spec.rb, spec/forms/internal_contacts/edit_added_by_user_form_spec.rb, spec/forms/transfer/create_project_form_spec.rb, spec/models/project_spec.rb
In order to prevent invalid records being created by the new .NET application with whom we are sharing a DB, we add some controls to ensure that a project always has its expected "regional delivery officer", which should be set on creation.
We:
- add application level validation
- make the `projects.regional_delivery_officer_id` foreign key non-nullable
Also: the two `CreateProjectForm` classes, which are used for creating projects manually from the UI as opposed to via the API, now call `Project#save!` to raise an error if invalid.
=> 207661 Enforce presence of project's regional delivery officer

CHANGELOG.md, app/views/service_support/users/edit.html.erb, config/locales/user.en.yml, spec/features/users/users_can_manage_user_accounts_spec.rb
Ticket [210076](https://dev.azure.com/dfe-gov-uk/Academies-and-Free-Schools-SIP/_workitems/edit/210076)
In e5fb0398172082431f56104fa43d951b4c1c8667 we renamed `User#team_leader` to `User#manage_team` -- but failed to change the form used by service support team members to edit the attribute via the UI.
Now it's again possible to toggle this "manage_team" property using the form at:
`/service-support/users/{userId}/edit`
We also add some guidance to advise the user that setting the `User#manage_team` attribute:
> will only be applied for RDOs and RCS team members. If the user is a member of a different team they will need to have a user-specific "Manage Team Capability" set. Raise a support ticket to request this.
=> (210076) Fix: toggle User#manage_team via UI

Gemfile.lock
In 3ab1ad3fd12536ed221a4344966b7e0fca687e47 we upgraded to Ruby 3.4.3 but didn't update the `Gemfile.lock` at that time.
=> Update Gemfile.lock after update to Ruby 3.4.3

CHANGELOG.md, config/locales/conversion/tasks/commercial_transfer_agreement.en.yml, config/locales/transfer/tasks/commercial_transfer_agreement.en.yml
The link to the guidance about Commercial Transfer Agreement (aka CTA) on Sharepoint  was broken.
=> (211569) Fix broken link to guidance on 'commercial transfer agreement'

CHANGELOG.md
Changed
- Service support can view re-routing rules for "dual-running" of service with the new .NET version
Fixed
- Link to guidance on Commercial Transfer Agreement fixed
=> Release 116

CHANGELOG.md, app/controllers/service_support/users_controller.rb, app/models/capability.rb, app/views/service_support/users/edit.html.erb, spec/features/service_support/can_manage_user_capabilities_spec.rb
[Ticket 212141](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/212141)
- So that I can override specific permissions for a particular individual
- As a member of service support team editing a user record
- I want to be able to add/remove user capabilities
---
In [PR 2088][] we introduced "user capabilities" to overcome the
limitations of the complex rules in how certain key user attributes are
assigned. This code in the `User` model is called every time a user is saved:
```rb
private def apply_roles_based_on_team
assign_attributes(
assign_to_project: allowing_override_for(:assign_to_project) { is_regional_caseworker? || is_regional_delivery_officer? },
manage_user_accounts: apply_service_support_role?,
manage_conversion_urns: …
```
=> (212141) Service support manages user's capabilities

.github/workflows/build-and-push-image.yml
This is required following the update to v 2.72.0
of the az cli.
See https://github.com/DFE-Digital/deploy-azure-container-apps-action/releases/tag/v5.2.1
=> Chore: provide 'attestations' permissions value for build-import step

db/migrate/20250508082822_add_constraints_to_notes.rb, db/schema.rb, spec/models/project_spec.rb
We're seeing a lot of invalid notes being created in the dev and test DBs by the new .NET version of the service which is under construction.
In the Ruby version, the `User` and `Project` associations are enforced, as is the presence of the `#body`.
In this migration we add these constraints to the `notes` table in the db itself.
=> Chore: Add not-null constraints to the notes table

db/migrate/20250604124333_add_conversion_declaration_of_expenditure_certificate_task_attributes.rb
A user reported that a tick box for declaration of expenditure certificates was unable to be unticked. 
Investigation found that the `declaration_of_expenditure_certificate_not_applicable` on the table `conversion_tasks_data` is missing, while it is present on table `transfer_tasks_data`. 
This PR introduces a migration to add this field to `conversion_tasks_data`.
=> Adds declaration of expenditure task attributes to conversion tasks data table

app/forms/conversion/task/receive_grant_payment_certificate_task_form.rb
This PR builds on the bug approached in [PR 2168](https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/2168).
A user reported that a tick box for declaration of expenditure certificates was unable to be unticked. Further debugging allowed the box to be unticked, but the certificate status was still showing as NOT APPLICABLE in the task list.
This PR removes the not_applicable attribute set in the `receive_grant_payment_certificate_task_form`. With this in place, the 'not applicable' attribute was being set for this form regardless of user input in the interface. This caused the certificate to show as NOT APPLICABLE even when unticked by the user.
=> Removes not_applicable attribute setting from receive grant payment form for conversion
