DFE-Digital/dfe-complete-conversions-transfers-and-changes

- Gemfile
- Gemfile.lock
We rely on the GOVUK-frontend which is written in Sass. We use the
sass-rails gem [1] as it is compatible with the GOVUK-frontend, DartSass
is not [2].
[1] https://github.com/rails/sass-rails
[2] https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#silence-deprecation-warnings-from-dependencies-in-dart-sass
> Install sass-rails

- .adr-dir
- doc/decisions/0001-record-architecture-decisions.md
We will record our decisions as Architecture Decision Records [1] with
ADR Tools [2].
[1] http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions
[2] https://github.com/npryce/adr-tools
> Add Architecture Decision Records

- .gitignore
- Gemfile.lock
- db/schema.rb
- script/all/process-script-args
- script/all/test
- script/bootstrap
- script/ci/cibuild
- script/ci/test
- script/console
- script/docker/bootstrap
- script/docker/console
- script/docker/server
- script/docker/setup
- script/docker/test
- script/docker/update
- script/no-docker/bootstrap
- script/no-docker/console
- script/no-docker/server
- script/no-docker/setup
- script/no-docker/test
- script/no-docker/update
- script/server
- script/setup
- script/test
- script/update
As per [RFC 023](https://github.com/dxw/tech-team-rfcs/blob/main/rfc-023-use-scripts-to-rule-them-all.md), add the [Scripts To Rule Them All from our Rails template](https://github.com/dxw/rails-template/tree/develop/script).
This simplifies things like onboarding and maintaining dependencies, eg by allowing `script/setup` to install all necessary dependencies and perform tasks to bring a working environment up.
> Add Scripts To Rule Them All

- Brewfile
This specifies rbenv and nodenv as dependencies for Homebrew to install, simplifying the setup process to "install Homebrew, run `script/setup`".
> Add Brewfile

- Gemfile
- Gemfile.lock
- doc/decisions/0002-use-simplecov-to-monitor-code-test-coverage.md
- spec/spec_helper.rb
As per [dxw RFC 173](https://github.com/dxw/tech-team-rfcs/blob/main/rfc-173-testing-our-work.md), set up test coverage monitoring so that anything less than 100% coverage counts as a test failure.
> (99040) Add simplecov to monitor test coverage

- .env.example
- Gemfile
- Gemfile.lock
- app/controllers/concerns/authentication.rb
- app/controllers/home_controller.rb
- app/controllers/sessions_controller.rb
- app/views/home/index.html.erb
- app/views/layouts/application.html.erb
- app/views/sessions/new.html.erb
- app/views/shared/_flash.html.erb
- config/initializers/dontenv.rb
- config/initializers/omniauth.rb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20220620083237_create_users.rb
- lib/tasks/users.rake
- spec/features/users_can_sign_in_spec.rb
- spec/features/users_can_sign_out_spec.rb
- spec/rails_helper.rb
- spec/requests/sign_in_spec.rb
- spec/requests/sign_out_spec.rb
We will be using Microsoft to authenticate users as we know all DfE users of our service will have an acoount.
To do so we use the Omniauth gem, a light touch way of intergrating with authentication services. Along with Omniauth, we'll use a Microsoft Graph plugin to orchistrate the authentication.
Initially we will authorise users by storing 'registered' users in our applicaiton and checking the user authenticatin has an email address we know of, this prevents any DfE user access our application.
Once we have an authenticated and authorised user, we store our user id in the secure Rails session cookie, the presence of this id tells us a user is authenticated.
The sign in flow is based around the idea of returning the user to the sign in page whenever something happens:
- successful sign …
> (98752) Feature: authenticate users

- README.md
As part of `script/test`, bootstrapping and code formatting tasks are run. At some point in the past these have been missed – this commit re-applies the result of those tasks so they don't pollute future PRs.
> Apply formatting checks

- .env.example
- .env.test
- Gemfile
- Gemfile.lock
- README.md
- app/views/sessions/new.html.erb
- config/initializers/dontenv.rb
- config/initializers/omniauth.rb
- doc/decisions/0003-user-sign-in.md
- spec/features/users_can_sign_in_spec.rb
- spec/rails_helper.rb
- spec/requests/sign_in_spec.rb
- spec/requests/sign_out_spec.rb
- spec/support/sign_in_helpers.rb
Whilst writing the included ADR we realised that we should support 'single tenant' mode in Azure Active Directory. This means only DfE users can authenticate, which will give us more confidence in the security of the applicaiton.
The previous Omniauth strategy did not support this mode of operation so we found one that does.
Once switched, we add some environment variable documentation and the ADR to cover sign in.
https://trello.com/c/ERSuVJsi
> (137) Chore: Switch omniauth strategy

- Gemfile
- Gemfile.lock
- app/models/academies_api/client.rb
- app/models/academies_api/establishment.rb
- config/locales/academies_api_en.yml
- spec/models/academies_api/client_spec.rb
This is a basic wrapper for the Academies API, here we shape the Client and the Establishment.
This work let's you fetch `Establishment` objects from the Rails console by URN (123456 is a real URN):
```
client = AcademiesApi::Client.new
establshment = client.get_establishment(123456)
```
Right now we only model the Establishment name:
```
establishment.name
```
I am not sure what a reasonable timeout for connecting to the Academies API is, but poking about led me to this 0.6 second value for now.
Our next steps will be to use the Establishment alongside the `Project` so we can show users more useful information.
https://trello.com/c/R4v0B6W4
> (107) Feature: academies api client

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/task-list.scss
- app/controllers/projects_controller.rb
- app/helpers/task_list_helper.rb
- app/views/projects/show.html.erb
- app/views/shared/_task_list.html.erb
- config/locales/en.yml
- spec/factories/project_factory.rb
- spec/factories/section_factory.rb
- spec/factories/task_factory.rb
- spec/features/users_can_create_projects_spec.rb
- spec/helpers/task_list_helper_spec.rb
- spec/rails_helper.rb
https://trello.com/c/YpH2TlYQ
- Add a task list the the project `show` page. The GOV.UK task list component is currently in a "being worked on" state, meaning that we have to pull in the styling from the prototype kit for now.
- Generate a task list on project creation, via the TaskListCreator.
- Add the `FactoryBot` Gem, along with minimal factories for project, section, and task, so that we can easily create models in various states for easier testing.
> (173) Task list view

- docker-compose.ci.yml
- script/all/test
We kept seeing PRs with all tests passing but we knew the PR contained
linting errors.
It turns out our scripts test for the presence of the
AUTOMATICALLY_FIX_LINTING variable, not it's value, you can set it to
true or false and see the same behaviour.
As we do not want to run in fix mode, we remove the variable from the ci
docker compose file and so, switch the statement in `script/all/test`.
> (181) Do not flag linters to auto fix in CI

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/projects_controller.rb
- app/policies/project_policy.rb
- app/views/projects/index.html.erb
- app/views/projects/show.html.erb
- config/locales/en.yml
- doc/decisions/0004-use-pundit-to-manage-authorisation.md
- spec/factories/user.rb
- spec/features/users_can_create_projects_spec.rb
- spec/features/users_can_sign_in_spec.rb
- spec/features/users_can_update_projects_spec.rb
- spec/features/users_can_view_projects_spec.rb
- spec/rails_helper.rb
- spec/support/factory_bot.rb
- spec/support/feature_helpers.rb
We should appropriately control who has access to which resources and functionality
> (168) Implement permission control for resources

- app/assets/stylesheets/application.scss
- app/models/academies_api/base_api_model.rb
- app/models/academies_api/client.rb
- app/models/academies_api/establishment.rb
- app/models/project.rb
- app/views/projects/index.html.erb
- app/views/projects/show.html.erb
- spec/factories/academies_api/establishment.rb
- spec/features/users_can_create_projects_spec.rb
- spec/features/users_can_update_projects_spec.rb
- spec/features/users_can_view_projects_spec.rb
- spec/models/academies_api/base_api_model_spec.rb
- spec/models/project_spec.rb
- spec/rails_helper.rb
- spec/support/academies_api_helpers.rb
We want fetch establishment information from the Academies API - for now, starting with the name.
The establishment data should be present, as we are going to validate that it exists on project creation. Therefore, we want to raise an error if establishment data is not available.
We are accidentally adding FactoryBot configuration twice. Remove one.
Because establishment is a property of Project, we need to mock the Academies API in quite a few places.
For now we want to use a helper to DRY these up, but we may come up with a better solution soon.
Currently, we pass the JSON response from the API into the constructorcof our API models. However, this doesn't work nicely with FactoryBot,where we have to use the `initialize_with` method in order to create mock objects.
Use the …
> (108) Retrieve establisment name from Academies API

- app/models/project.rb
- app/models/section.rb
- app/models/task.rb
- spec/models/project_spec.rb
- spec/models/section_spec.rb
- spec/models/task_spec.rb
Deleting a project should also delete associated sections, tasks and actions so we don't end up with orphaned entities (or relational integrity preventing the deletion).
> (215) Add cascading deletes for projects

- app/models/project.rb
- config/locales/en.yml
- spec/features/users_can_create_projects_spec.rb
- spec/features/users_can_view_projects_spec.rb
- spec/helpers/task_list_helper_spec.rb
- spec/models/project_spec.rb
- spec/services/task_list_creator_spec.rb
We fetch establishment information from the API by URN. We want to enforce that the establishment exists at the point of Project creation.
I've tried to reduce the mocking by having a default establishment on the project factory `establishment { build(:academies_api_establishment) }`, but it didn't help much. I've also used `any_args` a couple of times where we are testing the other validations. You can't control the order of validation, and mocking a specific URN doesn't make sense in those tests (we could also potentially remove the feature specs as the model specs cover the validations anyway)
> Validate establishment exists on Project creation

- Gemfile
- Gemfile.lock
- app/models/academies_api/base_api_model.rb
- app/models/academies_api/client.rb
- app/models/academies_api/conversion_project.rb
- app/models/project.rb
- config/locales/academies_api_en.yml
- config/locales/en.yml
- spec/factories/academies_api/conversion_project.rb
- spec/models/academies_api/base_api_model_spec.rb
- spec/models/academies_api/client_spec.rb
- spec/models/project_spec.rb
- spec/spec_helper.rb
- spec/support/academies_api_helpers.rb
To allow us to retrieve details of existing conversion projects (such as those from pre-AB), implement a new class which fronts Academies API to retrieve those objects.
This PR also adds [webmock](https://github.com/bblimke/webmock), which _could_ be used to simplify mocking in future but is mostly added because it prevents all outgoing HTTP calls and causes test failures unless those calls have been mocked. This gives us confidence that we're not accidentally interacting with an external service.
> (172) Model ConversionProject in the Academies API

- app/controllers/tasks_controller.rb
- app/models/action.rb
- app/models/section.rb
- app/models/task.rb
- app/views/shared/_task_list.html.erb
- app/views/tasks/show.html.erb
- config/routes.rb
- spec/factories/action_factory.rb
- spec/factories/section_factory.rb
- spec/factories/task_factory.rb
- spec/features/users_can_update_the_actions_for_a_task_spec.rb
- spec/features/users_can_view_the_actions_for_a_task_spec.rb
- spec/models/action_spec.rb
- spec/models/section_spec.rb
- spec/models/task_spec.rb
- spec/requests/tasks_controller_spec.rb
https://trello.com/c/CsNfWkNp
Initially, we want to show our YAML Actions as a completable checklist on each individual Task page.
We can simply use the name of the related factory when declaring relationships in FactoryBot.
Users need to be able to complete Actions, and for this to be persisted.
> (194) View and update actions

- app/controllers/project_information_controller.rb
- app/controllers/tasks_controller.rb
- app/views/project_information/show.html.erb
- app/views/shared/_key_information.html.erb
- app/views/shared/_project_tabs_list.html.erb
- app/views/shared/_tab.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/requests/project_information_controller_spec.rb
- spec/requests/tasks_controller_spec.rb
1. Add project subnavigation tabs
We want to use the GOV.UK tab component to navigate between the project task list page and the project information page. Move the "key information" into a partial, add partials to build the tab component, and add a basic controller and view for the new project information page.
2. Include authentication on the TasksController
[screen-capture (1).webm](https://user-images.githubusercontent.com/47089130/180465758-43689642-a63b-4637-83fc-f90b56b8ff94.webm)
> (195) Project tabs

- app/helpers/task_list_helper.rb
- app/models/task.rb
- app/views/shared/_task_list.html.erb
- spec/helpers/task_list_helper_spec.rb
- spec/models/task_spec.rb
The completion status of each item in the task list should reflect reality instead of all being marked as "Completed".
> (256) Tags in the task list reflect the actual state of a task

- app/assets/stylesheets/application.scss
- app/views/project_information/show.html.erb
- app/views/projects/show.html.erb
- app/views/shared/_project_sub_navigation.html.erb
- app/views/shared/_project_tabs_list.html.erb
- app/views/shared/_sub_navigation_item.html.erb
- app/views/shared/_tab.html.erb
- package.json
- yarn.lock
This better aligns with the prototype, and also means that we're no longer having to render tabs outside of their intended behaviour of on-page visibility switching using JavaScript.
To do this we do need to include the [MoJ Frontend](https://github.com/ministryofjustice/moj-frontend) pattern library (which is where this component originates, as it's not part of the GOV.UK Design System). This is done using the npm package, which introduces our first development dependency on npm. I don't think we should be afraid of this though, since our start scripts handle this just fine and we only introduce new SCSS so there isn't anything complex to do with the asset pipeline.
> (296) Swap tabs on project view for MoJ sub-navigation pattern

- app/controllers/application_controller.rb
- app/controllers/project_information_controller.rb
- app/controllers/projects_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/tasks_controller.rb
This change means that all controller actions are now automatically authenticated unless explicitly instructed otherwise using `skip_before_action` (as in `SessionsController`).
In the case of `SessionsController` we use `only` to explicitly list actions which should be excluded from authentication. Although in this case we list every action, it means that if we add a new action to the controller it will be protected unless we make the conscious decision to also exclude it.
> (279) Move authentication to be included in ApplicationController

- app/views/project_information/_project_information_list.erb
- app/views/project_information/_side_navigation.html.erb
- app/views/project_information/show.html.erb
- config/locales/en.yml
- spec/features/users_can_view_project_information_spec.rb
We currently show the local authority name in the at-a-glance summary list, we want to include it in the full project information list as well.
> Add local authority name to the project information list

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- .github/PULL_REQUEST_TEMPLATE/release.md
- .github/pull_request_template.md
- .github/workflows/tasks-completed-check.yml
- CHANGELOG.md
- README.md
- doc/decisions/0008-use-a-changelog-for-tracking-changes-in-a-release.md
- doc/decisions/0009-use-sequential-numbering-for-release-versions.md
We should be keeping a curated list of key changes between versions, so that interested parties can easily see what has been done.
This PR:
- Adds an ADR for the above decision
- Adds a CHANGELOG.md with key features so far
- Adds a PR template to remind developers to update the changelog
- Adds a new Github action to check that tasks in a PR description have been completed
- Documents the process for creating a new release
> (321) Use a changelog

- CHANGELOG.md
- app/views/project_information/_project_information_list.erb
- config/locales/en.yml
- spec/features/users_can_view_project_information_spec.rb
The user who creates the project is assigned as the team lead. We want to display this in the project information tab.
> (348) show team lead

- .env.database.example
- .env.development
- .env.example
- .env.test
- Brewfile
- Dockerfile
- Gemfile
- Gemfile.lock
- README.md
- app/services/task_list_creator.rb
- config/database.yml
- config/environments/production.rb
- config/initializers/dontenv.rb
- db/migrate/20220620083237_create_users.rb
- db/schema.rb
- doc/decisions/0008-variance-between-local-and-production-environments.md
- doc/environment-variables.md
- doc/microsoft-sql-server.md
- docker-compose.ci.yml
- docker-compose.database.local.yml
- script/no-docker/console
- script/no-docker/database
- script/no-docker/server
- script/no-docker/setup
- script/no-docker/update
This is a first attempt to switch our development environment from Postgres to Microsoft SQL Server. The reasons for doing so are in this [ADR](https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/blob/develop/doc/decisions/0007-use-the-academies-db-as-the-datastore.md).
There is a lot here, take your time and please ask anything, but I'll be the frist to say this is not something I am super experienced with!
As SQL Server cannot be run natively on Mac OS we have to use Docker, this renders the whole Docker/No Docker thing even more confusing, but we are essentially still running Ruby and Rails natively. I haven't updated the Docker parts yet as:
- no one on the team uses them
- we have no production environment using them
I've have tried to update the  no-docker …
> (225) Chore: local environment uses mssql server

- Brewfile
The free_tds gem requires the freetds library be installed in order to build. This change ensures it is installed as part of the Homebrew dependencies.
> Add freetds dependency to Brewfile

- CHANGELOG.md
- app/controllers/notes_controller.rb
- app/models/note.rb
- app/models/project.rb
- app/models/user.rb
- app/views/notes/_notes.html.erb
- app/views/notes/_submission_form.html.erb
- app/views/notes/index.html.erb
- app/views/shared/_project_sub_navigation.html.erb
- app/views/shared/_sub_navigation_item.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20220804103138_create_notes.rb
- db/schema.rb
- spec/factories/note_factory.rb
- spec/features/users_can_create_and_view_notes_spec.rb
- spec/models/note_spec.rb
- spec/models/project_spec.rb
- spec/rails_helper.rb
- spec/requests/notes_controller_spec.rb
Users must be able to add notes to a project.
Scaffold the basic structure for now. This will be followed by commits which enable users to add and view notes.
Users need a way to add notes to a project. Add a form at the top of the notes index view as in the prototype.
Users must be able to see the previous notes for a project, including the name of the author (email for now), the date the note was created, and the body of the note. 
Order notes in descending order by `created_at`, so that the most recent notes are first. Add the `ActiveSupport::Testing::TimeHelpers` module to make testing this easy.
The `current_page?` helper always returns false on POST requests. Currently, this means that the subnavigation component won't show which page the user is on when they submit a new note form …
> (358) Project notes

- .github/dependabot.yml
We have recently switched to trunk-based development. We want dependabot to target our working `main` branch instead of the `develop` branch we used to use.
> Change dependabot target branch to `main`

- app/controllers/notes_controller.rb
- app/helpers/notes_helper.rb
- app/views/notes/_notes.html.erb
- app/views/notes/_submission_form.html.erb
- app/views/notes/index.html.erb
- app/views/notes/new.html.erb
- config/locales/en.yml
- spec/features/users_can_create_and_view_notes_spec.rb
- spec/helpers/notes_helper_spec.rb
- spec/requests/notes_controller_spec.rb
Currently, the new note form is underneath the project summary and subnavigation. This means that the error summary sits halfway down the page, whereas the GOV.UK guidance says it should sit at the top.
After a chat with our interaction designer, we have decided to move the new note form onto its own page. This solves the error message issue, and has an additional benefit that editing messages will be easier if we choose to implement that in the future.
This includes a few style updates:
- Add a cancel link to the new note form
- Rename the textarea label from "Notes" to "Enter note"
- Change the notes form submission button from "Add note" to "Save note"
- Remove the top separator of the list of notes
> (370) Move the new note form onto its own page

- CHANGELOG.md
- app/views/projects/new.html.erb
- config/locales/en.yml
- spec/models/project_spec.rb
Our interaction designer suggested that we could improve our hint text and use of text inputs on the new project page.
- Add hint text to the UKPRN and URN specifying what kind of input is expected.
- Use more appropriate widths for the input boxes. When we know the length of
the content, the guidance says we should use matching fixed-width inputs. 
We did a mini review of our error messages because so far we have been making them up on the fly, or using the Rails default messages.
Update the messages based on input from our content and interaction designers.
> (376) Mini content review

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- README.md
- app/views/tasks/show.html.erb
- app/workflows/conversion.yml
- app/workflows/schemas/task-list.json
- db/migrate/20220812103655_add_hint_and_guidance_to_actions.rb
- db/schema.rb
- spec/fixtures/files/workflows/conversion.yml
- spec/models/action_spec.rb
- spec/services/task_list_creator_spec.rb
IDE highlighted this so I thought I might as well fix it while I was there
We want to offer users some additional hints and guidance. 
Update the models to include the new columns, and update the conversions workflow to match.
For now, render the hint as part of the checkbox, and conditionally render the guidance.
The guidance (rendered as a details component) currently sits within the checkbox fieldset (because we have modelled actions checkboxes within a fieldset). I can imagine this will change as move move toward each action being a distinct thing.
> (365) YAML guidance and hint text

- CHANGELOG.md
- app/controllers/projects_controller.rb
- app/models/project.rb
- app/policies/project_policy.rb
- app/views/project_information/show/_information_list.erb
- app/views/projects/new.html.erb
- config/locales/en.yml
- db/migrate/20220815100605_add_regional_delivery_officer_to_users.rb
- db/schema.rb
- spec/factories/project_factory.rb
- spec/factories/user.rb
- spec/features/users_can_create_projects_spec.rb
- spec/features/users_can_view_project_information_spec.rb
- spec/features/users_can_view_projects_spec.rb
- spec/requests/projects_controller_spec.rb
We want to add a new role of `regional delivery officer` to the User model.
On project creation, a regional delivery officer must be selected from a drop down to be associated with the project.
Now that a project has a regional delivery officer, we want to display this on the project information tab.
We only want regional delivery officer to see projects that they are associated with.
We don't policy scope the `show` view currently, so this only applies to the `index` view.
> (336) Regional delivery officer

- app/models/project.rb
- spec/models/project_spec.rb
Leaving any of a Projects associated entities will create orphans.
Here we destroy a Projects notes along with the other associations
(Contacts and Sections (which in turn destroy Tasks and Actions)).
We also add some coverage around this behaviour to document it and make
it explicit.
https://trello.com/c/qqY8bE6H
> (413) Destroy a projects notes along with the project

- CHANGELOG.md
- app/services/task_list_creator.rb
- app/views/tasks/show.html.erb
- app/workflows/schemas/task-list.json
- db/migrate/20220818142154_add_hints_and_guidance_to_tasks.rb
- db/schema.rb
- spec/factories/action_factory.rb
- spec/factories/task_factory.rb
- spec/features/users_can_view_the_actions_for_a_task_spec.rb
- spec/fixtures/files/workflows/conversion.yml
- spec/requests/tasks_controller_spec.rb
- spec/services/task_list_creator_spec.rb
Tasks will have hints and guidance in the same form that Actions do.
Add the model attributes.
The TaskListCreator and workflow need updating to handle task-level hints and guidance. Update them, following the sam structure as used for the action-level hints and guidance.
Because some of the keys of the workflow task are now optional, this also replaces any calls to `fetch` with `[]` in the TaskListCreator. `fetch` raises an error when the key isn't found, whereas `[]` does not.
We want to render the task-level hints and guidance as GOV.UK Frontend content.
Follow the same pattern as the action-level guidance, and call the GovukMarkdown gem with the workflow markdown.
NOTE: I haven't updated the real workflow at all yet. Here it is working though 👇
> (404) Task level hints and guidance

- CHANGELOG.md
- app/controllers/tasks_controller.rb
- app/helpers/task_list_helper.rb
- app/models/task.rb
- app/services/task_list_creator.rb
- app/views/tasks/show.html.erb
- app/workflows/conversion.yml
- app/workflows/schemas/task-list.json
- config/locales/en.yml
- db/migrate/20220819104914_add_optional_to_task.rb
- db/migrate/20220819121534_add_not_applicable_to_task.rb
- db/schema.rb
- spec/factories/task_factory.rb
- spec/features/users_can_mark_optional_tasks_as_not_applicable_spec.rb
- spec/fixtures/files/workflows/conversion.yml
- spec/models/task_spec.rb
- spec/requests/tasks_controller_spec.rb
- spec/services/task_list_creator_spec.rb
Not all Tasks apply to every Project, a simple example would be the Church fundung agreement is not applicable to non-fatih establishments.
For the moment Users want to be able to mark this kind of task as 'Not applicable' in the applicaiton. To do this we need two things:
1. the ability to control which Tasks can be made not applicable i.e. the Task is optional
2. the ability to store the state i.e is the Task applicable to the Project
We've settled on `optional` for controlling which Tasks can be 'not applicable' and `not_applicable` to store the state. We settled on `not_applicable` as this reflects the UI and the way users think about this, being true when checked.
Allow users to do this and showing not applicable tasks in the task list means users get a clear view of what Task are …
> (419) Feature: tasks can be optional i.e. not applicable

- CHANGELOG.md
- app/models/project.rb
- config/locales/en.yml
- spec/factories/project_factory.rb
- spec/features/users_can_create_and_view_contacts_spec.rb
- spec/features/users_can_create_and_view_notes_spec.rb
- spec/features/users_can_create_projects_spec.rb
- spec/features/users_can_mark_optional_tasks_as_not_applicable_spec.rb
- spec/features/users_can_update_projects_spec.rb
- spec/features/users_can_update_the_actions_for_a_task_spec.rb
- spec/features/users_can_view_project_information_spec.rb
- spec/features/users_can_view_projects_spec.rb
- spec/features/users_can_view_the_actions_for_a_task_spec.rb
- spec/models/project_spec.rb
- spec/requests/contacts_controller_spec.rb
- spec/requests/notes_controller_spec.rb
- spec/requests/project_information_controller_spec.rb
- spec/requests/projects_controller_spec.rb
- spec/requests/tasks_controller_spec.rb
- spec/services/task_list_creator_spec.rb
Establishment URNs are always 6 digits long. We can provide some help to the users by showing a useful message if the URN is not the right length.
UKPRNs are always 8 digits long and start with a 1. We can provide some help to the users by showing a useful message if the UKPRN is not the right format.
We think it's very unlikely that users will need to set a completion date that isn't in the future.
Add some validation to cover this.
_NOTE: The Trello card says to validate that caseworker cannot be blank on the update page. However, there is a spec which tests the unsetting of a caseworker, so this sounds like an intentional thing, and I haven't added the validation_
> (389) - Improve validation

- CHANGELOG.md
- app/workflows/conversion.yml
_Steve spotted a naming error in the hint text link on Church supplemental agreement task during our desk review. Fixing this_
VS code seems to have added an app.code-workspace file. Not sure what that's for or where it's come from. Hopefully it makes sense to the more technically knowledgeable members of the team.
> Fix error in Church supplemental agreement link

- CHANGELOG.md
- app/controllers/projects_controller.rb
- app/models/project.rb
- app/models/user.rb
- app/policies/project_policy.rb
- app/views/project_information/show/_information_list.erb
- app/views/projects/new.html.erb
- config/locales/en.yml
- db/migrate/20220823081934_remove_null_constraints_on_team_lead_and_regional_delivery_officer.rb
- db/schema.rb
- spec/factories/user_factory.rb
- spec/features/users_can_assign_users_to_projects_spec.rb
- spec/features/users_can_create_projects_spec.rb
- spec/models/project_spec.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
- spec/requests/project_assignment_spec.rb
- spec/requests/project_management_spec.rb
- spec/requests/projects_controller_spec.rb
- spec/support/project_helpers.rb
We decided that Regional delivery officers will create (aka Handover) projects from the prepare side of the service to us. For our MVP this will be a manual process with automating it coming later.
Originally we had the Team Lead creating projects and assigning them to Caseworkers, here we make the changes to move the responsibility for creating the project to Regional delivery officers.
In the spirit of 'leave the code better than you found it' I've made some changes to some specs to try and follow the general principle of features testing the happy path and tighter unit test for everything else.
I think we have some work to do to make the assignment jounrney more intuitive for Team Leads, but that will come later.
https://trello.com/c/90qSKSQt
> (424) Feature: change the project creation journey

- db/migrate/20220815100605_add_regional_delivery_officer_to_users.rb
- db/schema.rb
The previous form of this migration tried to add a non-nullable `regional_delivery_officer_id` column, which fails in databases where there is existing data.
Making this relationship nullable allows migrations to be performed.
> (447) Change migration adding RDOs to work with existing data

- Dockerfile
- doc/decisions/0011-use-sentry-io-for-error-reporting-and-performance-monitoring.md
The doc directory was not included in the CI Docker image and so any formating errors would not be flagged in CI. Running locally does include the doc directory and reports errors, this cause confusion.
We store our docs in the code so they should form part of the CI tests we run.
> (fix) doc directory is included in ci tests

- CHANGELOG.md
- app/controllers/contacts_controller.rb
- app/helpers/contacts_helper.rb
- app/models/contact.rb
- app/views/contacts/_contacts.html.erb
- app/views/contacts/edit.html.erb
- app/views/contacts/new.html.erb
- config/locales/en.yml
- db/migrate/20220826124914_add_category_to_contacts.rb
- db/schema.rb
- spec/features/users_can_create_and_view_contacts_spec.rb
- spec/helpers/contacts_helper_spec.rb
Contacts can now be assigned to an organisation, and will be grouped accordingly.
> (412) Add organisations to contacts

- CHANGELOG.md
- app/views/tasks/show.html.erb
This allows for rich formatting such as paragraphs, links and lists in hint text.
There are some open questions about if this is the best way to provide richer hints and if it introduces too much complexity in the page, but this will be addressed separately.
> (449) Process action hint text through markdown

- .gitignore
- terraform/README.md
- terraform/container-registry.tf
- terraform/data.tf
- terraform/locals.tf
- terraform/providers.tf
- terraform/terraform.tfvars.example
- terraform/variables.tf
* We need somewhere to store the image that will be created by Github
actions
* This uses terraform to launch an Azure Container Registry within a
given resource group
* `skip_provider_registration` has been set, as we will be using
accounts that do not have the permissions to register new Azure
resource providers. https://github.com/hashicorp/terraform-provider-azurerm/issues/7206
> (486) Create Azure Container Registry

- .github/workflows/build-and-push-image.yml
This gets us on the road to deployments, we build our application docker image and push it to the Azure container registry we created with the new Terraform.
There is still plenty to do, but this work let's us confirm the basics are working.
> (443) Chore: automate container image build in ci

- CHANGELOG.md
- app/views/tasks/show.html.erb
- spec/requests/tasks_controller_spec.rb
The GovukMarkdown.render method expects a string and cannot handle nil.
Action hints are optional so we have lots of instances where the
`Action.hint` is nil.
Adding this guard clause means the view can still be rendered where
there are actions without a hint.
https://trello.com/c/FJaXxrXz
> (481) Fix: Guard against an Action hint being nil

- CHANGELOG.md
- app/controllers/projects_controller.rb
- app/models/project.rb
- app/views/projects/new.html.erb
- config/locales/en.yml
- spec/features/users_can_create_projects_spec.rb
- spec/models/project_spec.rb
- spec/requests/projects_controller_spec.rb
The handover proforma and KIM allow users to add a handover note. We want to replicate this by adding an optional "handover comment" field to the new project form. This will create a new `Note` record for the `Project`.
> (451) Add optional handover comment field to the new project form

- CHANGELOG.md
- app/models/academies_api/establishment.rb
- app/views/project_information/show/_information_list.erb
- app/views/project_information/show/_side_navigation.html.erb
- config/locales/en.yml
- spec/factories/academies_api/establishment.rb
- spec/features/users_can_view_project_information_spec.rb
A diocese is available only on certain types of faith schools.
Here we add the diocese name to the attributes we get on an
establishment from the Academies API and show that on the project
information view.
The default behaviour of showing 'not applicable' may not be the best
for this attribute, but it is good enough for this version.
https://trello.com/c/T83NT5uu
> (452) Feature: Add diocese details to project information

- CHANGELOG.md
- app/assets/config/manifest.js
- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
- app/views/projects/edit.html.erb
- package.json
- yarn.lock
When selecting a caseworker, if the user has Javascript enabled the default select dropdown is replaced with an accessible autocomplete input.
> (417) Add accessible-autocomplete to caseworker dropdown

- Rakefile
The default rake task is the one that runs when you call `bin/rails`
without anything.
It's actually set to the `spec` task by the rspec-rails gem [1]. We like
our linter to run first so we cleared the task and set it to `standard`
then `spec`, however in production the rpec-rails gem is not loaded so
the default rake task is never set and trying to clear it results in an
error.
Here we check for the presence of the rspec-rails gem (via the RSpec::Rails
module) before we try to clear the default task.
[1] https://github.com/rspec/rspec-rails/blob/21731ed0aba404a46a63db32136b0756d2cb1060/lib/rspec/rails/tasks/rspec.rake#L6
> Fix: default rake task error in production

- config/database.yml
* We are using an Azure SQL database
* This setting is needed to specify the default database name in the login packet since Azure has no notion of `USE [database]`
* https://github.com/rails-sqlserver/tiny_tds#using-tinytds-with-azure
> Set database `Azure` flag

- config/environments/production.rb
This known issue with sassc and the GOV.UK kit [1] can be avoided by explicitally setting `config.assets.css_compressor` to nil and then enabling compression in sassc with:
`config.sass.style`
[1] https://github.com/alphagov/govuk-frontend/issues/1350#issuecomment-493129270
> Fix: do not use a css compressor in production

- .github/workflows/continuous-integration-terraform.yml
- .prettierignore
- CHANGELOG.md
- README.md
Files in `/terraform` were being checked by Prettier locally, but not in CI, leading to unexpected local failures and introducing a chance of unintended changes being committed.
This now excludes this folder from all Prettier checks.
> (495) Exclude terraform folder from Prettier checks

- CHANGELOG.md
- app/controllers/projects_controller.rb
- db/migrate/20220906094506_add_caseworker_assigned_at_to_project.rb
- db/schema.rb
- spec/models/project_spec.rb
- spec/requests/project_assignment_spec.rb
We want to record the time that a project has been assigned to a caseworker. This will represent the start point when measuring how long it takes a project in the service to reach completion.
This adds a `caseworker_assigned_at` timestamp to the `Project`. Because we should not update this value once it has been set, we override the setter to raise an error if this is attempted (this seems like it will more useful to future devs than just an early return).
We only want to set the `caseworker_assigned_at` timestamp once.
This assigns the timestamp in the controller conditionally on whether the timestamp has been previously set.
This also contains very small tidy-up to update any instances of "case_worker" to "caseworker" for consistency.
> (483) Store assignment timestamp

- CHANGELOG.md
- app/controllers/contacts_controller.rb
- app/views/contacts/confirm_destroy.html.erb
- app/views/contacts/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/users_can_create_and_view_and_delete_contacts_spec.rb
- spec/requests/contacts_controller_spec.rb
We want users to be able to delete contacts. Add the destroy action to the ContactsController
We want to show an "Are you sure?" page when a user selects to delete a contact.
Add a `confirm_destroy` action to the ContactsController that will be used to show the "Are you sure?" page.
This adds a delete contact confirmation page, which is accessed through a link on the edit contacts page.
> (478) Contacts can be deleted

- .github/dependabot.yml
We were seeing some internittent issues that linked to this, but are not
100% confident this is the fix.
We do know that github-actions for dependabot does not use
versioning-strategy[1] so we remove it.
Also removed the quotes for consistency with the rest of the file.
[1] https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy
> Fix: Remove unnecessary dependabot config to try address intermittent test failures

- CHANGELOG.md
- README.md
- app/models/user.rb
- db/migrate/20220906151837_add_caseworker_to_user.rb
- db/schema.rb
- spec/factories/user_factory.rb
- spec/features/users_can_update_projects_spec.rb
- spec/models/user_spec.rb
We want to make the `caseworker` role explicit rather than inferring it from the lack of any other role.
This adds a new column to the User model of `caseworker`,  and updates the existing code to use this.
> (491) Make user `caseworker` role explicit

- CHANGELOG.md
- app/views/projects/new.html.erb
- config/locales/en.yml
We've added hint text taken from the 'handover proforma' as a starting point and wraped the page in a two thirds layout to make the line length shorter which improved legibility.
https://trello.com/c/HsQNdRxt
> (512) Chore: Update new Project view

- app/views/projects/show/_task_list.html.erb
A slight syntax error caused the ERB linter to remove the closing tag for the task list anchors.
Fix the syntax error, then run the linter again to make sure it now works fine.
> (519) Fix task list links

- config/initializers/omniauth.rb
Seeing the errors during testing bugs me - maybe it is the right thing, I am not sure, this work prevents these errors in our test suite:
- Omniauth errors should probably go to the logger anyway
https://trello.com/c/jxNskVEt
> (514) Chore: clean up test suite output

- .erb-lint.yml
- script/all/test
- erblint uses `--autocorrect` instead of `--fix` to automatically solve problems; change this in the test runner script
- Exclude the contents of the vendor folder from linting
> Improvements to erblint behaviour

- CHANGELOG.md
- app/assets/stylesheets/application.scss
- app/helpers/application_helper.rb
- app/views/tasks/show.html.erb
- app/workflows/conversion.yml
- config/initializers/govuk_markdown.rb
- spec/features/users_can_view_the_actions_for_a_task_spec.rb
- spec/helpers/application_helper_spec.rb
We want to use the GOV.UK two-thirds layout for the task list. This is recommended to stop lines of text getting so long that they are difficult to read.
This removes the "Actions" legend for the checklist, and increases the whitespace beneath the task title and guidance to maintain the separation.
Include the guidance details component in the Proc that is passed into the Action hint in order to align them.
The labels of the action checkboxes are becoming lost amongst the content that has been added to the task page as hint text and guidance.
Bold the labels so that they stand out.
So that each checkbox is distinct and easy to visually separate, add some additional spacing between each. 
This makes the legal documents section in its current form (with the divider) look a bit odd, but this …
> (500) Update task list content and layout

- CHANGELOG.md
- app/models/academies_api/establishment.rb
- app/views/project_information/show/_information_list.erb
- app/views/shared/_project_summary.html.erb
- config/locales/en.yml
- spec/factories/academies_api/establishment.rb
- spec/features/users_can_view_a_project_spec.rb
- spec/features/users_can_view_project_information_spec.rb
Whilst not directly helpful right now, we are in Regional Services Division and have regional delivery officers and regional caseworkers - it seems likely that the concept of 'region' will be useful.
Here we are exposing the establishment (school) region which we get from get informatiion about schools via the academies API.
https://trello.com/c/x1coxpiz
> (487) Feature: add region to project information

- README.md
When adding Terraform we updated the GitHub workflows, which broke this badge in the README. Restore the badge to its full (hopefully green) glory.
> Fix broken CI badge in README

- CHANGELOG.md
- app/views/project_information/show/_information_list.erb
- spec/features/users_can_assign_users_to_projects_spec.rb
- spec/features/users_can_view_project_information_spec.rb
This behaviour was rebased away during #165 this work restores it and adds coverage to prevent it happening again.
I've refactored the feature spec that covers for two reasons:
1. I had broken it
2. I was finding it very hard to parse
https://trello.com/c/J5Xk2cD6
> (545) Fix: show assigned user names

- app/controllers/project_information_controller.rb
- config/routes.rb
- Move the project information routes into the projects resources block (this also changes the params name, so update the controller to match).
- Restrict the routes created to the ones which we have defined.
- Use a concern to DRY up the repeated destroy confirmation page routes.
> (550) Tidy up Rails routes

- app/controllers/projects_controller.rb
- app/models/project.rb
- app/validators/ukprn_validator.rb
- app/views/project_information/show/_information_list.erb
- app/views/projects/index/_project_summary.html.erb
- app/views/projects/new.html.erb
- app/views/shared/_project_summary.html.erb
- config/locales/en.yml
- db/migrate/20220915130012_rename_project_trust_to_incoming_trust.rb
- db/schema.rb
- spec/factories/project_factory.rb
- spec/features/users_can_assign_users_to_projects_spec.rb
- spec/features/users_can_mark_optional_tasks_as_not_applicable_spec.rb
- spec/features/users_can_view_a_project_spec.rb
- spec/features/users_can_view_project_information_spec.rb
- spec/features/users_can_view_projects_spec.rb
- spec/models/project_spec.rb
- spec/requests/project_assignment_spec.rb
- spec/support/project_helpers.rb
- spec/validators/ukprn_validator_spec.rb
When we modelled `trust` we kept the naming simple, we've since learnt
that `trust` is a keyword in Ruby in certain conditions.
A conversion represents a school becoming an academy by joining a Trust,
we use the term 'incomming trust' to describe to which trust the school is
joining.
Later when adding transfers we will be storing both the
incomming and outgoing trust i.e the new trust and the trust the school
is leaving - changing this column name now solves the Ruby name clash and
sets us up nicely for a time when we introduce the concept of
`outgoing_trust_ukprn` as well.
This work also adds a new UKPN validator that decouples the validation from the speciific attribute.
https://trello.com/c/ma1FCLSP
> (557) Chore: rename trust to incoming trust

- CHANGELOG.md
- app/controllers/project_information_controller.rb
- app/controllers/projects_controller.rb
- app/models/project.rb
- app/presenters/project_presenter.rb
- app/validators/past_date_validator.rb
- app/views/project_information/show/_information_list.erb
- app/views/projects/new.html.erb
- config/locales/en.yml
- db/migrate/20220915130100_add_advisory_board_attributes_to_project.rb
- db/schema.rb
- spec/factories/project_factory.rb
- spec/features/users_can_create_projects_spec.rb
- spec/features/users_can_view_project_information_spec.rb
- spec/models/project_spec.rb
- spec/presenters/project_presenter_spec.rb
- spec/validators/past_date_validator_spec.rb
#171 
The advisory board is where the decsion is made to allow a school to convert. Whilst we are not sure how the date this board met and any conditions that arise from it are useful, we have plenty of evidence they will be needed.
This works introduces capturing these details during the handover of a project. As with most data that makes up the handover, we could get it from the prepare system, but in order to get to a working MVP we will keep this step manual for now and have a Regional delivery officer provide them, automating this step away will come later.
The advisory board date is required as it must have taken place and must be in the past for the same reason.
The conditions are optional, as there may be none, although we may want to think about what none vs forgot to add them …
> (517) Feature: capture approvals board data

- CHANGELOG.md
- app/workflows/lists/conversion/sections/ready-for-opening.yml
This works adds our first stab at content and tasks for the 'get ready for opening' section.
The 'Confirm all conditions have been met' task had to be re-worked a little as we do not support two additional guidance copy right now, we are happy to accept this and get this work merged, we are confident that we will be back here in a future iteration.
https://trello.com/c/5r9wq93G
> (276) Chore: content for get ready for opening

- CHANGELOG.md
- app/models/academies_api/trust.rb
- spec/factories/academies_api/trust.rb
- spec/models/academies_api/client_spec.rb
Previously trust names would display in ALL CAPS, since this is how they arrive from upstream APIs. They are now run through `titleize` before display, which converts them to title case.
> (523) Titleise the trust name for display

- CHANGELOG.md
- app/assets/stylesheets/application.scss
- app/controllers/tasks_controller.rb
- app/models/task.rb
- app/views/tasks/clear_legal_documents/show.html.erb
- app/views/tasks/shared/_action_checkbox.html.erb
- app/views/tasks/shared/_action_guidance_summary.html.erb
- app/views/tasks/shared/_action_hint.html.erb
- app/views/tasks/shared/_not_applicable_checkbox.html.erb
- app/views/tasks/shared/_task_guidance_summary.html.erb
- app/views/tasks/shared/_task_hint.html.erb
- app/views/tasks/shared/_task_title.html.erb
- app/views/tasks/show.html.erb
- spec/factories/section_factory.rb
- spec/features/users_can_mark_optional_tasks_as_not_applicable_spec.rb
- spec/models/task_spec.rb
- spec/requests/tasks_controller_spec.rb
Tasks in the "Clear legal documents" section have a significantly different appearance than the tasks in the "Project kick-off" section.
So that we can differentiate between the two types, add a simple method on the Task model that check the section title.
We have a helper which can be used to apply the `govuk-hint` class.
Apply this to the Task-level hint to match the prototype.
We will be introducing a separate template for "Clear legal documents" tasks.
Move common view components into partials so that we can build the new view from them.
Introduce a new template for "Clear legal documents" type Tasks.
The styling for the "Not applicable" checkbox has been updated to sit at the top.
This introduces extra partials for the checkboxes to make controlling this easier.
> (522) Add Clear legal documents template/Move not applicable

- CHANGELOG.md
- app/helpers/assignments_helper.rb
- app/views/assignments/assign_caseworker.html.erb
- app/views/assignments/assign_regional_delivery_officer.html.erb
- app/views/assignments/assign_team_leader.html.erb
- spec/helpers/assignments_helper_spec.rb
We want to show the full name and email of users in the autocomplete on the assignment pages so users can be confident that they are selecting the right person.
> (542) Show full name and email on assignment pages

- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/variables.tf
* Bumps azurerm container apps hosting module to version 0.2.0
* Now has the option to set environment variables as secrets, so that they are not exposed via `az containerapp` commands
> Bump azurerm container apps hosting version 0.2.0

- package.json
- An incorrect path in the file glob meant that sections weren't being correctly validated against the schema. They now are.
- Schema documentation wasn't being generated into a clean folder, so files which were no longer relevant could still be kicking around. It now nukes the folder first.
> Fixes and improvements for schema testing

- CHANGELOG.md
- app/helpers/project_information_helper.rb
- app/models/user.rb
- app/views/notes/_notes.html.erb
- config/locales/en.yml
- doc/getting-started.md
- doc/users-accounts.md
- lib/tasks/users/create.rake
- spec/features/users_can_create_and_view_and_delete_contacts_spec.rb
- spec/helpers/project_information_helper_spec.rb
- spec/lib/tasks/users/create_spec.rb
- spec/models/user_spec.rb
- spec/requests/contacts_controller_spec.rb
- spec/requests/sign_in_spec.rb
- spec/requests/sign_out_spec.rb
- spec/requests/tasks_controller_spec.rb
Users now have a `first_name` and `last_name`. 
This updates the `users:create` Task, so that they can be passed as Task arguments, and updates the relevant documentation.
Currently, the `first_name` and `last_name` properties of the User model are optional.
This adds validation to check that all users do have `first_name` and `last_name`. 
There is no need for any data migrations as we don't yet have a deployed application.
We have various bit of logic dotted around to handle users that don’t have `first_name` and `last_name`.
Now that these are required, we can safely remove any fallbacks.
> (582) Required first name and last name

- CHANGELOG.md
- app/controllers/projects_controller.rb
- app/helpers/application_helper.rb
- app/models/project.rb
- app/validators/url_validator.rb
- app/views/project_information/show/_information_list.erb
- app/views/projects/new.html.erb
- app/views/shared/_project_summary.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20220921141636_add_establishment_sharepoint_link_to_project.rb
- db/schema.rb
- spec/factories/project_factory.rb
- spec/features/users_can_create_projects_spec.rb
- spec/features/users_can_view_a_project_spec.rb
- spec/features/users_can_view_project_information_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/models/project_spec.rb
- spec/validators/url_validator_spec.rb
We know that users collate documents in a SharePoint folder as part of the prepare journey, and that users of this service will need to update/add to them.
Add a SharePoint link property to the Project model.
We don't use all seven default routes, only create the ones we do use.
We want to collect the SharePoint link when the user creates a project.
We want to check the hostname and scheme of the SharePoint link.
Add a generic validator.
We believe all project SharePoint links will start with `https://educationgovuk-my.sharepoint.com/` or `educationgovuk.sharepoint.com`.
Validate this on project creation.
This also updates the UrlValidator to handle multiple URLs
Currently, it's possible for a user to provide a malicious SharePoint link such as `"javascript:alert('malicious')"`, which is …
> (573) SharePoint link

- config/database.yml
* Modifies database.yml production environment, so that the database name can be set via an environment variable. Defaults to 'sip'
> Allow database name to be specified via env

- CHANGELOG.md
- app/assets/stylesheets/application.scss
- app/controllers/notes_controller.rb
- app/controllers/tasks_controller.rb
- app/helpers/notes_helper.rb
- app/models/note.rb
- app/models/task.rb
- app/policies/note_policy.rb
- app/views/notes/edit.html.erb
- app/views/notes/new.html.erb
- app/views/tasks/clear_legal_documents/show.html.erb
- app/views/tasks/shared/_task_notes.html.erb
- app/views/tasks/show.html.erb
- config/locales/en.yml
- config/locales/note.en.yml
- db/migrate/20220929115655_add_task_id_to_note.rb
- db/schema.rb
- spec/factories/note_factory.rb
- spec/features/users_can_create_and_view_and_delete_notes_spec.rb
- spec/features/users_can_create_and_view_and_delete_task_level_notes_spec.rb
- spec/helpers/notes_helper_spec.rb
- spec/models/note_spec.rb
- spec/models/task_spec.rb
- spec/requests/notes_controller_spec.rb
We want to add task-level notes.
We are going to use the existing Note model with an optional relationship to a Task.
This allows users to add a new note from the task page which is associated to the task.
For now, the only difference is that the note has a task ID. The following commits will update any behaviours.
Add a helper method so that we can easily find out if a note is a task level note.
Users should be redirected back to the task page where they started adding their task level note.
Update the redirect in the controller so that it is variable backed on the note type.
Currently, we show all notes on the notes page. Now that we have task level notes, we want to only show project level notes on the notes page.
Add a scope for project level notes, and surface these only.
We want to …
> (589) Task level notes

- CHANGELOG.md
The links in the CHANGELOG to compare two versions were to invalid destinations. They now compare releases correctly.
> Fix incorrect release comparison links

- CHANGELOG.md
- app/controllers/static_pages_controller.rb
- app/views/layouts/application.html.erb
- app/views/static_pages/privacy.html.erb
- config/routes.rb
- spec/features/users_can_view_static_pages_spec.rb
This adds the text of the privacy notice from the prototype to a new static page (accessible without signing in), updates the content date in the notice, and adds a link to the site footer.
> (612) Add privacy notice and link

- CHANGELOG.md
- app/views/tasks/show.html.erb
Move the task notes block down below the header, in line with the first action.
> Move task notes below header block

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/projects_controller.rb
- app/views/projects/index.html.erb
- config/initializers/pagy.rb
We want to implement pagination using the GOV.UK components library, which is
compatible with Pagy.
This adds and configures Pagy. The default number of items per page is set to
10, and the default size parameter is set to match the Design System
documentation.
For now, we send a request to the API for each project on the project index
page. These requests are very slow, resulting in a very, very slow page load time
when there are multiple projects. We want to paginate the projects in order to
reduce the load.
This paginates the projects index page. It also moves the `Add a new project`
button to the top of the page, because it was looking a bit odd next to the
pagination component.
We need to update the way we calculate the total number of projects now that we
paginate them (else we are …
> (565) Projects pagination

- docker-compose.ci.yml
We have seen lots of intermittent failures in CI that we believe are due
to the MSSQL server container not starting before the applications
attempts to utilise it.
This results in an error:
> TinyTds::Error: Unable to connect: Adaptive Server is unavailable or
does not exist (test-db)
To avoid this we want the applicaiton to start once the MSSQL server is
ready to accept connections.
We tried a number of ways to do this and settled on what is here.
`depends_on` can use a `healthcheck` to make sure the containers are
considered healthy before starting the dependent container.
We have to use a seperate container to run the `sqlcmd` tool to attach
to the running MSSQL server, if we can attach, it we consider ourselves
healthy and so achieve the goal. This is because the `sqlcmd` is not …
> Compose depends_on includes a condition WIP

- .github/workflows/continuous-integration-tests.yml
- Dockerfile
- Gemfile
- Gemfile.lock
- README.md
- app/views/projects/index.html.erb
- docker-compose.test.yml
- docker-compose.yml
- script/all/test
- script/all/test-application
- script/all/test-linting
- script/no-docker/test
- script/no-docker/update
At the moment, our test suite under CI doesn't run linting and formatting checks on all files. This is because all our tests run in the Docker container, which only includes files we explicitly copy in to the image.
To solve this, this PR separates the linting/formatting/schema tests and the application tests into two distinct processes. The linting can run directly in a GitHub worker (which completes a lot faster, giving us a fail-fast error for the more mundane things like style issues), and then the application tests run in the full-blown Docker container for parity with production. It also gives us more immediate visibility over which part of the test suite has failed.
> (643) Separate linting/formatting and application tests under CI

- CHANGELOG.md
- app/assets/stylesheets/application.scss
- app/views/projects/index.html.erb
- app/views/projects/index/_project_summary.html.erb
- app/views/projects/index/_project_summary_item.html.erb
Currently, the projects index summary wraps onto two lines when overlaps occur on small viewports and doesn't look great. We want to ensure the summary looks good on any screen size.
This applies responsive styling to the summary when the viewport is smaller than desktop size. Unfortunately, this was difficult to achieve with the GOV.UK grid system, so instead uses flexbox.
This includes a general tidy up of the component, which defines a `govuk-section-break--s` class that is absent from the GOV.UK Frontend styles.
[screen-capture (3).webm](https://user-images.githubusercontent.com/47089130/195080921-158d8f40-79b5-4ff5-bdc3-20983ad76feb.webm)
> (386) Make projects index summary responsive

- .github/workflows/build-and-push-image-development.yml
Fixes error:
```
Starting script execution via docker image mcr.microsoft.com/azure-cli:2.40.0
ERROR: The command requires the extension containerapp. Unable to prompt for extension install confirmation as no tty available. Run 'az config set extension.use_dynamic_install=yes_without_prompt' to allow installing extensions without prompt.
Error: Error: az cli script failed.
```
> Allow installation of `az containerapp` command

- CHANGELOG.md
- Rakefile
- app/views/layouts/application.html.erb
- config/locales/en.yml
- spec/features/users_can_view_the_home_page_spec.rb
Phase banners help users to understand a product in context - they are also used to collect general feedback on every page of the product.
As we are entering our private beta, here we add the phase banner and link to a generic feedback form.
> (553) Chore: add phase banner

- CHANGELOG.md
- app/views/projects/index.html.erb
Previously we showed the service name on the Project index.
As the service name is in the header, this was duplication.
We also used an h1 for two elements, which I don't believe is good practice.
> (687) Remove duplicate service name

- app/models/task.rb
- spec/features/users_can_mark_optional_tasks_as_not_applicable_spec.rb
- spec/fixtures/files/workflows/conversion/sections/clearing.yml
- spec/models/task_spec.rb
- spec/requests/tasks_controller_spec.rb
- spec/services/task_list_creator_spec.rb
Our "legal documents' section renders a different view which includes the ability to show the 'not applicable' option.
We really don't like this and have work planned to change this very (very) soon, however, we use the section title to identify when to render a legal document task over a generic task.
Recently we changed the title of this section to:
Clear and sign legal documents
and did not update the condition.
Here we do that, even though it is horrific.
> Fix: missing not applicable options

- CHANGELOG.md
- app/models/project.rb
- app/policies/project_policy.rb
- spec/features/users_can_view_projects_spec.rb
- spec/models/project_spec.rb
By target completion date seems the most reasonable sort order in a lot of situations and is
certainly an improvement over a random order from the database, which is
what we have now.
https://trello.com/c/h71w1gvi
> (708) Feature: add a by target completion date scope to project

- CHANGELOG.md
Our designers are currently making rapid changes to the content of the task list, which is making the CHANGELOG difficult to follow.
Separate the CHANGELOG into `Features` and `Content` to tidy up. We can continue this pattern going forward.
> Separate Features and Content in CHANGELOG

- terraform/.terraform.lock.hcl
- terraform/README.md
- terraform/data.tf
- terraform/key-vault-tfvars-secrets.tf
- terraform/locals.tf
- terraform/terraform.tfvars.example
- terraform/variables.tf
* Allows providing a list of users that require access to the Key Vault tfvars secrets
* The values should be the User Principle Name found in AD
> Add list of Key Vault users

- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/variables.tf
* Redis is used along with Sidekiq to run tasks asynchronously
* This is the first step, which allows the tasks to be sent to Redis
* Once this is up and running, we will configure the worker (Sidekiq) app to run the queued tasks
> Launch Redis Cache

- CHANGELOG.md
- app/workflows/lists/conversion/sections/clear-legal-docs.yml
Adds the commercial transfer agreement to the legal docs section.
This needs a content check from @SteveMilnes and code check from a dev.
> Add Commercial transfer agreement to legal docs section

- config/environments/production.rb
- doc/environment-variables.md
We want to prevent DNS rebinding and other Host header attacks so we set a allow list of host names, which for now is only one.
We'll get the host name from the environment the deployment is in.
https://guides.rubyonrails.org/configuring.html#actiondispatch-hostauthorization
> Chore: Set the host name in production

- config/environments/production.rb
Sending emails will not work without being configured.
Here we add the default hostname so links to the application in emails work and configure ActionMailer to use GOV.UK Notify to actually send emails - this is already configured in local development.
We don't have Sidekiq configured in production environments just yet, so for now, these emails are sent asynhronusly, see:
https://guides.rubyonrails.org/action_mailer_basics.html#calling-the-mailer
> Chore: Configure ActionMailer in production

- CHANGELOG.md
- app/controllers/projects_controller.rb
- app/models/project.rb
- app/views/project_information/show/_information_list.erb
- app/views/projects/new.html.erb
- app/views/shared/_project_summary.html.erb
- config/locales/project.en.yml
- db/migrate/20221020124723_add_trust_sharepoint_link_to_project.rb
- db/schema.rb
- spec/factories/project_factory.rb
- spec/features/users_can_create_projects_spec.rb
- spec/features/users_can_view_a_project_spec.rb
- spec/features/users_can_view_project_information_spec.rb
- spec/models/project_spec.rb
The two main entities involved in a conversion are the School and the Trust it
is joining. We already collect the school SharePoint folder link, we should do
the same for the Trust.
We want to collect the trust SharePoint link when the user creates a project.
This includes some minor changes to the validation messages for a school
SharePoint link, so that they can be distinguished from the new trust
SharePoint link.
This also changes "link" to "folder" for the school SharePoint folder, so that
the description matches the header.
This also changes "link" to "folder" for the school SharePoint folder, so that
the description matches the header.
> (712) Trust SharePoint link

- CHANGELOG.md
- app/models/project.rb
- app/policies/project_policy.rb
- app/views/projects/index/_project_summary.html.erb
- spec/features/users_can_view_projects_spec.rb
TRELLO-oebBbkgX
- To surface the fact that a project has been closed whilst in the list view, display the closed date where it exists.
- Since it's unlikely for people to want access to closed projects as often, sort them to the bottom of the list view.
> (714) Add project closed date to the project index view

- CHANGELOG.md
- app/assets/stylesheets/application.scss
- app/views/tasks/shared/_action_wrapper.html.erb
- app/views/tasks/show.html.erb
TRELLO-hGeYurIn
This commit fine-tunes the padding for actions, actions with reduced padding, actions of the subtitle type, and between the list of actions and the submit task button to more closely match the prototype.
> (750) Fine-tune padding for actions

- doc/microsoft-sql-server.md
We now use the `Azure SQL Edge` image as some of the team use ARM based Macs, which aren't compatible with the official `Microsoft SQL Server` image.
This updates the documentation around this, and fixes some broken links.
> (746) Update documentation around the Docker SQL image

- CHANGELOG.md
- app/models/project.rb
- config/locales/project.en.yml
- spec/models/project_spec.rb
Currently, when an invalid date such as 42,01,2022 or -1,01,2022 is set, we see a MultiParameter error.
Unfortunately, there doesn't seem to be any particularly nice way to fix this.
This overrides the setter for the Project date attributes. We rescue from any invalid dates, and add a custom error. Simply setting the error in the `rescue` won't work as the date is nillfied and we will see the error associated with the `presence` validation. 
This solution does not show the user their previous incorrect input. However, to enable that does not seem worth the effort at this point.
> (740) Add errors when project dates are invalid

- .env.example
- CHANGELOG.md
- app/assets/stylesheets/application.scss
- app/helpers/environment_banner_helper.rb
- app/views/layouts/application.html.erb
- app/views/shared/_environment_banner.html.erb
- spec/features/user_can_see_environment_banner_spec.rb
- spec/helpers/environment_banner_helper_spec.rb
We want to know which environment we are currently in to help with development purposes. 
We have added an environment banner which displays this. 
We are currently using the sentry environment to control this.
> Add environment banner

- CHANGELOG.md
- app/views/layouts/application.html.erb
- app/views/pages/accessibility.erb
- app/views/pages/internal_server_error.html.erb
- app/views/pages/page_not_found.html.erb
- app/views/pages/privacy.html.erb
- spec/features/users_can_view_static_pages_spec.rb
For ticket https://trello.com/c/MzrMzefK/339-write-an-accessibility-statement-for-our-service
- add in accessibility page
- footer now have link to accessibility page
- standardise the email the team link based on GOV.UK guidance
- privacy policy page uses service name helper rather than explicit text
Footer 
Example of how we ask users to contact us
> 339 write an accessibility statement for our service

- CHANGELOG.md
- app/workflows/lists/conversion/sections/clear-legal-docs.yml
Based on user research we have added in an extra action to explicitly indicate if they have received the email from the school/trust that shows the 125 year lease has been signed and agreed.
125 year lease adds action to explicitly indicate that the email from the school has been received.
> Added extra action to 125 year lease

- CHANGELOG.md
- app/workflows/lists/conversion/sections/clear-legal-docs.yml
Based on user research we have added in an extra action to explicitly indicate if they have received the email from the school/trust that shows the CTA has been signed and agreed.
Added extra action to Commercial transfer agreement
Based on user research we have added in an extra action to explicitly
indicate if they have received the email from the school/trust
that shows the CTA has been signed and agreed.
> Added extra action to Commercial transfer agreement

- CHANGELOG.md
- app/workflows/lists/conversion/sections/clear-legal-docs.yml
Subleases adds action to explicitly indicate that the email from the school has been received.
> Add email received step to subleases

- CHANGELOG.md
- app/views/projects/index.html.erb
TRELLO-z1U8cdt1
Use the component helpers to make sure that a link styled as a button is marked up correctly for screen readers and browsers to implement the expected behaviour, improving accessibility.
> (763) Mark up links styled as buttons correctly

- CHANGELOG.md
- app/workflows/lists/conversion/sections/clear-legal-docs.yml
The checkbox should say "Signed by solicitor" not "Signed by school or trust".
We have had some feedback that `Articles of association` should be optional. 
We generally show optional tasks last in the "Clear and sign legal documents"
section. but as `Articles of association` is the last non-optional task, there is no to
change its order. 
We have had some feedback that this link is incorrect and should be swapped.
We have had some feedback that the `Signed by secretary of state` section is not
needed in the `Trust modification order` task.
The caseworker doesn't need to arrange for these documents to be signed by
secretary of state - academy operations does this for them, after they send
these documents to them with the single worksheet.
We have had some feedback that the `Signed by …
> (760) - Legal documents private beta changes

- CHANGELOG.md
- app/models/project.rb
- config/locales/project.en.yml
- spec/models/project_spec.rb
The development environment is currently broken, when creating a new project we see the following errors:
```
2 error(s) on assignment of multiparameter attributes [error on
assignment [1, 1, 2023] to target_completion_date (super: no
superclass method `target_completion_date=' for #<Project > Did you
mean?  target_completion_date_is_in_the_future),error on assignment
[1, 10, 2022] to advisory_board_date (super: no superclass method
`advisory_board_date=' for #<Project >)]
```
This behaviour cannot be replicated locally, right now our next best step is to remove this work and test in development.
Later work moves the multiparameter validation introduced here, so ruling this out now would be helpful.
This reverts commit f05b64bbc21e649bb67811e5bab5ee816f8c3b86.
> Revert "Add errors when project dates are invalid"

- .github/workflows/build-and-push-image-development.yml
- .github/workflows/build-and-push-image-test.yml
- .github/workflows/continuous-integration-terraform.yml
- .github/workflows/continuous-integration-tests.yml
- .github/workflows/continuous-integration-tfsec.yml
- README.md
Having the actions all have the same name wasn't helpful, for me at least.
Here we've renamed them to show their intention.
We've also removed the GitHub environment/deployments as they are not compatible with our deployment actions - once this is merged we can delete the GitHub environments so they are no longer shown in the GitHub UI.
> (chore) Tidy GitHub action names and environments

- app/controllers/projects_controller.rb
- spec/requests/projects_controller_spec.rb
TRELLO-xPjY0AZI
Previously, since we created projects before attempting to populate the task list, it was possible to reach a condition (if task list creation failed for any reason) where there would be a project with no tasks, or only part of the task list.
This change wraps the entire project creation process in a database transaction, so it either succeeds or fails as an entirety.
> (739) Projects are no longer created if task list creation fails

- CHANGELOG.md
- Dockerfile
- Gemfile
- Gemfile.lock
- spec/features/test_for_ci_spec.rb
- spec/rails_helper.rb
- spec/spec_helper.rb
Set up selenium to work within CI
This is our first step in automating our accessibilty tests.
The next step is to make our test feature test be more specific for an accessibility test and to install axe-core-selenium gem as the accessibility tool.
> (765) Allow test suite to use real browser for capybara tests

- CHANGELOG.md
- app/workflows/lists/conversion/sections/after-opening.yml
Change copy as it is not only funding documents that can be redacted and set for publishing on GOV.UK
- Title and slug change to be Redact and send documents to be published on GOV.UK
- guidance no longer mentions funding docs only
- guidance indicates that documents may end up published on GOV.UK
- I also changed the slug and it did not seem to break anything but I thought I'd better highlight that
> After opening redact funding docs becomes redact documents

- CHANGELOG.md
- app/controllers/application_controller.rb
- app/views/pages/api_client_timeout.html.erb
- config/locales/en.yml
- spec/features/users_can_view_static_pages_spec.rb
- spec/requests/projects_controller_spec.rb
- spec/support/academies_api_helpers.rb
If the Academies API times out, show an error page to the user, indicating they might be able to try again.
Previously, the users were being shown a less user-friendly error.
> Show a specific timeout error when the Academies API times out

- app/helpers/application_helper.rb
- app/views/pages/accessibility.erb
- app/views/pages/api_client_timeout.html.erb
- app/views/pages/page_not_found.html.erb
- spec/helpers/application_helper_spec.rb
You can now call `ApplicationHelpers#support_email` without a display name
and it will show the support email mailto: link with the support email itself
as the display text.
Requires https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/325 to be merged first.
> Refactor `support_email` helper to not need a display name

- .prettierignore
Add artefacts created by Intellij IDEs to .prettierignore. This ensures a test run with `AUTO_FIX_FORMATTING` enabled doesn't fail because prettier can't figure out what to do with these artefacts.
> Add artefacts created by Intellij IDEs to .prettierignore

- CHANGELOG.md
- app/views/projects/new.html.erb
- config/locales/project.en.yml
- include guidance on how to find the UKPRN, link to GIAS establishment
search and explain what a UKPRN is.
- include guidance on how to find the URN, link to GIAS school search
and explain what a URN is.
This does mean we now have html links in the yml file and sanitise the link when we put it in the hint.
> 849 update guidance for school urn and ukprn

- config/environments/production.rb
- doc/environment-variables.md
Once we put the applicaiton behind a CDN we found that Rails built in host authorization kicked in, preventing the application from responding via the CDN.
Adding this, allows us to specify all of the possible hostnames the host authorization validation may encounter.
We retain the sepearate `HOSTNAME` to specify the external host name users use when accessing the application as this is used to build links.
> (chore) Add allowed hosts to Rails hosts

- config/environments/production.rb
We want a secure service, enabling this setting in production like environments means the applicaiton will only allow secure connections.
More information on this here:
https://guides.rubyonrails.org/security.html#session-hijacking
https://trello.com/c/ea1Hdf88
> (chore) Enable force SSL

- CHANGELOG.md
- app/views/notes/new.html.erb
- spec/features/users_can_create_and_view_and_delete_notes_spec.rb
- spec/features/users_can_create_and_view_and_delete_task_level_notes_spec.rb
Currently, the "Cancel" link on the new note page always takes the user to the project notes path.
Instead, we want to take the user to the project task page if the note is a task-level note.
> Fix the destination of the new Note "Cancel" link

- CHANGELOG.md
- app/assets/stylesheets/application.scss
- app/views/tasks/shared/_action_single-checkbox.html.erb
The `Not applicable` checkboxes should have bold text to match the other task checkboxes.
> Make `Not applicable` checkbox text bold

- .github/workflows/continuous-integration-tests.yml
- app/views/conversion/involuntary/projects/new.html.erb
- app/views/conversion/voluntary/projects/new.html.erb
- app/views/project_information/show/_side_navigation.html.erb
- script/all/test-accessibility
- spec/accessibility/assignments_spec.rb
- spec/accessibility/authentication_spec.rb
- spec/accessibility/contacts_spec.rb
- spec/accessibility/notes_spec.rb
- spec/accessibility/project_information_spec.rb
- spec/accessibility/projects_spec.rb
- spec/accessibility/task_spec.rb
- spec/spec_helper.rb
This PR is part 2 for accessibility tests (part 1: [https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/350](https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/350))
The accessibility tests are based per page so we decided to group them together into seperate spec files.
The groupings include:
- tasks
- project information
- notes
- contacts
- assignments
- authentication
run `bundle exec rspec --tag accessibility spec/accessibility`
> Accessibility tests for remaining groups

- app/views/contacts/confirm_destroy.html.erb
- app/views/contacts/edit.html.erb
- app/views/contacts/new.html.erb
- app/views/notes/confirm_destroy.html.erb
- app/views/notes/edit.html.erb
When we added the concept of Conversion Projects in a previous commit, we omitted to make the paths to edit/delete notes and contacts *explicitly* the paths for projects. Because all projects will (for now) be conversion projects, but notes and contacts are attached to "plain" projects, we need to be explicit that the forms for these objects needs to submit to `project_{object}_path`, not `conversion_project_{object}_path`
> Fix: make url to edit notes and contacts more explicit

- doc/environment-variables.md
We added `NO_COVERAGE` to allow the AXE accessibility test to not include coverage reports as they will never meet the 100% requirement (our specs do!).
We should document this.
> Document the NO_COVERAGE environment variable

- spec/requests/assignments_controller_spec.rb
- spec/requests/contacts_controller_spec.rb
- spec/requests/conversion/involuntary/projects_controller_spec.rb
- spec/requests/conversion/voluntary/projects_controller_spec.rb
- spec/requests/notes_controller_spec.rb
- spec/requests/project_complete_spec.rb
- spec/requests/project_information_controller_spec.rb
- spec/requests/project_management_spec.rb
- spec/requests/tasks_controller_spec.rb
- spec/support/shared_examples/conversion_project.rb
- spec/support/sign_in_helpers.rb
We have something similar for feature specs, this just reduces noise in
our specs that are not focused on how we signed in, but need to behave
as a user who is signed in.
> Add sign in with helper

- CHANGELOG.md
- app/views/assignments/assign_caseworker.html.erb
- app/views/assignments/assign_regional_delivery_officer.html.erb
- app/views/assignments/assign_team_leader.html.erb
- app/views/shared/_autocomplete.html.erb
We enhance our select elements on the user assignment pages with the
accessible autocomplete component.
Currently, we use the ID of the select element to attach the component.
However, because this ID is generated from the form builder, it has changed
with a recent renaming of attributes.
This adds a "target" class to the select element so any further renames will
not break the autocomplete.
> (886) Fix accessible autocomplete on user assignment pages

- CHANGELOG.md
- app/controllers/projects_controller.rb
- app/models/conversion/involuntary/details.rb
- app/models/conversion/voluntary/details.rb
- app/views/projects/index/_project_summary.html.erb
- app/views/shared/_project_summary.html.erb
- config/locales/conversion_project.en.yml
- spec/factories/conversion/involuntary/details_factory.rb
- spec/factories/conversion/involuntary/project_factory.rb
- spec/factories/conversion/voluntary/details_factory.rb
- spec/factories/conversion/voluntary/project_factory.rb
- spec/factories/user_factory.rb
- spec/features/users_can_view_a_project_summary_spec.rb
- spec/features/users_can_view_project_information_spec.rb
- spec/models/conversion/involuntary/details_spec.rb
- spec/models/conversion/voluntary/details_spec.rb
As we have two 'routes' for converison projects we want to show users which
project is which.
Here we introduce that behaviour, which is also our first time to reach for our
new voluntary and involuntary details objects.
Because of this we have to do a bunch of things to get a working set of
factories to help us.
https://trello.com/c/ZZLlHN7W
> Show the conversion project route

- CHANGELOG.md
- app/views/conversion/involuntary/projects/new.html.erb
- app/views/conversion/voluntary/projects/new.html.erb
- config/locales/conversion_project.en.yml
- config/locales/project.en.yml
Content changes to new project screen including hints and errors.
   - provisional conversion date has been agreed by the school, trust and local authority  - local authority proforma has been received or requested
> 895 copy changes to project create fields

- CHANGELOG.md
- app/workflows/lists/conversion/involuntary/sections/clear-legal-docs.yml
- app/workflows/lists/conversion/voluntary/sections/clear-legal-docs.yml
Tiny PR to change the link URL for the Church supplemental agreement so that it now points to specific guidance rather than a general model docs page.
> 906 update link in csa page

- CHANGELOG.md
- app/controllers/conversion/involuntary/projects_controller.rb
- spec/requests/conversion/involuntary/projects_controller_spec.rb
- spec/requests/conversion/voluntary/projects_controller_spec.rb
- spec/support/shared_examples/conversion_project.rb
Right now, when a new involuntary conversion project is created, there
is no value in notifying a Regional caseworker team lead as they play
no role in the projects life.
Here we remove the notification for involuntary conversions and move the
coverage from the shared example and into specific specs.
https://trello.com/c/2bLWZ5Ig
> New Involuntary conversions notificaitons

- app/models/conversion/voluntary/task_list.rb
- app/models/conversion/voluntary/tasks/handover.rb
- app/models/task_list/base.rb
- app/models/task_list/section.rb
- app/models/task_list/task.rb
- db/migrate/20221212121642_add_conversion_voluntary_task_lists.rb
- db/schema.rb
- spec/models/conversion/voluntary/task_list_spec.rb
- spec/models/task_list/task_spec.rb
We want an easy way to create different types of task list by defining a
task list layout composed of `TaskList::Task` objects.
The `TaskList::Base` class handles the mapping of the `TaskList::Task` objects
to the task list database table. This uses the `TaskList::Task` key/identifier,
which must be named consistently with the database columns. For example, a task
list containing a `TaskList::Task` named
`Conversion::Voluntary::Tasks::Handover` which has a `review` attribute, must
have a column named `handover_review`.
For now, the base class is tested through an instance of a
`Conversion::Voluntary::TaskList`. As we introduce more task list types, this
will likely be moved into a shared spec.
Rename the `key` method of the `Task` class so that:
- It's more consistent with the `Section` …
> Add `TaskList::Base` class and basic `Conversion::Voluntary::TaskList`

- CHANGELOG.md
- app/workflows/lists/conversion/involuntary/sections/after-opening.yml
- app/workflows/lists/conversion/voluntary/sections/after-opening.yml
- remove to be published on GOV.UK from title and slug
- update hint
- Correct capitalisation on documents with names
- Add step to send to solicitors
- Send to guidance simplified to be less repetitive
> Content changes to redact and send documents for voluntary & involuntary

- app/controllers/conversion/involuntary/projects_controller.rb
- app/controllers/conversion/voluntary/projects_controller.rb
- app/views/shared/_flash.html.erb
- config/locales/conversion_project.en.yml
- config/locales/project.en.yml
Now supports bespoke project creation banner for voluntary and involuntary routes. 
This also renders the flash message as `html_safe` so that message formatting can be defined in the translations file
> 896 project created confirmation tells users what to do next

- CHANGELOG.md
- app/models/project.rb
- spec/models/project_spec.rb
Currently, when creating a project with an empty URN or UKPRN, the project
model will try to validate these against the API. The API will throw a bad
request error, which is re-raised in the API client, and the user will see an
error page.
Instead, we can conditionally validate that the URN or UKPRN returns an
establishment or trust only if they are present. This ensures that a
blank URN or UKPRN will not call out to the API for validation, and will
instead show the error message associated with `presence: true`.
> Fix bug where empty URNs and UKPRNs raise an API error

- app/controllers/conversion/involuntary/projects_controller.rb
- app/controllers/conversion/projects_controller.rb
- app/controllers/conversion/voluntary/projects_controller.rb
- app/controllers/projects_controller.rb
- app/forms/conversion/create_project_form.rb
- app/forms/conversion/voluntary/create_project_form.rb
- app/models/project.rb
- app/views/conversion/involuntary/projects/new.html.erb
- app/views/conversion/voluntary/projects/new.html.erb
- spec/factories/conversion/create_project_form_factory.rb
- spec/forms/conversion/involuntary/create_project_form_spec.rb
- spec/forms/conversion/voluntary/create_project_form_spec.rb
- spec/models/project_spec.rb
- spec/requests/conversion/involuntary/projects_controller_spec.rb
- spec/requests/conversion/voluntary/projects_controller_spec.rb
- spec/support/shared_examples/conversion_project.rb
Now that we have a FormObject pattern to create Involuntary & Voluntary conversion projects, change the form in the UI to submit the Project Create form to the FormObject. This will then handle creating the project, creating a note if one is required, and assigning the correct Tasklist to the project.
> Use FormObject to create projects

- app/forms/conversion/involuntary/create_project_form.rb
- app/forms/conversion/voluntary/create_project_form.rb
- app/models/concerns/task_list.rb
- app/models/conversion/involuntary/task_list.rb
- app/models/conversion/involuntary/tasks/handover.rb
- app/models/project.rb
- app/models/task_list/base.rb
- db/migrate/20221214132249_add_task_list_to_project.rb
- db/migrate/20221214134847_create_conversion_involuntary_task_list.rb
- db/schema.rb
- spec/factories/conversion/involuntary/project_factory.rb
- spec/factories/conversion/involuntary/task_list_factory.rb
- spec/factories/conversion/project_factory.rb
- spec/factories/conversion/task_list_factory.rb
- spec/forms/conversion/involuntary/create_project_form_spec.rb
- spec/forms/conversion/voluntary/create_project_form_spec.rb
- spec/models/conversion/involuntary/task_list_spec.rb
- spec/models/conversion/voluntary/task_list_spec.rb
- spec/models/project_spec.rb
- spec/support/shared_examples/create_conversion_project_form.rb
- spec/support/shared_examples/task_list.rb
We are doing a bunch of work to bring the concept of the 'task list' into Ruby and allow it to be constructed of more data type than a simple checkbox value.
The model of `TaskList` has already been introduced, with a base that allows us the have different task lists backed by database tables. Here we joing our two main concepts up with a `Project` having a `TaskList` and so access to all of the attributes it stores.
We've chosen delegated types to achieve this 'reverse polymorphic' associtation, which is a relatively new feature of Rails that seems to fit our use case:
https://edgeapi.rubyonrails.org/classes/ActiveRecord/DelegatedType.html
In order to exercise this fully, we've added a really basic involuntary conversion task list with a single task and attribute, this is purely to give …
> Add TaskList association to Project

- README.md
- doc/environment-variables.md
- doc/getting-started.md
- doc/infrastructure-and-terraform.md
As we move into running a live service and because healthy documentation
is a good thing, we want to keep our readme focused.
Here we create more in-depth documentaiton and link from the readme, the
intention is to help layer the documentation from light in the top level
readme to very in-depth, for example in the Terrafrom specific readme.
> Refactor readme and documentation

- doc/console-and-logs.md
When trying to log into the Development site for the first time, it wasn't obvious at first that the Console & Log access sections were below the PIM section. It's easy to miss them if you're trying to access Development and don't need a PIM.
Add a couple of links to the "Development" paragraph to show where the console and log access sections are.
> Make it explicit where the console & log sections are

- CHANGELOG.md
- app/workflows/lists/conversion/involuntary/sections/clear-legal-docs.yml
- app/workflows/lists/conversion/voluntary/sections/clear-legal-docs.yml
125 year lease, subleases, commercial transfer agreement and tenancy at will actions follow the following format:
- Email the school to ask if all relevant parties have agreed and signed DOCUMENT
- Receive email from the school confirming all relevant parties have agreed and signed DOCUMENT
- Save a copy of the confirmation email in the school's SharePoint folder
This applies for both voluntary and involuntary routes.
> 932 rarely used legal docs have consistent confirm and signed actions

- CHANGELOG.md
- app/forms/conversion/create_project_form.rb
- spec/support/shared_examples/create_conversion_project_form.rb
When entering dates in the create project form, we want to be able to validate them in a meaningful way. Previously missing or incomplete dates were throwing MultipartAssignment errors on the front end (translating to a 500 error and a bad experience for the user).
This PR checks for:
- Blank dates
- Partially complete dates (e.g. missing a month or year)
- Invalid dates (like 31st February)
- "Dates" made up of strings of letters
All but the first of these result in the user being told the date entered is invalid. The first renders an error which tells the user the date is blank.
> Correctly validate incomplete, invalid or missing multipart dates

- CHANGELOG.md
- app/controllers/assignments_controller.rb
- app/mailers/caseworker_mailer.rb
- spec/mailers/caseworker_mailer_spec.rb
- spec/requests/assignments_controller_spec.rb
When a caseworker is assigned to a project, they will receive an email notification informing them of the assignment along with a link to the project.
The email template has been set up in `Notify`
Currently an email is sent when a reassignment is made, even if it that reassignment is to the same caseworker that is already the current caseworker. I don't necessarily think this is a problem, but it's worth noting.
> (934) Send notification to caseworker when assigned to a project

- CHANGELOG.md
- app/views/tasks/show.html.erb
- config/locales/task_list.en.yml
- spec/features/users_can_mark_optional_tasks_as_not_applicable_spec.rb
- spec/features/users_can_update_the_actions_for_a_task_spec.rb
Tasks list continue button becomes Save and return
- Added a new task submit default button text to yml file
- task list shared view now used yml for copy
- update tests
> Tasks list continue button becomes Save and return

- app/controllers/conversion/involuntary/task_lists_controller.rb
- app/controllers/conversion/voluntary/task_lists_controller.rb
- app/controllers/task_list_controller.rb
- app/controllers/task_lists_controller.rb
- app/views/conversion/involuntary/task_lists/tasks/handover.html.erb
- app/views/conversion/shared/_task_list.html.erb
- app/views/conversion/voluntary/task_lists/tasks/handover.html.erb
- config/brakeman.ignore
- config/routes.rb
- spec/factories/conversion/involuntary/task_factory.rb
- spec/factories/conversion/task_factory.rb
- spec/requests/conversion/involuntary/task_lists_controller_spec.rb
- spec/requests/conversion/voluntary/task_lists_controller_spec.rb
- spec/support/shared_examples/task_lists_controller.rb
Add `update` and `edit` functionality for the voluntary task list. This:
- Adds generic `update` and `edit` actions to the base `TaskListController`
from which the various types of task list controller will derive from.
- Adds `task_edit_path` and `task_template_path` methods to the voluntary
conversion controller. These must be configured in the derived controllers. 
- Adds routes for the voluntary task list edit and update actions.
This adds `update` and `edit` functionality for the involuntary task list. This
follows a commit which adds generic actions to the base `TaskListController`.
Request specs are moved into a shared example.
We generate our task path by matching the  `:task_id` param at the end of the
path to a task, then using the `identifier` of the task to find the relevant …
> (965) `edit` and `update` for the new task list

- CHANGELOG.md
- app/workflows/lists/conversion/involuntary/sections/clear-legal-docs.yml
- app/workflows/lists/conversion/involuntary/sections/kickoff.yml
- app/workflows/lists/conversion/voluntary/sections/clear-legal-docs.yml
- app/workflows/lists/conversion/voluntary/sections/kickoff.yml
- app/workflows/lists/conversion/voluntary/sections/ready-for-opening.yml
Morrighan and Steve reviewed and listed all the things the Dev environment build links out to. This includes:
- Documents on SharePoint
- Guidance on the DfE Intranet
- Model documents on GOV.UK
- Email addresses for teams
During that, we spotted 3 things to resolve:
- a [broken link in the External stakeholder kick-off](https://trello.com/c/kvEhmmtl/982-fix-broken-link-in-external-stakeholder-kick-off-task) task
- inaccurate [language in a link to guidance in Articles of association](https://trello.com/c/NzfVzQhU/983-review-and-update-language-used-in-link-to-articles-of-association-guidance-to-check-its-relevant) task
- inaccurate [language in title of Share the grant certificate and information about opening with the trust task](https://trello.com/c/1IVWQMKf/984-check-language-in-share- …
> Content maintenance following link audit

- terraform/README.md
- terraform/container-apps-hosting.tf
* Adds a default feature which restricts requests to the Container App from the CDN only
> Bump terraform container apps hosting module v0.12.0

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/task_list/check-box-action-component.scss
- app/components/task_list/check_box_action_component.html.erb
- app/components/task_list/check_box_action_component.rb
- app/components/task_list/task_header_component.html.erb
- app/components/task_list/task_header_component.rb
- app/helpers/task_list_helper.rb
- app/models/task_list/base.rb
- app/models/task_list/section.rb
- app/models/task_list/task.rb
- app/views/conversion/involuntary/task_lists/index.html.erb
- app/views/conversion/involuntary/task_lists/tasks/handover.html.erb
- app/views/conversion/shared/_task_list.html.erb
- app/views/conversion/voluntary/task_lists/tasks/handover.html.erb
- app/views/projects/show/_task_list.html.erb
- config/locales/task_list.en.yml
- config/locales/task_lists/conversion_involuntary.en.yml
- config/locales/task_lists/conversion_voluntary.en.yml
- spec/components/task_list/check_box_action_component_spec.rb
- spec/components/task_list/task_header_component_spec.rb
- spec/helpers/task_list_helper_spec.rb
- spec/models/conversion/involuntary/task_list_spec.rb
- spec/models/conversion/voluntary/task_list_spec.rb
- spec/models/task_list/section_spec.rb
- spec/models/task_list/task_spec.rb
- spec/rails_helper.rb
This PR has two main parts:
1. Use locales to render the text for tasks, instead of the workflow YAML files.
2. Use ViewComponents to render the TaskLists, instead of partials.
Using ViewComponents should hopefully result in a less complex way of building the new TaskLists, instead of nested partials which can get very complicated quickly. 
In order to use ViewComponents, we needed the Tasks to be aware of their locales, and therefore tie a task to a particular locale file for its content. We can then use the locale files to output the required text for the Task.
This PR also adds templates for the ViewComponents, and relevant styling; as well as unit tests for the ViewComponents.
> Use locales and ViewComponents to render parts of the TaskList

- app/components/task_list/check_box_action_component.rb
- spec/components/task_list/check_box_action_component_spec.rb
Previously we used `parameterize` which would concatonate a multi-word
class name like `StakeholderKickOff` to `stakeholderkickoff` which is
not what our naming conventions expect.
Switching to `underscore` and swapping the `/` for `_` solves this
issue, resulting in `stakeholder_kick_off`.
This issue hightlights:
- how important it is to get the naming right
- that we should use a custom form builder to make this less error prone
> Fix the CheckBoxActionComponent name creation

- .github/workflows/build-and-push-image-development.yml
- .github/workflows/build-and-push-image-production.yml
- .github/workflows/build-and-push-image-test.yml
* The `set-output` command is depreciated. This refactors the workflows to output them into the `GITHUB_OUTPUT` environment variable instead.
* ```Warning: The \`set-output\` command is deprecated and will be disabled soon.```
> Refactor GitHub workflow outputs

- app/components/task_list/check_box_action_component.rb
Our view component dynaically calls a model attribute, we have seen instances of this failing, most likely due to encapsulation issues, where a private method exists with the same name as the attribute.
We switch to `public_send` here to avoid these issues, see:
https://ruby-doc.org/3.2.0/Object.html#method-i-public_send
> View component uses `public_send`

- app/forms/conversion/create_project_form.rb
- app/models/project.rb
- spec/models/project_spec.rb
- spec/support/shared_examples/create_conversion_project_form.rb
Now that we have a FormObject (CreateProjectForm) for creating projects, we no longer create them with the Project model directly. This means we can change some of the validations. We have:
- Loosened the `provisional_conversion_date` validation. It now only checks the date is in the future on creation (via the form). In the project model, the date only needs to exist, as the project should still be valid even if the conversion date has passed.
- Changed the validation of `advisory_board_date` - it should always be in the past, even if the project is being edited, so we should not check it only on create.
- The sharepoint links should always be validated, not just on create.
- Added the `trust_exists` and `establishment_exists` validations to the FormObject, as these need to be checked on …
> Change validations on `Project` and `CreateProjectForm`

- CHANGELOG.md
- app/views/layouts/application.html.erb
- app/views/shared/_autocomplete.html.erb
- config/initializers/content_security_policy.rb
> I've had a good browse around. Everything seems to work as expected, and I don't see any violations.
Our recent IT Health Check raised the lack of a CSP as a medium warning for the
application.
This enables the Rails CSP with minimal rules.
For now, we won't report any CSP violations via the `report-uri`, however, this
may be revisited later.
We have added a CSP to the application. 
This is blocking our inline scripts for:
- Enabling the GOV.UK JavaScript
- Enabling the Accessible Autocomplete component.
This adds nonces to the inline scripts. Because a nonce generator is configured
in `content_security_policy.rb`, we can simply call
`content_security_policy_nonce`.
Note: It's nicer to add nonces to a `javascript_tag` (for example `<%=
javascript_tag nonce: true do %>`). However, the …
> (985) Content Security Policy

- app/models/conversion/involuntary/task_list.rb
- app/models/conversion/involuntary/tasks/subleases.rb
- app/models/task_list/optional_task.rb
- app/views/conversion/involuntary/task_lists/tasks/subleases.html.erb
- config/locales/task_lists/conversion/involuntary/subleases.en.yml
- db/migrate/20230105102319_add_subleases_to_involuntary_conversion_task_list.rb
- db/schema.rb
- spec/models/task_list/optional_task_spec.rb
We have a bunch of tasks which can be optional/not applicable.
Add a derived class of TaskList::Task which computes the status of a optional
task.
This adds an "optional" Sublease task for the involuntary conversion task
list.
> (1002) Not applicable task

- app/assets/stylesheets/components/task_list/check-box-action-component.scss
Content for hints and guidance is in the locales files and we want to
minimise the markup developers have to remember to add there.
We can force any content to have GOVUK styles by targeting elements,
this means no styles are required in the locales.
> Force GOVUK styles in hints and guidance

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/task_list/check-box-action-component.scss
- app/assets/stylesheets/components/task_list/task-header-component.scss
- app/components/task_list/task_header_component.html.erb
- app/views/conversion/voluntary/task_lists/tasks/articles_of_association.html.erb
- app/views/conversion/voluntary/task_lists/tasks/check_baseline.html.erb
- app/views/conversion/voluntary/task_lists/tasks/church_supplemental_agreement.html.erb
- app/views/conversion/voluntary/task_lists/tasks/commercial_transfer_agreement.html.erb
- app/views/conversion/voluntary/task_lists/tasks/conditions_met.html.erb
- app/views/conversion/voluntary/task_lists/tasks/conversion_grant.html.erb
- app/views/conversion/voluntary/task_lists/tasks/deed_of_variation.html.erb
- app/views/conversion/voluntary/task_lists/tasks/direction_to_transfer.html.erb
- app/views/conversion/voluntary/task_lists/tasks/handover.html.erb
- app/views/conversion/voluntary/task_lists/tasks/land_questionnaire.html.erb
- app/views/conversion/voluntary/task_lists/tasks/land_registry.html.erb
- app/views/conversion/voluntary/task_lists/tasks/master_funding_agreement.html.erb
- app/views/conversion/voluntary/task_lists/tasks/one_hundred_and_twenty_five_year_lease.html.erb
- app/views/conversion/voluntary/task_lists/tasks/receive_grant_payment_certificate.html.erb
- app/views/conversion/voluntary/task_lists/tasks/redact_and_send.html.erb
- app/views/conversion/voluntary/task_lists/tasks/school_completed.html.erb
- app/views/conversion/voluntary/task_lists/tasks/share_information.html.erb
- app/views/conversion/voluntary/task_lists/tasks/single_worksheet.html.erb
- app/views/conversion/voluntary/task_lists/tasks/stakeholder_kick_off.html.erb
- app/views/conversion/voluntary/task_lists/tasks/subleases.html.erb
- app/views/conversion/voluntary/task_lists/tasks/supplemental_funding_agreement.html.erb
- app/views/conversion/voluntary/task_lists/tasks/tell_regional_delivery_officer.html.erb
- app/views/conversion/voluntary/task_lists/tasks/tenancy_at_will.html.erb
- app/views/conversion/voluntary/task_lists/tasks/trust_modification_order.html.erb
- app/views/conversion/voluntary/task_lists/tasks/update_esfa.html.erb
The new tasklist has slightly different markup to the old.
Here we tweak the markup and styles to bring them closer visually, it's not
perfect but I am keen not to labour over this too much right now - the value is
us shipping the new task list.
https://trello.com/c/CfJsfWoo
> Fix new task layouts

- app/models/note.rb
In some instances `super` here will not be what you think it is - this
seems to always be true in production like environments.
Before this change, calling `super(value)` results in:
```
NoMethodError (super: no superclass method `task_identifier=' for #<Note>
```
Calling this in local development does work and we have not been able to
identify why.
The fix here is to use the `write_attribute` method to achieve the same
end result without using `super` i.e to set the attribute on the model.
We can only validate this fix will work in our development environment.
https://trello.com/c/FfXozFMT
> Use `write_attribute` in Note setter

- app/views/conversion/involuntary/task_lists/index.html.erb
- app/views/conversion/voluntary/task_lists/index.html.erb
Right now all we need to do to allow a project to be completed is to
show the 'complete' widget on the task list index view.
https://trello.com/c/SR9BmPGI
> Show the task complete ui on refactored task list

- .github/workflows/build-and-push-image-development.yml
- .github/workflows/build-and-push-image-production.yml
- .github/workflows/build-and-push-image-test.yml
* The `GITHUB_SHA` is the sha of the commit that triggered the workflow, not the sha of the commit that is checked out by the checkout action
* This ensures that the correct sha is used to tag the image before it is pushed
> Fix workflow docker tag shas

- CHANGELOG.md
- app/helpers/application_helper.rb
- app/views/layouts/application.html.erb
- app/views/pages/api_client_timeout.html.erb
- app/views/pages/internal_server_error.html.erb
- app/views/pages/page_not_found.html.erb
- config/application.rb
- config/locales/en.yml
- spec/helpers/application_helper_spec.rb
https://trello.com/c/plnRSrK7
Update the support email address to regionalservices.rg@education.gov.uk
Change the support email helper to output an optional subject line, to help email filtering in the support inbox. This subject is on by default, as so far the acceptance criteria expect it to always be there.
Add a new support email link to the footer.
> Update support email address & add subject line

- app/views/conversions/involuntary/task_lists/tasks/church_supplemental_agreement.html.erb
- app/views/conversions/voluntary/task_lists/tasks/receive_grant_payment_certificate.html.erb
- app/views/conversions/voluntary/task_lists/tasks/school_completed.html.erb
- config/locales/task_lists/conversion/involuntary/tenancy_at_will.en.yml
- spec/features/all_conversion_project_tasks_have_locales_spec.rb
Add a feature test to check all locale strings are present for tasks.
This is more long-winded than I intended. I had hoped to do this more automatically - to visit the task list pages, iterate over any link on the page, check the content and then go back to the task list page. E.g. 
```
page.find_all("ol.app-task-list ul li a").each do |link|
click_link link.text
expect(page).to_not have_css(".translation_missing")
click_link "Back"
end
```
But for some reason Rspec doesn't like this, it only goes into the first link and exits.
I also looked into using shared examples but I think these make it harder to debug and pinpoint where the missing strings are. 
In this implementation, every time a new task is added to a task list, it will have to be added to the list of tasks, plus the overall …
> Test all locale strings exist for Conversions

- CHANGELOG.md
- app/controllers/application_controller.rb
- app/controllers/assignments_controller.rb
- app/controllers/conversions/involuntary/projects_controller.rb
- app/controllers/conversions/involuntary/task_lists_controller.rb
- app/controllers/conversions/voluntary/projects_controller.rb
- app/controllers/conversions/voluntary/task_lists_controller.rb
- app/controllers/projects_controller.rb
- app/controllers/task_lists_controller.rb
- app/helpers/application_helper.rb
- app/views/assignments/assign_caseworker.html.erb
- app/views/assignments/assign_regional_delivery_officer.html.erb
- app/views/assignments/assign_team_leader.html.erb
- app/views/conversions/involuntary/task_lists/index.html.erb
- app/views/conversions/voluntary/task_lists/index.html.erb
- app/views/project_information/show/_information_list.erb
- app/views/projects/show.html.erb
- app/views/shared/_project_sub_navigation.html.erb
- app/views/shared/projects/_list.html.erb
- config/brakeman.ignore
- config/routes.rb
- spec/features/team_leaders_can_assign_users_to_project_roles_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/requests/assignments_controller_spec.rb
- spec/requests/conversions/involuntary/projects_contoller_spec.rb
- spec/requests/conversions/involuntary/task_lists_controller_spec.rb
- spec/requests/conversions/voluntary/projects_contoller_spec.rb
- spec/requests/conversions/voluntary/task_lists_controller_spec.rb
This is the one! 🎉 This PR updates a bunch of things to make the application use the 'new task list'.
It's mostly about routes and path helpers as the new task list is already running.
Nothing here removes any of the old task list, we'll do that seperately.
I am not 100% about the 'path helpers' heing helpers as it makes using them in controllers ugly with the `helpers` prefix - but I think it is good enough for right now.
> Switch to new task list

- CHANGELOG.md
- app/controllers/conversions/involuntary/projects_controller.rb
- app/controllers/conversions/voluntary/projects_controller.rb
- spec/requests/conversions/involuntary/projects_contoller_spec.rb
- spec/requests/conversions/voluntary/projects_contoller_spec.rb
- spec/support/shared_examples/conversion_project.rb
When a new project is created we want to take the user to that project
on the correct path, whilst the generic projects paths can handle this
right now, this may not always be the case.
I couldn't find a good way to test this with the shared example so I
settled on this approach - I am not loving it, but I think it will have
to do given time constriants right now.
https://trello.com/c/KUzM7u6w
> Redirect to correct path after create project

- CHANGELOG.md
- app/mailers/application_mailer.rb
- app/mailers/caseworker_mailer.rb
- app/mailers/team_leader_mailer.rb
- spec/mailers/application_mailer_spec.rb
- spec/mailers/caseworker_mailer_spec.rb
- spec/mailers/team_leader_mailer_spec.rb
When we send a user an email with a link to a project the link should be
to the appropriate path.
Here we add a helper in the application mailer so it can be reused by
any mailer and then update our current mailers to use it.
https://trello.com/c/KUzM7u6w
> Add simple helper for project urls

- app/views/conversions/involuntary/task_lists/tasks/subleases.html.erb
The feature tests added in a previous commit revealed that this button has the wrong text.
> Correct the text on the submit button for Subleases

- spec/features/users_can_complete_conversion_involuntary_tasks_spec.rb
- spec/features/users_can_complete_conversion_voluntary_tasks_spec.rb
These feature tests ensure that:
- When all actions on a task are completed, the task list page shows "Completed" for that task
- If a task is optional, it can be set to Not applicable and the correct status shows in the task list page
> Add feature tests for the voluntary & involuntary task lists 

- CHANGELOG.md
- app/views/projects_complete/completed.html.erb
- spec/features/users_can_complete_a_project_spec.rb
To help us collect feedback from users are key points on the journey,
here we add a feedback link to the view seen when a project is
completed.
> Project complete view links to survey

- CHANGELOG.md
- app/controllers/contacts_controller.rb
- app/helpers/contacts_helper.rb
- app/models/contact.rb
- app/views/contacts/_contacts.html.erb
- app/views/contacts/edit.html.erb
- app/views/contacts/new.html.erb
- app/views/cookies/shared/_cookie_banner.html.erb
- config/locales/contact.en.yml
- db/migrate/20230113150412_add_organisation_to_contact.rb
- db/schema.rb
- spec/factories/contact_factory.rb
- spec/features/users_can_create_and_view_and_delete_contacts_spec.rb
- spec/features/users_can_manage_contacts_spec.rb
- spec/helpers/contacts_helper_spec.rb
- spec/models/contact_spec.rb
- spec/requests/contacts_controller_spec.rb
Users told us that the order and presentation of the contact category options could be improved. They felt having 'other' first and the default felt unhelpful.
They also felt a way to store 'the name of an organistation the contact represents' would be helpful.
We also missed adding a category for 'solicitor'
This PR updates the Contact model to meet these needs.
We re-ordered the contact category select box and added a 'choose category' option as the default that cannot be submitted.
We decieded not to use the 'choose category' option on the edit view as the category will have a value at this point.
We add a scope to order the contacts and groups on the index view and added test coverage for that.
The `organisation_name` attribute  gets added to Contact.
And fianlly we take the …
> Update contacts based on user feedback

- Gemfile
- Gemfile.lock
We discovered that the version of Redis running in Azure is not yet
compatible with Sidekiq 7.
As we don't use any Sidekiq 7 features and there is a block on upgrading
Redis in Azure for at least 10 days [1], we think it best to rollback
and lock sidekiq to the 6.x branch for the moment.
[1] https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-how-to-upgrade#upgrade-using-the-azure-portal
https://trello.com/c/D83bHMfs
> Rollback Sidekiq

- spec/features/users_can_manage_contacts_spec.rb
Running the test at `/spec/features/users_can_manage_contacts_spec.rb:79` was raising this warning:
```
Checking for expected text of nil is confusing and/or pointless since it will
always match. Please specify a string or regexp instead.
/spec/features/users_can_manage_contacts_spec.rb:79
```
Amend the test to only check for the `organisation_name` if it is not `nil`
> Suppress `nil` warning when running test

- doc/user-accounts.md
- spec/services/user_importer_spec.rb
The UserImporter will not create duplicate records (based on email as the primary key). Make this explicit in the documentation, and add a test to show that User records can be updated in place with the UserImporter script.
> Make it explicit that the UserImporter will not create duplicate records

- CHANGELOG.md
- app/controllers/contacts_controller.rb
- app/models/contact.rb
- app/views/contacts/_contact_group.html.erb
- app/views/contacts/index.html.erb
- spec/features/users_can_manage_contacts_spec.rb
- spec/models/contact_spec.rb
During a recent product review it was noted that the contact groups were
ordered in an unexpected way. We talked about this and decided that the
order users expect would likely be by the likelyhood of using the
contacts, so pretty arbitary.
Previously, we used `group_by`, an enumerable [1] method, not active
record in a scope. Revisiting this, it felt wrong for a scope to return a
hash, so we have changed the approach here. We also noted that group_by
does not honour sorting - which was resulting in a seemingly random
order of the contact groups noted.
Honestly, this felt far more difficult that it should be! We have relied
on the category order on the Contact model to define the expected order.
Some acceptably small logic in the view pulls out contacts from the
groups in the order …
> Contacts are ordered as a user might expect

- .prettierignore
- CHANGELOG.md
- Gemfile
- Gemfile.lock
- lib/generators/conversion_involuntary_task/USAGE
- lib/generators/conversion_involuntary_task/conversion_involuntary_task_generator.rb
- lib/generators/conversion_involuntary_task/templates/locales.en.yml
- lib/generators/conversion_involuntary_task/templates/model.rb
- lib/generators/conversion_involuntary_task/templates/view.html.erb
- lib/generators/conversion_voluntary_task/USAGE
- lib/generators/conversion_voluntary_task/conversion_voluntary_task_generator.rb
- lib/generators/conversion_voluntary_task/templates/locales.en.yml
- lib/generators/conversion_voluntary_task/templates/model.rb
- lib/generators/conversion_voluntary_task/templates/view.html.erb
- spec/fixtures/generators/involuntary/add_involuntary_dummy_task_task.rb
- spec/fixtures/generators/involuntary/dummy_task.en.yml
- spec/fixtures/generators/involuntary/dummy_task.html.erb
- spec/fixtures/generators/involuntary/dummy_task.rb
- spec/fixtures/generators/voluntary/add_voluntary_dummy_task_task.rb
- spec/fixtures/generators/voluntary/dummy_task.en.yml
- spec/fixtures/generators/voluntary/dummy_task.html.erb
- spec/fixtures/generators/voluntary/dummy_task.rb
- spec/lib/generators/conversion_involuntary_task_generator_spec.rb
- spec/lib/generators/conversion_voluntary_task_generator_spec.rb
- spec/spec_helper.rb
- spec/support/shared_examples/conversion_task_generator.rb
https://trello.com/c/9cuLFH1Y
The new Task List requires several files to be added to the codebase every time we add a new task to a project.
Add a rails generator to make this process easier. The involuntary/voluntary task generator will create a model, view, locale file and migration for you, given a task name.
The generators are tested by testing their output. Unfortunately this does not satisfy SimpleCov's method of calculating code coverage, so we have had to exclude the custom generators from  SimpleCov's coverage checker (see `spec/spec_helper.rb`) to keep coverage at 100%.
> Task Generators

- CHANGELOG.md
- app/views/project_information/show/_information_list.erb
- config/locales/project.en.yml
In the Project Information tab, add a link to the school's page on GIAS.
Wasn't sure of the layout for this so I've done:
> Add a link to the school's page in GIAS on project information

- app/helpers/application_helper.rb
- spec/helpers/application_helper_spec.rb
Previously the last check performed by the helper was to check the value
of the cookie, the check was for the true object, which a cookie will
not return as cookies store JSON and so must be parsed first.
As with the check for the SENTRY_ENV, we check for a string which fixes
the behavioiur.
> Fix: Enable Google analytics helper

- terraform/.terraform.lock.hcl
- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/variables.tf
- This change adds support for deploying HTTP availability, latency, cpu and memory monitors to Azure via Terraform.
> Add health probes and monitors for endpoint availability

- CHANGELOG.md
- app/views/conversions/involuntary/projects/new.html.erb
- app/views/conversions/voluntary/projects/new.html.erb
- config/locales/conversion_project.en.yml
- config/locales/project.en.yml
- spec/features/new_conversion_project_has_locales_spec.rb
Update hint text and error message for provisional conversion date for both voluntary and involuntary conversion projects.
All `provisional_conversion_date` entries are now consolidated into the `conversion_projects` YAML file to be consistent with the language we use for conversion projects.
> Update the hint text and error message for provisional conversion date entry

- CHANGELOG.md
- app/controllers/assignments_controller.rb
- app/controllers/internal_contacts_controller.rb
- app/helpers/application_helper.rb
- app/views/contacts/index.html.erb
- app/views/internal_contacts/show.html.erb
- app/views/project_information/show/_information_list.erb
- app/views/projects/shared/_project_sub_navigation.html.erb
- config/locales/contact.en.yml
- config/locales/en.yml
- config/routes.rb
- spec/features/team_leaders_can_assign_users_to_project_roles_spec.rb
- spec/features/users_can_view_internal_contacts_spec.rb
- spec/features/users_can_view_project_information_spec.rb
- spec/features/users_can_view_projects_spec.rb
- spec/requests/assignments_controller_spec.rb
- spec/requests/internal_contacts_controller_spec.rb
- spec/requests/project_information_controller_spec.rb
Move the Caseworker, Team leader and Regional delivery officer to a new "Internal contacts" tab on the project details. These users can be assigned from this tab as usual.
Rename the Contacts tab External contacts, and alias the routes for `contacts`.
> Create internal and external contacts

- CHANGELOG.md
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/notification-banner.scss
- app/components/notification_banner.html.erb
- app/components/notification_banner.rb
- app/views/layouts/application.html.erb
- spec/components/notification_banner_component_spec.rb
We make use of the Rails flashes. Our general approach is to show one
after a successful operation such as:
- user adds a note
- user adds a contact
- user adds a project
- user signed out
We chose to use the Notfication banner component for this [1], did not
use the explicit 'success' version. This version is designed
specifically for
> Reacting to something the user has done
which is a much better fit for our use case.
We do have a couple of instances where the flash is used for
unsuccessful events, such as:
- user is not registered
- user could not be signed in
- user is not authorised
Here we introduce a view component to handle both cases, using a view
component helps us encapsulate all the behaviour and make it easy to
test.
The component takes the two standard Rails flash types …
> Add notification banner component

- CHANGELOG.md
- app/controllers/projects_controller.rb
- app/views/projects/index/_project_summary.html.erb
- app/views/shared/projects/_list.html.erb
- spec/features/users_can_view_projects_spec.rb
Projects are now grouped by their `provisional_conversion_date` within hte project list
The `provisional_conversion_date` has also been removed from the individual project, as this now sits as the header for all the projects with that same date.
> Group projects in project list by their provisional conversion date

- CHANGELOG.md
- app/controllers/assignments_controller.rb
- app/helpers/application_helper.rb
- app/helpers/assignments_helper.rb
- app/models/project.rb
- app/policies/assignment_policy.rb
- app/policies/project_policy.rb
- app/views/assignments/assign_assigned_to.html.erb
- app/views/internal_contacts/show.html.erb
- config/locales/en.yml
- config/locales/project.en.yml
- config/routes.rb
- db/migrate/20230203161446_add_assigned_to_to_projects.rb
- db/schema.rb
- spec/features/users_can_assign_a_project_spec.rb
- spec/features/users_can_view_projects_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/helpers/assignments_helper_spec.rb
- spec/models/project_spec.rb
- spec/requests/assignments_controller_spec.rb
We wish to capture the user who is assigned to a project. When we began this project, we had fewer user roles than we have now. With the addition of `caseworker`, `team leader` and `regional delivery officer` on projects, it's unclear who the project is *actually* assigned to. 
This PR starts off a solution by adding a new `assigned_to` relation for projects. This can hold the ID of any user. The initial database migration will copy the caseworker or regional delivery officer ID into this field for existing projects.
Any user can then visit the new "Internal contacts" tab on a project, and assign/reassign a project to another user. The list of available users is any caseworker, team leader or regional delivery officer.
Additionally, caseworkers and regional delivery officers will be able …
> Capture the user that is assigned to a project

- CHANGELOG.md
- app/controllers/healthcheck_controller.rb
- config/routes.rb
- spec/requests/healthcheck_controller_spec.rb
Added in `/check` endpoint for TechOps to monitor that the app is up and responding.
> Add healthcheck endpoint

- CHANGELOG.md
- app/controllers/conversions/voluntary/projects_controller.rb
- app/forms/conversion/voluntary/create_project_form.rb
- app/views/conversions/voluntary/projects/new.html.erb
- config/locales/conversion_project.en.yml
- config/locales/en.yml
- db/migrate/20230210105741_add_assigned_to_regional_caseworker_team_to_projects.rb
- db/schema.rb
- spec/factories/conversion/create_project_form_factory.rb
- spec/factories/conversion/project_factory.rb
- spec/features/users_can_create_involuntary_conversion_projects_spec.rb
- spec/features/users_can_create_voluntary_conversion_projects_spec.rb
- spec/forms/conversion/voluntary/create_project_form_spec.rb
- spec/models/project_spec.rb
When creating a new voluntary project, allow the user to indicate if the project will be handed over to Regional Caseworker Services or not.
If yes, the project will be created with `assigned_to` left blank, and an email will be sent to the team leaders.
If no, the creating user will be `assigned_to` the project, and no email will be sent to team leaders.
There is no visible change for involuntary projects.
> Capture if a project is being handed over to Regional Caseworker Team 

- CHANGELOG.md
- app/controllers/projects_controller.rb
- app/models/project.rb
- app/policies/project_policy.rb
- app/views/projects/shared/_project_index_sub_navigation.html.erb
- app/views/projects/unassigned.html.erb
- config/locales/en.yml
- config/locales/project.en.yml
- config/routes.rb
- spec/features/users_can_view_unassigned_projects_spec.rb
- spec/models/project_spec.rb
Team leaders can now view a list of unassigned projects within a new assigned projects tabs.
> Unassigned project view

- CHANGELOG.md
- app/assets/stylesheets/components/task-list.scss
- app/views/conversions/shared/_task_list.html.erb
Note, after discussion, we kept the full width column as we have long task names that would cause layout issues.
https://trello.com/c/JEQFscpj
> Tasks in the task list are no longer indented

- CHANGELOG.md
- app/models/conversion/involuntary/tasks/stakeholder_kick_off.rb
- app/views/conversions/involuntary/task_lists/tasks/stakeholder_kick_off.html.erb
- config/locales/task_lists/conversion/involuntary/stakeholder_kick_off.en.yml
- db/migrate/20230217155419_add_host_meeting_to_involuntary_conversion_projects.rb
- db/migrate/20230217160251_add_involuntary_check_provisional_conversion_date.rb
- db/schema.rb
Much like https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/517
The copy on the involuntary stakeholder kick-off task has changed.
Move the "Enter confirmed kick off date" field to the end of the page.
Add two new actions to the task - Host stakeholder meeting and Check provisional conversion date. The latter requires a variable in the action title (the conversion date) so the checkbox HTML has been added "longhand" to the template to accommodate this.
> Update the external kick off task - involuntary route

- CHANGELOG.md
- app/controllers/assignments_controller.rb
- app/controllers/projects_controller.rb
- app/models/project.rb
- app/views/assignments/assign_assigned_to.html.erb
- app/views/projects/index/_project_summary.html.erb
- config/locales/conversion_project.en.yml
- spec/features/users_can_assign_a_project_spec.rb
- spec/models/project_spec.rb
In a previous commit we added an Unassigned projects tab for Team leaders only. The projects on this tab now have an Assign button, via which the Team leaders can assign a project to another user. Once assigned, the Team leader is redirected to the project's Internal contacts tab.
> Add Assign button to the Unassigned project view

- app/controllers/assignments_controller.rb
- app/helpers/assignments_helper.rb
- app/models/user.rb
- app/views/assignments/assign_assigned_to.html.erb
- spec/helpers/assignments_helper_spec.rb
- spec/models/user_spec.rb
Change `all_eligible_users` helper method to a scope on Users. This scope returns all users who have a role, and are therefore eligible to be assigned to a project. 
Also name the scope `all_assignable_users` to make it clearer what it does.
> Refactor: change `all_eligible_users` helper to a User scope

- CHANGELOG.md
- app/helpers/project_helper.rb
- app/views/project_information/show/_information_list.erb
- config/locales/project.en.yml
- spec/helpers/project_helper_spec.rb
Added a link to the trust on GIAS from the project information tab
Also refactored the school's link implementation to keep the code for the two links consistent.
> Add link to the trust on GIAS from the project information tab

- CHANGELOG.md
- app/assets/stylesheets/application.scss
Right now all our users are internal DfE users who have DfE provided
devices. Our analytics show that increasing the width of our viewport,
the space inside the browser window is viable as no one accesses the
service on a screen that cannot accomadte this change.
Horizontal space will place an important role in the application as we
introduce tables and these extra 64px could mean being able to show an
extra column.
> Increase page width to 1024px

- config/environments/production.rb
- doc/environment-variables.md
Re: https://ukgovernmentdfe.slack.com/archives/C03AANC6UJF/p1677253180105049
We added a new `/healthcheck` endpoint for monitoring.
Unfortunately when implementing the monitoring, techops encountered an error because the health probes' IP address is not in the app's allowed hosts:
```
ERROR -- : [ActionDispatch::HostAuthorization::DefaultResponseApp] Blocked host: 172.16.0.126
```
As a solution, techops are going to add a new environment variable to terraform called `CONTAINER_VNET`. This will be an IP range.
https://guides.rubyonrails.org/configuring.html#actiondispatch-hostauthorization
We can add this to the allowed hosts in the application via `IPAddr.new(ENV["CONTAINER_VNET"])`
> Add new `CONTAINER_VNET` value to `config.hosts`

- doc/user-accounts.md
Added an example to show how to escape square brackets when using ZSH
> Add example on how to escape square brackets when using Zsh

- CHANGELOG.md
- config/locales/task_lists/conversion/involuntary/stakeholder_kick_off.en.yml
- Send introductory emails task does not mention who to email
- Send introductory emails hint informs who to emails and to contact LA separately this is now consistent with voluntary conversions
> Update sponsored kickoff call

- CHANGELOG.md
- app/views/conversions/involuntary/task_lists/tasks/stakeholder_kick_off.html.erb
- app/views/conversions/voluntary/task_lists/tasks/stakeholder_kick_off.html.erb
- config/locales/task_lists/conversion/involuntary/stakeholder_kick_off.en.yml
- config/locales/task_lists/conversion/voluntary/stakeholder_kick_off.en.yml
- Check the LA proforma should have hint text saying `Check the information is correct and there is no missing information.`
- Send introductory emails hint text says `Email the school, trust and solicitors. Also email the diocese if this is a faith school.`
- Check LA proforma - details component append `You can use a local authority email template (opens in new tab) to help you write this email.` uses same link send introductory emails guidance link
- check LA can convert by conversion date: add hint text `The school or trust may have provided a provisional conversion date. Email the local authority to make sure they are able to do what they need to do by this date.`
- Enter the confirmed conversion date hint should be `Everyone should have agreed to and know the confirmed conversion …
> Tidy up copy on external stakeholder kick-off

- CHANGELOG.md
- app/controllers/application_controller.rb
- app/controllers/projects_controller.rb
- app/models/project.rb
- app/policies/project_policy.rb
- app/views/projects/openers.html.erb
- app/views/shared/projects/_table.html.erb
- config/locales/project.en.yml
- config/routes.rb
- spec/models/project_spec.rb
- spec/requests/projects_controller_spec.rb
Add a route to a new view at `projects/openers/:month/:year`. The route is constrained by month & year being present, and within the scope of 1-12 (month) and 2000-2499 (year).
This page shows a tabular view of all projects. The list of projects is filtered to projects which have a confirmed opening date of the supplied year & month.
If a year or month are not supplied in the URL, the user is redirected to a 404. 
If the year is not in the scope of 2000-2499, or the month is not in the scope of 1-12, the user is redirected to a 404. 
If no projects fall within the scope of a correctly supplied month and year, an appropriate informational message will be shown.
As a side effect of doing this work, we now have URL constraints on the `project/:id` URLs (for "plain" projects, and …
> Add Project Openers table

- CHANGELOG.md
- app/controllers/conversions/date_histories_controller.rb
- app/forms/conversion/new_date_history_form.rb
- app/helpers/application_helper.rb
- app/helpers/project_path_helper.rb
- app/models/conversion/date_history.rb
- app/models/conversion/project.rb
- app/models/note.rb
- app/policies/project_policy.rb
- app/views/contacts/index.html.erb
- app/views/conversions/date_histories/confirm_new.html.erb
- app/views/conversions/date_histories/new.html.erb
- app/views/conversions/voluntary/task_lists/index.html.erb
- app/views/internal_contacts/show.html.erb
- app/views/notes/index.html.erb
- app/views/project_information/show.html.erb
- app/views/projects/shared/_project_actions.html.erb
- app/views/projects/show.html.erb
- config/locales/conversion_history.en.yml
- config/routes.rb
- db/migrate/20230301171454_create_conversion_date_histories.rb
- db/schema.rb
- spec/features/conversions/users_can_change_the_conversion_date_spec.rb
- spec/forms/conversion/new_date_form_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/helpers/project_path_helper_spec.rb
- spec/models/conversion/date_history_spec.rb
- spec/models/note_spec.rb
- spec/policies/project_policy_spec.rb
- spec/requests/conversions/date_histories_controller_spec.rb
We want users to be able to change the conversion date, as this is a significant event, we want the process to feel significant. We also want to record any changes to the conversion date over the life of a project.
This is our first version of this behaviour and does not adress re-surfacing the changed dates right now.
As well as the date changes, we also want users to tell us why the date had to move, for this we have used the existing Note model to keep all that narrative in one place.
This work builds on the existing `conversion_date` attribute on Project, we change the value and record the previous and revised values along with a note.
The end result gives a complete conversion date history:
- project created with provisional date
- user confirm date with all parties and records it as …
> Users can change the conversion date

- CHANGELOG.md
- app/models/academies_api/trust.rb
- app/views/project_information/show/_information_list.erb
- config/locales/project.en.yml
- spec/factories/academies_api/trust.rb
- spec/features/project_information/users_can_view_trust_details_spec.rb
- spec/helpers/project_helper_spec.rb
The trust address from Get information about schools is now shown in the trust details on the project information tab
This mirrors the work done for fetching and displaying the schools address from Get information about schools.
> Users can view the trust address in the application

- CHANGELOG.md
- app/controllers/assignments_controller.rb
- db/migrate/20230314150625_rename_caseworker_assigned_at.rb
- db/schema.rb
- spec/models/project_spec.rb
- spec/requests/assignments_controller_spec.rb
The `caseworker_assigned_at` attribute on Projects is now redundant, as we are assigning people to the projects in the `assigned_to` field - and they may not be caseworkers.
Rename the column `caseworker_assigned_at` to just `assigned_at` Fill this column whenever anyone is added to the `assigned_to` field on a project
If any projects already on the system are assigned but do not have an `assigned_at` value (e.g. if they are assigned to an RDO, not a caseworker), backfill the column with the project's `created_at` date (it's close enough!)
> Rename `caseworker_assigned_at` to `assigned_at`

- app/services/project_conversion_date_migrator.rb
- spec/services/project_conversion_date_migrator_spec.rb
When we attempted to run the conversion date migration in development it
failed. This was because any existing project did not get the default
value of true for the new `conversion_date_provisional` meaning the
first if case did not pass and the project fell into the else.
There the code attepmts to create a history but cannot as there is no
value to get a revised date (because it is acually provisional!)
This fixed version:
- changes the first if case to check for a nil converison date, a
present provisional conversion date and a stake holder kick off task
that has no value, in production this should mean a project that is
still provisional
- we use an elsif to confirm the other case has a value for the
stakeholder kick off task we can use before attempting to do so.
- if neither of …
> Fix the conversion date migration

- app/views/conversions/involuntary/task_lists/index.html.erb
- spec/features/conversions/users_can_change_the_conversion_date_spec.rb
The involuntary conversion Task list page did not show the "Change conversion date" button. This was accidentally missed from a previous commit.
> Add "change conversion date" button to involuntary conversions

- CHANGELOG.md
- app/views/projects/show/_complete.html.erb
- config/locales/project.en.yml
Added more guidance to be explicit about completing every task or marking as not applicable before clicking big green button. Also changed language on green button to say complete project.
> Change to guidance above complete project button

- CHANGELOG.md
- app/controllers/assignments_controller.rb
- app/controllers/contacts_controller.rb
- app/controllers/notes_controller.rb
- app/controllers/projects_complete_controller.rb
- app/controllers/task_lists_controller.rb
- app/policies/contact_policy.rb
- app/policies/note_policy.rb
- app/policies/project_policy.rb
- app/policies/task_list_policy.rb
- spec/accessibility/projects_spec.rb
- spec/features/conversions/users_can_change_the_conversion_date_spec.rb
- spec/features/users_can_complete_a_project_spec.rb
- spec/features/users_can_complete_conversion_involuntary_tasks_spec.rb
- spec/features/users_can_complete_conversion_voluntary_tasks_spec.rb
- spec/policies/contact_policy_spec.rb
- spec/policies/note_policy_spec.rb
- spec/policies/project_policy_spec.rb
- spec/policies/task_list_policy_spec.rb
- spec/requests/conversions/date_histories_controller_spec.rb
- spec/requests/conversions/involuntary/task_lists_controller_spec.rb
- spec/requests/conversions/voluntary/task_lists_controller_spec.rb
- spec/spec_helper.rb
This is our first step to add some authorisation around projects.
This works adds or updates policies so that:
- can update the task list
- can add, delete and update their own notes
- can add, delete and update contacts
- can change the converison date
- can complete the project
- can change the assigned_to
- cannot update the task list
- can add, delete and update their own notes
- can add, delete and update contacts
- cannot change the converison date
- cannot complete the project
- can change the assigned_to
- task list cannot be updated regardless of assigned_to
- notes cannot be added, deleted or updated
- contacts cannot be added, deleted or updated
- cannot change the assigned_to
As we are working with the authorisation, for now the applciation shows the existing 'not authorised' …
> Basic auhorisation policies

- CHANGELOG.md
- app/views/conversions/involuntary/task_lists/tasks/stakeholder_kick_off.html.erb
- app/views/conversions/voluntary/task_lists/tasks/stakeholder_kick_off.html.erb
- spec/features/users_can_complete_conversion_involuntary_tasks_spec.rb
- spec/features/users_can_complete_conversion_voluntary_tasks_spec.rb
When the projects conversion date is confrimed we do not show the
conversion date fields on the external stakeholder kick off task.
When submitted the task list attempts to save the task expecting all of
the attributes to be present for mass assignment, but because the form
does not show the date fields this fails.
We saw this in production, here is a link to the exception in Sentry:
https://sdd-n7.sentry.io/issues/4001605117/?project=6684508
The solution is tricky, mostly because of our reliance on mass
assignment on the task list.
However as we have this issus in production, this is a proposed qucik
fix.
Once the conversion date is confirmed we add hidden fields to the form
to ensure all attributes are passed along correctly.
At this point, we are not sure what the long term fix will be …
> Bugfix: external stakeholder kick off converison date

- CHANGELOG.md
- app/models/conversion/voluntary/task_list.rb
- app/models/conversion/voluntary/tasks/conversion_grant.rb
- app/models/conversion/voluntary/tasks/sponsored_support_grant.rb
- app/views/conversions/voluntary/task_lists/tasks/conversion_grant.html.erb
- app/views/conversions/voluntary/task_lists/tasks/sponsored_support_grant.html.erb
- config/locales/task_lists/conversion/voluntary/conversion_grant.en.yml
- config/locales/task_lists/conversion/voluntary/sponsored_support_grant.en.yml
- db/migrate/20230321162440_add_conversion_grant_not_applicable_to_voluntary_task_lists.rb
- db/migrate/20230322142230_add_sponsored_support_grant_to_voluntary_task_list.rb
- db/schema.rb
- spec/features/all_conversion_project_tasks_have_locales_spec.rb
- spec/features/users_can_complete_conversion_voluntary_tasks_spec.rb
1. Make the Process conversion grant in the Voluntary task list optional
2. Add a new Process the Sponsored support grant task to the Voluntary task list, with the same content as the same-named task in the Involuntary task list
These two changes are further steps towards removing the Involuntary conversion type of project. With these two tasks, we should be able to support all conversion types 🤞
> Add "Process the sponsored support grant" task to the voluntary conversion task list

- CHANGELOG.md
- app/views/projects/shared/_new_projects.html.erb
- config/locales/conversion_project.en.yml
- spec/features/regional_delivery_officers_can_create_new_projects_spec.rb
We are removing the concept of "voluntary" and "involuntary" conversions.
We want all conversion projects from here on to use the "voluntary" route, and to choose tasks which reflect the project's status. In previous commits we amended the voluntary task list to support more conversion types.
We now remove the "Create new involuntary conversion" button.
> Remove button to create an involuntary conversion project

- CHANGELOG.md
- app/views/project_information/show/_information_list.erb
- app/views/project_information/show/_side_navigation.html.erb
- config/locales/project.en.yml
- spec/features/project_information/users_can_view_advisory_board_details_spec.rb
- spec/features/project_information/users_can_view_project_details_spec.rb
The advisory board is a significant event and is a natural grouping of
information, here we split it out.
We also remove the sharepoint links as they are always available in the
project summary.
> Split the advisory board details

- terraform/.terraform.lock.hcl
- terraform/README.md
- terraform/container-apps-hosting.tf
- Update the Terraform Container App module to 0.16.1 [Full changelog](https://github.com/DFE-Digital/terraform-azurerm-container-apps-hosting/compare/v0.16.0...v0.16.1)
This patches an issue with HTTP Availability checks not responding when using custom domain names, and also supports switching the Container App liveness probe to use `tcp` instead of `https` which fixes an issue of internal connections not being responded to by the Rails server.
> Update Terraform Container Module to v0.16.1

- CHANGELOG.md
- app/views/conversions/date_histories/confirm_new.html.erb
- app/views/conversions/voluntary/projects/created.html.erb
- config/routes.rb
- spec/features/users_can_create_voluntary_conversion_projects_spec.rb
Product review for release 17 found this bug where a regional delivery
officer creates a new projec to be handed over to regional casework
services, upon creating the project the link back to their own projects
view was broken and casued an error.
We fix the link to the users in progress projects.
We also remove the route for `/projects` which has no controller action
and update any places we rely on that route.
> Fix: link back to projects

- CHANGELOG.md
- app/forms/conversion/create_project_form.rb
- config/locales/project.en.yml
- spec/support/shared_examples/create_conversion_project_form.rb
The same school should never been converting more that once, we've seen
some issues in production where different users add the same project
resulting in duplicates.
This works prevents the issue by checking that a project that is in
progress does not already exist and if it does, showing a simple error
message.
https://trello.com/c/TBOAIBeo
> Validate new projects URN

- app/forms/conversion/voluntary/create_project_form.rb
- spec/features/users_can_create_voluntary_conversion_projects_spec.rb
- spec/forms/conversion/voluntary/create_project_form_spec.rb
A small bug in project creation meant that when a user creates a project and is *not* handing it over, the `assigned_at` DateTime was not being set on the project. The `assigned_at` time should reflect when someone was added to the `assigned_to` field on the project.
> Set the `assigned_at` DateTime when a user is keeping a project they created

- CHANGELOG.md
- app/validators/date_in_the_past_validator.rb
- spec/validators/date_in_the_past_validator_spec.rb
We had a user attempting to create a new project on the same day as the
advisory board, our validation was in the past so this was not possible.
Here we allow todays date as well.
> Projects can be added the same day as the board

- CHANGELOG.md
- config/locales/project.en.yml
Adding full stops to empty state messages in project lists. Also changing table headings to match those in openers list for consistency.
> 1384 content tweaks full stops

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- config/application.rb
- config/environments/production.rb
- doc/environment-variables.md
We have been asked to follow all the .NET products in the program and
use Microsoft Applcation Insights. Whilst not something the team is
familiar with, we want to try and accomadate where it does not effect
our ability to deliver value or support the live service.
The gem used here is set to archived on Github [1], but may be stable
enough for our needs, we have to test it to find out.
After a small spike, here we have the absolute minimum working version
of this, with basic stats going to Application Insights.
We have set the following options as the defaults:
- buffer size: 500
- send interval: 60
See: https://github.com/microsoft/ApplicationInsights-Ruby/blob/5db6b4ad65262d23f26b678143a4a1fd7939e5c2/lib/application_insights/rack/track_request.rb#L18
We will ship this version and let …
> Add basic Application Insights support

- CHANGELOG.md
- config/locales/project.en.yml
Improved summary text on openers list and added full stop.
> Improved the summary text on the openers list and added a full stop

- CHANGELOG.md
- app/helpers/project_helper.rb
- app/views/project_information/show/_information_list.erb
- config/locales/project.en.yml
- spec/helpers/project_helper_spec.rb
Add a link to the companies house information page from the project information page
> Add a link to the companies house information page

- CHANGELOG.md
- app/models/project.rb
- spec/factories/conversion/involuntary/project_factory.rb
- spec/factories/conversion/project_factory.rb
- spec/models/project_spec.rb
Our current model of 'in-progress' is that the completed at time is not
set, it feels right to add to this projects that are assigned to a user,
if the project was not assigned who would do the work to make it
in-progress?
Here we address this in the in-progress scope.
We may want to add a view that exposed projects that are neither
in-progress or completed, for now we don't need to worry because:
- for regional caswork services they can already do this with the
unassigned view
- for regional users, they are auto assigned to the project at creation
so the risk is minimised
https://trello.com/c/Kn8FjAr0
THis work also includes setting the order of in-progress projects.
https://trello.com/c/5Ndm9aRO
> In-progress projects does not include unassigned and is ordered

- CHANGELOG.md
- config/locales/conversion_project.en.yml
- config/locales/en.yml
- spec/features/users_can_create_voluntary_conversion_projects_spec.rb
Full stops added to project handover confirmation page. Also explicitly call out the URN to make it clearer in first sentence.
> 1386 content tweaks misc changes

- CHANGELOG.md
- app/models/conversion/voluntary/tasks/handover.rb
- app/views/conversions/voluntary/task_lists/tasks/handover.html.erb
- config/locales/task_lists/conversion/voluntary/handover.en.yml
- db/migrate/20230403101729_handover_task_is_optional.rb
- db/schema.rb
- spec/features/users_can_complete_conversion_voluntary_tasks_spec.rb
As we work to make the voluntary project route work for both voluntary
and sponsored converisons we will need the 'Handover with regional
delivery officer' task optional so that when a regional delivery officer
is completed the a sponsored conversion (which is currently always)
they can skip this task.
https://trello.com/c/vcdEuEY0
> Handover task is optional

- CHANGELOG.md
- app/controllers/all/projects_controller.rb
- app/models/project.rb
- app/views/all/projects/new.html.erb
- app/views/projects/shared/_new_table.html.erb
- config/locales/project.en.yml
- config/routes.rb
- db/migrate/20230403140609_add_academy_urn_to_project.rb
- db/schema.rb
- spec/features/projects/new/users_can_view_a_list_of_new_projects_spec.rb
- spec/models/project_spec.rb
This work lays the ground work for service support users to come to the application and provide the new Academy URN.
This information will allow us to pull the new academy details from the GIAS data in the Academies database and use it.
Right now this is just a new attribute and view, it does nothing useful, but it does allow us to test the logic that includes the correct projects and build on this foundation.
> Add academy urn to project

- CHANGELOG.md
- app/controllers/all/conversion_date_changed/projects_controller.rb
- app/models/project.rb
- app/views/all/conversion_date_changed/projects/index.html.erb
- app/views/projects/shared/_conversion_date_changed_table.html.erb
- config/locales/project.en.yml
- config/routes.rb
- spec/factories/conversion/date_history_factory.rb
- spec/features/projects/conversion_date_changed/viewing_projects_with_a_revised_converison_date_spec.rb
- spec/models/project_spec.rb
This work covers the concept of 'slipped' projects. Projects that were going to convert in a given month but have since changed their conversion date.
The complexity here is in the scope for these projects, there is an extensive commit message there, but in summary:
- for all in progress projects
- for a given month and year
- get the conversion date histories ordered by creation date
- get the last conversion date history item
- if the previous_date in that item is the same month and year as the given ones, included it
Much of the work is already done with existing scopes, the main work comes from the join to the converison date histories.
With the scope in place, we add a simple view to the application to render matching projects, we'll use this view to see how many projects match the …
> View a list of projects where the conversion date has changed

- CHANGELOG.md
- app/controllers/conversions/involuntary/projects_controller.rb
- app/controllers/conversions/voluntary/projects_controller.rb
- app/forms/conversion/create_project_form.rb
- app/forms/conversion/involuntary/create_project_form.rb
- app/forms/conversion/voluntary/create_project_form.rb
- app/models/conversion/project.rb
- app/models/project.rb
- app/views/conversions/involuntary/projects/new.html.erb
- app/views/conversions/voluntary/projects/new.html.erb
- app/views/project_information/show/_information_list.erb
- config/locales/conversion_project.en.yml
- config/locales/project.en.yml
- db/migrate/20230404144130_remove_sponsor_trust_required.rb
- db/schema.rb
- spec/factories/conversion/create_project_form_factory.rb
- spec/factories/conversion/involuntary/project_factory.rb
- spec/factories/conversion/project_factory.rb
- spec/features/project_information/users_can_view_project_details_spec.rb
- spec/features/projects/completed/users_can_view_a_list_of_all_projects_spec.rb
- spec/features/projects/in_progress/users_can_view_a_list_of_all_projects_spec.rb
- spec/features/users_can_create_involuntary_conversion_projects_spec.rb
- spec/features/users_can_create_voluntary_conversion_projects_spec.rb
- spec/features/users_can_view_a_project_summary_spec.rb
- spec/forms/conversion/voluntary/create_project_form_spec.rb
- spec/models/conversion/project_spec.rb
- spec/models/project_spec.rb
- spec/requests/conversions/involuntary/projects_controller_spec.rb
- spec/requests/conversions/voluntary/projects_controller_spec.rb
- spec/support/shared_examples/create_conversion_project_form.rb
After we deployed the new `sponsor_trust_required` attribute, we quickly learnt that the way we wored the quesiton and the reality of projects let to not needing to collect this attribute.
There is a case where a school is converting voluntarily by joining a trust that can be a sponsor, but this would not be considered a 'sponsored' conversion. We came to this conclusion after seeing a real project meet this criteria:
https://www.complete.education.gov.uk/conversions/voluntary/projects/E22A0D59-CE7C-486E-A6DB-B3F781CEDC4E/information
(not project will show as voluntary once this work is merged!)
Armed with the confidence this brings, this works redefines what constitutes a 'sponsored' conversion - the issuing of a directive academy order and then goes on to remove the …
> Update what constitutes sponsored

- CHANGELOG.md
- app/controllers/regional/projects_controller.rb
- app/models/project.rb
- app/views/regional/projects/_project_index_sub_navigation.html.erb
- app/views/regional/projects/completed.html.erb
- app/views/regional/projects/completed_by_region.html.erb
- app/views/regional/projects/in_progress.html.erb
- app/views/regional/projects/in_progress_by_region.html.erb
- config/locales/project.en.yml
- config/routes.rb
- spec/features/projects/users_can_view_a_list_of_regional_projects_spec.rb
- spec/models/project_spec.rb
Add views for all Regional projects (i.e. projects not assigned to Regional caseworker services), and Regional projects filtered by region. 
The region keys have underscores (e.g. `west_midlands`) and the URLs to view regional projects use these keys (e.g. `/projects/regional/west_midlands/in-progress`). However if a user decides to manually type the URL, they can use hyphens instead (`/projects/regional/west-midlands/in-progress`) and the URL will still work. 
If the user attempts to view an unrecognised region (e.g. `/projects/regional/paris/in-progress`) then they will be redirected to a Not Found page.
> Users can view projects filtered by region

- CHANGELOG.md
- config/locales/task_lists/conversion/involuntary/trust_modification_order.en.yml
- config/locales/task_lists/conversion/voluntary/trust_modification_order.en.yml
Correcting Legal advisers office in trust modification order task checklist to Legal Adviser's Office.
> Correcting Legal advisers office to Legal Adviser's Office

- CHANGELOG.md
- app/controllers/all/statistics/projects_controller.rb
- app/models/project_statistics.rb
- app/views/all/statistics/projects/index.html.erb
- config/routes.rb
- spec/features/projects/statistics/users_can_view_project_statistics_spec.rb
- spec/models/project_statistics_spec.rb
We now have a statistics page which gives an overview of all projects split into different categories:
- a general overview of all projects
- Regional casework services projects
- Regional projects
- Projects per region
- a 6 month view of all project openers
page can be found at `projects/all/statistics`
> User can view statistics page for all project statistics

- CHANGELOG.md
- config/locales/task_lists/conversion/involuntary/receive_grant_payment_certificate.en.yml
- config/locales/task_lists/conversion/involuntary/redact_and_send.en.yml
- config/locales/task_lists/conversion/voluntary/receive_grant_payment_certificate.en.yml
- config/locales/task_lists/conversion/voluntary/redact_and_send.en.yml
Capitalised document names correctly to make consistent in the application and with other products in the division. Also removed some duplicate content from the redact and send documents task.
> Standardising capitalisation in after opening tasks

- CHANGELOG.md
- app/models/project.rb
- app/views/project_information/show/_academy_details.html.erb
- app/views/project_information/show/_information_list.erb
- app/views/project_information/show/_side_navigation.html.erb
- config/locales/project.en.yml
- spec/features/project_information/users_can_view_academy_details_spec.rb
- spec/models/project_spec.rb
- spec/support/academies_api_helpers.rb
We capture the new academy URN so we can show and utilise the details.
This work introduce a way to meet this first case, showing users the academy details.
Because we fetch academy details from the Academies API, which relies on the academies database, we think there could be delay between the GIAS record being created and it showing up in the academies database, for this reason we expect this case and handle it by showing a message.
The only way to validate this now is to see it happen in the real service - this work allows us to do this.
https://trello.com/c/snQido0j
> View new academy details

- .env.example
- CHANGELOG.md
- app/controllers/application_controller.rb
- app/forms/conversion/create_project_form.rb
- app/models/api/academies_api/client.rb
- app/models/api/academies_api/establishment.rb
- app/models/api/academies_api/trust.rb
- app/models/api/base_api_model.rb
- app/models/api/members_api/client.rb
- app/models/api/members_api/member_contact_details.rb
- app/models/api/members_api/member_name.rb
- app/models/members_api/client.rb
- app/models/project.rb
- app/services/establishments_fetcher.rb
- app/services/incoming_trusts_fetcher.rb
- config/locales/members_api.en.yml
- spec/factories/academies_api/establishment.rb
- spec/factories/academies_api/trust.rb
- spec/models/api/academies_api/client_spec.rb
- spec/models/api/base_api_model_spec.rb
- spec/models/api/members_api/client_spec.rb
- spec/models/members_api/client_spec.rb
- spec/models/project_spec.rb
- spec/services/establishments_fetcher_spec.rb
- spec/services/incoming_trusts_fetcher_spec.rb
- spec/support/academies_api_helpers.rb
- spec/support/shared_examples/create_conversion_project_form.rb
We want to be able to show the name and contact details of a local authority's MP in the application, so that users can send a letter (or other correspondence) to the MP and notify them of a school's academisation.
The Parliamentary Members API is available to find details about members of parliament. 
Build a new MembersApi Client. Use it to find a constituency via a free text search (we will use the name of a school district as the search term). Then use that constituency data to find the member of parliament's name and contact details.
Render the MP's name and contact details as custom models we can later use in the UI.
> Use Parliamentary Members API to get MP details

- spec/features/projects/new/users_can_view_a_list_of_new_projects_spec.rb
This test was testing for the presence of nil, which generated a warning each time the tests were run. Swap the expectation for something better.
```
Checking for expected text of nil is confusing and/or pointless since it will
always match. Please specify a string or regexp instead.
```
> (Fix) Remove nil warning in tests

- CHANGELOG.md
- app/models/project_statistics.rb
- app/views/all/statistics/projects/index.html.erb
- spec/models/project_statistics_spec.rb
When we added the stats page, we should have include the projects that are unassigned to make the numbers add up.
This is because we currently do not consider an unassigned project to be 'in-progress'
We know that, right now, there will be no unassigned projects because the Regional delivery officer is always assigned when the project is created - we include the value for consistancy.
We've also increased the column width of the layout row that contains the big table of regions.
> Add unassigned counts to stats page

- config/initializers/omniauth.rb
If the app is put behind a proxy, the redirect URI query parameter that is sent to the Microsoft Identity Provider (IdP) contains the proxy url/hostname instead of the app's FQDN. 
According to the [Omniauth readme](https://github.com/RIPAGlobal/omniauth-azure-activedirectory-v2#explaining-authorize_params) it's possible to override the parameters in the initial request. I looked at the [Microsoft OAuth docs](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-authorization-code) and there does seem to be a `redirect_uri` option that can be defined.
I propose we use an environment variable for setting this value.
> Dynamically set the Redirect Uri passed through to the IdP

- CHANGELOG.md
- app/forms/conversion/create_project_form.rb
- app/models/project.rb
- spec/models/project_spec.rb
- spec/support/shared_examples/create_conversion_project_form.rb
A very subtle bug occurred with the CreateProject form, allowing two projects
with the same URN & UKPRN combination to be created.
This happened because the duplicate project had a nil `assigned_to` value, which
meant it did not appear in the `Project.in_progress` scope.
Adding a new `Project.not_completed` scope to use instead for this validation
has fixed the issue. A project which has no `assigned_to` value is not considered
`in_progress` because no-one will actively be working on it.
> (Bug) User can add duplicate projects

- CHANGELOG.md
- app/controllers/application_controller.rb
- app/models/api/academies_api/client.rb
- app/views/pages/academies_api_client_unauthorised.html.erb
- config/locales/en.yml
- spec/features/users_can_view_static_pages_spec.rb
- spec/models/api/academies_api/client_spec.rb
- spec/support/academies_api_helpers.rb
- spec/support/shared_examples/conversion_project.rb
https://sdd-n7.sentry.io/issues/3912539267/?project=6684508&referrer=slack
We have had a few instances where our access to the Academies Api has been
revoked. This has resulted in the application returning a generic 500
error.
If our access has been revoked, raise a specific error with an informative page.
This will alert us to the situation more quickly, so we can
resolve it with the Academies Api maintainers.
> Raise error if the Academies API returns 401 Unauthorised

- app/controllers/tasks_controller.rb
- app/forms/base_task_form.rb
- app/forms/conversion/task/redact_and_send_task_form.rb
- app/models/conversion/voluntary/tasks/one_hundred_and_twenty_five_year_lease.rb
- app/models/conversion/voluntary/tasks/redact_and_send.rb
- app/views/conversions/tasks/redact_and_send/edit.html.erb
- app/views/conversions/tasks/shared/_task_notes.html.erb
- app/views/conversions/voluntary/task_lists/tasks/one_hundred_and_twenty_five_year_lease.html.erb
- app/views/conversions/voluntary/task_lists/tasks/redact_and_send.html.erb
- config/locales/conversion/tasks/redact_and_send.en.yml
- config/locales/task_lists/conversion/voluntary/one_hundred_and_twenty_five_year_lease.en.yml
- config/locales/task_lists/conversion/voluntary/redact_and_send.en.yml
- config/routes.rb
- db/migrate/20230420132458_do_not_use_save_as_an_attribute.rb
- db/schema.rb
- spec/forms/conversion/tasks/redact_and_send_task_form_spec.rb
- spec/requests/tasks_controller_spec.rb
Here is the first step in what we hope to be the last (?!) big refactoring of the task list.
The motivation for this is again to allow the tasks to handle more than simple checkboxes, the previous refactor went someone towards this but missed.
The main issue is that the TaskList is currently responsible for saving the tasks and does so through meta programming (it can save any task) - the result is that when we want to override the behaviour, we cannot.
This work, introduces a new `TaskForm` base class that can be used to create objects that save themselves, giving us the ability to override the behaviour as needed. Right now we have demonstated this by recreating the existing 'Redact and send' task with the new model.
You can load the new task at: …
> Refactor task list part one: tasks as first class models

- CHANGELOG.md
- app/controllers/sessions_controller.rb
- spec/features/users_can_sign_in_spec.rb
A helpful user pointed out that when their email is not registered in
the applcation and they attempt to sign it, the notification banner
title is 'success' even though the action clearly fails.
Here we switch this notificaiton to the 'important' notification.
> Fix wrong notification banner when user not found

- CHANGELOG.md
- app/views/conversions/voluntary/projects/new.html.erb
- config/locales/conversion_project.en.yml
- config/locales/project.en.yml
- spec/features/users_can_create_involuntary_conversion_projects_spec.rb
- spec/features/users_can_create_voluntary_conversion_projects_spec.rb
Adding guidance to add a conversion page so users know to find information in the advisory board template.
Also clarifying page title to make more succinct. 
And updated and corrected casing for directive academy order.
> Adding guidance to project creation questions 

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- app/models/api/academies_api/establishment.rb
- app/models/local_authority.rb
- app/services/local_authority_importer.rb
- app/validators/postcode_validator.rb
- app/views/project_information/show/_information_list.erb
- app/views/projects/index/_project_summary.html.erb
- app/views/projects/shared/_project_summary.html.erb
- config/locales/en.yml
- config/locales/project.en.yml
- db/migrate/20230417094053_create_local_authorities.rb
- db/schema.rb
- db/seeds/local_authorities.csv
- lib/tasks/local_authority/import.rake
- spec/factories/academies_api/establishment.rb
- spec/factories/local_authority_factory.rb
- spec/features/project_information/users_can_view_local_authority_details_spec.rb
- spec/features/users_can_view_a_project_spec.rb
- spec/lib/tasks/local_authorities/import_spec.rb
- spec/models/api/academies_api/establishment_spec.rb
- spec/models/local_authority_spec.rb
- spec/services/local_authority_importer_spec.rb
- spec/support/academies_api_helpers.rb
- spec/validators/postcode_validator_spec.rb
This creates a Local Authority model and importer which imports the local authority data into the database.
We then display the project's local authority address within the project information tab from this imported data, along with the local authority name which we still get from the Establishmennt via the Academies API.
I have included the `local_authorities.csv`, to allow easy access to the local authorities data in the future.
To run the importer: `bundle exec rake local_authorities:import["db/seeds/local_authorities.csv"]`
Those using zsh will need to escape the square brackets, like so: 
`bundle exec rake local_authorities:import\["db/seeds/local_authorities.csv"\]`
> Users can view a project's local authority details from the project information tab

- .dockerignore
This data contains no personally identifiable information and is in the
public domain. Making it available allows us to deploy and seed the
database.
> Allow the local authorities seeds to be deployed

- .prettierignore
- CHANGELOG.md
- app/views/project_information/show/_information_list.erb
- spec/features/project_information/users_can_view_local_authority_details_spec.rb
If a local authority is not found, the project information page was not loading
correctly. Gracefully handle instances where the LA is not found. Show the
information we can, and do not attempt to render the LA address.
> Handle cases where local authority information is missing

- CHANGELOG.md
- config/locales/task_lists/conversion/voluntary/trust_modification_order.en.yml
This corrects the use of Legal Advisors Office to Legal Adviser's Office in the trust modification order task.
> Make Legal Advisors Office, Legal Adviser's Office

- CHANGELOG.md
- config/locales/task_lists/conversion/voluntary/share_information.en.yml
This PR makes the content in the Share the grant certificate and information about opening task appropriate for both voluntary and sponsored conversions.
> Update content in Share the grant certificate task

- app/forms/conversion/task/funding_agreement_contact_task_form.rb
- app/views/conversions/tasks/funding_agreement_contact/edit.html.erb
- config/locales/conversion/tasks/funding_agreement_contact.en.yml
- db/migrate/20230426111303_add_funding_agreement_contact_to_contacts.rb
- db/schema.rb
- spec/forms/conversion/tasks/funding_agreement_contact_task_form_spec.rb
This is our second scenario that motivates the refactor to the task list.
Here we prove that we can have a task with no attributes stored in the task list table. This task creates a `Contact` object instead - this would not have been a simple thing to do with the old models.
The thing about this one is that the designs are not finalised so I have had to guess at what this task might look like, again - this work is not shown to users so I am not concerned and we can come back and refine this task when designs are completed - what I do want to do is demonstarte how the refactor can handle a task like this one.
To support this we override the `initialize` and `save` methods on the `TaskForm` which lets us load the correct `Contact` and save it again.
We added a `funding_agreement_contact` …
> Refactor task list part two: funding agreement contact task

- config/routes.rb
Previously, visiting `/projects/:id` with an incorrect project ID was correctly rendering a 404, while visiting `/conversions/voluntary/projects/:id/task-list` was incorrectly rendering a 500 error.
This was because we were only applying the route constraint on the "outermost" `projects` resource group. And within the voluntary & involuntary namespaces we were only applying the constraint to the `#show` route. 
So visiting any of the concern routes with an incorrect project ID made the application pass the ID to the database and throw an `ActiveRecord::StatementInvalid` error (rendered as a 500).
Encapsulate all the namespaced routes with the routing constraint. This means the `#show` page *and* all the concernable pages will be subject to the route constraint.
> Correctly enforce project ID constraints

- app/controllers/conversions/tasks_controller.rb
- app/controllers/tasks_controller.rb
- app/models/base_task_list.rb
- app/models/conversion/task_list.rb
- app/views/conversions/tasks/index.html.erb
- config/locales/conversion/task_list.en.yml
- config/locales/task_list.en.yml
- config/routes.rb
- spec/models/base_task_list_spec.rb
- spec/models/conversion/task_list_spec.rb
- spec/requests/conversions/tasks_controller_spec.rb
- spec/requests/tasks_controller_spec.rb
depends on #674 
Here is the next proof in the task list refactor - the task list itself, not much is too different here, it's a base class that handles all the clever bits and simple definitions of the new task models in the actual classes.
As we have an index view from this work, we update the tasks to redirect back to the task list upon update - this is the current behaviour.
> Refactor task list part four: a task list

- config/environments/production.rb
We have been asked to use MS Application Insights if possible.
We are already sending Rack telemetry, here we are seeing what exception
handling might look like.
We are using the archived gem to achieve this right now, it may support
all that we need we do not really know.
According to the docs, this is all that is required:
https://github.com/microsoft/ApplicationInsights-Ruby#collecting-unhandled-exceptions
I've tested this locally and it sent the exception I raised manually so
this appears to be a good first step.
The plan is to deploy this and see if any exceptions are raised in our
existing service (Sentry) and from here, also in Application Insights.
> Try to capture exceptions in Applcation Insights

- .bundle/config
- .gitignore
We have seen multiple instances of developers struggling to build tiny
tds because of the free-tds dependancy.
It takes us a while but we usually figure out that it is and define this
environment variable.
I cannot think of a reason to not have some local bundler config so
here we remove it from gitignore and commit the thing we keep
forgetting.
There is a small chance developers not using Brew will have to deal with
this - but those users are far less likely than those that will benefit
from this change.
> Stop ignoring bundler config and configure it

- app/forms/base_optional_task_form.rb
- app/forms/base_task_form.rb
- app/forms/conversion/task/articles_of_association_task_form.rb
- app/models/conversion/task_list.rb
- app/views/conversions/tasks/articles_of_association/edit.html.erb
- config/locales/conversion/task_list.en.yml
- config/locales/conversion/tasks/articles_of_association.en.yml
- spec/forms/conversion/tasks/articles_of_association_task_form_spec.rb
- spec/models/conversion/task_list_spec.rb
Depends on #675 
Next on the new task list menu: Optional tasks, at this point there is nothing interesting here, this is a repeat of the existing approach against the new classes.
We have a `BaseOptionalTaskForm` that provides the additional behaviour, any subclass can inherit from this to become optional with little to no effort.
We start to flesh out the Converison task list here, adding more sections and moving the tasks into the right places.
> Refactor task list part five: optional tasks

- app/views/conversions/tasks/church_supplemental_agreement/edit.html.erb
- app/views/conversions/tasks/commercial_transfer_agreement/edit.html.erb
- app/views/conversions/tasks/conditions_met/edit.html.erb
- app/views/conversions/tasks/conversion_grant/edit.html.erb
- app/views/conversions/tasks/deed_of_variation/edit.html.erb
- app/views/conversions/tasks/direction_to_transfer/edit.html.erb
- app/views/conversions/tasks/funding_agreement_contact/edit.html.erb
- app/views/conversions/tasks/handover/edit.html.erb
- app/views/conversions/tasks/land_questionnaire/edit.html.erb
- app/views/conversions/tasks/land_registry/edit.html.erb
- app/views/conversions/tasks/master_funding_agreement/edit.html.erb
- app/views/conversions/tasks/one_hundred_and_twenty_five_year_lease/edit.html.erb
- app/views/conversions/tasks/receive_grant_payment_certificate/edit.html.erb
- app/views/conversions/tasks/redact_and_send/edit.html.erb
- app/views/conversions/tasks/school_completed/edit.html.erb
- app/views/conversions/tasks/share_information/edit.html.erb
- app/views/conversions/tasks/single_worksheet/edit.html.erb
- app/views/conversions/tasks/sponsored_support_grant/edit.html.erb
- app/views/conversions/tasks/stakeholder_kick_off/edit.html.erb
- app/views/conversions/tasks/subleases/edit.html.erb
- app/views/conversions/tasks/supplemental_funding_agreement/edit.html.erb
- app/views/conversions/tasks/tenancy_at_will/edit.html.erb
- app/views/conversions/tasks/trust_modification_order/edit.html.erb
- app/views/conversions/tasks/update_esfa/edit.html.erb
- lib/generators/conversion/templates/edit.html.erb
Whilst we have one, the back link should return a user to the task list.
This was missed in the generator and so we take care of it here by
updating all the task views and the generator template.
https://trello.com/c/bDdlNkGo
> Refactor task list part eight: fix back links

- CHANGELOG.md
- app/forms/conversion/create_project_form.rb
- app/views/conversions/voluntary/projects/new.html.erb
- config/locales/conversion_project.en.yml
- spec/features/users_can_create_involuntary_conversion_projects_spec.rb
- spec/features/users_can_create_voluntary_conversion_projects_spec.rb
We saw a number of instances of users getting the answer to the question
wrong, so we are rephrasing it.
We've also added hint text to align the response to the outcome, which
is a sponsored or voluntary project.
> Change how we ask about directive academy order

- CHANGELOG.md
- app/controllers/user/projects_controller.rb
- app/models/project.rb
- app/views/conversions/voluntary/projects/created.html.erb
- app/views/internal_contacts/show.html.erb
- app/views/projects/shared/_project_index_sub_navigation.html.erb
- app/views/user/projects/added_by.html.erb
- config/locales/contact.en.yml
- config/locales/conversion_project.en.yml
- config/locales/en.yml
- config/locales/project.en.yml
- config/routes.rb
- spec/features/projects/added_by/user_can_view_the_projects_they_have_added_spec.rb
- spec/features/team_leaders_can_assign_users_to_project_roles_spec.rb
- spec/features/users_can_create_voluntary_conversion_projects_spec.rb
- spec/models/project_spec.rb
When a regional delivery officer creates a new project and hands it over
to regional casework services, it dissappears from their view. This
means it is difficult for them to find it again and add notes or
contacts.
We already know the projects a user has 'created' so we can help by
showing a list of these projects.
> List of projects added by a user

- CHANGELOG.md
- app/controllers/all/projects_controller.rb
- app/controllers/conversions/academy_urn_controller.rb
- app/models/project.rb
- app/policies/project_policy.rb
- app/views/all/projects/with_academy_urn.html.erb
- app/views/conversions/academy_urn/confirm.html.erb
- app/views/conversions/academy_urn/edit.html.erb
- app/views/conversions/academy_urn/not_found.html.erb
- app/views/projects/shared/_new_table.html.erb
- app/views/projects/shared/_with_academy_urn_table.html.erb
- config/locales/en.yml
- config/locales/project.en.yml
- config/routes.rb
- spec/features/conversions/users_can_edit_the_academy_urn_spec.rb
- spec/features/projects/new/users_can_view_a_list_of_new_projects_spec.rb
- spec/features/projects/with_academy_urn/users_can_view_a_list_of_projects_with_academy_urn_spec.rb
- spec/models/project_spec.rb
- spec/policies/project_policy_spec.rb
- spec/support/academies_api_helpers.rb
Users can now edit a project to add an Academy URN. 
From the "All conversions without an academy URN" page (`/projects/all/new`) they can click on a link to add the Academy URN. This brings them to a form where they can enter the Academy URN.
If they do not enter anything, they see an error message:
If the Academy URN does not exist in GIAS, they see an error message:
If the Academy URN is found in GIAS, they see a confirmation message:
Upon confirmation, they are returned to the list page, with a success message:
The "All conversions without an academy URN" now has a sister page featuring all projects with an academy URN. The two pages are linked by tabs.
> Users can provide the new Academy URN

- CHANGELOG.md
- app/views/project_information/show/_information_list.erb
- spec/requests/project_information_controller_spec.rb
We came across a trust record in the academies database without a
companies house number, this caused our view to explode.
Although the Get information about schools record for the trust has the
number, we should still handle this case and render nothing.
https://trello.com/c/mAAlHQ4r
> Fix: handle missing companies house number

- CHANGELOG.md
- config/locales/project.en.yml
This work takes the guidance about what to include in handover comments out of the details component and into the standard text. Hopefully this helps delivery officers understand what to include and write better comments for caseworkers.
> Edit handover comments guidance and remove details component

- app/controllers/all/projects_controller.rb
- spec/requests/all/projects_controller_spec.rb
- spec/support/academies_api_helpers.rb
We noticed during a product review that the two 'academy urn' views
include completed projects when they should not.
https://trello.com/c/KZmV71Rx
> Update academy urn view scopes

- CHANGELOG.md
- app/views/conversions/tasks/commercial_transfer_agreement/edit.html.erb
This little `p` was breaking the back link.
> Fix - errant p on task view

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/task-list.scss
- app/assets/stylesheets/components/task_list/task-header-component.scss
I have moved the scss code for this hint text into the general task-list scss file, as it felt more logical for it to sit within the general task-list styling. 
I am not aware of the original reasoning behind separating the hint text styling into it's own file, but it personally feels simpler to locate it within the `task-list.scss` file.
> Apply govuk hint styling onto all hint text within the task list

- config/locales/project.en.yml
Throughout the project we have displayed `SharePoint` so. The changes to the 2 links are to reflect this and keep consistency
> Change Sharepoint to SharePoint on links in project summary

- CHANGELOG.md
- app/models/api/academies_api/trust.rb
- app/views/project_information/show/_information_list.erb
- config/locales/project.en.yml
Although the Acadmies API only lets us search for trusts by UKPRN, we have learnt that users prefer other identifiers in their searches. We have identified that Group Identifier (ID) is one of their preferences and one that we are able to access via the Academies API. So to help users gain more confidence that they have the correct trust, we are displaying this group identifier within the project information view.
> Display trust's group identifier within the project information view

- CHANGELOG.md
- app/services/director_of_child_services_importer.rb
- config/locales/en.yml
- lib/tasks/director_of_child_services/import.rake
- spec/lib/tasks/director_of_child_services/import_spec.rb
- spec/services/director_of_child_services_importer_spec.rb
Note that this commit does not contain the seed data, as it includes sensitive information.
The importer is run with
`rake director_of_child_services:import[path/to/data.csv]`
The CSV headers must be
`LA,Name,Title,Email,Phone`
where `LA` is the local authority code
This importer borrows heavily from the LocalAuthorityImporter by @beeLorna
> Import Director of Child Services data

- db/migrate/20230517131621_add_conversion_academy_details_task_attributes.rb
A recent migration had a mis-matching class and file name. This is the
fix.
> Fix migration class name

- CHANGELOG.md
- app/policies/note_policy.rb
- spec/factories/conversion/date_history_factory.rb
- spec/factories/note_factory.rb
- spec/policies/note_policy_spec.rb
Changing the conversion date is a signigicant event and we do not want
to loose the note associsated with the change.
We use the Note model to store it, which by design, allows the user who
created the note to delete it.
This change prevents that for notes associated with a conversion date
history change.
https://trello.com/c/OBQzALPu
> Conversion date history notes cannot be deleted

- CHANGELOG.md
- app/helpers/project_helper.rb
- app/views/projects/shared/_new_table.html.erb
- app/views/projects/shared/_with_academy_urn_table.html.erb
- config/locales/project.en.yml
- spec/features/projects/new/users_can_view_a_list_of_new_projects_spec.rb
- spec/features/projects/with_academy_urn/users_can_view_a_list_of_projects_with_academy_urn_spec.rb
- spec/helpers/project_helper_spec.rb
Once the academy name is confirmed, a service support users adds the new
record to Get infromation about schools, we then read that information
back in and show it.
So the service support users knows the academy name and can provide it
we show it on our views that support this process.
Once the new academy record is created the service support user adds the
URN and can verify the correct name is being returns - for this reason,
the 'with academy URN' view shows the fetched name NOT the local
'confirmed' name.
https://trello.com/c/2SjUUyCI
> Show the academy name to service support users

- config/initializers/inflections.rb
One Director of Child Services; two Directors of Child Services
By default, Rails would make the plural of "Director of Child Services", "Director of Child Services"
> Add correct pluralisations for DirectorOfChildServices

- app/views/project_information/show/_information_list.erb
- config/locales/local_authorities.en.yml
- config/locales/project.en.yml
Change "Role" to "DCS Position" for Director of Child Services and show the DCS Position on the project information page.
Correct capitalisation for director of child services.
> Change "Role" to "DCS Position" for Director of Child Services

- CHANGELOG.md
- app/controllers/conversions/projects_controller.rb
- app/forms/conversion/create_project_form.rb
- app/views/conversions/projects/new.html.erb
- config/locales/project.en.yml
- spec/factories/conversion/create_project_form_factory.rb
- spec/forms/conversion/create_project_form_spec.rb
- spec/requests/conversions/projects_controller_spec.rb
The goal of this work is twofold:
- make the handover note on the create project form required
- associate the handover note with the handover task
We are making the handover note required at all times as it is an important piece of information and is used more than it is not. The only time it would not be used is when the regional delivery officer creating the project is also working on the project. Whilst it is frustrating in this one instance, the rest of the time it is super valuable.
Associating the handover note to the handover task makes the note appear alongside the task, this is feedback we have recieved from users.
> Handover note improvements

- app/assets/config/manifest.js
We need to add the full path to this asset for it to load in a
production environment.
The quotes are needed as the path contains the @ symbol.
> Fix MOJ image asset

- CHANGELOG.md
- app/controllers/all/trust/projects_controller.rb
- app/models/project.rb
- app/views/all/trust/projects/by_trust.html.erb
- config/locales/project.en.yml
- config/routes.rb
- spec/features/projects/trust/users_can_view_a_list_of_projects_for_a_given_trust_spec.rb
- spec/models/project_spec.rb
Users can view a list of projects for a given trust
Some regional delivery officers are also `Trust relationship managers` and want to see all projects for the trust whose relationship they manage.
Currently this view is only accessible via url: `/projects/all/trust/<trust_ukprn>`
Projects are ordered by conversion date, in ascending order
> Users can view a list of projects for a given trust

- app/views/all/completed/projects/index.html.erb
- app/views/all/completed/projects/sponsored.html.erb
- app/views/all/completed/projects/voluntary.html.erb
- app/views/all/conversion_date_changed/projects/index.html.erb
- app/views/all/in_progress/projects/index.html.erb
- app/views/all/in_progress/projects/sponsored.html.erb
- app/views/all/in_progress/projects/voluntary.html.erb
- app/views/all/projects/new.html.erb
- app/views/all/projects/with_academy_urn.html.erb
- app/views/conversions/academy_urn/confirm.html.erb
- app/views/conversions/academy_urn/edit.html.erb
- app/views/conversions/academy_urn/not_found.html.erb
- app/views/local_authorities/index.html.erb
- app/views/projects/index.html.erb
- app/views/projects/unassigned.html.erb
- app/views/projects_openers/openers.html.erb
- app/views/regional/projects/completed.html.erb
- app/views/regional/projects/completed_by_region.html.erb
- app/views/regional/projects/in_progress.html.erb
- app/views/regional/projects/in_progress_by_region.html.erb
- app/views/regional_casework_services/projects/completed.html.erb
- app/views/regional_casework_services/projects/in_progress.html.erb
- app/views/regional_casework_services/projects/unassigned.html.erb
- app/views/user/projects/added_by.html.erb
- app/views/user/projects/completed.html.erb
- app/views/user/projects/in_progress.html.erb
- spec/features/users_can_sign_in_spec.rb
- spec/requests/sign_in_spec.rb
This PR removes the text `You are signed in with the email address user.name@education.gov.uk` from the top of the view pages
We now do not need to display to the user who is signed in from within the service. We had added this in the early stages of the product as a way to validate the sign in was working.
> Remove the signed in users email verification text from the view

- app/views/all/openers/projects/index.html.erb
- app/views/all/revised_conversion_date/projects/index.html.erb
- config/routes.rb
- spec/features/users_can_view_a_table_of_project_openers_spec.rb
- spec/requests/all/openers/projects_controller_spec.rb
The route to the project openers page should be `/projects/opening`.
This was missed in an earlier commit.
> (Fix) Route to project openers page should be `opening`

- CHANGELOG.md
- app/models/api/academies_api/establishment.rb
- app/views/project_information/show/_information_list.erb
- config/locales/project.en.yml
- spec/factories/academies_api/establishment.rb
- spec/features/project_information/users_can_view_school_details_spec.rb
- spec/models/api/academies_api/establishment_spec.rb
The DfE number is another identifier for the establishment which may be useful for users to use as a form of validation.
It is also known as LAESTAB.
The DfE number is shown within the GIAS but isn't accessible via the AcademiesApi, so we have therefore needed to construct it from the local authority code and the establishment number.
> Display generated DfE number

- CHANGELOG.md
- app/views/conversions/projects/created.html.erb
- config/locales/conversion_project.en.yml
when a project has been created
This work changes the content on the confirmation page that a delivery officer sees after creating a conversion. 
It prioritises and emphasises the importance of adding contact details to the project for caseworkers to pick up.
It also re-routes the primary action button to the external contacts page, so that the call to action on the page reflects the instruction in the content.
> Make clear delivery officers need to add contacts 

- CHANGELOG.md
- config/locales/conversion/tasks/single_worksheet.en.yml
This takes the full stop in a sentence of guidance about the single worksheet out of the mailto hyperlink and into the <p> text outside the link.
It also adds more specifics to the changelog about a change to where the primary action button points on the confirmation page after a delivery officer creates a project.
> Move full stop from link to text in single worksheet task

- CHANGELOG.md
- config/locales/conversion/tasks/receive_grant_payment_certificate.en.yml
> Add full stop to guidance in grant certificate task

- CHANGELOG.md
- config/locales/conversion_history.en.yml
- Academy name and URN presented in way that is consistent with other confirmation pages in the build
- Content about when to change the date again is made more direct and clear by using statement rather than question in the heading. Also covers changing date because of further delays and not just because of human error
> Making academy name and URN style consistent and clarifying content on conversion date confirmation page

- app/views/all/trust/projects/by_trust.html.erb
- app/views/notes/_notes.html.erb
- app/views/notes/confirm_destroy.html.erb
- app/views/notes/new.html.erb
- app/views/user/projects/_table.html.erb
- config/locales/en.yml
- config/locales/project.en.yml
When looking into https://trello.com/c/6toiEBHZ we found some other missing locale strings, which were being overlooked by the i18n default behaviour (of presenting the local key in Sentence Case).
> Add some missing locale strings

- CHANGELOG.md
- app/controllers/root_controller.rb
- app/views/all/projects/new.html.erb
- app/views/all/projects/with_academy_urn.html.erb
- app/views/local_authorities/index.html.erb
- app/views/shared/_service_support_sub_navigation.html.erb
- config/locales/project.en.yml
- config/locales/service_support.en.yml
- spec/features/conversions/users_can_edit_the_academy_urn_spec.rb
- spec/features/local_authorities/users_can_view_local_authorities_spec.rb
- spec/features/projects/new/users_can_view_a_list_of_new_projects_spec.rb
- spec/features/projects/with_academy_urn/users_can_view_a_list_of_projects_with_academy_urn_spec.rb
- spec/features/service_support/users_can_navigate_the_application_spec.rb
This work brings the three service support user views togther and redirects them to it upon login or visiting the root page.
We haven't consolidate the paths just yet, that may come later, for now we want to have the option of sharing the behaviour of the new app/service with users.
https://trello.com/c/692dTdzf
> Service support user views

- CHANGELOG.md
- app/forms/conversion/create_project_form.rb
- app/models/api/academies_api/establishment.rb
- spec/forms/conversion/create_project_form_spec.rb
- spec/models/api/academies_api/establishment_spec.rb
When a new project is created we can help users by pre-marking some tasks as not applicable:
- when the school is not considered 'religious' the Church supplemental funding agreement task is likely to be not applicable
- when the project is considered 'voluntary' the Process the sponsored support grant task is likely to be not applicable
Here we add this logic into the create conversion project form object.
Along the way we looked for a reliable marker for a school being considered 'religious' - there wasn't a clear one so we have gone with if the school has a diocese - this may turn out to be not the best marker - but this feature is not critical so it is good enough for now.
https://trello.com/c/YvCZ2meO
> New project logic

- .irbrc
The Rails console is great, but on Azure the autocompelete is a pain,
disabling it will make working on Azure much nicer and less risky.
I have been unable to see any diffrence locally, but other developers
might have different results?
> Disable console autocomplete

- CHANGELOG.md
- app/controllers/projects_complete_controller.rb
- app/models/conversion/project.rb
- app/models/project.rb
- config/locales/project.en.yml
- spec/accessibility/projects_spec.rb
- spec/features/users_can_complete_a_project_spec.rb
- spec/models/conversion/project_spec.rb
- spec/models/project_spec.rb
A Project cannot be completed until All conditions have been met, the Grant payment certificate is received and the academy has opened. If the user tries to complete the project when these conditions are not met, they will see a message.
> Add project completion validation

- CHANGELOG.md
- app/forms/conversion/task/funding_agreement_contact_task_form.rb
- app/models/conversion/task_list.rb
- app/models/project.rb
- app/views/conversions/tasks/funding_agreement_contact/edit.html.erb
- app/views/external_contacts/_contact_group.html.erb
- config/locales/contact.en.yml
- config/locales/conversion/tasks/funding_agreement_contact.en.yml
- db/migrate/20230531110401_remove_funding_agreement_contact_column_from_contacts.rb
- db/migrate/20230605095316_add_funding_agreement_letters_contact_id_to_project.rb
- db/schema.rb
- spec/features/conversions/users_can_complete_conversion_tasks_spec.rb
- spec/features/conversions/users_can_select_a_funding_agreement_letter_contact_spec.rb
- spec/features/users_can_manage_contacts_spec.rb
- spec/forms/conversion/tasks/funding_agreement_contact_task_form_spec.rb
- spec/models/conversion/task_list_spec.rb
- spec/models/project_spec.rb
Add the "Confirm who will get the funding agreement letters" task.
This task was begun previously but this is a reworking & completion of it. 
If a project has external contacts already entered, then they will appear on the task page. The user will then be able to select a contact and assign them as the "funding agreement letters" contact. 
On the external contacts page, the "funding agreement letters" contact will be indicated as per the second screenshot.
If a project has no external contacts already, the user will be invited to add more contacts by some text on the task page, and a link leading to the external contacts page. They can then come back to the task later and assign contacts as above.
Previously, we had anticipated that the user would be adding a contact directly on the task …
> Add the Funding agreement letters contact task

- CHANGELOG.md
- app/models/transfer/project.rb
- app/models/transfer/tasks_data.rb
- db/migrate/20230607103526_create_transfer_tasks_data.rb
- db/schema.rb
- spec/factories/transfer/project_factory.rb
- spec/factories/transfer/tasks_data_factory.rb
- spec/models/transfer/project_spec.rb
- spec/models/transfer/tasks_data_spec.rb
Add a new Project type, Transfer::Project. It uses the ProjectPolicy.
Add a new Transfer::TasksData model, which uses a new table `transfer_tasks_data` and the TaskListPolicy.
Add factories for the project and tasks data, and prove that new models can be created using them.
> Create a bare bones Transfer::Project and Transfer::TasksData

- CHANGELOG.md
- app/controllers/all/opening/projects_controller.rb
- app/models/api/members_api/client.rb
- app/services/opening_projects_csv_exporter.rb
- config/routes.rb
- spec/models/api/members_api/client_spec.rb
- spec/requests/all/opening/projects_controller_spec.rb
- spec/services/opening_projects_csv_exporter_spec.rb
This isn't the finished feature.
This work is to introduce the process of exporting projects from the openers list into a csv file.
This covers just a few basic attributes to allow us to test this against a larger number of projects within the `production environment`.
The are at least 44 attributes that will end up in the csv, so we want to make sure we have a solid foundation to work from.
To add in the remaining attributes once we know this is the sensible route.
> First pass at data export for funding agreement letters

- CHANGELOG.md
- app/views/regional_casework_services/projects/completed.html.erb
- app/views/regional_casework_services/projects/in_progress.html.erb
- app/views/regional_casework_services/projects/unassigned.html.erb
- app/views/shared/navigation/_header_navigation.html.erb
- app/views/shared/navigation/_team_projects_primary_navigation.html.erb
- config/locales/en.yml
- config/locales/project.en.yml
We have a navigation pattern, here we follow it for the team projects
'section'.
Right now we only support the regional casework services team but other
teams will be supported soon.
https://trello.com/c/r0c5esjA
> Add team projects primary navigation

- app/models/conversion/tasks_data.rb
- app/models/project.rb
- app/models/transfer/tasks_data.rb
- db/migrate/20230608114403_rename_task_list_table.rb
- db/schema.rb
To keep things consitent, keep the TasksData table names the same.
Also turned out we still have to set the table names on the models, I thought we didn't here #775 
Last thing I noticed is that we haven't update the delegated type name, doesn't seem to have stop it all from working, I checked the `tasks_data_type` in production and they are all set correctly?
Verified all this on the console by creating both types of Project and TasksData and verifying they can be loaded, see below.
https://trello.com/c/pqaaMSG4
> Update task list table name and fix a couple of Transfer issues

- Dockerfile
In production environments in Azure the autocomplete in the Rails
console does not work well and actually makes things more risky.
We thought we had turned this off by including the setting in the irbrc
but this file was not included in the Docker build.
> Add irbrc to Docker build

- app/models/api/members_api/client.rb
- app/models/api/members_api/member_details.rb
- app/services/opening_projects_csv_exporter.rb
- config/locales/opening_projects_csv_exporter.yml
- spec/models/api/members_api/client_spec.rb
- spec/models/api/members_api/member_details_spec.rb
- spec/requests/all/opening/projects_controller_spec.rb
- spec/services/opening_projects_csv_exporter_spec.rb
- spec/support/members_api_helpers.rb
We have to add a lot of columns to the export, so we are adding them in multiple PRs.
This one adds the MP details. Because we fetch this from the Members API, we want this in so we can test real world 
performance.
We took some time to improve the exporter so that the column names and order are defined in one place and come from the locales.
We also refactored the return from the members api client that we introduced.
> Opening export includes MP details

- db/migrate/20230609110127_remove_task_list_id_and_task_list_type_from_projects.rb
- db/schema.rb
- doc/task-lists-and-tasks.md
These two Project attributes are now redundant:
`task_list_id`
`task_list_type`
Remove the two columns from projects. Update the documentation to reflect that we've now moved to the TasksData model.
> Remove task_list_id and task_list_type from project

- app/controllers/all/opening/projects_controller.rb
- app/controllers/all/trust/projects_controller.rb
- app/controllers/service_support/projects_controller.rb
- app/controllers/user/projects_controller.rb
- app/models/conversion/project.rb
- app/models/project.rb
- app/models/project_statistics.rb
- app/services/conversion_projects_fetcher.rb
- app/services/projects_fetcher.rb
- spec/models/conversion/project_spec.rb
- spec/models/project_spec.rb
- spec/services/projects_fetcher_spec.rb
Now that Transfer::Project exists, we need to start moving the Conversion-specific attributes and scopes (etc) from Project to Conversion::Project.
The first three are:
- `academy_urn`
- `conversion_date_provisional`
- `conversion_date`
All three have been moved to Conversion::Project, and any scopes which rely on these attributes have also moved to Conversion::Project.
The scope `.in_progress` has stayed in Project, but its ordering by `conversion_date` has been removed. We imagine the concept of "in progress" will apply to all Project types, hence retaining this scope. 
A version of the `.in_progress` scope has been added to Conversion::Project, and retains the ordering by `conversion_date`.
> Move three conversion-specific attributes from Project to Conversion::Project

- app/controllers/sessions_controller.rb
- app/models/user.rb
- db/migrate/20230609151244_add_active_directory_ids_to_user.rb
- db/schema.rb
- spec/features/users_can_sign_in_spec.rb
- spec/models/user_spec.rb
- spec/requests/sign_in_spec.rb
- spec/support/sign_in_helpers.rb
We don't want to have to manage user authrorisation ourselves.
When a user is authenticated against the DfE Active Directory, it returns an array of the Group IDs the user is part of. We can leverage this authorise users.
The first step is to store the IDs with the User, we do so here.
We store all the Group IDs in the same column and serialize the result, later we can check which groups we care about.
https://trello.com/c/W1w259AY/1641-store-the-active-directory-group-ids-with-the-user
> Store active directory group ids on user

- CHANGELOG.md
- app/models/conversion/project.rb
- spec/features/projects/revised_conversion_date/viewing_projects_with_a_revised_converison_date_spec.rb
- spec/models/conversion/project_spec.rb
Previously we stored the provvisional covnersion date in a seperate
column. We then removed that and simply mark the project as 'with
provisional conversion date'.
However, we missed the impact this has on the
`self.conversion_date_revised_from` scope. Now the first Converison Date
History  is always the change from provisional to confirmed and, if the
dates are diffrent, the test is triggered and the project included when
it should not be.
The fix is to exclude any project that only has one
Conversion::DateHistory when grouping. A project in this state must only
have been confirmed and all projects must be confirmed.
(https://trello.com/c/UpLORrCE)
> Fix: Different provisional/confirmed conversion dates is not a change

- CHANGELOG.md
- app/models/transfer/project.rb
- config/locales/project.en.yml
- db/migrate/20230613093255_add_outgoing_trust_ukprn_to_projects.rb
- db/schema.rb
- spec/models/project_spec.rb
- spec/models/transfer/project_spec.rb
The `outgoing_trust_ukprn` attribute is mandatory for Transfer::Project but not other kinds of Project. Add the standard validations, to ensure it is not blank, is a valid UKPRN and that the trust exists, to Transfer::Project only.
> Add mandatory `outgoing_trust_ukprn` to Transfer::Project

- CHANGELOG.md
- app/views/projects/shared/_unassigned_table.html.erb
- spec/features/projects/view_unassigend_team_projects_spec.rb
Regional casework services need to know which region a project is in
when making a decision about assignment.
Here we add the column to the table that is render in that view.
https://trello.com/c/FW4ISAHa
> Add the region to the unassigned projects view

- CHANGELOG.md
- app/views/layouts/application.html.erb
- spec/features/navigation/footer_navigation_spec.rb
Adds a link to the new service guidance in the footer.
https://trello.com/c/rVD5vBhj
> Add footer link to the service guidance

- app/controllers/all/trusts/projects_controller.rb
- app/views/all/trusts/projects/show.html.erb
- spec/features/projects/trusts/users_can_view_a_list_of_projects_for_a_given_trust_spec.rb
When we introduced the new master view for the existing projects for a
given trust view, we didn't realised it does not handle unassigned and
the scope includes completed projects.
This means the converison count on the trust view will not match that of
the view of projects.
> Fix by trust projects view

- CHANGELOG.md
- app/services/opening_projects_csv_exporter.rb
- spec/services/opening_projects_csv_exporter_spec.rb
The CSV was not displaying correctly in MS Excel, due to UTF-8 encoding not being enforced. Enforce UTF-8 via a BOM prepended to the CSV data (byte order mark) and encoding the CSV file as it is generated.
Screenshot below to show the apostrophe in "Children's services" is being rendered correctly in Excel.
> Add a BOM to the CSV file and enforce UTF-8

- app/controllers/all/completed/projects_controller.rb
- app/controllers/all/in_progress/projects_controller.rb
- app/models/conversion/project.rb
- app/models/project.rb
- spec/models/conversion/project_spec.rb
- spec/models/project_spec.rb
Move the validation for `directive_academy_order` to the Conversion::Project model (from Project). This attribute is only required for conversions.
Also move two scopes - .voluntary and .sponsored - to the Conversion::Project model, as these rely on the directive_academy_order attribute.
Finally, amend two controllers to only look for Conversion::Projects. We may need to move these controllersi nto a conversion project namespace in future.
> Move `directive_academy_order` to Conversion::Project

- CHANGELOG.md
- app/models/api/members_api/client.rb
- app/services/opening_projects_csv_exporter.rb
- config/initializers/time_formats.rb
- config/locales/members_api.en.yml
- config/locales/opening_projects_csv_exporter.yml
- spec/models/api/members_api/client_spec.rb
- spec/services/opening_projects_csv_exporter_spec.rb
- Rescue an error we saw on production when an MPs contact details were nil
- Add Route and Academy name to the CSV
- Do a little refactoring
> Add more columns to the funding agreement letters export

- CHANGELOG.md
- app/controllers/all/local_authorities/projects_controller.rb
- app/models/project.rb
- app/services/by_local_authority_project_fetcher_service.rb
- app/views/all/local_authorities/projects/_local_authority_table.html.erb
- app/views/all/local_authorities/projects/index.html.erb
- app/views/all/local_authorities/projects/show.html.erb
- app/views/shared/navigation/_all_projects_primary_navigation.html.erb
- config/locales/en.yml
- config/locales/project.en.yml
- config/routes.rb
- spec/features/projects/local_authorities/users_can_view_projects_by_local_authority_spec.rb
- spec/features/projects/local_authorities/users_can_view_projects_for_a_local_authority_spec.rb
- spec/services/by_local_authority_project_fetcher_service_spec.rb
Hot on the heels of the by trust views, here is the by local authority! It is pretty much a repeat of #808, the main difference being a bit more effort is required to fetch the projects per local authority as they come via the establishment.
Another difference is tha there was no existing project for local authority view as there was for trusts - so that gets added.
Second time through, I wondered if the fetching of projects for the local authority might be better inside the service - my reasoning was to keep the scopes as close together as we can - not sure it is necessary, let me know your thoughts? 
I came to this the hard way (#810), once deployed to development it was obvious that the count of projects was for `not_completed` projects and the actual list of projects did not include …
> By local authority view

- app/services/opening_projects_csv_exporter.rb
- spec/services/opening_projects_csv_exporter_spec.rb
We are still ironing out how this export will work, but as lots of
projects have no academy we should guard against nil.
> Opening export handles no academy

- CHANGELOG.md
- app/models/user.rb
- app/services/user_team_updater.rb
- db/migrate/20230626112559_add_team_to_user.rb
- db/schema.rb
- lib/tasks/teams/update_users.rake
- spec/factories/user_factory.rb
- spec/lib/tasks/teams/update_users_spec.rb
- spec/models/user_spec.rb
- spec/services/user_team_updater_spec.rb
Add a team attribute to User. Possible values are taken from an enum of regions + three other non-region teams.
> Add `team` to User

- app/models/project.rb
- db/migrate/20230626152519_add_team_to_project.rb
- db/schema.rb
- spec/factories/conversion/project_factory.rb
- spec/models/project_spec.rb
Add a team attribute to Project. Possible values are taken from an enum of regions + the regional casework services team.
> Add `team` to Project

- CHANGELOG.md
- app/controllers/all/regions/projects_controller.rb
- app/services/by_region_project_fetcher_service.rb
- app/views/all/regions/projects/_regions_table.html.erb
- app/views/all/regions/projects/index.html.erb
- app/views/all/regions/projects/show.html.erb
- app/views/shared/navigation/_all_projects_primary_navigation.html.erb
- config/locales/en.yml
- config/locales/project.en.yml
- config/routes.rb
- spec/features/projects/regions/users_can_view_a_list_of_projects_for_a_given_region_spec.rb
- spec/features/projects/regions/users_can_view_projects_by_trust_spec.rb
- spec/services/by_region_project_fetcher_service_spec.rb
This is the third 'by' view that takes the existing pattern and applies it to region, every project is in a region based on the schools location.
We fetch all the in-progress projects and group them by region, we then add two views, one shows the regions with counts of conversion projects, the second shows the projects in a given region.
https://trello.com/c/eSU9aea0
> By region view

- app/forms/conversion/create_project_form.rb
- app/models/project.rb
- spec/accessibility/team_projects_spec.rb
- spec/features/projects/users_can_view_a_list_of_regional_casework_services_projects_spec.rb
- spec/features/projects/users_can_view_a_list_of_regional_projects_spec.rb
- spec/features/projects/view_unassigend_team_projects_spec.rb
- spec/features/users_can_assign_a_project_spec.rb
- spec/forms/conversion/create_project_form_spec.rb
- spec/models/project_spec.rb
- spec/models/project_statistics_spec.rb
To be merged after https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/823
This PR changes the behaviour of the CreateProjectForm. When a project creator selects "Assigned to regional caseworker team", the Project's team is set to "regional_casework_services". Otherwise, the team is set to be the same as the establishment's region.
Then, update two scopes on Project to use the project's team attribute, not the assigned_to_regional_caseworker_team attribute. Behaviour should remain identical.
> Refactor Project.assigned_to_regional_caseworker_team

- app/controllers/all/completed/projects_controller.rb
- app/controllers/all/in_progress/projects_controller.rb
- app/controllers/all/local_authorities/projects_controller.rb
- app/controllers/all/regions/projects_controller.rb
- app/controllers/all/trusts/projects_controller.rb
- app/controllers/conversions/projects_controller.rb
- app/controllers/regional/projects_controller.rb
- app/controllers/service_support/projects_controller.rb
- app/controllers/team/projects_controller.rb
- app/controllers/user/projects_controller.rb
- app/services/by_local_authority_project_fetcher_service.rb
- app/services/establishments_fetcher.rb
- app/services/establishments_fetcher_service.rb
- app/services/incoming_trusts_fetcher.rb
- app/services/trusts_fetcher_service.rb
- spec/accessibility/projects_spec.rb
- spec/requests/all/opening/projects_controller_spec.rb
- spec/services/by_local_authority_project_fetcher_service_spec.rb
- spec/services/establishments_fetcher_service_spec.rb
- spec/services/establishments_fetcher_spec.rb
- spec/services/incoming_trusts_fetcher_spec.rb
- spec/services/trusts_fetcher_service_spec.rb
- spec/support/academies_api_helpers.rb
Initially the ByLocalAuthoirtyProjectsFetcher called the academies API for each project it was given - this takes a long, long time in prod (~10s on ~150 projects).
To make things much quciker we can bulk fetch and pre-load the projects with their establishments.
Before this work, it was generally true that we would never fetch more than 20 trust or establishments due to paging, but here we could suddenly be fetching hundreds.
This work refactors the fetchers to batch fetch in sets of 20 for both establishments and trusts.
Whilst we were here we move some things around and renamed in an effort to make this two service objects more obvious.
https://trello.com/c/iQlgA47w
> Establishment and trust pre-fetcher refactor

- app/models/concerns/teamable.rb
- app/models/project.rb
- app/models/user.rb
- spec/models/project_spec.rb
- spec/models/user_spec.rb
Move the shared User & Project teams into a shared "Teamable" module. This way we can manage the teams in one place, should we need to add/remove any.
> Refactor team definitions into "Teamable" module

- CHANGELOG.md
- app/models/api/members_api/client.rb
- app/services/opening_projects_csv_exporter.rb
- spec/models/api/members_api/client_spec.rb
- spec/requests/all/opening/projects_controller_spec.rb
- spec/services/opening_projects_csv_exporter_spec.rb
- spec/support/members_api_helpers.rb
Because of data inconsistencies between GIAS and the Parliamentary Members API,
we have had issues getting the CSV export to work properly when a school's
parliamentary constituency is unclear (e.g. "Middlesbrough" is not a single
constituency, but GIAS insists some schools are in "Middlesbrough")
To get round this, if we query the Members API for a constituency but get
multiple results back, still allow the CSV to be downloaded but with empty
values for the MP details. The CSV requester will then have to fill in the
blanks themselves.
We also send a warning to Application Insights to let us know this has happened. This way we
can track which constituencies are returning multiple results.
The solution for this is a little complex in the CSV exporter, due to the way
the Members details …
> Allow CSV export to go ahead when there are data issues with the members API

- CHANGELOG.md
- app/controllers/all/completed/projects_controller.rb
- app/controllers/all/in_progress/projects_controller.rb
- app/controllers/user/projects_controller.rb
- spec/features/projects/users_can_view_a_list_of_assigned_projects_spec.rb
We recently moved the `conversion_date` attribute onto Conversion::Project, and as a result any Project index pages using plain Project objects lost the expected date ordering.
Make all the project index pages use Conversion::Project, and add a test to make sure the date ordering is working as expected.
TODO: Figure out how these controllers will work when we have more than one project type.
> Enforce date ordering in Project index pages

- CHANGELOG.md
- app/controllers/all/opening/projects_controller.rb
- app/views/shared/_sub_navigation_item.html.erb
- config/routes.rb
- spec/features/projects/revised_conversion_date/viewing_projects_with_a_revised_converison_date_spec.rb
- spec/features/users_can_view_a_table_of_project_openers_spec.rb
- spec/requests/all/opening/projects_controller_spec.rb
Previously we used a default set of parameters in the routes file, but
this was only called once during Rails initialisation (we think) and so
was locked to a single month the application was deplyed.
Here we switch to a redirect based on the current month and year, me
moved the path helpers as we don't actually use the specific month and
year paths excpet from the redirect.
https://trello.com/c/sCpYdjeR
> Fix the default opening date routes

- .github/workflows/build-and-push-image.yml
- Previously this was set to the branch name which meant the az cli command to restart the container did not do anything because the image tag had not changed. Changing this to be the 'SHA' means that az cli will consider it a changed image for every deployment
> Replace branch name with SHA reference

- .github/workflows/build-and-push-image.yml
the `RAILS_ENV` needs to be set to `development` during the build. This is then overridden at runtime by the appropriate value based on the environment it is deployed into.
> Always use 'development' build flag

- CHANGELOG.md
- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/policies/user_policy.rb
- app/views/users/_users_table.html.erb
- app/views/users/set_team.html.erb
- config/locales/user.en.yml
- config/routes.rb
- spec/features/users/user_with_no_team_spec.rb
- spec/models/user_spec.rb
We have added team to users and have a bunch that we do not know the
value for now.
Here we ask users who have `team: nil` to provide it when their
session is created.
We also updated the team names in line with the RSD content guidelines.
https://trello.com/c/VxmMww9q
> Collect a users team if they do not have one

- CHANGELOG.md
- app/services/by_user_project_fetcher_service.rb
- app/views/all/users/projects/_users_table.html.erb
- spec/features/projects/users/users_can_view_projects_by_user_spec.rb
- spec/services/by_user_project_fetcher_service_spec.rb
When viewing all users, it is helpful to know which team a user is
associtated with.
To achieve this we had to update the ByUserProjectFetcherService to
include `team`.
https://trello.com/c/geXJm8K9
> Show team on by users view

- CHANGELOG.md
- app/controllers/team/projects_controller.rb
- app/policies/navigation_policy.rb
- app/policies/project_policy.rb
- app/services/by_team_project_fetcher_service.rb
- app/views/shared/navigation/_dfe_header_navigation.html.erb
- app/views/shared/navigation/_team_projects_primary_navigation.html.erb
- config/locales/project.en.yml
- spec/features/projects/users_can_view_a_list_of_regional_casework_services_projects_spec.rb
- spec/features/users_can_assign_a_user_to_a_project_spec.rb
- spec/policies/navigation_policy_spec.rb
- spec/policies/project_policy_spec.rb
- spec/services/by_team_project_fetcher_service_spec.rb
Scope the Team projects views to reflect the current user's team.
If the user's team is `regional_casework_services`, then they see all projects
there the Project.team is `regional_casework_services`
If the user's team is a region, then they see all projects where Project.region
is the same as the user's team (note that it is the project's REGION).
Change the navigation within the Team projects view so that only team_leader
users can view the Unassigned projects view.
All users with a role and a team can now view the Team projects views.
> Dynamic team projects view

- app/controllers/users_controller.rb
- app/mailers/user_account_mailer.rb
- spec/mailers/user_account_mailer_spec.rb
- spec/requests/users_controller_spec.rb
We currently manually send each new users an email when we onboard them.
This work simply automates this process for a consistent experience for
our users.
https://trello.com/c/tRZMvGXn
> Send an email when a new account is added

- CHANGELOG.md
- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/users/_users_sub_navigation.html.erb
- app/views/users/edit.html.erb
- app/views/users/index_active.html.erb
- app/views/users/index_inactive.html.erb
- config/locales/en.yml
- config/locales/user.en.yml
- config/routes.rb
- db/migrate/20230710091311_add_deactivated_at_to_user.rb
- db/schema.rb
- spec/factories/user_factory.rb
- spec/features/users/users_can_manage_user_accounts_spec.rb
- spec/models/user_spec.rb
- spec/requests/sign_in_spec.rb
This works allows users to be deactivated. A deactivated user:
- cannot access the application
- does not appear in list of users when assgining projects
- may have done these things in the past
We store the `deactivated_at` date and time and wrap it with a `active` method so we can treat it like a boolean in the interface.
https://trello.com/c/g6tlmXfG
> Users can be deactivated and reactivated

- db/migrate/20230712100251_rename_user_deactivated_at_column.rb
- db/schema.rb
In an earlier commit we accidentally committed a migration with an incorrect column name. Add another migration to fix this.
https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/859
> Rename User.deactived_at to User.deactivated_at

- app/services/establishments_fetcher_service.rb
- app/services/trusts_fetcher_service.rb
- spec/services/establishments_fetcher_service_spec.rb
- spec/services/trusts_fetcher_service_spec.rb
We've seen some errors in production that seem to relate to not handling errors from the Academies API (timeouts are likely). This work should surface the errror and allow recovery and also log to Application Insights.
https://trello.com/c/jl2qwQTx
> Raise error in establishment and trust fetchers

- CHANGELOG.md
- config/initializers/pagy.rb
I am not sure why we went with so few pagers, but we did.
Here we increase the number:
1 = 1 pager to the right of the start
4 = 4 pagers to the left of the current page
4 = 4 pagers to the right of the current page
1 = 1 pager to the left of the end
This gives us a total of 10 pagers on screen, as opposed to the 4 we
have now.
> Add more pagers

- CHANGELOG.md
- app/controllers/team/projects_controller.rb
- app/models/user.rb
- app/services/by_team_project_fetcher_service.rb
- app/views/projects/shared/_users_table.html.erb
- app/views/shared/navigation/_team_projects_primary_navigation.html.erb
- app/views/team/projects/by_user.html.erb
- app/views/team/projects/users.html.erb
- config/locales/en.yml
- config/locales/project.en.yml
- config/routes.rb
- spec/features/projects/team/users_can_view_others_users_in_their_team_spec.rb
- spec/models/user_spec.rb
- spec/services/by_team_project_fetcher_service_spec.rb
Add a "Users" page to the Team projects area, showing a list of all users on the current_user's team, with a list of their conversion project counts (ordered by user name).
The current_user can then click through to view a list of user's projects. This view reuses the table view from the Your projects area, as it is essentially the same data (projects assigned to a certain user).
> Add team projects by user view

- CHANGELOG.md
- app/controllers/all/in_progress/projects_controller.rb
- app/services/by_local_authority_project_fetcher_service.rb
- app/services/establishments_fetcher_service.rb
- app/services/trusts_fetcher_service.rb
- spec/services/establishments_fetcher_service_spec.rb
- spec/services/trusts_fetcher_service_spec.rb
- spec/support/academies_api_helpers.rb
Gah! back again.
We've been seeing errors due to the shoddy work in the two 'prefetching' objects (mine) when we added batch support we added some really bad code.
We also introduced an issue that is hard to pin down, it only happens when you load more projects than the pager is calling for, so 20 by default and 10 for the Your projects view. It has also proven pretty inconsitent, which we think is casued by the Academies API timing out and then the shoddy code not allowing a revcovery.
There appears to be an issue with the pager and the `in_batches` that both use offsets and we see the issue when these are working together - it's difficult to be sure though.
After much fiddling, this is the propsed short term solution. Essentially we have two prefetching methods, one for paged views and …
> Offer batch pre fetch and paged

- app/controllers/all/export/funding_agreement_letters/projects_controller.rb
- app/controllers/all/export/risk_protection_arrangement/projects_controller.rb
- app/services/projects_for_export_service.rb
- spec/factories/transfer/project_factory.rb
- spec/services/projects_for_export_service_spec.rb
Off the back of #869 we need to use the bacthed version of the prefetching when the projects are no paged.
To do this cleanly, we've encapsulated the business logic of which projects and the correct prefetching in an object clearly labelled for exporting - this sets a presedence that we have one way of prefetching for views and another for exports - which feels solid.
You'll noticed I keep including new api mocks - I am planning to try and unpick these across the test suite and ragionalise - but not here!
https://trello.com/c/h30FfOmP
> Used batched prefetcher for exports

- CHANGELOG.md
- app/controllers/users_controller.rb
- spec/requests/users_controller_spec.rb
When we added the UserAccountMailer we missed actually sending it, here
we fix that!
> Send the new user email

- app/controllers/all/export/risk_protection_arrangement/projects_controller.rb
- app/views/all/export/risk_protection_arrangement/projects/index.html.erb
- app/views/all/export/risk_protection_arrangement/projects/show.html.erb
- config/locales/export/risk_protection_arrangement_csv_export.en.yml
- config/locales/project.en.yml
- config/routes.rb
- spec/features/projects/export/risk_protection_arrangement/users_can_export_rpa_data_spec.rb
- spec/requests/all/export/risk_protection_arrangement/projects_controller_spec.rb
This work introduces a proposed way for users to navigate exports. Their needs a centred around the idea of projects that will 'open' in a given month.
The first view starts last month and then goes forward for a total of six months. Each month links to the opening list for that month, both confirmed and revised to allow validation of the project that will be in the export.
The export itself moves to it's own page where ther actual download is triggered, this gives us the opportunity to set expecations for the download process and potentially later, documentation about the contents of the file and its use.
All this is NOT linked in navigation just yet, whilst we are confident this is right enough, we want to see it with live data to really get a sense for how it feels. Once happy, we can …
> Basic RPA export UI

- CHANGELOG.md
- app/controllers/all/local_authorities/projects_controller.rb
- app/controllers/all/opening/projects_controller.rb
- app/controllers/team/opening/projects_controller.rb
- app/models/project.rb
- app/services/by_month_project_fetcher_service.rb
- app/services/establishments_fetcher_service.rb
- app/services/trusts_fetcher_service.rb
- app/views/shared/navigation/_team_projects_primary_navigation.html.erb
- app/views/team/opening/projects/confirmed.html.erb
- app/views/team/opening/projects/revised.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/models/project_spec.rb
- spec/requests/all/opening/projects_controller_spec.rb
- spec/requests/team/opening/projects_controller_spec.rb
- spec/services/by_month_project_fetcher_service_spec.rb
Add a tab for Project openers to the Teams view. 
This tab is split into two pages - confirmed openers for a given month by team, and revised openers for a given month by team.
These pages closely replicate the existing Openers pages, with the only difference that they are filtered by the current_user's team.
> Add confirmed and revised project openers views, filtered by team

- app/models/user.rb
- spec/models/user_spec.rb
We had users struggling to update their team because their email address
was in capitals and so their User was not considered valid.
https://trello.com/c/xpYq3w8O
> User email validation is case insensitive

- CHANGELOG.md
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/app-content.scss
- app/views/layouts/application.html.erb
This change adjusts line lengths within the application to approximately 75 characters. It comes in response to the expansion of the app's width from 1024px to 1200px. By constraining the line lengths, the update ensures optimal readability and consistency across the wider layout.
The class is adapted from the Design System documentation app. Adaptations include limitations to checkbox label and detail component texts to ensure consistency with the 1200px app layout.
Go to tasks views from within the task list.
> Limit line lengths to 75 characters in 1200px app

- CHANGELOG.md
- app/services/academies_api_pre_fetcher_service.rb
- app/services/by_month_project_fetcher_service.rb
- app/services/by_team_project_fetcher_service.rb
- spec/features/users_can_assign_a_user_to_a_project_spec.rb
- spec/requests/team/opening/projects_controller_spec.rb
- spec/services/academies_api_pre_fetcher_service_spec.rb
- spec/services/by_month_project_fetcher_service_spec.rb
Our approach to batch fetching from the Academies API to speed up the application has grown organically, this has caused us some problems with various things including eager loading and paging.
This work sets out to resolve this by offering a single object that takes care of it all with a simple method call.
Because this object can be passed ActiveRecord results with eager loading, we have to disbale Bullet inside it to prevent false positives caused by bullet thinking we are not using the the eager loaded association, when we are just passing them on to what does use them.
We continue with the idea of 'dependancy injection' and allow the pre fetching to be diisabled to allow testing of any class that utilising pre fetching without having to deal with the pre fetching as it can make …
> Academies api pre fetcher

- CHANGELOG.md
- app/controllers/conversions/projects_controller.rb
- app/forms/conversion/create_project_form.rb
- app/models/conversion/project.rb
- app/views/conversions/projects/new.html.erb
- app/views/project_information/show/_information_list.erb
- config/locales/conversion_project.en.yml
- config/locales/project.en.yml
- db/migrate/20230720145221_add2ri_to_projects.rb
- db/schema.rb
- spec/factories/conversion/create_project_form_factory.rb
- spec/features/project_information/users_can_view_project_details_spec.rb
- spec/features/users_can_create_conversion_projects_spec.rb
- spec/models/conversion/project_spec.rb
- spec/requests/conversions/projects_controller_spec.rb
Add a new question to the create Conversion project form to indicate if a school is converting because it has received two "requires improvement" ratings. This question is mandatory for conversion projects.
> Add "2 Requires improvement" (2RI) to Conversion Projects

- CHANGELOG.md
- app/models/conversion/project.rb
- app/views/all/opening/projects/_confirmed_table.html.erb
- app/views/all/opening/projects/_revised_table.html.erb
- config/locales/project.en.yml
- spec/all_projects/by_month/users_can_view_confrimed_projects_spec.rb
- spec/models/conversion/project_spec.rb
- spec/requests/all/opening/projects_controller_spec.rb
- spec/team_projects/by_month/users_can_view_confrimed_projects_spec.rb
We no longer want to support the concept of voluntary or sponsored conversions,
instead we hold the actual attributes of a project that would lead to these
terms.
This work removes the 'route' column from the opening table on both all projects
and team projects and adds 'academy order type'.
We leave the locales and various other bits of code as we cannot remove it all until no views are using 'route'.
https://trello.com/c/BRwrYkYD
> Replace route on the opening lists

- CHANGELOG.md
- app/controllers/all/regions/projects_controller.rb
- app/controllers/team/projects_controller.rb
- app/policies/project_policy.rb
- app/services/by_region_project_fetcher_service.rb
- app/views/projects/shared/_handed_over_table.html.erb
- app/views/shared/navigation/_team_projects_primary_navigation.html.erb
- app/views/team/projects/handed_over.html.erb
- config/locales/en.yml
- config/locales/project.en.yml
- config/routes.rb
- spec/features/projects/team/users_in_regional_teams_can_view_handed_over_projects_spec.rb
- spec/policies/project_policy_spec.rb
- spec/services/by_region_project_fetcher_service_spec.rb
This work adds in a `Handed over` view to the Team projects area which displays the projects that have been handed over to the Regional casework services team.
Each regional team can view this `Handed over` view and will see all their handed over regional projects.
The view is restricted to the Regional casework services team who won't see the `Handed over` tab.
> Add handed over view to team projects

- CHANGELOG.md
- app/views/all/trusts/projects/show.html.erb
Pager was appearing at the top of the page due to being inside the `table` element.
> Move pager out of table element

- CHANGELOG.md
- app/controllers/projects_controller.rb
- app/controllers/transfers/projects_controller.rb
- app/forms/conversion/create_project_form.rb
- app/forms/create_project_form.rb
- app/forms/transfer/create_project_form.rb
- app/views/transfers/projects/new.html.erb
- config/locales/transfer_project.en.yml
- config/routes.rb
- spec/factories/conversion/create_project_form_factory.rb
- spec/factories/transfer/create_project_form_factory.rb
- spec/features/transfers/users_can_create_a_transfer_project_spec.rb
- spec/forms/conversion/create_project_form_spec.rb
- spec/forms/transfer/create_project_form_spec.rb
- spec/requests/transfers/projects_controller_spec.rb
**Content TBC**
Add a very basic create form for Transfer projects. Once the project is created, the user is redirected to a blank `show` page. Once we have created Tasks for Transfer projects the user will be redirected to the Tasks page, but this is out of scope for this ticket.
This PR also contains some refactoring to support the creation of two project types.
> Users could add a Transfer project

- CHANGELOG.md
- app/views/projects/shared/_new_table.html.erb
- app/views/projects/shared/_with_academy_urn_table.html.erb
- config/initializers/date_formats.rb
- spec/features/projects/service_support/users_can_view_a_list_of_new_projects_spec.rb
- spec/features/projects/service_support/users_can_view_a_list_of_projects_with_academy_urn_spec.rb
This commit updates the columns shown on the service support specific
project views;
We remove the route because it is not a concept we want to support any
longer.
We remove school type and phase as  whilst they are useful during the
conversion academy URN journey, they are not needed here.
Overall this user journey is blocked by not having 'unpublished' GIAS
data anyway and until that is resolved, we can do no more.
https://trello.com/c/9CYkHIlF
> Update service support project views

- CHANGELOG.md
- app/views/conversions/external_contacts/index.html.erb
- app/views/conversions/internal_contacts/index.html.erb
- app/views/conversions/notes/index.html.erb
- app/views/conversions/project_information/show.html.erb
- app/views/conversions/tasks/index.html.erb
- app/views/member_of_parliament/show.html.erb
- app/views/projects/shared/_project_actions.html.erb
- app/views/shared/projects/_actions.html.erb
- app/views/shared/projects/_sub_navigation.html.erb
- app/views/shared/projects/_task_list.html.erb
- app/views/transfers/tasks/index.html.erb
Some small frontend tweaks - mostly making sure eveything is laid out properly.
This does put the task list in a two-thirds column and fixes an issue with some of the project sub views not being rendered at the correct width.
> Frontend updates

- CHANGELOG.md
- app/controllers/projects_complete_controller.rb
- app/models/conversion/project.rb
- app/models/project.rb
- app/models/transfer/project.rb
- app/views/shared/project_information/_project_details.html.erb
- app/views/transfers/tasks/index.html.erb
- config/locales/conversion_project.en.yml
- config/locales/project.en.yml
- config/locales/project_information.en.yml
- config/locales/transfer_project.en.yml
- spec/features/conversions/users_can_complete_a_conversion_project_spec.rb
- spec/features/transfers/users_can_complete_a_transfer_project_spec.rb
- spec/models/project_spec.rb
A Transfer project can be completed if its transfer date is confirmed and in the past. 
This PR includes some refactoring to allow for Conversion and Transfer projects to be completed under different sets of conditions.
> Users can complete a Transfer project

- CHANGELOG.md
- app/forms/conversion/task/receive_grant_payment_certificate_task_form.rb
- app/views/conversions/tasks/receive_grant_payment_certificate/edit.html.erb
- config/locales/conversion/tasks/receive_grant_payment_certificate.en.yml
- db/migrate/20230731150711_remove_update_sheet_action_from_grant_payment_task.rb
- db/schema.rb
- spec/accessibility/projects_spec.rb
- spec/features/conversions/users_can_complete_a_conversion_project_spec.rb
- spec/models/conversion/project_spec.rb
Remove the third checkbox (`update_sheet`) from this task, and make the guidance on the first checkbox more explicit.
> Amendments to "Receive grant payment certificate" task

- CHANGELOG.md
- app/views/conversions/external_contacts/index.html.erb
- app/views/conversions/internal_contacts/index.html.erb
- app/views/conversions/notes/index.html.erb
- app/views/conversions/project_information/show.html.erb
- app/views/conversions/tasks/index.html.erb
The back link is hard wired to a specific view which is not what users
expect in all cases.
As we have the back button and primary nav, we are removing this to
prevent confusion but deffering a long term solution.
https://trello.com/c/L7cFxs16
> Remove back link from conversion project show

- CHANGELOG.md
- app/views/sessions/new.html.erb
This work adds more content to the sign in page so that it functions like a service start page.
> Improve content on sign in page

- CHANGELOG.md
- app/controllers/transfers/projects_controller.rb
- app/forms/conversion/create_project_form.rb
- app/forms/create_project_form.rb
- app/forms/transfer/create_project_form.rb
- app/views/conversions/projects/new.html.erb
- app/views/transfers/projects/new.html.erb
- config/locales/transfer_project.en.yml
- spec/factories/transfer/create_project_form_factory.rb
- spec/features/transfers/users_can_create_a_transfer_project_spec.rb
- spec/forms/conversion/create_project_form_spec.rb
- spec/forms/transfer/create_project_form_spec.rb
We went ahead and added transfer behaviour before we had fully designed some aspects of it (and that is okay!!)
This work brings the new transfer project form up to scratch, using the supplied design for layout and content.
We tweaked a few things in the spririt of 'leave it better'.
https://trello.com/c/9xjVW2bS
> Update transfer create form

- CHANGELOG.md
- config/locales/project_information.en.yml
This corrects `Addresss` to `Address` in the project information page
> Fixing spelling error on project information page

- CHANGELOG.md
- app/models/contact.rb
- spec/features/users_can_manage_contacts_spec.rb
Change the "Trust" contact category to be "Incoming trust", and add new category "Outgoing trust".
This does not require a database migration, as the category is stored on the Contact in the database as the integer value, not the label.
> Update Contact category "Trust" to be "Incoming trust"

- CHANGELOG.md
- app/views/conversions/external_contacts/index.html.erb
- app/views/conversions/project_information/_local_authority_details.html.erb
- app/views/conversions/project_information/_side_navigation.html.erb
- spec/features/project_information/users_can_view_local_authority_details_spec.rb
- spec/requests/contacts_controller_spec.rb
Move the Director of Child Services contact information into the External contacts area.
> Show the Director of child services in the External contacts area

- app/forms/conversion/task/sponsored_support_grant_task_form.rb
- app/models/conversion/tasks_data.rb
- app/views/conversions/tasks/sponsored_support_grant/edit.html.erb
- db/migrate/20230807091931_correct_support_grant_types.rb
- db/schema.rb
- spec/features/conversions/users_can_complete_conversion_tasks_spec.rb
For the sponsored support grant type we save the value with hyphens, this is a bit at odds with Rails conventions.
We also do not validate the strings stored, which leaves us open to potential injections.
Here we fix both by making the attribute an enum so only the three acceptable values can be stored and those values are underscored so things work as expected when pulling the values out.
https://trello.com/c/k1DjbrHd
> Grant type options

- app/views/conversions/projects/new.html.erb
- config/locales/conversion_project.en.yml
- spec/features/users_can_create_conversion_projects_spec.rb
The locales here are a bit of a mix between hardcoded and form builder
convention.
We've done what we can to try and make things better and show the new
hint for the school sharepoint link.
https://trello.com/c/2wiSEvg0
> Update new conversion project form hint

- CHANGELOG.md
- config/locales/conversion/tasks/conversion_grant.en.yml
- config/locales/conversion/tasks/sponsored_support_grant.en.yml
RCS told us the email address for the grants team has changed. This work corrects email address we use to the new one.
It affects 2 tasks. `Process the conversion grant` and `Confirm and process the sponsored support grant`.
> Change grants team email address to their new one

- CHANGELOG.md
- app/views/pages/accessibility.erb
Accessibility statement has been updated to include the problem with Church of England abbreviations in school names pulled in from Get Information About Schools.
> Adds C of E/cofe issue to accessibility statement

- CHANGELOG.md
- app/forms/transfer/task/stakeholder_kick_off_task_form.rb
- app/views/transfers/tasks/stakeholder_kick_off/edit.html.erb
- config/locales/transfer/tasks/stakeholder_kick_off.en.yml
- db/migrate/20230807151713_add_stakeholder_kickoff_attributes_to_transfers.rb
- db/schema.rb
- spec/forms/transfer/tasks/stakeholder_kick_off_task_form_spec.rb
Add the remaining actions to this task. This is much like the Stakeholder Kick- off task for Conversions with slightly different wording.
> Add more actions to the Stakeholder Kick-off task for Transfers

- CHANGELOG.md
- app/controllers/sessions_controller.rb
- app/helpers/user_helper.rb
- app/views/users/_users_table.html.erb
- config/locales/user.en.yml
- db/migrate/20230804140435_add_last_session_column_to_users.rb
- db/schema.rb
- spec/features/users/users_can_manage_user_accounts_spec.rb
- spec/helpers/user_helper_spec.rb
- spec/models/user_spec.rb
- spec/requests/sign_in_spec.rb
When a user logs in (creates a session), store a DateTime in the `latest_session` column on the user. This value will update each time a user creates a session.
> Store when a user last created a session

- CHANGELOG.md
- app/controllers/all/in_progress/projects_controller.rb
- app/views/all/local_authorities/projects/show.html.erb
- app/views/all/regions/projects/show.html.erb
- app/views/all/trusts/projects/show.html.erb
- app/views/projects/shared/_handed_over_table.html.erb
- app/views/projects/shared/_in_progress_table.html.erb
- app/views/projects/shared/_unassigned_table.html.erb
- app/views/your/projects/_table.html.erb
- config/locales/project.en.yml
On the back of adding `transfer` projects to the service, we need our table views to be able to reflect the two project types they will be displaying.
There was a slight overlap with PR https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/946, so the work around making the `conversion_date` and associated controllers step away from being solely conversion projects now happens within that work. 
This PR builds on that by adding in a new table column `Type` to display whether it is a conversion project or transfer prioject and formats the `conversion or transfer date` using the `significant_date` format.
This PR also updates the table view by removing the `View project` column and adds in the project link to the school name
> Update all table views

- CHANGELOG.md
- app/forms/transfer/task/articles_of_association_task_form.rb
- app/models/transfer/task_list.rb
- app/views/transfers/tasks/articles_of_association/edit.html.erb
- config/locales/transfer/task_list.en.yml
- config/locales/transfer/tasks/articles_of_association.en.yml
- db/migrate/20230809134700_add_transfer_articles_of_association_task_attributes.rb
- db/schema.rb
This task is much like the same one for Conversion projects except with slightly different wording.
> Add Articles of Association task to Transfer projects

- CHANGELOG.md
- app/controllers/your/projects_controller.rb
- app/forms/conversion/task/conditions_met_task_form.rb
- app/forms/transfer/task/conditions_met_task_form.rb
- app/models/conversion/project.rb
- app/models/transfer/project.rb
- app/models/transfer/task_list.rb
- app/presenters/export/csv/project_presenter.rb
- app/services/by_month_project_fetcher_service.rb
- app/views/transfers/tasks/conditions_met/edit.html.erb
- app/views/transfers/tasks/shared/_back_link.erb
- config/locales/transfer/task_list.en.yml
- config/locales/transfer/tasks/conditions_met.en.yml
- db/migrate/20230809083044_add_all_conditions_met_to_project.rb
- db/schema.rb
- spec/accessibility/projects_spec.rb
- spec/factories/conversion/project_factory.rb
- spec/features/conversions/users_can_complete_a_conversion_project_spec.rb
- spec/features/conversions/users_can_complete_conversion_tasks_spec.rb
- spec/features/transfers/users_can_complete_transfer_tasks_spec.rb
- spec/features/users_can_view_a_table_of_project_openers_spec.rb
- spec/helpers/project_helper_spec.rb
- spec/models/conversion/project_spec.rb
- spec/models/project_spec.rb
- spec/models/transfer/project_spec.rb
- spec/presenters/export/csv/project_presenter_spec.rb
Previously, the `all_conditions_met?` value for a Conversion::Project was determined by its
TasksData, on the `conditions_met_confirm_all_conditions_met` task.
Move this value up to be a native attribute on Project. This reduces a lot of
eager loading and makes the Project model simpler, although it does mean that
the "Conditions met" task becomes another "special case" task.
The All conditions met? task for Transfers is identical to the same task for Conversions, including the same
content (with references to Conversions changed to Transfers).
> Add All conditions met? for Transfers

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- app/components/notification_banner.html.erb
- app/components/notification_banner.rb
- app/helpers/notification_helper.rb
- app/views/layouts/application.html.erb
- config/locales/conversion_project.en.yml
- spec/helpers/notification_helper_spec.rb
The flash banner should be in its own two-thirds layout.
The banner should be styled as per the GOV.uk guidelines. The main message
must be an h3, and any other text in a paragraph.
We have added a helper to parse the flash messages correctly. If a message only
has one line (no HTML), the helper encapsulates the message in an h3 tag. If
a message contains HTML, we output the HTML in its entirety. 
We determine if a message has HTML by parsing it with Nokogiri and counting
the number of node children. A non-zero number means there is HTML present.
We will have to
ensure any HTML added to flash messages via local files has the correct HTML
format.
We only currently have one multi-line flash message, and the HTML for this has
been updated in the locale file. …
> Bring the flash messages inline with GOV.uk styles

- CHANGELOG.md
- app/models/statistics/project_statistics.rb
- app/views/all/statistics/statistics/index.html.erb
- spec/models/statistics/project_statistics_spec.rb
Now that we have transfer projects within the service, we want to be able to differentiate between Conversion projects and Transfer projects within our statistics page.
> Add transfer project statistics to statistics page

- CHANGELOG.md
- app/views/projects/shared/_users_table.html.erb
These counts were already added in the controller, we just needed to show them in the view.
> Add Transfer projects count to Team > By user table

- CHANGELOG.md
- app/views/conversions/shared/_project_summary.html.erb
- app/views/transfers/shared/_project_summary.html.erb
The banner is in its own two-thirds div, so don't encapsulate it in another one!
> (Fix) Do not constrain the banner to a two-thirds section

- app/views/shared/navigation/_all_projects_primary_navigation.html.erb
- app/views/shared/navigation/_team_projects_primary_navigation.html.erb
This namepsace should be "by-month". This means the currect navigation link remains selected in the By month section.
> (Fix) Correct navigation namespace in By month section

- config/locales/note.en.yml
This should be "role" not "title"
> (Fix) Correct error message for "role" field on contacts

- CHANGELOG.md
- app/views/shared/_side_navigation_item.html.erb
- app/views/shared/projects/_task_list.html.erb
Add jump links to the task sections for both Transfer and Conversion task lists.
> Add jump to section to both task lists

- CHANGELOG.md
- app/forms/transfer/create_project_form.rb
- config/locales/project.en.yml
- spec/forms/transfer/create_project_form_spec.rb
A transfers incoming trust should not be the same as its outgoing trust.
This work sets a validation to check that these UKPRNs do not match, and if they do to throw an error
> Validate that a transfers incoming trust is not the same as its outgoing trust

- app/views/layouts/application.html.erb
I really wanted to add a test for this but I can't figure out how to mock out `content_for?` in a feature spec!
> (Fix) Supply a default page title if none is set

- app/views/conversions/tasks/index.html.erb
- app/views/projects/show/_complete.html.erb
- app/views/shared/projects/_task_list.html.erb
- app/views/transfers/tasks/index.html.erb
After adding the jump links to the task list, the "Complete project" button and info was out of alignment with the task list. Put it back into alignment.
> (Fix) Move the "complete project" content into alignment with task list

- CHANGELOG.md
- app/models/statistics/project_statistics.rb
- app/views/all/statistics/statistics/index.html.erb
- spec/models/statistics/project_statistics_spec.rb
This info is needed every month for reporting purposes. Count the total, conversions and transfrs for the current month.
> Add "new projects this month" to Statistics

- CHANGELOG.md
- app/forms/conversion/task/main_contact_task_form.rb
- app/forms/transfer/task/main_contact_task_form.rb
- app/models/conversion/task_list.rb
- app/models/project.rb
- app/models/transfer/task_list.rb
- app/views/conversions/tasks/main_contact/edit.html.erb
- app/views/external_contacts/_contact_group.html.erb
- app/views/transfers/tasks/main_contact/edit.html.erb
- config/locales/contact.en.yml
- config/locales/conversion/tasks/main_contact.en.yml
- config/locales/transfer/tasks/main_contact.en.yml
- db/migrate/20230830095034_add_main_contact_to_projects.rb
- db/schema.rb
- spec/features/conversions/users_can_complete_conversion_tasks_spec.rb
- spec/features/conversions/users_can_select_a_funding_agreement_letter_contact_spec.rb
- spec/features/conversions/users_can_select_a_main_contact_spec.rb
- spec/features/users_can_manage_contacts_spec.rb
- spec/forms/transfer/tasks/main_contact_task_form_spec.rb
- spec/models/conversion/task_list_spec.rb
- spec/models/project_spec.rb
- spec/spec_helper.rb
Remove the "Funding agreement letters contact" task from Conversion projects. 
Add a new "Main contact" task to both Conversions and Transfers. This task acts much like the old Funding agreement letters contact, except it stores the contact ID on the `main_contact_id` association on the project.
The content is TBC.
> Collect the "main contact" for a project

- app/views/external_contacts/_contact_group.html.erb
- config/locales/contact.en.yml
Move the signifier showing this contact is the project's "main contact" into the summary table.
> Move the "main contact" signifier

- .github/workflows/checks.yml
- Dockerfile.checks
- docker-compose.checks.yml
We've moved the installation of firefix and geckodriver into the base
stage but made the installation conditional based on the RAILS_ENV. This
is a common pattern in the Dockerfile.
The result is that we should see the install cached by Docker saving
lots of time in CI.
We can also drop the 'test' stage as all it now does is copies the test
files into the image - we can live with that overhead being in the
production build.
Now the entire build is controlled by the RAILS_ENV build argument.
> Improve the checks Dockerfile

- script/check_accessibility
- script/lint_and_format
- script/specs
- script/specs_and_coverage
- script/static_analysis
For scripts that check something and fail, we need to bubble the errors
up the script, `set -e` does that.
> Bubble errors up

- .github/workflows/checks.yml
- sonar-project.properties
We want to try and pass the coverage report to Sonarcloud and that will
require running it within our workflow.
This is the basic setup for that.
> Add Sonarcloud to checks workflow

- .github/workflows/continuous-integration-terraform.yml
- The 'validate terraform docs' step will fail if there is a diff in the source so this needs to happen before the 'remove azure backend' step.
> Shift priority for tfdocs

- .github/workflows/checks.yml
The workflows depending on the scripts feels a bit off, whilst it keeps
things in one place, the link is not obvious and as the lint and format
script is the only one we can use in the ci environment, it feels better
to keep the workflows consistent by not running scripts.
> Remove script from workflow

- docker-compose.checks.yml
- Using a named volume mount allows us to persist the files between container runs and extract the files with an ephemeral container
- After the /bin/rspec test has finished and the container exits, you can manipulate the coverage report with other containers
- `docker run --rm -v test-ci-coverage-report:/source -v $PWD:/dest -w /source alpine cp -r . /dest/coverage/` can be used to download the coverage report onto the runner using a shim container
> Added named volume mount

- CHANGELOG.md
- app/forms/transfer/task/deed_of_novation_and_variation_task_form.rb
- app/forms/transfer/task/deed_termination_church_agreement_task_form.rb
- app/models/transfer/task_list.rb
- app/views/transfers/tasks/deed_of_novation_and_variation/edit.html.erb
- app/views/transfers/tasks/deed_termination_church_agreement/edit.html.erb
- app/views/transfers/tasks/stakeholder_kick_off/edit.html.erb
- config/locales/transfer/tasks/deed_of_novation_and_variation.en.yml
- config/locales/transfer/tasks/deed_termination_church_agreement.en.yml
- db/migrate/20230906134022_add_deed_termination_church_agreement_task_attributes.rb
- db/migrate/20230907085358_rename_task_action_on_deed_novation_variation.rb
- db/schema.rb
- spec/features/transfers/tasks/users_can_compelte_main_contact_spec.rb
- spec/features/transfers/tasks/users_can_compelte_stakeholder_kick_off_spec.rb
- spec/features/transfers/tasks/users_can_complete_all_conditions_met_spec.rb
- spec/features/transfers/users_can_complete_transfer_tasks_spec.rb
- spec/models/transfer/task_list_spec.rb
Adding in this task to the transfers task list.
Took some time to put in some coverage around the transfers task list based on what we have for conversions, just with a few tweaks - the test revealed some issues that we have taken care of here.
https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_sprints/taskboard/Complete%20conversions%20transfers%20and%20changes/Academies-and-Free-Schools-SIP/Complete%20sprint%2031?team=Complete%20conversions%20transfers%20and%20changes&workitem=138920
> Add Deeds of termination for CSA task to transfer task list

- CHANGELOG.md
- app/models/gias/establishment.rb
- db/migrate/20230907143938_add_gias_establishment.rb
- db/schema.rb
- spec/factories/gias/establishment_factory.rb
- spec/models/gias/establishment_spec.rb
We want to model GIAS establishment so we can:
- have access to the unopen academy data
- allow searching
- improve performance
- break dependancies on the Academies API
This is a very simple start to that work that creates the table,
indexes, model and factory.
We don't validate any attribute other than `urn` because we do not own
the data (we'll be importing it later) so we need to remain flexible for
the moment and validate the data set first.
If a urn was missing, the record would be unusable for us, so we do
validate that attribute.
We try to balannce following the attribute names from the dataset, which
is the GIAS data from a signed in user with all fields selected, whilst
keeping thing approachable.
We store attriubute name and 'code' as these may be useful later, we
already model …
> Add basic GIAS Establishment model

- CHANGELOG.md
- app/controllers/external_contacts_controller.rb
- app/forms/contact/create_project_contact_form.rb
- app/models/contact/project.rb
- app/models/project.rb
- app/views/external_contacts/_contact_group.html.erb
- app/views/external_contacts/edit.html.erb
- app/views/external_contacts/new.html.erb
- config/locales/contact.en.yml
- db/migrate/20230831160511_add_establishment_contact_id_to_projects.rb
- db/schema.rb
- spec/features/users_can_manage_contacts_spec.rb
- spec/forms/contact/contact_project_form_spec.rb
- spec/models/contact/project_contact_spec.rb
- spec/models/project_spec.rb
- spec/requests/contacts_controller_spec.rb
We want to be able to designate a Project Contact as the "main contact" for an establishment (school).
Users can now mark a contact as the "establishment main contact" when they create or edit an external contact.
ONLY "School" contacts can be establishment main contacts, not any other category of contact.
There can only be one establishment main contact per Project.
If a contact is the establishment main contact, this is shown on the External contacts list page.
> Allow a Project Contact to be selected as the main contact for an establishment

- .github/workflows/build-and-push-image.yml
We've proven the value of using the Github action cache to speed up
builds, here we add it to the deploy workflow.
> Update build workflow to use cache

- CHANGELOG.md
- app/controllers/external_contacts_controller.rb
- app/forms/contact/create_project_contact_form.rb
- app/models/contact/project.rb
- app/models/project.rb
- app/views/external_contacts/_contact_group.html.erb
- app/views/external_contacts/edit.html.erb
- app/views/external_contacts/new.html.erb
- config/locales/contact.en.yml
- db/migrate/20230907113049_add_incoming_trust_main_contact_id_to_projects.rb
- db/schema.rb
- spec/features/users_can_manage_contacts_spec.rb
- spec/forms/contact/contact_project_form_spec.rb
- spec/models/contact/project_contact_spec.rb
- spec/models/project_spec.rb
Allow users to select an external contact as the main contact for an incoming trust. This can be done on create and update.
The contact must be an Incoming trust contact - trying to select any other contact type as the incoming trust main contact will result in a validation error.
The contact will be marked as the incoming trust main contact on the External contacts list pagel
> Add main incoming trust contact

- app/services/project_search_service.rb
- db/migrate/20230914082600_add_ukprn_indexes.rb
- db/schema.rb
- doc/decisions/0020-keep-search-simple.md
- spec/services/project_search_service_spec.rb
We want to offer search to users. This work begins to lay the foundation on which we can build a valuable search.
We add a ProjectSearchService that takes a query, infers the best search to use and performs the search, returning matching projects.
Right now, we can only search on distinct identifiers, URN and UKPRN, but once we have completed the GIAS Establishement and Establishment group work, we'll be able to offer support for much more.
For now we know that searching by the identifiers is valuable and so laying a strong foundation is a great start, we won't offer this to users until we can offer a more complete search, so there is no UI here.
https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_sprints/taskboard/Complete%20conversions%20transfers%20and%20changes/Academie …
> Basic search service

- CHANGELOG.md
- config/locales/en.yml
- config/routes.rb
- spec/features/projects/users_can_view_a_list_of_regional_casework_services_projects_spec.rb
We decided that updating the path was not necessary.
https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_sprints/taskboard/Complete%20conversions%20transfers%20and%20changes/Academies-and-Free-Schools-SIP/Post%20Advisory%20Board/Sprint%2032?team=Complete%20conversions%20transfers%20and%20changes&workitem=138923
> Change Team projects to Your team projects

- CHANGELOG.md
- app/controllers/external_contacts_controller.rb
- app/forms/contact/create_project_contact_form.rb
- app/models/contact/project.rb
- app/models/project.rb
- app/views/external_contacts/_contact_group.html.erb
- app/views/external_contacts/edit.html.erb
- app/views/external_contacts/new.html.erb
- config/locales/contact.en.yml
- db/migrate/20230914102113_add_outgoing_trust_main_contact_id_to_projects.rb
- db/schema.rb
- spec/features/users_can_manage_contacts_spec.rb
- spec/forms/contact/contact_project_form_spec.rb
- spec/models/contact/project_contact_spec.rb
- spec/models/project_spec.rb
Add the ability to mark a contact as the main contact for an outgoing trust. This is pretty much identical to https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/1066
> Add outgoing trust main contact
