DFE-Digital/dfe-complete-conversions-transfers-and-changes

- .env.development
- .env.example
- .env.test
- .gitignore
- Gemfile
- Gemfile.lock
- config/initializers/dontenv.rb
Dotenv helps us manage environment variables accross our environmenets.
https://github.com/bkeepers/dotenv
> Install dotenv

- .eslintignore
- .eslintrc.json
- .prettierignore
- .prettierrc
- Rakefile
- app/assets/javascript/application.js
- config/environments/production.rb
- config/puma.rb
- doc/decisions/0001-record-architecture-decisions.md
- package.json
- spec/spec_helper.rb
- yarn.lock
More linting from the Rails template.
> More linting

- README.md
Update the README file so it contains project-relevant information rather than a generic template.
> Make the README more immediately useful

- LICENSE
- package.json
Following the convention for other DfE projects, add the MIT licence to this repository.
> Add LICENSE to project

- Gemfile
- Gemfile.lock
- README.md
- app/models/user.rb
- config/locales/en.yml
- db/migrate/20220620083237_create_users.rb
- db/schema.rb
- lib/tasks/users.rake
- spec/lib/users_spec.rb
We want to store basic information about users so we can idetify them once authorised.
This work introduces a basic model to store users and a simple task to add them on the command line.
> (98854) Feature: store users

- Dockerfile
- Gemfile
- Gemfile.lock
- app/models/project.rb
- app/models/section.rb
- app/models/task.rb
- app/services/task_list_creator.rb
- db/migrate/20220704100152_create_sections.rb
- db/migrate/20220704100256_create_tasks.rb
- db/schema.rb
- package.json
- script/all/test
- spec/fixtures/files/workflows/conversion.yml
- spec/models/project_spec.rb
- spec/models/section_spec.rb
- spec/models/task_spec.rb
- spec/rails_helper.rb
- spec/services/task_list_creator_spec.rb
- workflows/conversion.yml
- workflows/schemas/task-list.json
- yarn.lock
https://trello.com/c/4U1Nvl1E
Add models to represent the sections and tasks associated with the task list of a project.
Add `shoulda-matchers` Gem to use one-liner tests.
We want to generate task list sections and tasks based on a YAML definition. This will mean that we can easily change and update the task list, as well as introduce new definitions for other workflows.
This also adds the `ajv` package so that we can validate that our workflows fit the schema defined in `./workflows/schemas/task-list.json`
Add a service that creates task list sections and tasks when passed a project. This will be used at on project creation.
> (142) Create sections and tasks from workflow

- doc/decisions/0006-build-a-ruby-on-rails-monolith.md
This addresses a whitespace formatting change which Prettier makes when running `script/test`.
> Run prettier over the project

- doc/decisions/0010-use-trunk-based-development.md
Introduce an ADR for moving to [Trunk Based Development](https://trunkbaseddevelopment.com/).
> Add ADR for moving to Trunk Based Development

- CHANGELOG.md
- README.md
- doc/decisions/0010-use-trunk-based-development.md
- doc/getting-started.md
Makes minor changes to better break up getting started documentation into followable steps.
> Improvements to documentation

- CHANGELOG.md
- app/workflows/conversion.yml
Through user research we came to what we think is a fair order and
naming for this section.
This work simply updates the conversion workflow file to reflect these
changes.
As we have no production data, there is no concerns for existing
Projects not reflecting this change.
As we also decided that all tasks in this section will have the same set
of Actions for our MVP, we updated any that were not already the agreed
shape of:
- Received
- Cleared
- Saved in SharePoint
https://trello.com/c/A2kl1hfX
> (391) Update Clear legal documents section

- CHANGELOG.md
- app/workflows/conversion.yml
Adding all the task content and guidance for the clear legal documents section
> Update content for clear legal documents

- CHANGELOG.md
- app/workflows/conversion.yml
_All the content changes to add project kick-off tasks and actions to the build_
https://trello.com/c/XJGQVvlZ/274-users-can-complete-the-project-kick-off-tasks
> Project kick off guidance

- .env.example
- Gemfile
- Gemfile.lock
- README.md
- config/initializers/sentry.rb
- doc/decisions/0011-use-sentry-io-for-error-reporting-and-performance-monitoring.md
- docker-compose.ci.yml
- docker-compose.test.yml
- docker-compose.yml
All applications in RSD use sentry.io to montior errors so we will do the same. 
This works introduces the gems and adds some basic configuration to get things working.
https://trello.com/c/chTMm5wS
> (330) Chore: error reporting

- CHANGELOG.md
- app/controllers/notes_controller.rb
- app/policies/note_policy.rb
- app/views/notes/_notes.html.erb
- app/views/notes/confirm_destroy.html.erb
- app/views/notes/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/users_can_create_and_view_and_delete_notes_spec.rb
- spec/features/users_can_create_and_view_notes_spec.rb
- spec/requests/notes_controller_spec.rb
> (453) Notes can be formatted, edited and deleted

- README.md
- doc/users-accounts.md
- doc/workflow-files.md
Spliting things out and adding documentation.
https://trello.com/c/MmMDrIVA
> (545) Chore: readme house keeping

- README.md
Broken links to documentation.
> (Fix) readme links

- terraform/README.md
- terraform/container-apps-hosting.tf
* Bumps  azurerm container apps hosting module to version 0.1.2
* Also updates the source repo name, as it was changed upstream due to a typo
> Bump azurerm container apps hosting version 0.1.2

- app/views/assignments/assign_caseworker.html.erb
- app/views/assignments/assign_regional_delivery_officer.html.erb
- app/views/assignments/assign_team_leader.html.erb
Our CI is still not correctly failing if formatting has not been run. Run missing formatters to minimise unrelated changes being included in future work.
> Run code formatters

- .github/workflows/build-and-push-image-test.yml
* Use outputs rather than env for the release version
> Fix test build and push GitHub workflow

- .github/workflows/build-and-push-image-test.yml
* Adds 'runs-on' property
* Removes TEST_RELEASE_VERSION env as it's no longer required
> Fix development workflow runs-on

- .github/workflows/build-and-push-image-test.yml
* https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/compare/release-3...release-4
> Bump `test` deployment to release-4

- .github/workflows/build-and-push-image-test.yml
* Fix test workflow release version
> Fix test workflow release version

- .github/workflows/build-and-push-image-test.yml
> Test workflow fixes

- .github/workflows/build-and-push-image-test.yml
* Changes from `DEVELOPMENT` to `TEST` (copy pasta)
> Fix test workflow ACR_URL secret reference

- .github/workflows/build-and-push-image-test.yml
This resolves an uncaught yaml formatting issue.
> Run prettier

- CHANGELOG.md
- app/workflows/lists/conversion/sections/clear-legal-docs.yml
Update the various clear legal document tasks to incorporate the new subheadings action type, as per the prototype.
> Content update: Add subheadings to clear document tasks

- README.md
- doc/releases-and-deploys.md
We have seperate release and deployment processes, here we add some initial documentation around them.
Worth noting that although we talk about production here, we do not yet have that environment.
> (619) Document release and deployment process

- app/workflows/schemas/section.schema.json
- app/workflows/schemas/tasklist.schema.json
- doc/workflow-files.md
- doc/workflows/section-properties-tasks-task-properties-actions-action-properties-action-type.md
- doc/workflows/section-properties-tasks-task-properties-actions-action-properties-guidance-summary.md
- doc/workflows/section-properties-tasks-task-properties-actions-action-properties-guidance-text.md
- doc/workflows/section-properties-tasks-task-properties-actions-action-properties-hint.md
- doc/workflows/section-properties-tasks-task-properties-actions-action-properties-title.md
- doc/workflows/section-properties-tasks-task-properties-actions-action.md
- doc/workflows/section-properties-tasks-task-properties-guidance-summary.md
- doc/workflows/section-properties-tasks-task-properties-guidance-text.md
- doc/workflows/section-properties-tasks-task-properties-hint.md
- doc/workflows/section-properties-tasks-task-properties-optional.md
- doc/workflows/section-properties-tasks-task-properties-title.md
- doc/workflows/section-properties-tasks-task.md
- doc/workflows/section-properties-title.md
- doc/workflows/section.md
- doc/workflows/tasklist-properties-list-of-sections-section-filename.md
- doc/workflows/tasklist-properties-list-of-sections.md
- doc/workflows/tasklist.md
In line with the principles of keeping things as self-documenting as possible, update the inline documentation for the workflow file schemas and regenerate the documentation.
> Update workflow files documentation

- CHANGELOG.md
- app/workflows/lists/conversion/sections/clear-legal-docs.yml
- Clear legal documents becomes Clear and sign legal documents
- Add sign and seal actions to Supplemental funding agreement
> Changes to legal docs sections

- CHANGELOG.md
- app/workflows/lists/conversion/sections/close.yml
- Change title from "complete processing of conversion grant" to "Receive grant payment certificate"
- Update the content, hints and guidance
> Copy changes to conversion grant task

- CHANGELOG.md
- app/workflows/lists/conversion/sections/ready-for-opening.yml
> Content updates to Confirm opening date with the school.

- CHANGELOG.md
- app/workflows/lists/conversion/sections/close.yml
Also update content
Rename redact task to be Redact and send funding agreement documents
Update content on page
> Rename redact task to be Redact and send funding agreement documents

- CHANGELOG.md
- app/workflows/lists/conversion/sections/ready-for-opening.yml
Content changes for all conditions met
> Content changes for all conditions met

- CHANGELOG.md
- app/workflows/lists/conversion/sections/ready-for-opening.yml
- Rename task
- link to blank single worksheet
- update content
> Content changes to Complete and send the single worksheet

- CHANGELOG.md
- app/workflows/lists/conversion/sections/ready-for-opening.yml
- merge into single step
- update guidance to work for single step
> Content updates to Check the baseline

- CHANGELOG.md
- app/workflows/lists/conversion/sections/ready-for-opening.yml
- Complete the final checklist with external stakeholder becomes Confirm the
school has completed all actions. 
- Also update the copy for actions and guidance.
> Content updates to complete final checklist with external stakeholder

- doc/getting-started.md
- docker-compose.database-only.yml
- Fix typo in the docker compose file.
- Update documentation to match renamed file.
> Fix typo in docker compose file and update documentation

- .github/workflows/build-and-push-image-test.yml
> Deploy release 6 to test

- config/locales/contact.en.yml
- config/locales/en.yml
- config/locales/note.en.yml
- config/locales/project.en.yml
Ahead of adding more project locales, this splits them into their own files.
> Chore: re organise locale files

- .github/workflows/build-and-push-image-test.yml
* After pushing the image to ACR (Test environment), use az cli to update the containerapp's image tog
* This will update te running container to the most recent image pushed to ACR
> Update containerapp after deploying to ACR Test environment

- doc/decisions/0014-use-govuk-notify-to-send-emails.md
Add an ADR for the decision to use GOV.UK Notify
> (724) Add an ADR for the decision to use GOV.UK Notify

- CHANGELOG.md
- app/workflows/lists/conversion/sections/kickoff.yml
- Update content on Handover to regional delivery officer
- Update content on external stakeholder kick-off
- Update content on process conversion grant
Content checked with @SteveMilnes. 
Needs a dev to check code
> 723 project kick off changes to make in build before private beta

- CHANGELOG.md
- app/workflows/lists/conversion/sections/ready-for-opening.yml
- Task becomes Complete and send Single worksheet
- Check the baseline task guidance now refers to this project, not all projects
> 721 get ready for opening changes to make in build before private beta

- CHANGELOG.md
- app/workflows/lists/conversion/sections/clear-legal-docs.yml
Add tenancy at will section to the legal documents section
@SteveMilnes please can you check the copy?
Dev please can you check the code?
> Add tenancy at will task to legal documents section

- CHANGELOG.md
- app/workflows/lists/conversion/sections/clear-legal-docs.yml
Add 125 year lease option.
@SteveMilnes to check content please
Dev to make sure nothing is broken please
> Add 125 year lease question to clear legal docs

- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/terraform.tfvars.example
- terraform/variables.tf
* Creates a duplicate container, that will run Sidekiq
* Uses the same image and environment variables as the web container
> Add worker container in Azure container apps

- CHANGELOG.md
- app/workflows/lists/conversion/sections/ready-for-opening.yml
The single worksheet has been updated.
This swaps out the link to the previous version of the single worksheet for the updated one.
> (747) Update the link to the single worksheet

- config/environments/production.rb
Our infrastructure is in place so we can enable Sidekiq in production environments.
> (chore) Enable Sidekiq in production

- doc/environment-variables.md
- doc/user-accounts.md
Update the documentation around Azure Active Directory.
https://trello.com/c/r9yIjAlC
> (745) Chore: update user documentation

- CHANGELOG.md
- app/workflows/lists/conversion/sections/clear-legal-docs.yml
Tenacy at will adds action to explicitly track email received
> Tenacy at will adds action to explicitly track email received

- app/models/project.rb
- app/validators/date_in_the_future_validator.rb
- app/validators/date_in_the_past_validator.rb
- app/validators/first_day_of_month_validator.rb
- app/validators/urn_validator.rb
- spec/models/project_spec.rb
- spec/validators/date_in_the_furue_validator_spec.rb
- spec/validators/date_in_the_past_validator_spec.rb
- spec/validators/first_day_of_month_validator_spec.rb
- spec/validators/urn_validator_spec.rb
Ahead of work to introduce a form object for creating new projects, here we extract the validation from the Project model into validators that can be reused.
> (refactor) Extract and tidy validations

- README.md
Now we have a production environment, link to it.
> (chore) Add link to production

- .github/workflows/build-and-push-image-production.yml
* Adds a GitHub action to push a specified release/tag to Azure Container Registry within the Production environment
> Add image push GitHub action for Prod

- .github/workflows/build-and-push-image-test.yml
The Worker container now has the credentials which allows us to update the container within Azure Container Apps
This adds to the Test workflow (GitHub action), which logs in with these new credentials, and updates the container
> Update Worker container revision in ACA for Test

- .github/workflows/build-and-push-image-development.yml
* The Worker container now has the credentials which allows us to update the container within Azure Container Apps
* This adds to the Devlopment workflow (GitHub action), which logs in with these new credentials, and updates the container
> Update Worker container revision in ACA for Development

- .github/workflows/build-and-push-image-production.yml
* This updates the container app after the image has been pushed to ACR
> Add containerapp update to prod GitHub workflow

- README.md
We have added CDNs infront of each environment which means the urls have had to change.
> Update the urls to the environments

- CHANGELOG.md
- Gemfile.lock
- app/views/pages/accessibility.erb
- app/workflows/lists/conversion/voluntary/sections/after-opening.yml
- app/workflows/lists/conversion/voluntary/sections/clear-legal-docs.yml
- app/workflows/lists/conversion/voluntary/sections/kickoff.yml
- app/workflows/lists/conversion/voluntary/sections/ready-for-opening.yml
- config/locales/project.en.yml
Iterate content with things we learned from private beta and regional delivery officers
> 867 content updates for the voluntary conversions workflow

- .github/workflows/build-and-push-image-test.yml
- Write accessibility tests to run axe, the accessibility tool
- First version of a task list for involuntary conversions.
- Renamed the new project button to 'new voluntary conversion project' and added
the 'new involuntary conversion project' button
- Show the conversion route on projects
- Page load speed has been improved on pages that fetch project data from the
API. The project index page fetches establishments and trusts in bulk.
- The "Cancel" link on the new note page takes the user back to the task page if
the note is a task-level note.
- The text of the "Not applicable" checkboxes is bold to match the other task
checkboxes.
- The assign user select elements are enhanced with the accessible autocomplete
component.
- Iterate content with things we learned from private beta and …
> Deploy Release 9 to Test

- CHANGELOG.md
- app/workflows/lists/conversion/involuntary/sections/after-opening.yml
- app/workflows/lists/conversion/involuntary/sections/clear-legal-docs.yml
- app/workflows/lists/conversion/involuntary/sections/kickoff.yml
- app/workflows/lists/conversion/involuntary/sections/ready-for-opening.yml
- app/workflows/lists/conversion/voluntary/sections/clear-legal-docs.yml
Add line breaks into YML files so that markdown renders correctly.
> 926 fix markdown formatting

- terraform/README.md
- terraform/container-apps-hosting.tf
* Contains a fix which creates the TLS validation TXT records and ALIAS records
> Bump container app hosting module v0.10.2

- CHANGELOG.md
- app/workflows/lists/conversion/involuntary/sections/kickoff.yml
- app/workflows/lists/conversion/voluntary/sections/kickoff.yml
- Remove the check and confirm grant eligibility action on voluntary and involuntary routes
- Grant claim form action includes 'save in school's SharePoiont' so users know where to save it
> 899 conversion grant task copy changes

- CHANGELOG.md
- config/locales/en.yml
Fix typo on phase banner feeback becomes feedback
> Fix typo on phase banner feeback becomes feedback

- CHANGELOG.md
- app/workflows/lists/conversion/involuntary/sections/after-opening.yml
- app/workflows/lists/conversion/involuntary/sections/clear-legal-docs.yml
- app/workflows/lists/conversion/involuntary/sections/kickoff.yml
- app/workflows/lists/conversion/involuntary/sections/ready-for-opening.yml
- app/workflows/lists/conversion/voluntary/sections/after-opening.yml
- app/workflows/lists/conversion/voluntary/sections/clear-legal-docs.yml
- app/workflows/lists/conversion/voluntary/sections/kickoff.yml
- app/workflows/lists/conversion/voluntary/sections/ready-for-opening.yml
- config/locales/contact.en.yml
- config/locales/note.en.yml
- spec/features/users_can_create_and_view_and_delete_contacts_spec.rb
- Remove negative contractions in the service
- They've becomes they have
> 949 change negative contractions nt to nots have not do not etc

- CHANGELOG.md
- app/workflows/lists/conversion/involuntary/sections/kickoff.yml
- app/workflows/lists/conversion/voluntary/sections/kickoff.yml
- Send introductory emails iterations 
- Proforma action is to check it is saved not check doc for errors
- External stakeholder hint prompts to talk about common problems
- Frame LA guidance around what if you do not have the proforma
- Check LA date hint becomes the action as it is more explicit
> 898 copy changes to external stakeholder kick off task

- README.md
- doc/console-and-logs.md
> Document console and log access

- config/locales/conversion_project.en.yml
This had been fixed before but has been removed in a later commit.
73246cf4340d96c258ec0ad5217004d87f04c8d2
> Fix missing title string in locales

- doc/decisions/0015-use-terraform-for-infrastructure-as-code.md
> ADR: Use of Terraform

- CHANGELOG.md
- app/workflows/lists/conversion/involuntary/sections/ready-for-opening.yml
- app/workflows/lists/conversion/voluntary/sections/ready-for-opening.yml
Confirm opening date becomes 'Share the grant certificate and information about opening with the trust'
Involuntary journey
Voluntary journey
> 900 share the grant certificate and information about opening with the trust

- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/variables.tf
* Allows creating a DNS zone if required
> Enable DNS zone

- CHANGELOG.md
- app/workflows/lists/conversion/involuntary/sections/clear-legal-docs.yml
- app/workflows/lists/conversion/voluntary/sections/clear-legal-docs.yml
Updates to Tenancy at will guidance in voluntary and involuntary task list.
Content changes that explain the document is and should be rarely used. Links to form to contact policy team for advice if a Tenancy at will is needed.
https://trello.com/c/coz7WqIs/919-tenacy-at-will-can-only-be-used-in-exceptional-circumstances
> 919 tenacy at will exceptional circumstances guidance

- doc/infrastructure-and-terraform.md
Document the tfvar files, mostly so we can link to the wiki as some aspects of
this are sensitive.
> Document fetching tfvar files

- CHANGELOG.md
- app/views/layouts/application.html.erb
- app/views/pages/cookies.erb
- spec/features/users_can_view_static_pages_spec.rb
Add initial cookies page to the service
- create cookies page
- add link in footer
- add test for cookies page
- update CHANGELOG
> Add cookies page

- .github/workflows/build-and-push-image-production.yml
* The name of the job should be `production` rather than `test`
> Fix production workflow typo

- app/assets/stylesheets/application.scss
- app/views/conversion/voluntary/task_lists/tasks/articles_of_association.html.erb
- app/views/conversion/voluntary/task_lists/tasks/church_supplemental_agreement.html.erb
- app/views/conversion/voluntary/task_lists/tasks/deed_of_variation.html.erb
- app/views/conversion/voluntary/task_lists/tasks/land_questionnaire.html.erb
- app/views/conversion/voluntary/task_lists/tasks/land_registry.html.erb
- app/views/conversion/voluntary/task_lists/tasks/master_funding_agreement.html.erb
- app/views/conversion/voluntary/task_lists/tasks/supplemental_funding_agreement.html.erb
- app/views/conversion/voluntary/task_lists/tasks/tenancy_at_will.html.erb
- app/views/conversion/voluntary/task_lists/tasks/trust_modification_order.html.erb
- config/locales/task_lists/conversion/voluntary/commercial_transfer_agreement.en.yml
- config/locales/task_lists/conversion/voluntary/conditions_met.en.yml
- config/locales/task_lists/conversion/voluntary/conversion_grant.en.yml
- config/locales/task_lists/conversion/voluntary/handover.en.yml
- config/locales/task_lists/conversion/voluntary/land_questionnaire.en.yml
- config/locales/task_lists/conversion/voluntary/master_funding_agreement.en.yml
- config/locales/task_lists/conversion/voluntary/one_hundred_and_twenty_five_year_lease.en.yml
- config/locales/task_lists/conversion/voluntary/redact_and_send.en.yml
- config/locales/task_lists/conversion/voluntary/school_completed.en.yml
- config/locales/task_lists/conversion/voluntary/stakeholder_kick_off.en.yml
- config/locales/task_lists/conversion/voluntary/subleases.en.yml
- config/locales/task_lists/conversion/voluntary/tenancy_at_will.en.yml
- config/locales/task_lists/conversion/voluntary/trust_modification_order.en.yml
- config/locales/task_lists/conversion/voluntary/update_esfa.en.yml
- Revise handover task content
- Revise stakeholder kickoff task content
- Revise conversion grant task content
- Add style for a task section hint
- Revise land questionnaire task content
- Update styles for land registry task
- Update styles for supplemenatl funding agreement task
- Add styles to church supplemental agreement task
- Update master funding agreement task
- Add styles to articles of association task
- Add styles to deed of variation task
- Update style and content for trust modification task
- Revise content for 125 year lease task
- Revised subleases task content
- Update style and content for tenancy at will task
- Revise commercial transfer agreement task content
- Revise conditions met task content
- Revise school complete task content
- Revise content for redact and …
> Voluntary conversion task list revisions

- .github/workflows/build-and-push-image-production.yml
- Fixes broken Github workflow for production pipeline
> Corrected invalid reference to workflow job output

- CHANGELOG.md
- Added cookies page to describe how we use cookies
- Send notification to caseworker when assigned to a project
- Add a Content Security Policy
- Church supplemental guidance link now points to specific guidance rather than
general model documents page
- Remove check grant amount on voluntary and involuntary routes
- Grant claim form action now includes where the document should be saved
- Voluntary and Involuntary changes to external stakeholder kick-off
- Involuntary & voluntary redact and send agreements copy iterations
- They've becomes they have to follow GDS guidelines
- Remove negative contractions
- Confirm opening date with school becomes Share the grant certificate and
information about opening with the trust
- Tasks Continue button now states 'Save and return', tests updated …
> release-10

- package.json
- script/all/test-linting
- yarn.lock
This all relates to the old task list schema tooling and is now
redundant.
> Remove unused npm packages and runners

- app/controllers/home_controller.rb
This controller serves no purpose as we redirect the to a sign-in page
or the project list - there is no longer a 'home page'.
> Remove home controller

- doc/console-and-logs.md
A PIM on the Test environment on Azure doesn't need to be approved by another team member to be activated - you just need to create the PIM request.
> Update Test PIM instructions

- CHANGELOG.md
- config/locales/task_lists/conversion/voluntary/stakeholder_kick_off.en.yml
We somehow ended up with duplicate content for this action.
https://trello.com/c/c2fKODPv
> Update stakeholder kick off task action

- README.md
- doc/task-lists-and-tasks.md
> Document the task list and task models for developers

- .github/workflows/build-and-push-image-test.yml
Deploy Release 15 to the test environment
> Deploy Release 15 to the test environment

- .github/workflows/build-and-push-image-production.yml
> Deploy Release 15 to the production environment

- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/variables.tf
Add an additional path override for the Container health check.
> Set up Container Health probe

- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/variables.tf
Reverts DFE-Digital/dfe-complete-conversions-transfers-and-changes#528
> Revert "Set up Container Health probe"

- CHANGELOG.md
- config/locales/task_lists/conversion/voluntary/stakeholder_kick_off.en.yml
- Shorten title as hint text now mentions all the people to email
- Hint text now informs who to email
- Added a copy to deal with Diocese if relevant
- link text now includes the verb for choose an email template
> Send introductory emails update to handle diocese

- CHANGELOG.md
- app/models/conversion/involuntary/tasks/conditions_met.rb
- app/models/conversion/voluntary/tasks/conditions_met.rb
- app/views/conversions/involuntary/task_lists/tasks/conditions_met.html.erb
- app/views/conversions/voluntary/task_lists/tasks/conditions_met.html.erb
- config/locales/task_lists/conversion/involuntary/conditions_met.en.yml
- config/locales/task_lists/conversion/voluntary/conditions_met.en.yml
- db/migrate/20230302151008_change_all_conditions_met_task_name.rb
- db/schema.rb
- spec/factories/conversion/project_factory.rb
- spec/features/users_can_complete_conversion_involuntary_tasks_spec.rb
- spec/features/users_can_complete_conversion_voluntary_tasks_spec.rb
Update the Confirm all conditions met task content, and change the column name in the database to better reflect what this task & action is for.
> Update the Confirm all conditions have been met task

- CHANGELOG.md
- config/locales/task_lists/conversion/voluntary/articles_of_association.en.yml
Correcting link and guidance in voluntary articles of association task
> Update guidance link

- CHANGELOG.md
- config/locales/contact.en.yml
- config/locales/note.en.yml
- config/locales/project.en.yml
The success messages for the notification banners have been updated to keep the messaging consistent across the service, with other services and GDS.
> Update success messages for notification banners

- app/views/conversions/voluntary/projects/new.html.erb
- spec/features/users_can_create_voluntary_conversion_projects_spec.rb
In commit aaf0043684d6df9f05f58fce635b36d3589d9d8d we figured out a nicer way to test radio button inputs. Add the improvement to this set of tests to make them more readable.
> Fix: Improve the "Assigned to Regional caseworker team" tests

- CHANGELOG.md
- app/controllers/user/projects_controller.rb
- app/views/projects/shared/_in_progress_table.html.erb
- app/views/projects/shared/_unassigned_table.html.erb
- config/initializers/pagy.rb
- config/locales/project.en.yml
- spec/factories/conversion/project_factory.rb
A couple of tweaks to the new table views.
One adds an additional field to the unassigned view to help users.
Another that increases the number of items on table views.
> Update project tables

- CHANGELOG.md
- README.md
> Update the README with the new dev & test URLs

- CHANGELOG.md
- config/locales/task_lists/conversion/involuntary/one_hundred_and_twenty_five_year_lease.en.yml
- config/locales/task_lists/conversion/voluntary/one_hundred_and_twenty_five_year_lease.en.yml
Changed school/trust references to solicitors.
> Correcting guidance in 125 year lease tasks

- CHANGELOG.md
- config/locales/task_lists/conversion/involuntary/deed_of_variation.en.yml
- config/locales/task_lists/conversion/involuntary/direction_to_transfer.en.yml
- config/locales/task_lists/conversion/involuntary/trust_modification_order.en.yml
- config/locales/task_lists/conversion/voluntary/deed_of_variation.en.yml
- config/locales/task_lists/conversion/voluntary/direction_to_transfer.en.yml
- config/locales/task_lists/conversion/voluntary/trust_modification_order.en.yml
Standardise capitalisation on clear and sign legal documents
- Deed of variation
- Trust modification order
- Direction to transfer
Content already checked, please check that nothing is broken!
> 1404 standardise capitalisation on clear and sign legal documents pt3

- CHANGELOG.md
- config/locales/task_lists/conversion/involuntary/land_questionnaire.en.yml
- config/locales/task_lists/conversion/involuntary/land_registry.en.yml
- config/locales/task_lists/conversion/involuntary/supplemental_funding_agreement.en.yml
- config/locales/task_lists/conversion/voluntary/land_questionnaire.en.yml
- config/locales/task_lists/conversion/voluntary/land_registry.en.yml
- config/locales/task_lists/conversion/voluntary/supplemental_funding_agreement.en.yml
Standardising capitalisation in some of the legal document tasks:
- Land questionnaire
- Land registry title plans
- Supplemental funding agreement
> 1401 standardise capitalisation on clear and sign legal documents

- CHANGELOG.md
- public/robots.txt
Stop search engines from crawling the application.
> Stop search engines from crawling the application

- .github/workflows/build-and-push-image-test.yml
> Deploy Release 22 to test

- doc/decisions/0018-use-parliamentary-members-api.md
> Document the ADR for using the Members API

- Gemfile.lock
Updating gemfile for ARM macs. Steve had unstaged changes he had to keep stashing before working on new branches. Checked what do with them. Laura said to discard one and commit the gemfile change in a separate PR. This is that PR.
Convo in Slack: https://ukgovernmentdfe.slack.com/archives/C03AANC6UJF/p1682435763915459
> Update gemfile for ARM macs

- app/views/conversions/index.html.erb
- config/locales/conversion/tasks/stakeholder_kick_off.en.yml
- config/locales/project.en.yml
Add a missing `div` tag in one view.
Add some translation strings which were found to be missing after an audit.
> Some bugfixes

- CHANGELOG.md
- app/views/external_contacts/index.html.erb
- config/locales/contact.en.yml
> Add extra hint text to the External contacts tab

- terraform/README.md
- terraform/container-apps-hosting.tf
Fixes the regression from a previous version of the container app module wherein Azure Alarm notifications were not being sent to Slack.
> Hotfix for Logic App workflow not working

- app/views/shared/navigation/_your_projects_primary_navigation.html.erb
- app/views/user/projects/added_by.html.erb
- app/views/user/projects/completed.html.erb
- app/views/user/projects/in_progress.html.erb
- config/locales/en.yml
- config/locales/project.en.yml
We have a navigation pattern, here we follow it for the your projects
section.
https://trello.com/c/l8KUqWsv
> Add your projects primary navigation

- CHANGELOG.md
- config/locales/conversion/tasks/trust_modification_order.en.yml
This work updates content int eh trust modification order to more accurately reflect how the document is cleared and signed.
> Updating content in trust modification order task

- spec/accessibility/all_projects_spec.rb
- spec/accessibility/service_support_projects_spec.rb
- spec/accessibility/team_projects_spec.rb
- spec/accessibility/your_projects_spec.rb
Added some tests around the new views, we have also ensured each view has a project on there to test the complete page.
https://trello.com/c/qTYeKydL
> Update accessibility checks

- CHANGELOG.md
- app/forms/conversion/task/risk_protection_arrangement_task_form.rb
- app/models/conversion/task_list.rb
- app/views/conversions/tasks/risk_protection_arrangement/edit.html.erb
- config/locales/conversion/tasks/risk_protection_arrangement.en.yml
- db/migrate/20230626084707_add_conversion_risk_protection_arrangement_task_attributes.rb
- db/schema.rb
- lib/generators/conversion/templates/locales.en.yml
- spec/features/conversions/users_can_complete_conversion_tasks_spec.rb
- spec/forms/conversion/tasks/risk_protection_arrangement_spec.rb
- spec/models/conversion/task_list_spec.rb
Add the RPA task, which is radio buttons, one of which has a hidden hint text.
https://trello.com/c/2zl6epVj
> Add RPA task

- CHANGELOG.md
- app/views/users/_users_table.html.erb
- spec/features/users/users_can_manage_user_accounts_spec.rb
> Show 'No team' when a User's team is nil

- app/forms/conversion/task/check_accuracy_of_higher_needs_task_form.rb
- app/forms/conversion/task/complete_notification_of_change_task_form.rb
- app/models/conversion/task_list.rb
- app/views/conversions/tasks/check_accuracy_of_higher_needs/edit.html.erb
- app/views/conversions/tasks/complete_notification_of_change/edit.html.erb
- config/locales/conversion/tasks/check_accuracy_of_higher_needs.en.yml
- config/locales/conversion/tasks/complete_notification_of_change.en.yml
- db/migrate/20230712113655_add_conversion_check_accuracy_of_higher_needs_task_attributes.rb
- db/migrate/20230712113923_add_conversion_complete_notification_of_change_task_attributes.rb
- db/schema.rb
- spec/features/conversions/users_can_complete_conversion_tasks_spec.rb
- spec/models/conversion/task_list_spec.rb
These are the two new tasks to cover the higher needs.
Nothing unusual here, all boiler plate from the generator.
https://trello.com/c/pdkE4cn3
> Add tasks for higher needs

- app/controllers/all/local_authorities/projects_controller.rb
- app/controllers/all/regions/projects_controller.rb
- app/controllers/all/trusts/projects_controller.rb
- app/views/all/local_authorities/projects/show.html.erb
- app/views/all/regions/projects/show.html.erb
- app/views/all/trusts/projects/show.html.erb
- spec/features/projects/local_authorities/users_can_view_projects_for_a_local_authority_spec.rb
- spec/features/projects/regions/users_can_view_projects_by_trust_spec.rb
- spec/features/projects/trusts/users_can_view_projects_by_trust_spec.rb
When we added the various 'by' views we missed some paging - this adds it in.
https://trello.com/c/uNg71GFC
> Add pager to various 'by x' views

- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/variables.tf
Creates an Event Hub consumer to be used for exporting application exceptions into a centralised log management platform
> Deploy an Event Hub consumer

- app/views/all/opening/projects/_confirmed_table.html.erb
> Fix: header cell on the body

- app/presenters/export/csv/project_presenter.rb
- app/services/export/funding_agreement_letters_csv_exporter_service.rb
- app/services/export/risk_protection_arrangement_csv_export_service.rb
- config/locales/export/csv/project.en.yml
- spec/presenters/export/csv/project_presenter_spec.rb
Updates the two exporters to include:
- academy order type
- two requires improvement values
- sponsor grant type
https://trello.com/c/T9CpBai8
> Update exported columns

- CHANGELOG.md
- app/models/project_statistics.rb
- app/views/all/statistics/projects/index.html.erb
- spec/models/project_statistics_spec.rb
We are removing voluntary and sponsored from the application, here from the statistics view.
We taske some time to refactor how we generate some stats and the view itself as well.
https://trello.com/c/oG6nb6eO
> Update statistics view

- CHANGELOG.md
- config/locales/conversion/tasks/complete_notification_of_change.en.yml
> Use details component to improve readability in notification of changes task

- CHANGELOG.md
- app/forms/transfer/task/master_funding_agreement_task_form.rb
- app/models/transfer/task_list.rb
- app/views/transfers/tasks/master_funding_agreement/edit.html.erb
- config/locales/transfer/master_funding_agreement.en.yml
- db/migrate/20230809113348_add_master_funding_agreement_attributes_to_transfer.rb
- db/schema.rb
> Add master funding agreement task to Transfer projects

- CHANGELOG.md
- app/forms/transfer/task/deed_of_novation_and_variation_task_form.rb
- app/models/transfer/task_list.rb
- app/views/transfers/tasks/deed_of_novation_and_variation/edit.html.erb
- config/locales/transfer/tasks/deed_of_novation_and_variation.en.yml
- db/migrate/20230809115347_add_deed_of_novation_and_variation_task_attribute_to_transfers.rb
- db/schema.rb
> Add Deed of novation and variation task to Transfer projects

- CHANGELOG.md
- app/forms/transfer/task/commercial_transfer_agreement_task_form.rb
- app/models/transfer/task_list.rb
- app/views/transfers/tasks/commercial_transfer_agreement/edit.html.erb
- config/locales/transfer/tasks/commercial_transfer_agreement.en.yml
- db/migrate/20230809135448_add_commercial_transfer_agreement_task_attribute_to_transfers.rb
- db/schema.rb
> Add commercial transfer agreement task to Transfer projects

- CHANGELOG.md
- app/forms/transfer/task/supplemental_funding_agreement_task_form.rb
- app/models/transfer/task_list.rb
- app/views/transfers/tasks/supplemental_funding_agreement/edit.html.erb
- config/locales/transfer/tasks/supplemental_funding_agreement.en.yml
- db/migrate/20230808152500_add_transfer_supplemental_funding_agreement_task_attributes.rb
- db/schema.rb
> Add Supplemental funding agreement task to Transfer projects

- CHANGELOG.md
- app/forms/transfer/task/deed_of_variation_task_form.rb
- app/models/transfer/task_list.rb
- app/views/transfers/tasks/deed_of_variation/edit.html.erb
- config/locales/transfer/tasks/deed_of_variation.en.yml
- db/migrate/20230810120325_add_transfer_deed_of_variation_task_attributes.rb
- db/schema.rb
> Add Deed of Variation task for Transfer projects

- CHANGELOG.md
- config/locales/conversion/tasks/conditions_met.en.yml
> Correcting openers list to by month list in all conditions met task

- CHANGELOG.md
- app/views/conversions/tasks/master_funding_agreement/edit.html.erb
- config/locales/conversion/tasks/master_funding_agreement.en.yml
- config/locales/transfer/master_funding_agreement.en.yml
> Updating MFA task content to be the same in transfers and conversions

- CHANGELOG.md
- app/forms/transfer/task/land_consent_letter_task_form.rb
- app/models/transfer/task_list.rb
- app/views/transfers/tasks/land_consent_letter/edit.html.erb
- config/locales/transfer/tasks/land_consent_letter.en.yml
- db/migrate/20230822141039_add_transfer_land_consent_letter_task_attributes.rb
- db/schema.rb
> Add Land Consent Letter task to Transfer projects

- CHANGELOG.md
- app/forms/transfer/task/rpa_policy_task_form.rb
- app/models/transfer/task_list.rb
- app/views/transfers/tasks/rpa_policy/edit.html.erb
- config/locales/transfer/task_list.en.yml
- config/locales/transfer/tasks/rpa_policy.en.yml
- db/migrate/20230823100847_add_transfer_rpa_policy_task_attributes.rb
- db/schema.rb
> Add RPA Policy task to Transfers task list

- CHANGELOG.md
- app/forms/transfer/task/form_m_task_form.rb
- app/models/transfer/task_list.rb
- app/views/transfers/tasks/form_m/edit.html.erb
- config/locales/transfer/tasks/form_m.en.yml
- db/migrate/20230823143714_add_transfer_form_m_task_attributes.rb
- db/schema.rb
> Add Form M task to Transfer projects

- CHANGELOG.md
- config/locales/conversion/tasks/sponsored_support_grant.en.yml
Jo spotted some changes needed in the sponsored grant task for conversions. This work corrects those errors.
> Updating content in sponsored grant task

- CHANGELOG.md
- app/forms/transfer/task/church_supplemental_agreement_task_form.rb
- app/models/transfer/task_list.rb
- app/views/transfers/tasks/church_supplemental_agreement/edit.html.erb
- config/locales/transfer/tasks/church_supplemental_agreement.en.yml
- db/migrate/20230825100251_add_transfer_church_supplemental_agreement_task_attributes.rb
- db/schema.rb
> Add Church Supplemental Agreement task to Transfer projects

- CHANGELOG.md
- app/presenters/export/csv/project_presenter.rb
- app/services/export/education_and_skills_funding_agency_csv_export_service.rb
- app/services/export/funding_agreement_letters_csv_exporter_service.rb
- config/locales/export/csv/project.en.yml
- spec/presenters/export/csv/project_presenter_spec.rb
If a project has a "main contact", show it on the exports.
> Exports include the main contact when applicable

- .github/workflows/checks.yml
- Dockerfile.checks
- docker-compose.checks.yml
This work was prompted by the desire to clean up the scripts and that we run checks multiple times - it was also an opportunity to try and speed up the build and checks.
Becuase it is difficult to test the cache, we want to add these new components and test them across branches. We are caching Docker layers which means the majority of the image should be in the cache, but it is not super clear if this is indeed the case - so we want to find out!
This work also includes an update to how we install Node and Yarn as the previous way is no longer working (we have cherry-picked and merged that in the actual Dockerfile.
Long term, if this works, we will replace the current CI with this new one, which clears the way to delete more of the `scripts`, might improve perfromance and simplifies things …
> New checks workflow

- .github/workflows/checks.yml
We are still experminenting with this workflow, but missed running it on
main.
I am also keen to trial `min` caching first.
> Udpate ci checks workflow

- CHANGELOG.md
- app/views/transfers/tasks/conditions_met/edit.html.erb
- config/locales/transfer/tasks/conditions_met.en.yml
Update to the agreed content.
https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_sprints/taskboard/Complete%20conversions%20transfers%20and%20changes/Academies-and-Free-Schools-SIP/Complete%20sprint%2031
> Update transfer all condtions task content

- .github/pull_request_template.md
- doc/releases-and-deploys.md
And remove reference to Trello board release card :cry:
> Change Trello to DevOps

- app/views/shared/projects/_task_list.html.erb
> (Fix) Move the Task list h2 above the task list itself

- README.md
- doc/getting-started.md
- doc/seeding-the-database.md
- doc/user-accounts.md
Alot of the User related documentation is now out of date so has been
removed.
https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_sprints/taskboard/Complete%20conversions%20transfers%20and%20changes/Academies-and-Free-Schools-SIP/Post%20Advisory%20Board/Sprint%2032
> Add database seeding documentation

- terraform/.terraform.lock.hcl
- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/versions.tf
* Contains refactored container app resource terraform code
> Bump Container App hosting module to v1.0.0

- CHANGELOG.md
- app/forms/transfer/task/closure_or_transfer_declaration_task_form.rb
- app/models/transfer/task_list.rb
- app/views/transfers/tasks/closure_or_transfer_declaration/edit.html.erb
- config/locales/transfer/tasks/closure_or_transfer_declaration.en.yml
- db/migrate/20230919101125_add_transfer_closure_or_transfer_declaration_task_attributes.rb
- db/schema.rb
- spec/features/transfers/users_can_complete_transfer_tasks_spec.rb
- spec/models/transfer/task_list_spec.rb
> Add Closure or Transfer Declaration task to Transfers

- CHANGELOG.md
- app/forms/transfer/task/confirm_incoming_trust_has_completed_all_actions_task_form.rb
- app/models/transfer/task_list.rb
- app/views/transfers/tasks/confirm_incoming_trust_has_completed_all_actions/edit.html.erb
- config/locales/transfer/tasks/confirm_incoming_trust_has_completed_all_actions.en.yml
- db/migrate/20230919115055_add_transfer_confirm_incoming_trust_has_completed_all_actions_task_attributes.rb
- db/schema.rb
- spec/features/transfers/users_can_complete_transfer_tasks_spec.rb
- spec/models/transfer/task_list_spec.rb
> Add "Confirm incoming trust has completed all actions" task to transfers

- CHANGELOG.md
- app/forms/transfer/task/redact_and_send_documents_task_form.rb
- app/models/transfer/task_list.rb
- app/views/transfers/tasks/redact_and_send_documents/edit.html.erb
- config/locales/transfer/task_list.en.yml
- config/locales/transfer/tasks/redact_and_send_documents.en.yml
- db/migrate/20230920093557_add_transfer_redact_and_send_documents_task_attributes.rb
- db/schema.rb
- spec/features/transfers/users_can_complete_transfer_tasks_spec.rb
- spec/models/transfer/task_list_spec.rb
> Add "Redact and send documents" task to Transfer projects

- terraform/.terraform.lock.hcl
- terraform/README.md
- terraform/container-apps-hosting.tf
- New: App Insights Exceptions Log query alert rule so we can get notified when they happen
- Fix: CDN Origin hostname is now correctly referencing the FQDN of the Container App environment instead of the individual replica
> Update Container app module to v1.1.0

- CHANGELOG.md
- app/views/projects/shared/_completed_table.html.erb
- config/locales/project.en.yml
Updated the `your team projects` completed table to reflect the prototype
> Update the Your team projects completed table

- CHANGELOG.md
- app/forms/transfer/task/request_new_urn_and_record_task_form.rb
- app/models/transfer/task_list.rb
- app/views/transfers/tasks/request_new_urn_and_record/edit.html.erb
- config/locales/transfer/tasks/request_new_urn_and_record.en.yml
- db/migrate/20230925142942_add_transfer_request_new_urn_and_record_task_attributes.rb
- db/schema.rb
- spec/features/transfers/users_can_complete_transfer_tasks_spec.rb
- spec/models/transfer/task_list_spec.rb
> Add "Request new URN and Record" task to Transfer projects

- app/services/import/gias_establishment_csv_importer_service.rb
- spec/services/import/gias_establishment_csv_importer_service_spec.rb
We had these wrong, which got revealed when testing with chagned data
sets.
The import still works successfully, it is only the counts that were
worng.
> Fix the GIAS import stats

- CHANGELOG.md
- app/views/conversions/tasks/main_contact/edit.html.erb
- app/views/transfers/tasks/main_contact/edit.html.erb
- config/locales/conversion/tasks/main_contact.en.yml
- config/locales/transfer/tasks/main_contact.en.yml
- spec/features/conversions/users_can_complete_conversion_tasks_spec.rb
- spec/features/conversions/users_can_select_a_main_contact_spec.rb
- spec/features/transfers/tasks/users_can_compelte_main_contact_spec.rb
Update the main contact task content as per the new designs.
> Update the content for the Conversion & Transfer "main contact" tasks

- CHANGELOG.md
- Gemfile.lock
- config/locales/transfer/tasks/articles_of_association.en.yml
- config/locales/transfer/tasks/church_supplemental_agreement.en.yml
- config/locales/transfer/tasks/closure_or_transfer_declaration.en.yml
- config/locales/transfer/tasks/commercial_transfer_agreement.en.yml
- config/locales/transfer/tasks/conditions_met.en.yml
- config/locales/transfer/tasks/confirm_incoming_trust_has_completed_all_actions.en.yml
- config/locales/transfer/tasks/deed_of_novation_and_variation.en.yml
- config/locales/transfer/tasks/deed_of_termination_for_the_master_funding_agreement.yml
- config/locales/transfer/tasks/deed_of_variation.en.yml
- config/locales/transfer/tasks/deed_termination_church_agreement.en.yml
- config/locales/transfer/tasks/form_m.en.yml
- config/locales/transfer/tasks/handover.en.yml
- config/locales/transfer/tasks/land_consent_letter.en.yml
- config/locales/transfer/tasks/master_funding_agreement.en.yml
- config/locales/transfer/tasks/request_new_urn_and_record.en.yml
- config/locales/transfer/tasks/stakeholder_kick_off.en.yml
- config/locales/transfer/tasks/supplemental_funding_agreement.en.yml
A series of small content tweaks made to tasks in the transfers task list.
Mostly just correcting grammar and spelling errors.
> Content tweaks transfers complete

- doc/decisions/0007-use-the-academies-db-as-the-datastore.md
- doc/decisions/0021-use-a-seperate-database-server-instance.md
- doc/microsoft-sql-server.md
- doc/seeding-the-database.md
- ADR for isolated SQL instance
- Update  MS SQL related documentation
- Fix documentaiton link path for user accounts
> ADR isolated sql instance

- doc/console-and-logs.md
We have searchable logs in Azure, document how to access them.
> Update logs docs

- Gemfile
- Gemfile.lock
- app/components/task_list/check_box_action_component.html.erb
- app/components/task_list/check_box_action_component.rb
- app/components/task_list/task_header_component.html.erb
- app/components/task_list/task_header_component.rb
- app/controllers/assignments_controller.rb
- app/controllers/concerns/authentication.rb
- app/controllers/conversions/academy_urn_controller.rb
- app/controllers/cookies_controller.rb
- app/controllers/tasks_controller.rb
- app/views/conversions/academy_urn/confirm.html.erb
- app/views/conversions/project_information/_academy_details.html.erb
- app/views/conversions/project_information/_reasons_for_conversion.html.erb
- app/views/conversions/project_information/_school_details.html.erb
- app/views/conversions/shared/_project_summary.html.erb
- app/views/conversions/tasks/stakeholder_kick_off/edit.html.erb
- app/views/external_contacts/_contact_group.html.erb
- app/views/local_authorities/show.html.erb
- app/views/member_of_parliament/show.html.erb
- app/views/shared/_internal_contacts.html.erb
- app/views/shared/project_information/_advisory_board_details.html.erb
- app/views/shared/project_information/_incoming_trust_details.html.erb
- app/views/shared/project_information/_project_details.html.erb
- app/views/transfers/project_information/_academy_details.html.erb
- app/views/transfers/project_information/_outgoing_trust_details.html.erb
- app/views/transfers/shared/_project_summary.html.erb
- app/views/transfers/tasks/stakeholder_kick_off/edit.html.erb
- spec/features/conversions/users_can_complete_conversion_tasks_spec.rb
- spec/features/transfers/tasks/users_can_compelte_stakeholder_kick_off_spec.rb
Update govuk-components and govuk_design_system_formbuilder to v4.x. This also updates Pagy to v6.x.
> Update govuk-components and govuk_design_system_formbuilder

- CHANGELOG.md
- app/views/your/projects/_in_progress_table.html.erb
- app/views/your/projects/in_progress.html.erb
- config/locales/en.yml
- config/locales/project.en.yml
- spec/features/projects/users_can_view_a_list_of_assigned_projects_spec.rb
- spec/features/your_projects/users_can_view_their_projects_spec.rb
> Change the "Your projects" view to a table layout

- terraform/.terraform.lock.hcl
- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/variables.tf
- Fixes Redis networking so that connections do not rely on the public internet and instead go via private endpoints.
- Adds the ability to override the default redis configuration with the `redis_config` variable
- Adds the ability to change the SKU of the redis instance with the `redis_sku` variable
- This will change from the default "Basic" to "Standard" in Production.The specs remain the same, but an SLA is included with Standard so it is more suitable for production workloads.
> Update TF Container App module to 1.3.1

- app/models/project.rb
- spec/services/by_team_project_fetcher_service_spec.rb
We want the newest projects first.
> (Fix) Reverse sort order for Projects ordered by created date

- terraform/README.md
- terraform/container-apps-hosting.tf
Updates Azure Container App Terraform module to 1.4.7
Closes #1276 which is a duplicate
> Update to 1.4.7 of Container App module

- CHANGELOG.md
- app/views/shared/navigation/_service_support_primary_navigation.html.erb
- config/locales/en.yml
- spec/features/service_support/users_can_upload_gias_establishments_data_spec.rb
> (153281) Add link to GIAS upload page for service_support users

- app/forms/service_support/upload/gias/upload_establishments_form.rb
- app/jobs/import/gias_import_job.rb
- spec/forms/service_support/upload/gias/upload_establishments_form_spec.rb
- spec/jobs/import/gias_import_job_spec.rb
Refactor the Establishment GIAS import and Headteacher GIAS import jobs into one job. These both run off the same file and happen together (sequentially).
> (153282 ) Refactor Establishment and Headteacher GIAS imports into one job

- CHANGELOG.md
- app/services/export/conversions/education_and_skills_funding_agency_csv_export_service.rb
Add additional columns to the ESFA report
Theses include:
- School type
- School phase
- Local authority
- Region
- Advisory board date
> Add additional columns to the ESFA report

- CHANGELOG.md
- app/views/all/in_progress/projects/index.html.erb
- app/views/service_support/projects/without_academy_urn.html.erb
- app/views/shared/_maintenance_banner.html.erb
- app/views/your/projects/in_progress.html.erb
> Add maintenance banner for Wednesday 6th March 2024 maintenance

- app/policies/contact_policy.rb
- app/policies/project_policy.rb
These changes should clear some of the Sonarcloud issues.
- **DRY up project policy**
- **DRY up contact policy**
> (chore) DRY up policies

- CHANGELOG.md
- app/views/projects/shared/_new_projects.html.erb
- spec/requests/project_management_spec.rb
> (158748) Allow users to add a new Form a MAT conversion project

- CHANGELOG.md
- app/views/transfers/shared/_project_summary.html.erb
- spec/factories/transfer/project_factory.rb
- spec/features/transfers/users_can_view_a_transfer_spec.rb
To be merged after https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/pull/1402
> (158849) Show a pink Form a MAT label on Transfer project details page

- CHANGELOG.md
- app/presenters/export/csv/project_presenter.rb
- app/services/export/conversions/education_and_skills_funding_agency_csv_export_service.rb
- config/locales/export/csv/project.en.yml
- spec/presenters/export/csv/project_presenter_spec.rb
This is mirrored off the work which presents when an academy actually transfers
> Show the date a conversion happened in the ESFA export

- doc/import-gias-data.md
The EstablishmentCsvImporterService has moved namespace.
> Update GIAS import documentation

- CHANGELOG.md
- app/views/conversions/tasks/risk_protection_arrangement/edit.html.erb
- config/locales/conversion/tasks/risk_protection_arrangement.en.yml
Making it clear that the academy will be enrolled unless they say
otherwise.
> (162862) Update RPA task guidance

- Dockerfile
Added a `LABEL` metadata entry to the Docker image. This will associate the built image with the source code origin of this repository.
> Added Docker Label to container package

- .github/workflows/build-and-push-image.yml
- Using this workflow strategy aligns the release process closer to other sibling apps within RSD
- Using the 'matrix' strategy means we can deploy the worker container in parallel to the web app
> Switch to using a reusable workflow

- .github/workflows/build-and-push-image.yml
Reverts DFE-Digital/dfe-complete-conversions-transfers-and-changes#1521
The repository is not adequately updated to jump to this major version just yet :) 
(we should jump to 1.1.0 instead)
> Revert "Update DFE-Digital/deploy-azure-container-apps-action action to v2"

- app/api/api.rb
Describes the API key authentication in the API docs.
> Add authentication to API docs

- app/api/api.rb
- spec/requests/swagger_json_spec.rb
Filling out the API docs with basic information.
> Add more basic API documentation

- CHANGELOG.md
- app/services/export/conversions/all_data_csv_export_service.rb
We were asked to add these two columns to make reporting simpler.
> (169261) Add columns to by month conversions export

- CHANGELOG.md
- app/services/export/conversions/rpa_sug_and_fa_letters_csv_export_service.rb
> Include incoming trust UKPRN in RPA/SUG report

- CHANGELOG.md
- app/views/shared/projects/_actions.html.erb
Adding this container gives the button better spacing.
> Add button group

- CHANGELOG.md
- app/services/export/conversions/rpa_sug_and_fa_letters_csv_export_service.rb
> Add the team a project is assigned to to the RPA, SUG and FA letters export

- app/controllers/dao_revocations_controller.rb
- spec/requests/dao_revocations_controller_spec.rb
We are adding long form responses to the form in later work and the 4kb
cookie limit for the cookie store could potentially be reached.
To avoid the issue we have configured the Rails cache, backed by Redis
so we can store the values there.
We have a one hour expiry on the values so they are deleted after that
time.
We couldn't use the preferred option of moving the session store to the
cache as the OmniAuth CSRF protection is not compatible with the cache
store.
Based on #1747
> Switch DAO Revocation stepped form to cache

- CHANGELOG.md
Added
- When revoking a DAO, details for each reason must now be supplied.
> Release-79

- CHANGELOG.md
- app/views/shared/_dfe_footer.html.erb
> Update the feedback form link in Complete footer

- CHANGELOG.md
- app/views/project_groups/show.html.erb
- config/application.rb
- config/initializers/date_and_time_formats.rb
- config/initializers/time_formats.rb
- spec/helpers/user_helper_spec.rb
- spec/presenters/significant_date_presenter_spec.rb
We were asked to show the time on date history changes in the London timezone
rather than UTC.
> (175425) Date history timezone support

- spec/models/base_task_list_spec.rb
Noticed this typo whilst doing some other work.
> Fix typo in spec

- app/api/v1/conversions.rb
- app/api/v1/transfers.rb
Adding some niceties to the API docs.
We've added the `default` value to false for boolean attributes as we
have those set at the database level.
> Add API docs

- app/models/dao_revocation_reason.rb
- spec/features/dao_revocation/user_can_record_the_revocation_of_a_dao_from_a_project_spec.rb
- spec/models/dao_revocation_reason_spec.rb
Missed this part in a previous commit!
Also add a test for this reason in the feature test.
> (Fix) Add the "Change to policy" revocation reason to the enum

- app/models/api/academies_api/client.rb
> Remove unused API client error

- CHANGELOG.md
Changed
- The MP's name is now their full name with title (e.g. The Right Honourable)
Added
- Add new "Change to government policy" DAO revocation reason
> Release 90

- README.md
- app/api/api.rb
- app/api/v1/conversions.rb
- app/api/v1/healthcheck.rb
- app/api/v1/transfers.rb
- doc/api.md
Some more tweaks to the API swagger docs and project docs.
We've marked the API as 1.0.0-alpha!
> More API docs

- app/services/project_search_service.rb
- spec/factories/conversion/project_factory.rb
- spec/factories/transfer/project_factory.rb
- spec/services/project_search_service_spec.rb
Inactive (state 4) projects are not ready to be worked on and therefore should not show up in search results (for now)
> (182257) Do not show inactive projects in search results

- app/forms/export/new_academies_due_to_transfer_form.rb
- app/forms/export/new_pre_conversion_grants_form.rb
- app/forms/export/new_pre_transfer_grants_form.rb
- app/forms/export/new_rpa_sug_and_fa_letters_form.rb
- spec/forms/export/new_academies_due_to_transfer_form_spec.rb
- spec/forms/export/new_pre_conversion_grants_form_spec.rb
- spec/forms/export/new_pre_transfer_grants_form_spec.rb
- spec/forms/export/new_rpa_sug_and_fa_letters_form_spec.rb
Do not show inactive projects in any exports.
> (182258) Exclude inactive projects from exports

- app/services/api/base_create_project_service.rb
- app/services/api/conversions/create_project_service.rb
- app/services/api/transfers/create_project_service.rb
- spec/services/api/conversions/create_project_service_spec.rb
- spec/services/api/transfers/create_project_service_spec.rb
Update the validations and specs on the API create project services.
> API project validations

- CHANGELOG.md
- app/presenters/export/csv/incoming_trust_presenter_module.rb
- app/presenters/export/csv/outgoing_trust_presenter_module.rb
- app/presenters/export/csv/school_presenter_module.rb
- app/services/contacts_fetcher_service.rb
- app/services/export/conversions/rpa_sug_and_fa_letters_csv_export_service.rb
- app/services/export/transfers/all_data_csv_export_service.rb
- config/locales/export/csv/project.en.yml
- spec/presenters/export/csv/incoming_trust_presenter_module_spec.rb
- spec/presenters/export/csv/outgoing_trust_presenter_module_spec.rb
- spec/presenters/export/csv/school_presenter_module_spec.rb
- spec/services/contacts_fetcher_service_spec.rb
This work was added and then reverted back in #1894, the users are now ready to
use the changes so we re-apply the commits.
> Re-apply export changes

- doc/console-and-logs.md
At some point this changed and the previous one does not work.
> Update log query example

- Dockerfile
I am not sure I agree with all these, I think we loose some readability
here, but I am not concerned enough to not do it (I hate the little red
cross in Github more!)
> Tweaks to the Dockerfile to make SonarCloud happy

- sonar-project.properties
Recently SonarCloud started including our specs, when it should not.
This is an attempt to fix that.
> Update SonarCloud properties

- Gemfile
- Gemfile.lock
This updates Puma in the Gemfile as a fix for some of Steve's problems today.
> Updates to Puma 6

- CHANGELOG.md
- app/forms/conversion/task/single_worksheet_task_form.rb
- app/models/conversion/task_list.rb
- app/views/conversions/tasks/single_worksheet/edit.html.erb
- config/locales/conversion/tasks/single_worksheet.en.yml
- db/migrate/20241029114243_remove_single_worksheet_task_columns.rb
- db/schema.rb
- spec/features/conversions/users_can_complete_conversion_tasks_spec.rb
- spec/models/conversion/task_list_spec.rb
Reverts DFE-Digital/dfe-complete-conversions-transfers-and-changes#1979
This shouldn't be deployed until comms is completed
> Revert "Remove the Single Worksheet task from Conversions"

- LICENSE
Normalises the licence to match other services
> Removed copy date from licence

- .github/workflows/ci-checks.yml
- docker-compose.checks.yml
Also restricts to only scan for vulnerabilities
> Revert cache setup as it is now done at the provider level

- doc/infrastructure-and-terraform.md
This wasn't documented anywhere I could find it!
> Document the process to lint Terraform docs

- CHANGELOG.md
- Track "time on page" with AppInsights `PageVisitTime` custom metric
- Track users with AppInsights "authenticated user context"
> Release 100

- CHANGELOG.md
Changed:
- Record each project's associated local authority to improve performance
Fixed:
- Backfill missing note for SignificantDataHistoryReason
> Release 102

- CHANGELOG.md
- Use a new less alarming "error notification" for exceptions which are handled
> Release 104

- CHANGELOG.md
- Over-ride a user's role attributes with 'Capabilities'
> Release 106

- CHANGELOG.md
- Use fork of application insights to fix exception handling
> Release 107

- CHANGELOG.md
CHANGED
- Find a project to be handed over by URN, if there are too many to show on a single page.
> Release 109

- CHANGELOG.md
Fixed
- Link to accessible guidance on URN Transfers on Sharepoint from "Request new URN and record" task
> Release 112

- CHANGELOG.md
- Add caching to Academies API responses to improve performance.
> Release 113

- CHANGELOG.md
- Enforce presence of project region.
> Release 114

- CHANGELOG.md
- Handle pagination errors gracefully.
- Allow 'manage team' user attribute to be set by service support
> Release 115

- CHANGELOG.md
Changed
- Service support can now manage a user's "capabilities"
> Release 117

- config/locales/information_banner.yml
Updated the maintenance information banner with the latest change information to inform users appropriately.
> Set new maintenance message

- config/locales/transfer/tasks/deed_of_novation_and_variation.en.yml
This PR replaces an incorrect URL for the Deed of novation and variation task in complete, as per ticket 223867.
> Fix deed of novation URL 
